#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Invertible Sheaves

// Hartshorne II.6, Proposition 6.12
#proposition(number: 6.12)[
  If $shf.l$ and $shf.m$ are invertible sheaves on a ringed space $X$, so is
  $tensor(shf.l, shf.m, over: shf.o_X)$. If $shf.l$ is any invertible sheaf on $X$, then there
  exists an invertible sheaf $shf.l^(-1)$ on $X$ such that
  $tensor(shf.l, shf.l^(-1), over: shf.o_X) simeq shf.o_X$.
]

#proof[
  For the first statement, note that $tensor(shf.o_X, shf.o_X, over: shf.o_X) simeq shf.o_X$.
  For the latter, take $shf.l^(-1) := shf.l^ast$. Then
  $tensor(shf.l^ast, shf.l, over: shf.o_X) simeq shf.hom_(shf.o_X) (shf.l, shf.l) = shf.o_X$ by _[5.1]_.
]

// Hartshorne II.6, Definition D10
#definition(title: "Picard Group")[
  For any ringed space $X$, define the *Picard group* on $X$, denoted
  $ops.pic (X)$, to be the group of isomorphism classes of invertible sheaves on
  $X$, under the operation $tensor(#none, #none, over: shf.o_X)$. Note that _(6.12)_
  shows that $(ops.pic (X), tensor)$ is a group with identity $shf.o_X$.
]

// Hartshorne II.6, Remark 6.12.1
#remark(title: "6.12.1")[
  The Picard group will later be identified with the cohomology group
  $H^1 (X,shf.o_X^times)$.
]

// Hartshorne II.6, Definition D11
#definition(title: "Associated Sheaf to Cartier Divisors")[
  Fix a scheme $X$ and let $D in ops.cdiv (X)$ be represented by ${ (U_i, f_i) }$.
  Define $shf.l (D)$ to be the $shf.o_X$-submodule of $shf.k_X$ generated locally by
  $f_i^(-1)$ on $U_i$. This is well-defined, since
  $f_i / f_j in shf.o_X^times (U_i inter U_j)$, so both $f_i^(-1)$ and
  $f_j^(-1)$ generate the same $shf.o_X$-submodule. In particular,
  $shf.l (0) = shf.o_X$.
]

#lemma(
  number: "6.D", // number: 6.D
)[
  Given $X in cat.sch$ and any $U in shf.t_X$, then
  $
    f in shf.k_X (U) text(" is a unit")
    arrow.l.r.double.long
    f_x in shf.k_(X, x) text(" is ") shf.o_(X, x) text("-torsion-free for every ")
    x in U.
  $
]

#proof[
  The case $U = emptyset$ is clear, so assume $U != emptyset$.

  - Suppose $f in shf.k (U)$ such that $f(x) in shf.k_x^times$ for every $x in U$
    (note $shf.k_x$ equals the stalk of the presheaf total quotient ring). Take
    $g(x) := f(x)^(-1)$ for each $x in U$; this defines $g$ in the presheaf
    total quotient ring on $U$. We check that $g in shf.k (U)$. Indeed, if
    $x in U$, then there exists $V in shf.n_x (X)$ with $V subset U$ and
    $s$ in the presheaf total quotient ring on $V$ such that
    $f(y) = s_y$ in the presheaf stalk for every $y in V$. Now, if $t$ is a
    presheaf section on $W$ with $t_y = (s_y)^(-1)$ in the presheaf stalk for
    every $y in V inter W$, then $g(y) = t_y$ for every $y in V inter W$,
    which shows that $g in shf.k (U)$. Further, it is easy to see that
    $g in shf.k (U)^times$. Therefore,
    $
      f in shf.k (U)^times
      arrow.l.r.double.long
      f(x) in shf.k_x^times text(" for every ") x in U.
    $
    It remains to prove the following claim.

  - *Claim.* $f(x) in shf.k_x^times$ for every $x in U$ iff $f(x)$ is
    $shf.o_x$-torsion-free, i.e. $ops.ann_(shf.o_x) (f(x)) = 0$, for every $x in U$.

    $(Rightarrow)$ Given $x in U$, if $s in ops.ann_(shf.o_x) (f(x))$, then
    $s dot f(x) = 0$ in $shf.k_x$, hence $s = 0$ since $f(x)$ is a unit.

    $(Leftarrow)$ Given $x in U$, there exists $V in shf.n_x (X)$ with
    $V subset U$ such that $f(y) = (a \/ s)_y$ for every $y in V$, where
    $a in shf.o_X (V)$ and $s in shf.o_(X, reg) (V)$. Since $f(y)$ is
    $shf.o_y$-torsion-free for each $y in V$, so is each $a_y in shf.o_y$. Thus
    $a_y in shf.o_y$ is regular for every $y in V$, i.e.
    $a in shf.o_(X, reg) (V)$. Therefore $f(x) = (a \/ s)_x in shf.k_x$ is a unit.
]

#corollary(
  number: "6.E", // number: 6.E
)[
  Let $X$ be a scheme and $shf.l$ be an invertible $shf.o_X$-submodule of $shf.k_X$.
  Then, for each $x in X$, the stalk $shf.l_x$ is an $shf.o_(X, x)$-submodule of
  $shf.k_(X, x)$ generated by a unit.
]

#lemma(
  number: "6.F", // number: 6.F
)[
  #set enum(numbering: "i)", spacing: 1em)

  + *(Algebraic Fact).* Given $A in cat.ring$ and $B in cat.alg_A$. Suppose $M, N$ are
    $A$-submodules of $B$ such that one of them is generated by a regular
    element of $B$ over $A$. Then the natural homomorphism
    $
      tensor(M, N, over: A) arrow.r.twohead_(cat.alg_A) M dot N, quad
      m times.o n mapsto m n,
    $
    is an isomorphism.

  + For $X in cat.sch$ and $shf.o_X$-submodules $shf.f, shf.g$ of $shf.k_X$, define
    $shf.f dot shf.g in cat.alg_(shf.o_X)$ to be the sheafification of
    $U mapsto shf.f (U) dot shf.g (U)$. If both $shf.f$ and $shf.g$ are invertible sheaves,
    then the canonical morphism
    $tensor(shf.f, shf.g, over: shf.o_X) arrow.r.twohead_(cat.alg_(shf.o_X)) shf.f dot shf.g$ is an
    isomorphism.
]

#proof[
  Part (ii) follows from _(6.E)_ and (i).
]

// Hartshorne II.6, Proposition 6.13
#proposition(number: 6.13)[
  Let $X$ be a scheme. Then:

  #set enum(numbering: "a)", spacing: 1em)

  + For any $D in ops.cdiv (X)$, the subsheaf $shf.l (D)$ is an invertible sheaf on
    $X$. The map $D mapsto shf.l (D)$ gives a one-to-one correspondence
    $
      ops.cdiv (X) arrow.l.r.double.long
      { text("invertible subsheaves of ") shf.k_X }.
    $

  + $shf.l (D_1 - D_2) simeq tensor(shf.l (D_1), shf.l (D_2)^(-1), over: shf.o_X)$.

  + $D_1 tilde.op D_2 arrow.l.r.double.long shf.l (D_1) simeq shf.l (D_2)$ as
    invertible $shf.o_X$-modules.
]

#proof[
  *(a).* We proceed in three steps.

  - *(I).* Given any $D = { (U_i, f_i) } in ops.cdiv (X)$, show that $shf.l (D)$ is
    invertible.

    For each $i$, consider the morphism
    $phi_i: shf.o_X|_(U_i) -> shf.l (D)|_(U_i)$ given by
    $
      (phi_i)_V: shf.o_X (V) -> shf.l (D)(V), quad
      1 mapsto f_i^(-1)|_V
      text(" for every ") V subset U_i.
    $
    This induces
    $(phi_i)_x: shf.o_x -> shf.l (D)_x, 1_x mapsto (f_i^(-1))_x$ for each
    $x in U_i$. From the definition of $shf.l (D)$, we have
    $shf.l (D)_x = shf.o_x spn { (f_i^(-1))_x }$, and
    $(f_i^(-1))_x, (f_j^(-1))_x$ generate the same $shf.o_x$-submodule, since
    $(f_i^(-1))_x \/ (f_j^(-1))_x$ is invertible in $shf.l (D)_x$. It follows that
    $(phi_i)_x$ is an isomorphism for each $x in U_i$, whence
    $phi_i: shf.o_X|_(U_i) isoto shf.l (D)|_(U_i)$ for every $i$. Therefore,
    $shf.l (D)$ is an invertible $shf.o_X$-module.

  - *(II).* For any invertible $shf.o_X$-submodule $shf.l$ of $shf.k$, construct a
    Cartier divisor.

    - Cover $X$ with an open cover ${U_i}$ such that
      $shf.l|_(U_i) simeq shf.o_X|_(U_i)$ for all $i$. For each $i$, pick
      $f_i in shf.l (U_i) subset shf.k (U_i)$ corresponding to $1 in shf.o (U_i)$ under
      this isomorphism.

    - *Check.* $f_i in shf.k^times (U_i)$ for each $i$. By _(6.D)_, it suffices
      to show that $(f_i)_x in shf.l_x subset shf.k_x$ is $shf.o_x$-torsion-free for
      every $x in U_i$. This is clear since $shf.l_x simeq shf.o_x$.

    - *Claim.* ${ (U_i, f_i) } in ops.cdiv (X)$. Indeed, for any $i, j$, since
      $shf.l|_(U_i) simeq shf.o_X|_(U_i)$ and $shf.l|_(U_j) simeq shf.o_X|_(U_j)$, both
      $f_i|_j$ and $f_j|_i$ generate $shf.l (U_(i j))$ over $shf.o_X (U_(i j))$,
      where $U_(i j) := U_i inter U_j$. Hence there exists
      $u in shf.o_X (U_(i j))$ such that $f_i|_j = u dot f_j|_i$, i.e.
      $(f_i^(-1)|_j) \/ (f_j^(-1)|_i) in
      shf.o_X (U_(i j))^times = shf.o_X^times (U_(i j))$.

    - *Check.* ${ (U_i, f_i^(-1)) }$ is independent of the choice of the open
      cover ${U_i}$. Thus ${ (U_i, f_i^(-1)) } in ops.cdiv (X)$ is a well-defined
      Cartier divisor.

  - *(III).* Check the constructions are inverse to each other.

    - For any Cartier divisor $D in ops.cdiv (X)$,
      $
        D = { (U_i, f_i) } & mapsto shf.l (D): text(" generated by ") {f_i^(-1)}
                             text(" with ") 1 in shf.o_X|_(U_i) isoto f_i^(-1)
                             in shf.l|_(U_i) \
                           & mapsto { (U_i, (f_i^(-1))^(-1)) } = D.
      $

    - For any invertible $shf.o_X$-submodule $shf.l subset shf.k$ with
      $f_i in shf.l|_(U_i) isoto 1 in shf.o_X|_(U_i)$, we have
      $
        shf.l mapsto { (U_i, f_i^(-1)) } = D
        mapsto shf.l (D): text(" generated by ") { (f_i^(-1))^(-1) } = {f_i},
      $
      whence $shf.l (D) = shf.l$.

  *(b).* By choosing a common refinement of open covers, assume
  $D_1 = { (U_i, f_i) }$ and $D_2 = { (U_i, g_i) }$, where
  $f_i, g_i in shf.k^times (U_i)$. Then $D_1 + D_2 = { (U_i, f_i g_i) }$.
  For each $x in X$,
  $
    shf.l (D_1 + D_2)_x & = shf.o_x spn { (f_i g_i)^(-1)_x }
                          = shf.o_x spn { (f_i)^(-1)_x (g_i)^(-1)_x } \
                        & = (shf.l (D_1) shf.l (D_2))_x,
  $
  whence
  $
    shf.l (D_1 + D_2) = shf.l (D_1) dot shf.l (D_2)
    isoBy("(6.F)") tensor(shf.l (D_1), shf.l (D_2), over: shf.o_X).
  $

  *(c).* By (b), it suffices to show that
  $D := D_1 - D_2$ is principal iff $shf.l (D) simeq shf.o_X$.

  - $(Rightarrow)$ If $D tilde.op 0$, then $shf.l (D) simeq shf.o_X$. Indeed, if
    $D = { (X, f) }$, then $shf.l (D)$ is globally generated by $f^(-1)$.

  - $(Leftarrow)$ If $shf.l (D) simeq shf.o_X$, say
    $f in shf.l (D)(X) isoto 1 in shf.o_X (X)$. Thus
    ${ (X, f^(-1)) }$ is principal.
]

// Hartshorne II.6, Corollary 6.14
#corollary(number: 6.14)[
  For any scheme $X in cat.sch$, we have an injective group homomorphism
  $
    ops.cacl (X) -> ops.pic (X), quad D mapsto shf.l (D),
  $
  where $ops.cacl (X)$ denotes the group of Cartier divisors modulo linear
  equivalence.
]

// Hartshorne II.6, Remark 6.14.1
#remark(title: "6.14.1")[
  The injection $ops.cacl (X)->ops.pic (X)$ need not be surjective: an invertible sheaf
  need not embed into the total quotient sheaf. Proposition 6.15 shows that
  integrality is sufficient for surjectivity.
]

// Hartshorne II.6, Proposition 6.15
#proposition(number: 6.15)[
  If $X$ is an integral scheme, then the homomorphism in _(6.14)_ is an
  isomorphism.
]

#proof[
  - From _(6.14)_, it suffices to show that the homomorphism
    $ops.cacl (X) -> ops.pic (X)$ is surjective. By _(6.13a)_, we only have to show
    that every invertible sheaf is isomorphic to a subsheaf of $shf.k_X$.

  - Since $X$ is integral, it follows from _(6.Ciii)_ that $shf.k_X$ is the
    constant sheaf of $K = K(X)$.

  - For any $shf.l in ops.pic (X)$, consider
    $shf.m := tensor(shf.l, shf.k_X, over: shf.o_X) in cat.mod(shf.o_X)$. Since $shf.l$ is invertible,
    there exists an open cover ${U_i}$ of $X$ such that
    $shf.l|_(U_i) simeq shf.o_X|_(U_i)$. Then
    $
      shf.m|_(U_i) simeq tensor(shf.l|_(U_i), shf.k_X|_(U_i), over: shf.o_X|_(U_i))
      simeq shf.k|_(U_i)
    $
    is the constant sheaf of $K$ for every $i$. Further, $X$ is irreducible,
    so $shf.m simeq shf.k_X$ is the constant sheaf of $K$ by _(6.Cii)_.

  - Therefore, we have the natural injective morphism
    $shf.l arrow.r.hook tensor(shf.l, shf.k_X, over: shf.o_X) simeq shf.k_X$, i.e. we may regard
    $shf.l$ as a subsheaf of $shf.k_X$.
]

// Hartshorne II.6, Corollary 6.16
#corollary(number: 6.16)[
  If $X$ is an integral, separated, Noetherian, locally factorial scheme, then
  there is a natural isomorphism $ops.cl (X) isoto ops.pic (X)$.
]

#proof[
  Indeed,
  $ops.cl (X) isoBy("(6.11)") ops.cacl (X) isoBy("(6.15)") ops.pic (X)$.
]

// Hartshorne II.6, Corollary 6.17
#corollary(number: 6.17)[
  If $X = sch.p_k^n$ for any field $k$, then every invertible sheaf on $X$ is
  isomorphic to $shf.o_X (l)$ for some $l in ZZ$.
]

#proof[
  Since $X = sch.p_k^n$ satisfies the condition of _(6.11)_, we have the
  following one-to-one correspondence:

  #align(center)[
    #diagram(
      $
        ZZ edge("r", text("(6.4)"), arrow.l.r)
        & ops.cl (X) edge("r", text("(6.11)"), arrow.l.r)
        & ops.cacl (X) edge("r", text("(6.15)"), arrow.l.r)
        & ops.pic (X) \
        1 edge("r", mapsto)
        & H = V_+(x_0) edge("r", mapsto)
        & D = { (U_i, x_i / x_0) }_(i=0)^n edge("r", mapsto)
        & shf.l (D)
      $,
    )
  ]

  Indeed:

  - *(6.4).* Write $S := k[x_0, dots.c, x_n]$. Then the function field is
    $K = S_((0)) = (ops.frac S)_0$. Further, $x_0$ corresponds to the prime ideal
    $idl.p = (x_0)$ of height $1$, so we have the DVR given by
    $S_(idl.p) = k[{x_j / x_i : i != 0}]$ with its maximal ideal generated by
    $x_0 / x_i$. Thus $nu_H (x_0 / x_i) = 1$.

  - *(6.11).* Set $U_i := D_+(x_i)$, the usual open cover of $ops.proj S$. Then
    $
      x_i / x_0 in (ops.frac S)_0^times = K^times = shf.k_X^times (U_i)
    $
    and
    $
      x_i / x_j in k[{x_k x_l \/ (x_i x_j) : 0 <= k, l <= n}]^times
      = S_((x_i x_j))^times simeq shf.o_X^times (U_i inter U_j).
    $
    Further, $Gamma_ast (shf.o_X) simeq S$ by _(5.13)_, i.e.
    $shf.o_X (d)(X) = S_d$ for every $d >= 0$.

  - *(6.15).* The subsheaf $shf.l (D) subset shf.k_X$ is generated by
    ${ x_0 / x_i }_(i=1)^n$.

  We show that $shf.l (D) simeq shf.o_X (1)$ so that the generator
  $1 in ZZ$ corresponds to the generator $shf.o_X (1) in ops.pic (X)$. Consider
  the morphism $psi: shf.l (D) -> shf.o_X (1)$ given by
  $
    psi_(U_i): shf.l (D)(U_i) -> shf.o_X (1)(U_i) simeq (S_(x_i))_1, quad
    x_0 / x_i mapsto x_0 / 1
  $
  for each $i$, which is clearly an isomorphism by the definition of $shf.l (D)$.
  Thus $psi: shf.l (D) isoto shf.o_X (1)$, and therefore we have the group
  isomorphism
  $ (ZZ, +) isoto (ops.pic (X), tensor), quad l mapsto shf.o_X (l). $
]

// Hartshorne II.6, Definition D12
#definition(title: "Effective Cartier Divisors")[
  - A Cartier divisor ${ (U_i, f_i) } in ops.cdiv (X)$ is *effective* if
    $f_i in Gamma(U_i, shf.o_X|_(U_i))$ for every $i$.

  - In this case, define the *associated subscheme* $Y$ to be the closed
    subscheme of codimension $1$ defined by the sheaf of ideals $shf.i$ which is
    locally generated by $f_i$.
]

// Hartshorne II.6, Remark 6.17.1
#remark(title: "6.17.1")[
  If $X in cat.sch$ satisfies the condition of _(6.11)_, then the definition above
  gives a one-to-one correspondence under the isomorphism in _(6.11)_:
  $
    {D in ops.div (X) : text("effective")}
    arrow.l.r.double.long
    {D in ops.cdiv (X) : text("effective")}.
  $
]

// Hartshorne II.6, Proposition 6.18
#proposition(number: 6.18)[
  Let $D in ops.cdiv (X)$ be an effective Cartier divisor and let $Y$ be the
  associated *locally principal* closed subscheme, i.e. whose sheaf of ideals is
  locally generated by a single element. Then $shf.i_Y simeq shf.l (-D)$.
]

#proof[
  The sheaf $shf.l (-D)$ is a subsheaf of $shf.k_X$ locally generated by $f_i$ on
  $U_i$. Since $D$ is effective, $f_i in shf.o_X (U_i)$ for each $i$, which
  implies that $shf.l (-D)$ is in fact a subsheaf of $shf.o_X$. Therefore,
  $shf.l (-D) simeq shf.i_Y$, the ideal sheaf of $Y$.
]
