#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Weil Divisors

// Hartshorne II.6, Definition D1
#definition(number: none, title: "Regular in Codimension One")[
  A scheme is *regular in codimension one* if every one-dimensional local
  ring $shf.o_(X,x)$ is regular.
]

#emph-box()[
  *Axiom $(star)$.* Throughout this section, $X$ is a Noetherian, integral,
  separated scheme, which is regular in codimension $1$, i.e. every local ring
  $shf.o_x$ of dimension $1$ is regular.
]

// Hartshorne II.6, Definition D2
#definition(title: "Weil Divisors")[
  Fix a scheme $X in cat.sch$ satisfying $(star)$.

  - *(Prime Divisor).* A *prime divisor* on $X$ is a closed integral
    subscheme $Y$ such that $ops.codim(Y, X) = 1$.

  - *(Weil Divisor).* Let
    $
      ops.div (X) := text("the free abelian group generated by the prime divisors").
    $
    Its elements are called *Weil divisors*.

  - *(Effective Divisors).* An *effective divisor* is a (Weil) divisor
    $D = sum_i n_i Y_i in ops.div (X)$ with $n_i >= 0$ for every $i$.
]

#remark[
  Let $X in cat.sch$ satisfy $(star)$, and let $Y$ be a prime divisor.

  - As $Y$ is integral, it has a unique generic point $eta in Y$. Consider the
    local ring $shf.o_(X, eta)$. Let $U = ops.spec A$ be an open affine neighborhood
    of $eta in X$, say $eta = idl.p in ops.spec A$. By the axiom, $A$ is a
    Noetherian integral domain, so is its localization
    $A_idl.p = shf.o_(U, eta) = shf.o_(X, eta)$. Further,
    $
      dim shf.o_(X, eta) = ops.codim(overline({eta}), X) = ops.codim(Y, X) = 1.
    $
    Again from the axiom, $shf.o_(X, eta)$ is regular. Therefore, the local ring
    $shf.o_(X, eta)$ is a DVR.

  - Since $X$ is also an integral scheme, it has a unique generic point
    $mu in X$ (caution: $mu$ may not be the same as $eta$). By _(4.A)_, we
    have $ops.frac shf.o_(X, eta) = k(mu) =: K$, the function field of $X$.

  - As $shf.o_(X, eta)$ is a DVR in $K$, there exists a discrete valuation
    $nu_Y: K^times -> ZZ$ such that
    $
      shf.o_(X, eta) = { f in K : nu_Y (f) >= 0 } union {0}, \
      idl.m_(X, eta) = { f in K : nu_Y (f) > 0 }, \
      shf.o_(X, eta)^times = { f in K : nu_Y (f) = 0 },
    $
    where $idl.m_(X, eta) := ideal(pi)$ is principal with $nu_Y (pi) = 1$.

  - Since $X$ is separated, by _[4.5]_, such $Y$ is uniquely determined by
    $nu_Y$. *Why?*

  - Fix $f in K^times$. We say that $f$ has a *zero* [resp. *pole*] along $Y$
    of order $abs(nu_Y (f)) in ZZ_(>0)$ if $nu_Y (f) > 0$
    [resp. $nu_Y (f) < 0$].
]

#remark[
  If $X = ops.spec A$ is affine, there is a one-to-one correspondence
  $
    {Y subset X : text("prime divisor")} & arrow.l.r.double.long {idl.p in ops.spec A : ops.ht idl.p = 1}, \
                            ops.spec (A \/ idl.p) & arrow.long.l idl.p.
  $
]

#proof[
  Indeed, we see that

  - $Y subset X$ is a closed subscheme iff $Y simeq ops.spec (A \/ idl.a)$ for some
    $idl.a lt.closed A$.
  - $Y$ is an integral scheme iff $A \/ idl.a$ is an integral domain iff
    $idl.a = idl.p lt.closed A$ is a prime ideal.
  - Further, $ops.codim(Y, X) = dim A - dim(A \/ idl.p) = ops.ht idl.p$.
]

#definition(title: "Regular Functions")[
  Given an integral scheme $X$, we say:

  - $f in K(X)$ is *regular* at $x in X$ if
    $f in shf.o_(X, x) arrow.r.hook_(text("(4.A)")) K(X)$.

  - $f in K(X)$ is *regular* on an open affine subset $U = ops.spec A$ of $X$ if
    $f in shf.o_X (U) = A arrow.r.hook_(text("[3.6]")) K(X)$.
]

// Hartshorne II.6, Lemma 6.1
#lemma(number: 6.1)[
  Let $X in cat.sch$ satisfy $(star)$, and let $f in K^times$ be a nonzero function
  on $X$. Then the valuation $nu_Y (f) = 0$ for all but finitely many prime
  divisors $Y$ on $X$.
]

#proof[
  - Let $U = ops.spec A$ be an open affine subset of $X$ on which $f$ is regular,
    i.e. $f in shf.o_X (U)$. Then $Z := X - U$ is a proper closed subset of
    $X$.

  - If $ops.codim(Z, X) > 1$, then $Z$ cannot contain a subscheme $Y$ with
    $ops.codim(Y, X) = 1$, i.e. $Z$ cannot contain a prime divisor of $X$. If
    $ops.codim(Z, X) = 1$ and if $Y$ is a prime divisor of $X$ contained in $Z$,
    then $Y$ is an irreducible component of $Z$. Since $X$ is a Noetherian
    scheme, it is a Noetherian topological space, so is its subspace $Z$ with
    induced topology. By _(I, 1.5)_, $Z$ has finitely many irreducible
    components, so there are only finitely many such prime divisors
    $Y subset Z$ of $X$; all the others must meet $U$.

  - To see the prime divisors which meet $U$, it suffices to consider the prime
    divisors $Y$ of $U$, since $U subset X$ is open. It remains to show that
    there are only finitely many prime divisors $Y$ of $U = ops.spec A$ for which
    $nu_Y (f) != 0$.

  - Recall from the proof of _[2.9]_ that every open subset $V subset Y$ must
    contain its generic point $eta$. Then for the open subset $U subset X$, the
    inclusion $shf.o_X (U) arrow.r.hook K$ can be factored as
    $shf.o_X (U) -> shf.o_(X, eta) arrow.r.hook K$, which gives
    $shf.o_X (U) arrow.r.hook shf.o_(X, eta)$. Now we may view
    $f in shf.o_(X, eta)$, so $nu_Y (f) >= 0$.

  - If $Y$ is a prime divisor of $U = ops.spec A$, it corresponds to some prime
    ideal $idl.p lt.closed A$, i.e. $Y = V(idl.p) simeq ops.spec (A \/ idl.p)$ from the
    remark. Then
    $
      nu_Y (f) > 0 & arrow.l.r.double.long f in idl.m_(X, eta) = idl.p A_idl.p \
                   & arrow.l.r.double.long f in idl.p \
                   & arrow.l.r.double.long sqrt(ideal(f)) subset sqrt(idl.p) = idl.p \
                   & arrow.l.r.double.long Y = V(idl.p) subset V(ideal(f)).
    $

  - Since $X$ is integral, $A = shf.o_X (U)$ is a reduced integral domain, i.e.
    $ideal(0) = ops.nil (A) in ops.spec A$. Since $f in K^times$ is nonzero,
    $f in.not ops.nil (A)$, so $W := V(ideal(f)) subset U$ is a proper closed
    subset by _[AM, 1.17ii]_. Moreover, $X$ is Noetherian, so is its open
    affine subset $U$, hence $U$ is a Noetherian topological space. Again by
    _(I, 1.5)_, $W$ can contain only finitely many irreducible closed subsets
    $Y subset U$ with $ops.codim(Y, X) = 1$, i.e. there can only be finitely many
    prime divisors $Y$ for which $nu_Y (f) > 0$.
]

// Hartshorne II.6, Definition D3
#definition(number: none, title: "Principal Divisor")[
  For $0!=f in K(X)$, define
  $ops.dv (f)=sum_Y nu_Y (f) Y$. Lemma 6.1 makes the sum finite. Divisors of this
  form are *principal*.
]

// Hartshorne II.6, Definition D4
#definition(number: none, title: "Linear Equivalence and Class Group")[
  Divisors $D,D'$ are *linearly equivalent*, written $D tilde.op D'$, if
  $D-D'$ is principal. The quotient of $ops.div (X)$ by principal divisors is the
  divisor class group $ops.cl (X)$.
]

// Hartshorne II.6, Proposition 6.2
#proposition(number: 6.2)[
  Let $A$ be a Noetherian domain. Then
  $
    A text(" is a UFD")
    arrow.l.r.double.long
    X = ops.spec A text(" is normal and ") ops.cl (X) = 0.
  $
]

#proof[
  - If $A$ is a UFD, then it is integrally closed, whence $X = ops.spec A$ is
    normal.

  - From _(I.1.12)_, it suffices to show that if $A$ is an integrally closed
    Noetherian domain, then every prime ideal of height $1$ is principal iff
    $ops.cl (ops.spec A) = 0$.

  - $(Rightarrow)$ Suppose every prime ideal of height $1$ is principal.

    - Consider a prime divisor $Y$ of $X$, and let $idl.p in ops.spec A$ be its
      corresponding prime ideal of height $1$. By assumption, say
      $idl.p = ideal(f)$ for some $f in A$. Further, $idl.p = eta in Y$ is its unique
      generic point, so $shf.o_(X, eta) = A_idl.p$ is a DVR with unique maximal ideal
      $idl.m_eta = idl.p A_idl.p = ideal(f / 1)$. It follows that
      $nu_Y (f) = nu_Y (f) - nu_Y (1) = nu_Y (f / 1) = 1$ since
      $
        shf.o_(X, eta)
        = {x in K^times : nu_Y (x) > 0}
        union {x in K^times : nu_Y (x) = 0}
        = idl.m_eta union shf.o_(X, eta)^times.
      $

    - If $Z subset X$ is another prime divisor with corresponding prime ideal
      $idl.q = mu$, then since $f in A$ and $A$ is integral, we have
      $f / 1 in A_idl.q = shf.o_(Z, mu)$, so $nu_Z (f) = nu_Z (f / 1) >= 0$. If
      $nu_Z (f / 1) > 0$, then $f / 1 in idl.m_mu = idl.q A_idl.q$, i.e. $f in idl.q$.
      This implies that $idl.p = ideal(f) subset idl.q$. But $ops.ht idl.p = ops.ht idl.q = 1$,
      so $idl.p = idl.q$, whence $Z = overline({mu}) = overline({eta}) = Y$, a
      contradiction. Thus $nu_Z (f) = 0$ whenever $Z != Y$, i.e.
      $ops.dv (f) = 1 dot Y$.

    - Finally, for any divisor $D in ops.div (X)$, we have
      $
        D := sum_(text("finite")) n_i Y_i
        = sum_(text("finite")) n_i ops.dv (f_i)
        = ops.dv (product_(text("finite")) f_i^(n_i)),
      $
      which is a principal divisor. Therefore, $ops.cl (ops.spec A) = 0$.

  - $(Leftarrow)$ Conversely, suppose $ops.cl (ops.spec A) = 0$ and let
    $idl.p in ops.spec A$ with $ops.ht idl.p = 1$.

    - Let $Y = ops.spec (A \/ idl.p)$ be the corresponding prime divisor of $X$ to
      $idl.p$. Since $A$ is an integrally closed Noetherian domain, so is
      $A_idl.p$. Further, $dim A_idl.p = ops.ht idl.p = 1$, so $A_idl.p$ is a DVR.

    - For the divisor $Y in ops.div (X)$, since $ops.cl (X) = 0$, there exists
      $f in K^times$ such that $Y = ops.dv (f)$. So $nu_Y (f) = 1 > 0$, and hence
      $f in idl.p A_idl.p$, the maximal ideal of $A_idl.p$. But $A_idl.p$ is a DVR, so its
      maximal ideal is principal, say $idl.p A_idl.p = ideal(pi)$. Then
      $nu_Y (pi) = 1$, so $nu_Y (f / pi) = 0$, i.e. $f / pi in A_idl.p^times$.
      Thus $idl.p A_idl.p = ideal(pi) = ideal(f)$.

    - If $idl.q in ops.spec A$ is another prime ideal of height $1$, we have another
      corresponding prime divisor $Z = ops.spec (A \/ idl.q)$. As $ops.dv (f) = Y$, we see
      that $nu_Z (f) = 0$, i.e. $f in A_idl.q$. It follows that
      $f in inter_(ops.ht idl.q = 1) A_idl.q eqBy("(6.3)") A$. Now,
      $f in A inter idl.p A_idl.p = idl.p$, which implies $ideal(f) subset idl.p$.

    - For $g in idl.p$, we have $g / 1 in idl.p A_idl.p$, so
      $nu_Y (g) = nu_Y (g / 1) > 0$. By the similar argument as above, if
      $W subset X$ is any other prime divisor, then $nu_W (g) = 0$. Thus
      $nu_W (g / f) >= 0$, i.e. $g / f in A_idl.q$, for every prime divisor
      $W subset X$ with corresponding prime ideal $idl.q$. Again,
      $g / f in inter_(ops.ht idl.q = 1) A_idl.q eqBy("(6.3)") A$, so
      $g in ideal(f)$. Thus $idl.p subset ideal(f)$, and therefore
      $idl.p = ideal(f)$ is principal.
]

// Hartshorne II.6, Proposition 6.3A
#proposition(
  number: 6.3,
)[
  Let $A$ be an integrally closed Noetherian domain. Then
  $
    A = inter { A_idl.p : idl.p lt.closed A text(" prime with ") ops.ht idl.p = 1 }.
  $
]

#lemma-box(title: "Fact 6.A")[
  Let $X$ be a scheme satisfying $(star)$, and let $x in X$. Then
  $
    x text(" is not in any prime divisor ") Y text(" of ") X
    arrow.l.r.double.long
    x = eta, text(" the unique generic point of ") X.
  $
]

#proof[
  $(Leftarrow)$ Suppose $eta in Y$ for some $Y$. Let $U = ops.spec A$ be an open
  affine neighborhood of $eta in X$. Then $U inter Y$ is a prime divisor of
  $U$, i.e. $U inter Y simeq ops.spec (A \/ idl.p)$ for some $idl.p in ops.spec A$ with
  $ops.ht idl.p = 1$. But $xi = overline(0) in U inter Y$, which corresponds to
  $idl.p in U$, is the generic point of $Y$, so $eta = xi$, i.e. $idl.p = (0)$,
  which contradicts $ops.ht idl.p = 1$.

  $(Rightarrow)$ Let $U = ops.spec A$ be an open affine neighborhood of $x in X$,
  say $x = idl.p$ in $U$. From the assumption, we have
  $idl.p \/ idl.q in.not ops.spec (A \/ idl.q)$ for any $idl.q in ops.spec A$ with $ops.ht idl.q = 1$. Now,
  if $idl.p != (0)$, say $0 != a in idl.p$, then there exists a minimal prime ideal
  $idl.q lt.closed A$ such that $ideal(a) subset idl.q subset idl.p$. By _(I.1.11)_,
  we have $ops.ht idl.q = 1$, whence $idl.p \/ idl.q in ops.spec (A \/ idl.q)$, a contradiction.
  Therefore $idl.p = (0)$ in $U$, i.e. $x = eta$.
]

#lemma(
  number: "6.B", // number: 6.B
)[
  Suppose $X = sch.p_k^n = ops.proj S$ for any field $k$, i.e. $S_0 = k$ and
  $S_+ = lr(chevron.l x_0, dots.c, x_n chevron.r)$ is a maximal ideal of $S$. Then $X$
  satisfies $(star)$, so we may talk about divisors on $X = sch.p_k^n$.

  #set enum(numbering: "i)", spacing: 1em)

  + For any subset $Y subset X$, define
    $I_+(Y) := inter { idl.p : idl.p in Y }$; in particular,
    $I_+(emptyset) = S$. Then $I_+(Y_2) subset I_+(Y_1)$ for any subsets
    $Y_1 subset Y_2 subset X$.

  + If $idl.a lt.closed S$ is any homogeneous ideal, then
    $V_+(idl.a) = emptyset arrow.l.r.double.long sqrt(idl.a) = S$ or $S_+$.

  + If $idl.a lt.closed S$ is any homogeneous ideal with $V_+(idl.a) != emptyset$,
    then $I_+(V_+(idl.a)) = sqrt(idl.a)$.

  + For any $Y subset X$, we have $V_+(I_+(Y)) = overline(Y)$.

  + The operations $I_+(-)$ and $V_+(-)$ set up an inclusion-reversing
    one-to-one correspondence:
    $
      {idl.a lt.closed S : idl.a text(" homogeneous radical ideal with ") idl.a
        text(" not containing ") S_+} \
      arrow.l.r.double.long
      {Y subset X : text("closed subset")}, \
      idl.a mapsto V_+(idl.a), quad I_+(Y) arrow.long.l Y.
    $
    Note that $S arrow.l.r.double.long emptyset$ and $S_+ mapsto emptyset$.
    In particular, this restricts to the one-to-one correspondence between
    the following two subsets:
    $
      ops.proj S =
      {idl.p lt.closed S : idl.p text(" homogeneous prime ideal with ") idl.p
        text(" not containing ") S_+}\
      arrow.l.r.double.long
      {Y subset X : text("irreducible closed subset")}.
    $

  + Further, the correspondence above yields:
    $
      {idl.p in ops.proj S : ops.ht idl.p = 1} & arrow.l.r.double.long
                                   {Y subset sch.p_k^n : text("prime divisor, i.e. irreducible hypersurface")} \
                                 & arrow.l.r.double.long
                                   {f in S : text("homogeneous and irreducible, up to associates")}, \
                        ideal(f) & arrow.long.l V_+(f) arrow.long.l f,
    $
    if we give each closed subset the reduced induced subscheme structure.
]

#proof[
  *(vi).* Clearly, a homogeneous prime ideal with $ops.ht idl.p = 1$ corresponds to an
  irreducible closed subset with $ops.codim(Y, X) = 1$, and note that
  $ops.ht S_+ = ops.ht (lr(chevron.l x_0, dots.c, x_n chevron.r)) = n + 1 > 1$. This gives the first
  correspondence. For the second:

  - Given such $idl.p$ with $ops.ht idl.p = 1$. As $S = k[x_0, dots.c, x_n]$ is a UFD,
    it follows from _(I.1.12)_ that $idl.p = ideal(f)$ is principal for some
    homogeneous $f in S$. Further, $S$ is an integral domain, so $f$ is
    irreducible.

  - Given an irreducible homogeneous polynomial $f in S$. Since $S$ is a UFD,
    $ideal(f) lt.closed S$ is a homogeneous prime ideal and obviously does not
    contain $S_+$, whence $ideal(f) in ops.proj S$. Moreover, as $S$
    is Noetherian, _(I.1.11)_ implies that $ops.ht ideal(f) = 1$.
]

// Hartshorne II.6, Proposition 6.4
#proposition(number: 6.4)[
  Let $X = sch.p_k^n$ for any field $k$. For any divisor $D = sum n_i Y_i$,
  define the degree of $D$ by
  $deg D := sum n_i deg Y_i$, where $deg Y_i$ is the degree
  of the hypersurface $Y_i$, i.e. if $Y_i = V_+(f_i)$, then
  $deg Y_i = deg f_i$. Let $H = V_+(x_0)$ be the hyperplane.
  Then:

  #set enum(numbering: "a)", spacing: 1em)

  + If $D$ is any divisor of degree $d$, then $D tilde.op d H$.
  + For any $f in K^times$, $deg ops.dv (f) = 0$.
  + The degree function gives an isomorphism
    $deg: ops.cl (X) -> ZZ$.
]

#proof[
  *(b).* Suppose $S = k[x_0, dots.c, x_n]$ is the homogeneous coordinate ring
  of $X = sch.p_k^n$.

  - The function field $K$ of $X$ is $S_((0)) = (ops.frac S)_0$.

  - If $g in S_d$ with $d >= 0$ is a homogeneous polynomial, then as $S$ is a
    UFD, we may factor $g$ into irreducible polynomials
    $g = a g_1^(n_1) dots.c g_r^(n_r)$, where $a in k$ and
    $g_i in S^h$ is irreducible. By _(6.B)_, each $Y_i := V_+(g_i)$ is a
    hypersurface of degree $d_i = deg g_i$. Now we may extend the
    function $ops.dv: K^times -> ops.div (X)$ to $S^h -> ops.div (X)$ by letting
    $ops.dv (g) := sum n_i Y_i in ops.div (X)$. This makes sense since
    $nu_(Y_i) (g) = nu_(g_i) (g) = n_i$. It follows that
    $
      deg ops.dv (g) = sum_(i=1)^r n_i deg Y_i
      = sum_(i=1)^r n_i d_i = deg g = d.
    $

  - For any $f in K^times = (ops.frac S)_0$, write $f := g / h$ with
    $g, h in S_d$ and $d >= 0$. Then
    $ops.dv (f) = ops.dv (g) - ops.dv (h)$, since $nu_(g_i) (h) = 0$ for every $i$ and
    similarly for $h$, whence
    $
      deg ops.dv (f) = deg ops.dv (g) - deg ops.dv (h) = d - d = 0.
    $

  *(a).* Suppose $D in ops.div (X)$ is any divisor of degree $d$.

  - We may write $D := D_1 - D_2$ such that both $D_1$ and $D_2$ are effective
    divisors of degrees $d_1, d_2 >= 0$, respectively.

  - For any prime divisor $Y_i$, it corresponds to an irreducible homogeneous
    polynomial $h_i in S$ from _(6.B)_, i.e. $Y_i = V_+(h_i)$. Now, for
    $j = 1, 2$, set $g_j := product_(text("finite")) h_i^(n_(i j)) in S^h$.
    Then
    $
      D_j = sum_(text("finite")) n_(i j) Y_i
      = sum_(text("finite")) n_(i j) ops.dv (h_i)
      = ops.dv (g_j),
    $
    where
    $deg g_j = sum_(text("finite")) n_(i j) deg h_i
    = deg D_j = d_j$.

  - Finally, take $f := g_1 / (x_0^d g_2)$. Then
    $
      deg f = deg g_1 - (d deg x_0 + deg g_2)
      = d_1 - d - d_2 = 0,
    $
    whence $f in (ops.frac S)_0 = K^times$. Thus
    $
      D - d H = ops.dv (g_1) - ops.dv (g_2) - d ops.dv (x_0) = ops.dv (f)
    $
    is a principal divisor, and therefore $D tilde.op d H$.

  *(c).* From above, we obtain a group homomorphism
  $deg: ops.div (X) -> ZZ$.

  - By (b), the group of principal divisors is contained in
    $ops.ker (deg)$.

  - By (a), if $deg D = 0$, then $D tilde.op 0$, i.e. $ops.ker (deg)$ is
    contained in the group of principal divisors. Further, for any
    $d in ZZ$, we have $d H mapsto d$. Therefore, this lifts to a group
    isomorphism $deg: ops.cl (X) isoto ZZ$ by the isomorphism theorem.
]

// Hartshorne II.6, Proposition 6.5
#proposition(number: 6.5)[
  Let $X in cat.sch$ satisfy $(star)$. Suppose $Z subset X$ is a proper closed
  subset and $U := X - Z$. Then:

  #set enum(numbering: "a)", spacing: 1em)

  + There is a surjective homomorphism
    $
      ops.cl (X) -> ops.cl (U), quad
      D = sum n_i Y_i mapsto sum_(Y_i inter U != emptyset) n_i (Y_i inter U).
    $

  + If $ops.codim(Z, X) >= 2$, then $ops.cl (X) -> ops.cl (U)$ is an isomorphism.

  + If $Z subset X$ is an irreducible subset of codimension $1$, then there is
    an exact sequence
    $
      ZZ -> ops.cl (X) -> ops.cl (U) -> 0,
    $
    where the first map is defined by $1 mapsto 1 dot Z$.
]

#proof[
  *(a).* We proceed by the following steps:

  - Let $Y subset X$ be any prime divisor such that $Y inter U != emptyset$. I
    claim that $Y inter U$ is a prime divisor of $U$. Note that $U$ also
    satisfies $(star)$. Since $Y inter U arrow.r.hook U$ is the base change of
    the closed immersion $Y arrow.r.hook X$ via $U arrow.r.hook X$, it is also
    a closed immersion. Also, $Y inter U$ is an integral scheme as it is an open
    subscheme of the integral scheme $Y$. Further, the codimension remains the
    same on its nonempty open subset, so $Y inter U$ is indeed a prime divisor
    of $U$.

  - Now define $phi: ops.div (X) -> ops.div (U)$ on prime divisors by
    $phi(Y) = Y inter U$ if $Y inter U != emptyset$, and $phi(Y) = 0$
    otherwise. Since $Z subset X$ is a proper closed subset and
    $X in cat.top$ is Noetherian, there are only finitely many possibilities of
    $Y$ satisfying $Y subset Z$, i.e. $Y inter U = emptyset$.

  - I claim that $phi$ sends principal divisors of $X$ to those of $U$. Let
    $xi, eta$ be generic points of $X, Y$, respectively, where
    $Y inter U != emptyset$ and $K = shf.o_(X, xi)$. For any $f in K^times$, note
    that $ops.frac shf.o_(U, eta) = ops.frac shf.o_(X, eta) eqBy("(4.A)") K$, so
    $nu_(Y inter U)$ and $nu_Y$ define the same valuation, i.e.
    $nu_(Y inter U) (f) = nu_Y (f)$. Thus
    $
      phi(ops.dv (f))
      = sum_(Y_i inter U != emptyset) nu_(Y_i) (f) (Y_i inter U)
      = sum_(Y_i inter U != emptyset) nu_(Y_i inter U) (f) (Y_i inter U)
      = ops.dv_U (f).
    $
    Therefore, $phi$ induces a group homomorphism $ops.cl (X) -> ops.cl (U)$.

  - Clearly, $ops.cl (X) -> ops.cl (U)$ is surjective since every prime divisor of $U$
    is the restriction of its closure in $X$.

  *(b).* Since $X$ is a Noetherian topological space, decompose $Z$ into
  finitely many irreducible components $Z := union_(i=1)^r Z_i$. If
  $Y subset X$ is a prime divisor with $Y inter U = emptyset$, i.e.
  $Y subset Z$, then $Y subset Z_i$ for some $i$. It follows that
  $
    1 = ops.codim(Y, X) >= ops.codim(Z_i, X) >= ops.codim(Z, X) >= 2,
  $
  a contradiction. Hence
  $
    phi: {Y subset X : text("prime divisor")}
    -> {Y inter U subset U : text("prime divisor")}
  $
  is bijective, and therefore $ops.cl (X) isoto ops.cl (U)$.

  *(c).* If there are no prime divisors $Y subset X$ meeting $U$, then $Z$ is
  the only prime divisor of $X$. This implies
  $ops.ker (ops.cl (X) -> ops.cl (U)) subset ops.im (ZZ -> ops.cl (X))$. The containment
  $(supset)$ is clear, so the sequence is exact at $ops.cl (X)$.
]

// Hartshorne II.6, Proposition 6.6
#proposition(number: "6.6")[
  If $X$ satisfies $(star)$, then $X times sch.a^1$ also satisfies $(star)$ and
  pullback induces $ops.cl (X) simeq ops.cl (X times sch.a^1)$.
]


// Hartshorne II.6, Definition D5
#definition(number: none, title: "Curve")[
  Over an algebraically closed field $k$, a *curve* is an integral separated
  finite-type $k$-scheme of dimension one.
]

// Hartshorne II.6, Proposition 6.7
#proposition(number: "6.7")[
  For a nonsingular curve $X\/k$ with function field $K$, the following are
  equivalent: $X$ is projective; $X$ is proper; $X simeq C_K$, the abstract
  nonsingular curve of valuation rings of $K\/k$; and $X$ is complete in the
  sense that every valuation of $K\/k$ has a center on $X$.
]


// Hartshorne II.6, Proposition 6.8
#proposition(number: "6.8")[
  Let $X$ be a complete nonsingular curve and $Y$ any curve over $k$. For a
  morphism $f:X->Y$, either $f$ is constant or $f$ is surjective and induces
  a finite extension $K(Y) subset.eq K(X)$; in the latter case $f$ is finite.
]


// Hartshorne II.6, Definition D6
#definition(number: none, title: "Degree of a Morphism of Curves")[
  For a finite morphism $f:X->Y$ of curves, define
  $deg f=[K(X):K(Y)]$.
]

// Hartshorne II.6, Definition D7
#definition(number: none, title: "Pullback of Divisors on Curves")[
  For a finite morphism of nonsingular curves and a closed point $Q in Y$,
  define $f^*Q=sum_(P in f^(-1) (Q)) e_P P$, where $e_P$ is the ramification
  index of the DVR extension; extend linearly to $ops.div (Y)->ops.div (X)$.
]

// Hartshorne II.6, Proposition 6.9
#proposition(number: "6.9")[
  If $f:X->Y$ is finite between nonsingular curves, then
  $deg(f^*D)=deg(f) deg(D)$ for every divisor $D$ on $Y$.
]


// Hartshorne II.6, Corollary 6.10
#corollary(number: "6.10")[
  Every principal divisor on a complete nonsingular curve has degree zero.
  Hence degree induces a surjection $ops.cl (X)->ZZ$.
]


// Hartshorne II.6, Remark 6.10.3
#remark(title: "6.10.3")[
  For a smooth plane cubic with a chosen origin, the degree-zero part of the
  divisor class group is naturally the curve itself. This illustrates the
  general split between the discrete degree component and the algebraic
  family represented by the Picard variety.
]
