#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

// Hartshorne I.3, Definition D1
#definition(number: none, title: "Regular Function on a Quasi-affine Variety")[
  Let $Y subset.eq sch.a^n$ be quasi-affine. A function $f: Y -> k$ is *regular
  at* $P in Y$ if some open neighborhood $U$ of $P$ admits polynomials
  $g,h in k[x_1,...,x_n]$ with $h$ nowhere zero on $U$ and $f = g/h$ on
  $U$. It is *regular on* $Y$ if it is regular at every point.
]

// Hartshorne I.3, Lemma 3.1
#lemma(number: "3.1")[
  A regular function is continuous when $k$ is identified with $sch.a^1$ in its
  Zariski topology.
]


// Hartshorne I.3, Definition D2
#definition(number: none, title: "Regular Function on a Quasi-projective Variety")[
  Let $Y subset.eq sch.p^n$ be quasi-projective. A function $f: Y -> k$ is
  *regular at* $P in Y$ if on some open neighborhood $U$ of $P$ it can be
  written $f=g/h$, where $g,h in k[x_0,...,x_n]$ are homogeneous of the same
  degree and $h$ is nowhere zero on $U$. It is regular on $Y$ if it is regular
  at every point.
]

// Hartshorne I.3, Remark 3.1.1
#remark(title: "3.1.1")[
  A regular function on a quasi-projective variety is continuous. Consequently,
  if regular functions $f,g$ on a variety $X$ agree on a nonempty open subset,
  then they agree everywhere: the closed zero set of $f-g$ is dense in the
  irreducible space $X$.
]

// Hartshorne I.3, Definition D3
#definition(number: none, title: "Varieties and Morphisms")[
  Fix an algebraically closed field $k$. A *variety over* $k$ is an affine,
  quasi-affine, projective, or quasi-projective variety. A *morphism*
  $phi: X -> Y$ is a continuous map such that, for every open $V subset.eq Y$
  and every regular function $f:V->k$, the composite
  $f compose phi: phi^(-1) (V) -> k$ is regular. An isomorphism is a morphism
  admitting an inverse morphism.
]

// Hartshorne I.3, Definition D4
#definition(number: none, title: "Global and Local Rings")[
  For a variety $Y$, $shf.o (Y)$ is the ring of all regular functions on $Y$. For
  $P in Y$, the *local ring* $shf.o_(P,Y)$ (or $shf.o_P$) is the ring of germs of
  regular functions near $P$: pairs $(U,f)$ with $P in U$, modulo agreement on
  overlaps. It is local; its maximal ideal consists of germs vanishing at $P$,
  and its residue field is $k$.
]

// Hartshorne I.3, Definition D5
#definition(number: none, title: "Function Field")[
  The *function field* $K(Y)$ consists of equivalence classes of pairs $(U,f)$,
  where $U subset.eq Y$ is nonempty open and $f$ is regular on $U$, two pairs
  being equivalent when their functions agree on the intersection. Its
  elements are the *rational functions* on $Y$.
]

// Hartshorne I.3, Theorem 3.2
#theorem(number: "3.2")[
  Let $Y subset.eq sch.a^n$ be an affine variety with affine coordinate ring
  $A(Y)$.

  #set enum(numbering: "a)", spacing: 0.8em)

  + $shf.o (Y) simeq A(Y)$.
  + For $P in Y$, let $idl.m_P subset.eq A(Y)$ be the ideal of functions vanishing
    at $P$. Then $P mapsto idl.m_P$ is a bijection from $Y$ to the maximal ideals
    of $A(Y)$.
  + $shf.o_P simeq A(Y)_(idl.m_P)$ and $dim shf.o_P = dim Y$.
  + $K(Y)$ is the quotient field of $A(Y)$; it is a finitely generated field
    extension of $k$ with transcendence degree $dim Y$.
]


// Hartshorne I.3, Proposition 3.3
#proposition(number: "3.3")[
  The homeomorphism $phi_i: U_i -> sch.a^n$ of Proposition 2.2, where
  $U_i = {x_i != 0} subset.eq sch.p^n$, is an isomorphism of varieties.
]


// Hartshorne I.3, Theorem 3.4
#theorem(number: "3.4")[
  Let $Y subset.eq sch.p^n$ be a projective variety with homogeneous coordinate
  ring $S(Y)$.

  #set enum(numbering: "a)", spacing: 0.8em)

  + $shf.o (Y) = k$.
  + For $P in Y$, let $idl.m_P subset.eq S(Y)$ be generated by homogeneous
    elements vanishing at $P$. Then $shf.o_P simeq S(Y)_((idl.m_P))$, the degree-zero
    part of the homogeneous localization.
  + $K(Y) simeq S(Y)_(((0)))$.
]


// Hartshorne I.3, Proposition 3.5
#proposition(number: "3.5")[
  If $X$ is any variety and $Y$ is affine, there is a natural bijection
  $op("Hom")(X,Y) simeq op("Hom")_(k text("-alg")) (A(Y),shf.o (X))$.
]


// Hartshorne I.3, Lemma 3.6
#lemma(number: "3.6")[
  Let $X$ be any variety and $Y subset.eq sch.a^n$ affine. A set map
  $psi:X->Y$ is a morphism if and only if every coordinate function
  $x_i compose psi$ is regular on $X$.
]


// Hartshorne I.3, Corollary 3.7
#corollary(number: "3.7")[
  Affine varieties $X$ and $Y$ are isomorphic if and only if their coordinate
  rings $A(X)$ and $A(Y)$ are isomorphic as $k$-algebras.
]

// Hartshorne I.3, Corollary 3.8
#corollary(number: "3.8")[
  The functor $X mapsto A(X)$ is an arrow-reversing equivalence between affine
  varieties over $k$ and finitely generated integral domains over $k$.
]

// Hartshorne I.3, Theorem 3.9A
#theorem(number: "3.9A", title: "Finiteness of Integral Closure")[
  Let $A$ be an integral domain finitely generated over a field $k$, let $K$
  be its quotient field, and let $L\/K$ be a finite algebraic extension. The
  integral closure $A'$ of $A$ in $L$ is a finitely generated $A$-module and a
  finitely generated $k$-algebra.
]


#lemma-box(title: "Fact 3.A")[
  Let $A$ be an integral domain with $K = ops.frac A$.
  Then, for any prime ideal $idl.p lt.closed A$, $A_idl.p$ can be viewed as a subring of $K$, and
  $ A = { A_idl.p : idl.p lt.closed A text("prime ideal") } = { A_idl.m : idl.m lt.closed A text("maximal ideal") }. $
]

#proof[ (Matsumura, Lemma 2, p.8).
  The containment $subset$ is clear, as $A$ is an integral domain. ]

#lemma-box(title: "Fact 3.B")[
  Fix a graded ring $S$. Recall that for any homogeneous prime ideal $idl.p lt.closed S$,
  the localization $S_idl.p$ is a graded $S$-module, which is also a local ring with maximal ideal $idl.p S_idl.p$.

  - Show that its degree-$0$ part $S_((idl.p))$ is also a local ring with maximal ideal
    $(idl.p S_idl.p) inter S_((idl.p))$.
  - In particular, if $S$ is an integral domain and $idl.p = ideal(0)$, the zero ideal,
    show that $S_(((0))) = (ops.frac S)_0$ is a field.
]
