#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Exercises

#exercise(number: "1", title: [Counterexamples to Dedekind Rings])[
  Let $K$ be a field.
  - _(a)_ Is $K[x,y]$ a Dedekind domain?
  - _(b)_ Let $A=K[x^2,x^3]$ be the subring in $K[x]$. Then
    - $K[x]$ is a finitely generated $K[x^2]$-module, hence a Noetherian $K[x^2]$-module. Conclude that $A$ is Noetherian.
    - Every prime ideal in $A$ is maximal, but $A$ is not a Dedekind domain.


]

#proof[
  (a) $K[x,y]$ is not a Dedekind, for the prime ideal $(x)$ is not maximal (since $K[x,y]/(x) equiv K[y]$ is an ID but not a field). Moreover, $(x)$ is strictly contained in the maximal ideal $(x,y)$, (where $K[x,y]/(x,y) equiv K$ is a field).\
  (b) Note that $K[x^2]$ is obviously a Noetherian ring and that the map
  $
    K[x^2] times K[x^2] -> K[x], (f(x^2),g(x^2)) mapsto f(x^2)+x g(x^2),
  $

  is $K[x^2]$-linear and surjective. Hence $K[x]$ is a finitely generated, thus Noetherian $K[x^2]$-module. Moreover, $A=K[x^2,x^3] subset K[x]$ is a $K[x^2]$-submodule, whence $A$ is also a Noetherian $K[x^2]$-module. Since $K[x^2] subset K[x^2,x^3]=A$, it is also a Noetherian $A$-module, i.e. $A$ is a Noetherian ring.\
  Note that the rings
  $
    K[x^2,x^3] equiv K[x,y]/(y^2-x^3)
  $

  are isomorphic (even as a $K$-algebra). Now, consider the $K$-algebra homomorphism
  $
    phi:K[x,y] -> K[t], quad x mapsto t^2 text("and") y mapsto t^3.
  $

  Then the image is the subring $K[t^2,t^3] subset K[t]$, which is an integral domain. By Isomorphism Theorem, $op("ker")phi$ is a prime ideal. Since $K[x,y]/op("ker")phi equiv K[t^2,t^3]$ is not a field, we deduce from *Ch1 \#1* that $op("ker")phi$ is principal, hence it is generated by an irreducible polynomial. Since $y^2-x^3$ is irreducible, it must generate $op("ker")phi$, whence the assertion.\
  The only prime ideals of $K[x,y]$ which survive by taking the quotients are the maximal ideals of the form $(p,g)$ (cf. *Ch1 \#1*). Thus, any prime ideal is maximal. However, $K[x,y]/(y^2-x^3)$ is not integrally closed (cf. *Example 103c*), so it follows that $A$ is not Dedekind.
]


#exercise(number: "2", title: [Valuation Rings])[
  \ Let $A subset K$ be a ring extension with $K$ a field. We call $A$ a *valuation ring* of $K$ if for each $0 eq.not x in K$, either $x in A$ or $x^(-1) in A$.
  - _(a)_ Let $nu:K^times -> bb("Z")$ be a valuation. Then $nu(x^(-1))=-nu(x)$. Conclude that a DVR is a valuation ring.
  - _(b)_ Let $A$ be a valuation ring, then
    - $K=op("Quot")A$.
    - $A$ is a local ring.
    - $A$ is integrally closed in $K$, i.e. any valuation ring is normal.
    - If $B$ is a ring such that $A subset B subset K$, then $B$ is also a valuation ring. [AM, 5.18]


]

#proof[
  (a) Since $nu:K^times -> bb("Z")$ is a group homomorphism, it follows that
  $
    nu(x^(-1))+nu(x)=nu(x^(-1) dot x)=nu(1)=0,
  $

  thus $nu(x^(-1))=-nu(x)$. Since any $A$:\ DVR is of the form
  $
    A := {x in K=op("Quot")A:nu(x) >= 0}
  $

  for some valuation $nu$ on $K$. Thus, either $nu(x) >= 0$ or $nu(x^(-1)) >= 0$, i.e. either $x in A$ or $x^(-1) in A$, whence $A$ is a valuation ring.\
  (b)(i) Since $K$ is a field containing $A$, we have $op("Quot")A subset K$. Conversely, for $x in K^times$, if $x in.not A$, then $a=x^(-1) in A$ since $A$ is a valuation ring, whence $x=frac(1, a) in op("Quot")A$. Thus $K subset op("Quot")A$.\
  (ii) claim. $frak("m")=A without A^times$. As $A$ is a valuation ring, $x in frak("m") arrow.l.r.double$ either $x=0$ or $x^(-1) in.not A$. \
  Now, it suffices to show that $frak("m")$ is an ideal of $A$.
  - ($A frak("m") subset frak("m")$). Let $a in A, x in frak("m")$. If $a x=0$, then clearly $a x in frak("m")$. If $a x eq.not 0$, assume $(a x)^(-1) in A$. Then $x^(-1)=(a x)^(-1) dot a in A$, whence $x in frak("m")$ is a unit, i.e. $frak("m")=B. ( -> arrow.l )$. Thus $(a x)^(-1) in.not A$. From the previous claim, $a x in frak("m")$.
  - (Closed under $+$). Let $0 eq.not x,y in frak("m")$, then $x^(-1),y^(-1) in.not A$ by the previous claim. Consider $x y^(-1) in K=op("Quot")A$. Since $A$ is a valuation ring of $K$, either $x y^(-1) in A$ or $y x^(-1)=(x y^(-1))^(-1) in A$. If $x y^(-1) in A$, then $x+y=(1+x y^(-1)) dot y in A frak("m") subset frak("m")$. Similarly for the case $y x^(-1) in A$. Thus, $x+y in frak("m")$.

  Hence $frak("m")$ is the unique maximal ideal of $A$, i.e. $A$ is a local ring.\
  (iii) Suppose $0 eq.not x in K$ is integral over $A$ and assume $x in.not A$. Since $A$ is a valuation ring, we have $x^(-1) in A$. By assumption, $x$ satisfies
  $
    x^n+a_1 x^(n-1)+ dots.h.c +a_n=0, quad (a_i in A).
  $

  $arrow.r.double 1+ sum_(i=1)^n frac(a_i, x^i)=0. arrow.r.double 1=- sum_(i=1)^n frac(a_i, x^i)$ in $A$. Thus $x=x dot 1=- sum_(i=1)^n frac(a_i, x^(i-1)) in A. ( -> arrow.l )$. Hence $x in A$ and it follows that $A$ is integrally closed in $K$. \
  (iv) Given $0 eq.not x in K$. If $x^(-1) in.not B, because A subset B. therefore x^(-1) in A. because A$ is a valuation ring. $therefore x in A subset B$. If $x in.not B$, a similar argument shows that $x^(-1) in A subset B$. Hence $B$ is a valuation ring in $K$.
]


#exercise(number: "3", title: [The Integral Closure of a Ring])[
  Let $A subset K$ be a ring extension with $K$ a field. The integral closure $overline(A)$ of $A$ in $K$ is the intersection of all valuation rings of $K$ containing $A$.
]

#proof[
  Let $L$ be the algebraic closure of $K$ and we consider the set
  $
    Sigma := {(A,f):A subset.not.eq K text("subring"), f:A -> L text("ring homomorphism")}
  $

  partially ordered by
  $
    (A_1,f_1) <= (A_2,f_2) quad text("if") quad A_1 subset A_2 quad text("and") quad f_2|_(A_1)=f_1.
  $

  It has a maximal element $(B,g)$ by Zorn's Lemma and we use the fact from [AM, 5.21] that $B$ is a valuation ring in $K$. We prove that
  $
    overline(A)= inter.big {B: A subset B subset K text("valuation ring")}.
  $

  "$subset$"\ Let $B$ be a valuation with $A subset B subset K$. Let $x in overline(A)$, then $x$ is integral over $A subset B$. Since $B$ is a valuation ring, by *\#2(b.iii)* $A=overline(A)$ in $K. arrow.r.double x in B. arrow.r.double overline(A) subset B$. It follows that $overline(A) subset inter.big B$.\
  "$supset$"\ Let $x in K without overline(A)$, we claim: there is a valuation ring $A subset B subset K$ with $x in.not B$.\
  $because x in.not overline(A). therefore x in.not A' := A[x^(-1)] subset K$. If $x in A'$, then $x := sum_(i=0)^n a_i x^(-i), (a_i in A)$. Multiply by $x^n$, we have
  $
    x^(n+1)-a_0 x^n- dots.h.c -a_(n-1)x-a_n=0.
  $

  Thus $x in K$ is integral over $A$ and it follows that $x in overline(A). ( -> arrow.l )$ \ $because x^(-1) in A'$ but $x in.not A'. therefore x^(-1)$ is not a unit in $A'. arrow.r.double x^(-1) in frak("m")'$ for some maximal ideal $frak("m")' lt.closed A'$. Consider the map
  $
    f:A' arrow.r.twohead A'/frak("m")' := k' arrow.r.hook k'.
  $

  By the fact we noted above, there is a valuation ring $A subset B subset K$ with $(A,f|_A) <= (B,g)$, i.e. $g|_A=f|_A. because x^(-1) in frak("m")'. therefore f(x^(-1))=0$. If $x in B, because x^(-1) in A' subset B. therefore x dot x^(-1)=1$ in $B$. Now,
  $
    1=g(1)=g(x dot x^(-1))=g(x)g(x^(-1))=g(x)f(x^(-1))=g(x) dot 0=0. quad ( -> arrow.l )
  $

  Thus, $x in.not B$. It follows that $inter.big B subset overline(A)$.
]
