#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== The Ideal Class Group

#definition(number: "136", title: [Fractional Ideal])[
  Let $A$ be a Noetherian integral domain.
  - A *fractional ideal* is a finitely generated $A$-module inside $K=op("Quot")(A)$.
  - The fractional ideal $(b)=b A={b dot a:a in A}$, where $b eq.not 0$, is called *principal*.
  - Fractional ideals inside $A$ (i.e. the usual ideals) are called *integral*.
  - The product of two fractional ideals $frak("a"), frak("b")$ of $A$ is defined by:
  $
    frak("a") dot frak("b") := { sum_(text("finite"))a_i b_i: a_i in frak("a"), b_i in frak("b")}.
  $


]


#remark(number: 137)[
  By multiplying the generators of a fractional ideal $frak("a")$ with a common denominator, we can always find $d in A$ such that $d dot frak("a") subset A$. In fact, the $A$-submodules of $K$ which satisfy this condition are precisely the fractional ideals: $d dot frak("a")$ is finitely generated for $A$ Noetherian, and the map $frak("a") -> A, a mapsto d dot a$ induces an $A$-linear isomorphism.
]


#example(number: 138)[
  Let $A$ be a DVR with maximal ideal $frak("m")=(pi)$ and field of fractions $K=op("Quot")(A)$. Every element $b in K^times$ can be written as $b := u pi^m$, where $m in bb("Z"), u in A^times$. If $frak("a")$ is a fractional ideal, we therefore have $pi^n frak("a") subset A$ for some $n in bb("N")$, and consequently $pi^n frak("a") =(pi^m)$ for some $m in bb("N")$. It follows that $frak("a")=(pi^(m-n))$ and the fractional ideals of $A$ form a group isomorphic to $bb("Z")$.
]


#theorem(number: 139)[
  Let $A$ be a Dedekind domain. The set of fractional ideals $sans("Id")(A)$ is the free abelian group generated by the set of prime ideals. The principal ideals form a subgroup $sans("P")(A)$.
]

#proof[
  Note that the composition law is well-defined and it is obviously commutative. For associativity, one may check that
  $
    (frak("a") frak("b")) frak("c") = { sum a_i b_i c_i:a_i in frak("a"), b_i in frak("b"), c_i in frak("c")} = frak("a")(frak("b") frak("c")).
  $

  The ring $A$ plays the role of an identity element: $frak("a")A= frak("a")$. To show that $sans("Id")(A)$ is a group, it remains to show the existence of an inverse.
  Let $frak("a")$ be a nonzero integral ideal. By *Cor. 132*, there exists an ideal $frak("a")^ast lt.closed A$ and $a in A$ such that $frak("a") frak("a")^ast =(a). because a in A subset K. therefore exists a^(-1) in K. arrow.r.double frak("a") dot (a^(-1) dot frak("a")^ast )=(1)=A$, thus $a^(-1) frak("a")^ast$ is an inverse of $frak("a")$. Now, if $frak("a")$ is a fractional ideal, then $d dot frak("a")$ is an integral ideal of $A$ for some $d in A$, and $d dot (d frak("a"))^(-1)$ will be an inverse for $frak("a")$. \
  It remains to show that the group $sans("Id")(A)$ is freely generated by the prime ideals, i.e. each fractional ideal can be expressed in a unique way as a product of powers of prime ideals. \
  Let $frak("a")$ be a fractional ideal, then $d frak("a")$ is an integral ideal for some $d in A$. We write
  $
    d frak("a") := frak("p")_1^(r_1) dots.h.c frak("p")_m^(r_m) quad text("and") quad (d) := frak("p")_1^(s_1) dots.h.c frak("p")_m^(s_m).
  $

  Thus $frak("a")=frak("p")_1^(r_1-s_1) dots.h.c frak("p")_m^(r_m-s_m)$. The uniqueness follows from the uniqueness of the factorisation for integral ideals.
]


#corollary(number: 140)[
  Let $A$ be a Dedekind domain and $S subset A$ be a multiplicative subset. Then the extension map $A -> S^(-1)A, frak("a") mapsto frak("a")^e=S^(-1) frak("a")$ defines an isomorphism from the subfroup of $sans("Id")(A)$ generated by prime ideals not meeting $S$  to the group $sans("Id")(S^(-1)A)$.
]

#proof[
  As we have recalled in *Prop. 27*, the prime ideals of $S^(-1)A$ (which generate $sans("Id")(S^(-1)A)$) are precisely obtained by extending the prime ideals $frak("p") lt.closed A$ with $frak("p") inter S= nothing$ via $A -> S^(-1)A$. The assertion follows from $sans("Id")(S^(-1)A)=op("langle") frak("q") lt.closed S^(-1)A: text("prime") op("rangle")$.
]


#remark(number: 141)[
  Since extension commutes with the product of ideals, $(frak("a") dot frak("b"))^e=frak("a")^e dot frak("b")^e$, the decomposition $frak("a") := frak("p")_1^(r_1) dots.h.c frak("p")_n^(r_n)$ with $frak("p")_i inter S= nothing$ yields the decomposition $frak("a")^e=(frak("p")_1^e)^(r_1) dots.h.c (frak("p")_n^e)^(r_n)$ of $frak("a")^e$ in $S^(-1)A$.
]


Note that a PID defines always a UFD, the converse being false: $k[x,y]$ is factorial for a field $k$, but $(x,y)$ cannot be principal, since $x$ and $y$ have no common divisor. However, we have the following:
#proposition(number: 142)[
  If a Dedekind domain is a UFD, then it is a PID.
]

#proof[
  Suppose $A$ is a Dedekind UFD. It suffices to show that the nonzero prime ideals $frak("p") lt.closed A$ are principal. It will contain a nonzero element, which is a product of irreducibles. Since $frak("p")$ is prime, it contains one of the irreducible factors $pi$, also by *Cor. 132*, there exists an ideal $frak("p")^ast lt.closed A$ such that $frak("p") frak("p")^ast =(pi)$.
  Again, from *Cor. 132*, there are ideals $frak("q"), frak("q")^ast lt.closed A$ such that
  $
    frak("p") frak("q")=(a), quad frak("q")+frak("p")^ast =A; quad frak("q") frak("q")^ast =(b), quad frak("q")^ast +frak("p")=A,
  $

  for some $a, b in A$.
  - $because (pi b)=frak("p") frak("p")^ast frak("q") frak("q")^ast =(a) frak("p")^ast frak("q")^ast . therefore a|pi b. arrow.r.double exists c in A$ such that $pi b=a c. because A$ is UFD. $therefore$ We have either $pi|a$ or $pi|c$.
  - If $pi|a$, then $frac(a, pi) in A. arrow.r.double (frac(pi, a)) frak("p")^ast =frac(frak("p") frak("q"), frak("p") frak("p")^ast) frak("q")=frak("q")$. Thus any prime ideal dividing $frak("p")^ast$ will also divide $frak("q")$, which contradicts that $frak("q")$ and $frak("p")^ast$ are relatively prime, i.e. $frak("q")+frak("p")^ast =A. ( -> arrow.l )$. Therefore, there is no such ideal $frak("q") eq.not (0)$, so $frak("p")^ast =A$.
  - Similarly, if $pi|c$, then $frac(pi, c) in A. arrow.r.double (frac(pi, c)) frak("p")=frak("q")^ast . ( -> arrow.l )$.

  Hence, $frak("p")=frak("p")A=frak("p") frak("p")^ast =(pi)$ is principal.
]


#definition(number: "143", title: [Ideal Class Group])[
  - The *ideal class group* $sans("Cl")(A)$ is the quotient $sans("Id")(A)/sans("P")(A)$.
  - The *class number* of $A$ is the number $hash sans("Cl")(A)$ if it is finite.
  - If $A=cal("O")_K$ for a number field $K$, we simply speak of the ideal class group, respectively, the class number of $K$.

]


The ideal class group of an algebraic number field can be effectively computed by an algorithm. Unfortunately, we cannot prove this nor the following important result for the lack of time:
#theorem(number: 144)[
  The class number of a number field is finite.
]


We recall that any finitely generated $bb("Z")$-module is the direct sum of its torsion submodule and a free $bb("Z")$-module of rank $r$. We state this without proof:
#theorem(number: 145)[
  Let $A$ be a Dedekind domain.
  - _(a)_ Every finitely generated torsion-free $A$-module $M$ is isomorphic to a direct sum of fractional ideals.
  - _(b)_ Two finitely generated torsion-free $A$-modules $M tilde.equiv frak("a")_1 plus.o dots.h.c plus.o frak("a")_m$ and $N tilde.equiv frak("b")_1 plus.o dots.h.c plus.o frak("b")_n$ are isomorphic iff $m=n$ and $product frak("a")_i equiv product frak("b")_i$ modulo principal ideals.

]


In *Prop. 88* we determined the units of $bb("Z")[i]=cal("O")_(bb("Q")(i))$. Let us now consider a general ring of integers $cal("O")_K$, ($K$: number field). We have $[K:bb("Q")]=r+2s$ embeddings $K arrow.r.hook bb("C")$, where $r$ embeddings factorise via $bb("R")$ and $2s$ which do not. For instance, if $K=bb("Q")[alpha]$, then $r$ is the number of real roots of the minimal polynomial $f_alpha$, while $s$ is the number of complex-conjugated pairs of root which is why the number of embeddings into $bb("C")$ is even: We can always apply complex conjugation.

#theorem(number: "146", title: [Dirichlet's Unit Theorem])[
  The group of units $cal("O")_K^times$ in a number field $K$ is finitely generated. Considered as a $bb("Z")$-module, the rank of its free summand is equal to $r+s-1$.
]


#example(number: 147)[
  For $bb("Q")(i)$, we find $r=0$ and $s=1$. Hence $bb("Z")[i]^times$ is pure torsion. (cf. *Prop. 88*)
]
