#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Field Extensions

#definition(number: "66", title: [Field Extension])[
  A *field extension* is an embedding $K arrow.r.long L$ of two fields $K$ and $L$. In particular, we may view $L$ as a $K$-algebra and thus as a $K$-vector space. It is customary to write $L/K$ for the field extension and $[L:K]$ for $op("dim")_K L$, the *degree* of the field extension. We say a field extension is
  - _(i)_ *finite*, if $op("dim")_K L=[L:K]< oo$.
  - _(ii)_ *algebraic*, if for any $alpha in L$, there exists $f in K[x]$ such that $f(alpha)=0$.

]


#example(number: 67)[
  If $alpha in L$, then $cal("I") := {f in K[x]:f(alpha)=0} lt.closed K[x]$ is an ideal. Unless $cal("I")=(0)$, or $cal("I")=(f)$ for an irreducible monic polynomial $f$, the so-called *minimal polynomial* of $alpha$, since $K[x]$ is a PID. Hence $K(alpha)$ (the subfield of $L$ generated by $K$ and $alpha$) is isomorphic to $K[x]/(f)$. The field extension $K subset K(alpha)$ is called *simple* and is of degree $[K(alpha):K]=op("deg")f$.
]


#proposition(number: 68)[
  A finite field extension is algebraic. But the converse is false!
]

#proof[
  Consider the algebraic extension $bb("Q") subset overline(bb("Q"))= {alpha in bb("C"):alpha text("algebraic over") bb("Q")} subset bb("C")$.\ But $bb("Q")(root(n, 3)) subset overline(bb("Q"))$ has minimal polynomial $x^n-3$ since it is irreducible by *Einstein's Criterion*. It follows that $op("dim")_(bb("Q")) bb("Q")(root(n, 3))=n$. In particular, $op("dim")_(bb("Q")) overline(bb("Q"))= oo$.
]


#definition(number: "69", title: [Algebraically Closed])[
  A field $K$ is called *algebraically closed* if any polynomial $f in K[x]$ splits into linear factors. For instance, $bb("C")$ is algebraically closed (by *Fundamental Theorem of Algebra*).
]


#theorem(number: "70", title: [Algebraic Closure])[
  For any field $K$, there exists an algebraic field extension $K subset L$ such that $L$ is algebraically closed. This field $L$ is determined up to $K$-isomorphism in
  $
    op("Aut")_K(L) := {sigma in op("Hom")(L,L) :sigma|_K=1_K }.
  $

  We therefore speak of the *algebraic closure* and denote it by $overline(K)$.
]


#example(number: 71)[
  Let $K subset L$ be an algebraic field extension with $L$ algebraically closed. We can realise the algebraic closure of $K$ by
  $
    overline(K)={alpha in L:alpha text("algebraic over") K}.
  $

  This is indeed a field and defines an algebraic extension $K subset overline(K)$.\ For instance, $overline(bb("Q"))={alpha in bb("C"):alpha text("algebraic over") bb("Q")}$ yields the algebraic closure of $bb("Q")$.
]


#proposition(number: "72", title: [Normal Extension])[
  Let $K subset L$ be an algebraic field extension. T.F.A.E.:
  - _(a)_ $L$ is a splitting field for a family of polynomials in $K[x]$, i.e. every polynomial from that family splits completely into linear factors in $L[x]$.
  - _(b)_ Every irreducible polynomial in $K[x]$ which has a zero in $L$ splits completely into linear factors in $L[x]$.
  - _(c)_ Every $K$-homomorphism $L -> overline(K)$ restricts to an automorphism of $L$.

  Any algebraic field extension which satisfies one and hence all of these conditions is called a *normal extension*.
]


An important example of normal extensions comes from finite fields:
#theorem(number: 73)[
  Let $bb("F")$ be a finite field. Then $p=op("char") bb("F")>0$ and $bb("F")_p subset bb("F")$ is a normal extension of $bb("F")_p$. In fact, it is the splitting field of $f=x^q-x$, where $q= hash bb("F") =p^n, n := [bb("F"):bb("F")_p]$. The elements of $bb("F")$ are therefore just the zeros of $f$. Moreover, $bb("F")$ is the unique finite field of $q=p^n$ elements (up to isomorphism), and any finite field is isomorphic to one of this type.
]


#definition(number: "74", title: [Separable Polynomial])[
  A polynomial $f in K[x]$ is *separable* if it has only simple roots. An irreducible polynomial $f in K[x]$ is *separable* if either
  - _(i)_ $op("char")K=0$, or
  - _(ii)_ $op("char")K=p$ and $f$ is of the form $f(x)=g(x^(p^r)) , text("where") g in K[x] text("irreducible")$.

  Every zero of $f$ is a $p^r$-th square root of a zero of $g$ has multiplicity $p^r$.
]


#definition(number: "75", title: [Separable Extension])[
  For an algebraic extension $L/K$, $alpha in L$ is *separable* if it is the zero of a separable polynomial. $L/K$ is called *separable* if every $alpha in L$ is separable. In particular, a field $K$ is called *perfect* if any algebraic extension of $K$ is separable.
]


#example(number: 76)[
  The following types of fields are perfect: \
  (a) fields of characteristic 0; (b) finite fields; (c) algebraically closed fields.
]


#theorem(number: 77)[
  Let $K subset L$ be a finite extension. Then T.F.A.E.:
  - _(a)_ $L/K$ is separable.
  - _(b)_ There are separable elements $alpha_1, dots.h.c ,alpha_r in L$ such that $L=K(alpha_1, dots.h.c ,alpha_r)$.
  - _(c)_ $hash op("Hom")_K(L,overline(K))=[L:K]$, where $op("Hom")_K(L,overline(K)) :=$ field morphisms which restrict to the identity on $K$.

]


#definition(number: "78", title: [Trace & Norm])[
  Let $K subset L$ be a finite field extension. The *trace* $op("Tr")_(L/K)(alpha)$ and the *norm* $op("N")_(L/K)(alpha)$ of $alpha in L$ is the trace and determinant of the $K$-linear map\ $sans("T")_alpha:L -> L, x mapsto alpha dot x$, respectively.
]


#proposition(number: 79)[
  Let $L/K$ be a finite separable field extension, $H := op("Hom")_K (L,overline(K))$ and $alpha in L$ with minimal polynomial $f_alpha$. Then \ (a) $f_alpha(alpha)= product_(sigma in H)(t-sigma(alpha))$.
  (b) $op("Tr")_(L/K)(alpha)= sum_(sigma in H)sigma(alpha)$.
  (c) $op("N")_(L/K)(alpha)= product_(sigma in H)sigma(alpha)$.
]


#remark(number: 80)[
  If $K subset L$ is a finite extension, then the minimal polynomial of $alpha in L$ is given by the minimal polynomial of the $K$-linear map $op("T")_alpha$.
]


#theorem(number: "81", title: [Primitive Element Theorem])[
  If $K subset L$ is a finite separable field extension, then $L=K(alpha)$, that is, $K subset L$ is a simple extension. Such an $alpha in L$ is called a *primitive element*.
]


#definition(number: "82", title: [Galois Group])[
  A field extension $K subset L$ is *Galois* if it is normal and separable. In this case, the *Galois group* $op("Gal")(L/K) subset op("Aut")_K L$ of the field extension $K subset L$ is the group of $K$-automorphisms of $L$.
]


#theorem(number: "83", title: [Main Theorem of Galois Theory])[
  Let $K subset L$ be a finite Galois extension with Galois group $G := op("Gal")(L/K)$. Then we have a correspondence between subgoups of $H subset G$ and intermediate field extensions $K subset E subset L$ given by:
  $
    H mapsto E := {x in L:sigma(x)=x, forall sigma in H} text("and") E mapsto H := op("Gal")(L/E).
  $

]


#definition(number: "84", title: [Transcendental Extension])[
  $
    K[x_1, dots.h.c ,x_n] arrow.r.twohead K[beta_1, dots.h.c ,beta_n], x_i arrow.r.long.bar beta_i
  $

  defines an injection $K[x_1, dots.h.c ,x_n] arrow.r.hook L -> 0$. Equivalently, any polynomial relation of the form $f(beta_1, dots.h.c ,beta_n)=0$ where $f in K[x_1, dots.h.c ,x_n]$, implies $f=0$. \ A family $frak("B") := {beta_i }_(i in I)$ is algebraically independent if the previous definition applies to any finite subset of $frak("B")$. It is called a *transcendence base* if in addition $K(frak("B")) subset L$ is algebraic. If $L=K(frak("B"))$ for some transcendence base, then the field extension $K subset L$ is called *purely transcendental*.
]


#proposition(number: "85", title: [Transcendental Degree])[
  Any field extension $K subset L$ admits a (potentially empty) transcendence base $frak("B")$, and therefore can be factorised into a purely transcendental and an algebraic field extension $K subset K(frak("B")) subset L$. Furthermore, any two transcendental bases have the same cardinality. The latter is called the *transcendental degree* $op("trdeg")_K L$.
]
