#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Rings

#notation(number: 2)[
  - _(a)_ We use these notations:
    - $bb("N")={0,1,2, dots.h.c }=$ the monoid of natural numbers.
    - $bb("Z")=$ ring of integers.
    - $bb("Q")=$ field of rational numbers.
    - $bb("R")=$ field of real numbers.
    - $bb("C")=$ field of complex numbers.
    - $bb("F")_p=bb("Z")/p bb("Z")=$ field with $p$ elements, ($p$: prime).

  - _(b)_ Notations for sets and mappings:
    - The empty set is denoted by $nothing$.
    - The cardinality of a set $S$ by $hash S$.
    - A family of elements of a set $A$ indexed by a set $I$, written ${a_i }_(i in I)$, is a function $I -> A, i mapsto a_i$.
    - Given an equivalence relation, $overline(x)$ denotes the equivalence class of $x$.
    - Further, $arrow.r.hook$ and $arrow.r.twohead$ denote the injective and surjective maps, respectively.

  - _(c)_ Relations on sets:
    - $X subset Y$: $X$ is a subset (not necessarily proper) of $Y$.
    - $X tilde.equiv Y$: $X$ is isomorphic to $Y$.
    - $X equiv Y$: $X$ and $Y$ are canonically isomorphic (i.e. there is a given or unique isomorphism).


]



#definition(number: "3", title: [Ring])[
  - _(a)_ A *ring* $(A,+, dot )$ consists of an abelian group $(A,+)$ with neutral element $0$, and an associative multiplication $dot :A times A -> A$ such that for all $a,b,c, in A$,
  $
    a dot (b+c)=a dot b+a dot c quad text("and") quad (b+c) dot a=b dot a+c dot a.
  $

  In this course, a ring will always be assumed to be *commutative with 1*, i.e. multiplication $dot$ is commutative with neutral multiplicative element $1$.
  - _(b)_ A subgroup of a ring $A$ is a *subring* if it contains $1$ and is closed under $dot$.
  - _(c)_ A *unit* $u in A without {0}$ is an element such that there exists $u' in A$ with $u dot u'=1$. \ Units form a multiplicative subgroup of $A$ which we denote by $A^times$. If $1 eq.not 0$ and $A^times =A without {0}$, that is, all nonzero elements are units, then $A$ is called a *field* and usually denoted by $F$.
  - _(d)_ A *ring homomorphism* $phi:A -> B$ is a group homomorphism which satisfies that $phi(1_A)=1_B$ and $phi(a dot b)=phi(a) dot phi(b)$. A *ring isomorphism* is a bijective ring homomorphism, (its inverse is necessarily a ring homomorphism).

]


#definition(number: "4", title: [Ideal])[
  - _(a)_ A subset $cal("I") subset A$ is an *ideal* if it is an abelian subgroup of $A$ and for any $r in A, a in cal("I")$, we have $r dot a in cal("I")$. We denote by $cal("I") lt.closed A$.
  - _(b)_ The ideal *generated* by the subset ${a_i:i in Lambda}$ of $A$ is the set of finite linear combinations of generators $a_i$, i.e.
  $
    cal("I")={ sum_(text("finite"))r_i a_i:r_i in A, i in Lambda}.
  $

  This is indeed an ideal and we denote $cal("I") := (a_i: i in Lambda)$.
  - _(c)_ If $Lambda$ is a finite set, then we say $cal("I")$ is *finitely generated*.
  - _(d)_ An ideal is generated by a single element is called a *principal ideal*.
  - _(e)_ The *null ideal* is the ideal $(0)={0}$ generated by $0$.

]


#example(number: 5)[
  If $phi:A -> B$ is a ring homomorphism, the *kernel* $sans("ker")phi := phi^(-1)(0)$ is an ideal of $A$.
]


#definition(number: "6", title: [Constructions of Ideals])[
  - _(a)_ Let $cal("I")$ and $cal("J")$ be two ideals of $A$. Their *sum* is the ideal
  $
    cal("I")+cal("J") := {a+b:a in cal("I"), b in cal("J")}.
  $

  Their *product* is
  $
    cal("I") dot cal("J") := (a dot b:a in cal("I"), b in cal("J")).
  $

  - _(b)_ Let $phi:A -> B$ be a ring homomorphism and let $frak("b") lt.closed B$. Then its *contraction*, denoted by $frak("b")^c := phi^(-1)(frak("b"))$ is an ideal of $A$.
  - _(c)_ If $frak("a") lt.closed A$ is an ideal, then $phi(frak("a"))$ is, generally, merely a subring of $B$, but not an ideal. The *extension* of $frak("a")$ by $phi$ is the ideal $frak("a")^e := phi(frak("a")) dot B$ generated by $phi(frak("a"))$ in $B$.

]


#example(number: 7)[
  - _(a)_ If $cal("I") := (a_1, dots.h.c ,a_r)$ and $cal("J") := (b_1, dots.h.c ,b_s)$ are two finitely generated ideals, then so are their sum and their product. In fact,
  $
    cal("I")+cal("J")=(a_1, dots.h.c ,a_r,b_1, dots.h.c ,b_s) text("and") cal("I") dot cal("J")= (a_i b_j:1 <= i <= r, 1 <= j <= s).
  $

  - _(b)_ If $frak("a") := (a) lt.closed A$ is principal, then $frak("a")^e={phi(a) dot b:b in B}$.\
    For example, if $frak("a") := (m) subset bb("Z") arrow.r.hook bb("Q")$, then $frak("a")^e=frak("a") dot bb("Q")=bb("Q")$ if $m eq.not 0$.

]


#definition(number: "8", title: [Classes of Rings])[
  - _(a)_ A *zero divisor* $a in A$ divides $0$, i.e. there exists $b in A without {0}$ such that $a dot b=0$. An element $a in A$ is *nilpotent* if $a^n=0$ for some $n in bb("N")$. In particular, a nilpotent $a in A$ is a zero divisor if $a eq.not 0$.
  - _(b)_ A nontrivial ring $A$ is an *integral domain (ID)* / *reduced* if $A$ has no zero divisors/ no nilpotents other than $0$.
  - _(c)_ For an ID A, a nonunit $a in A$ is *irreducible* if $a eq.not 0$ and $a=b dot c$ for $b,c in A$ implies that either $b$ or $c$ is a unit. Further, a nonunit $a$ is called *prime* if $a eq.not 0$ and $a|(b dot c)$ implies either $a|b$ or $a|c$. Moreover, "prime" implies "irreducible", but the converse is false in general.
  - _(d)_ An ID $A$ is a *unique factorisation domain (UFD)* or is *factorial* if every nonunit $0 eq.not a in A$ admits a decomposition $a := a_1 dots.h.c a_r$ into primes unique up to their orders and units. In a UFD, irreducibles are prime.
  - _(e)_ An ID $A$ is a *principal ideal domain (PID)* if it has only principal ideals.
  - _(f)_ A *Euclidean domain (ED)* is an ID $A$ with a function $nu:A without {0} -> bb("N")$ such that for any $f,g in A, g eq.not 0$, there are elements $q,r in A$ with $f=q g+r$ and either $r=0$ or $nu(r)<nu(g)$. We call such $r$ the *remainder* of $f$ by $g$ and write $r equiv f (op("mod") g)$.

]


#remark(number: 9)[
  We have the following implications:
  $
    bold(text("Field")) arrow.r.double.long bold(text("ED")) arrow.r.double.long bold(text("PID")) arrow.r.double.long bold(text("UFD")) arrow.r.double.long bold(text("ID")).
  $

  There are counterexamples to every converse implication.
]


#example(number: 10)[
  Here are important examples of EDs:
  - _(a)_ The integers $bb("Z")$ with $nu(a) := |a|$, the *absolute value* of $a$.
  - _(b)_ The *Gaussian integers* $bb("Z")[i] := {a+i b:a,b in bb("Z")} subset bb("C")$ with $nu(a+i b) := a^2+b^2$, the *norm* of $a+i b$. (cf. *Prop. 88*).
  - _(c)_ The polynomial ring $F[x]$ in one variable over the field $F$ with $nu(f) := op("deg")f$, the *degree* of the polynomial $f$.

]


#definition(number: "11", title: [Multivariable Polynomials])[
  - A *monomial* in the variables $x_1, dots.h.c ,x_n$ is a formal expression\ $x^(alpha) := x_1^(alpha_1) dots.h.c x_n^(alpha_n), quad alpha=(alpha_1, dots.h.c ,alpha_n) in bb("N")^n$.\
    The set of monomials $op("Mon")(x_1, dots.h.c ,x_n) := {x^alpha:alpha in bb("N")^n }$ forms a semi-group with neutral element $1=x_1^0 dots.h.c x_n^0$ via
  $
    x_1^(alpha_1) dots.h.c x_n^(alpha_n) dot x_1^(beta_1) dots.h.c x_n^(beta_n)=x_1^(alpha_1+beta_1) dots.h.c x_n^(alpha_n+beta_n).
  $

  - The *degree* of $x^alpha$ is defined to be the sum $|alpha|=alpha_1+ dots.h.c +alpha_n$. A *polynomial* over $A$ in the variables $x_1, dots.h.c ,x_n$ is a formal finite linear combination of monomials $x^alpha$ over $A$:
  $
    f := sum_(alpha=(alpha_1, dots.h.c ,alpha_n)) a_alpha x_1^(alpha_1) dots.h.c x_n^(alpha_n),
  $

  where $a_alpha in A, a_alpha=0$ for all but finitely many $alpha$.
  - The *support* of $f$ is the set $op("supp")f := {x^alpha:a_alpha eq.not 0}$. For $f eq.not 0$, the *degree* $op("deg")f$ of $f$ is the maximum of all $|alpha|$ such that $x^alpha in op("supp")f$; by convention, we put $op("deg") 0 := -1$ and \ $A[x_1, dots.h.c ,x_n] :=$ set of polynomials in $n$ variables.

]


#definition(number: "12", title: [Ring Structure on the Polynomials])[
  A *term* is a polynomial of the form $a x^alpha$. The ring structure on $A[x_1, dots.h.c ,x_n]$ is defined as follows:
  $
    sum a_alpha x^alpha+ sum b_alpha x^alpha , := sum (a_alpha+b_alpha)x^alpha,; ( sum a_alpha x^alpha) dot ( sum b_alpha x^alpha) , := sum_gamma(sum_(alpha+beta=gamma)a_alpha b_beta)x^gamma.
  $

  If we identify $1 in A$ with $1=x^0$, then $A subset A[x_1, dots.h.c ,x_n]$ as a subring (with the obvious definitions). The elements of $A subset A[x_1, dots.h.c ,x_n]$ will be called the *constant polynomials*, and $A$ is the *base ring*.
]


#proposition(number: 13)[
  - _(a)_ $(A[x_1, dots.h.c ,x_(n-1)])[x_n] equiv A[x_1, dots.h.c ,x_n]$.
  - _(b)_ If $A$ is an ID, then so is $A[x_1, dots.h.c ,x_n]$.
  - _(c)_ (*Gauss Theorem*) If $A$ is a UFD, then so is $A[x_1, dots.h.c ,x_n]$.

]


An important construction method for rings is taking the quotient with respect to an ideal:
#definition(number: "14", title: [Quotient Ring])[
  Let $cal("I") lt.closed A$ be an ideal. Then $a tilde b attach(arrow.l.r.double.long, t: text("Def.")) a-b in cal("I")$ defines an equivalence class $overline(a)=overline(a+b), (b in cal("I"))$. \ The *quotient ring* $A\/cal("I")$ is the ring structure on the closed space ${overline(a):a in A}$ defined by the following operations:
  $
    overline(a)+overline(b) = (a+A)+(b+A) , := (a+b)+A =overline(a+b), ; overline(a) dot overline(b) = (a+A) dot (b+A) , := (a dot b)+A =overline(a dot b).
  $

  In particular, the *projection* or *quotient map* $pi_(cal("I")):A -> A/cal("I"), a mapsto overline(a)=a+A$ becomes a surjective ring homomorphism.
]


#example(number: 15)[
  In $bb("Q")[x,y]/(x^2,x y)$ we have $overline(x)^2=0$ and $overline(x) dot overline(y)=0$. For instance,
  $
    overline(5x^2 y+3x^4+y+1) dot overline(2x+x y+7y^3)= overline(y+1) dot overline(2x+7y^3)=2 overline(x)+7 overline(y)^3 +7 overline(y)^4.
  $

]

It is an important problem to understand the structure of ideals of a given ring as the set of ideals of a ring $A$ can be regarded as a measure for the complexity of $A$.

#lemma(number: "16", title: [Comparison Lemma])[
  - _(a)_ A ring homomorphism $phi:A -> B$ induces a ring isomorphism $A/op("ker")phi equiv op("im") phi$. In particular, if $phi$ is surjective, then $B equiv A/frak("a")$ for some ideal $frak("a") lt.closed A$.
  - _(b)_ The map $frak("b") mapsto frak("b")^e =pi_(frak("a"))(frak("b")) dot (A/frak("a"))$ induces a bijection
  $
    {frak("b") lt.closed A:frak("b") supset frak("a")} , arrow.l.r.long {frak("d") lt.closed A/frak("a")}, ; pi_(frak("a"))^(-1)(frak("d"))=frak("d")^c ,arrow.l.long.bar frak("d") lt.closed A/frak("a").
  $


]



#theorem(number: "17", title: [Chinese Remainder Theorem])[
  Let $frak("a")_1, dots.h.c ,frak("a")_r$ be ideals of $A$ which are pairwise coprimes, i.e. $frak("a")_i+frak("a")_j=A, forall i eq.not j$. Then $frak("a") := inter.big_j frak("a")_j= product_j frak("a")_j$ and the natural map
  $
    A arrow.r.long product_j(A/frak("a")_j), quad a arrow.r.long.bar (a+frak("a")_1, dots.h.c ,a+frak("a")_r)
  $

  induces a ring isomorphism $A/frak("a") equiv product_j(A/ frak("a")_j)$.
]


The following types of ideals are extremely important in algebraic geometry and algebraic number theory:
#definition(number: "18", title: [Prime and Maximal Ideals])[
  - A proper ideal $cal("I") lt.closed.not A$ is *prime* if $a dot b in cal("I")$ implies either $a in cal("I")$ or $b in cal("I")$.
  - A proper ideal $cal("I") lt.closed.not A$ is *maximal* if $cal("I") subset cal("J") subset.not.eq A$ implies $cal("I")=cal("J")$.

]


#lemma(number: 19)[
  - _(a)_ $cal("I") lt.closed A$ is prime $arrow.l.r.double A/cal("I")$ is an ID.
  - _(b)_ $cal("I") lt.closed A$ is maximal $arrow.l.r.double A/cal("I")$ is a field.
  - _(c)_ In particular, a maximal ideal is prime.

]


#example(number: 20)[
  In $bb("Z")$ an ideal $cal("I")=(m)$ is prime iff $m=0$, or $m$ is prime. Moreover, if $m$ is prime, then $cal("I")$ is maximal.
]


#remark(number: 21)[
  - _(a)_ For a field $K$ consider the ring homomorphism $phi:bb("Z") -> K, 1 mapsto 1_K$. Then $op("ker")phi =(m)$ for some $m in bb("Z")$. This integer is called the *characteristic* of $K$, and is denoted by $op("char")K := m$. It follows that the characteristic of a field must be prime, for $bb("Z")/op("ker")phi equiv op("im")phi$ is an ID. For example, $op("char") bb("Q")=0$ and $op("char") bb("Z")_p=p$.
  - _(b)_ If $phi:A -> B$ is a ring homomorphism and $frak("q") lt.closed B$ prime, then so is its contraction $frak("q")^c=phi^(-1)(frak("q"))$. On the other hand, contractions of maximal ideals are not necessarily maximal. (Consider the inclusion $bb("Z") arrow.r.hook bb("Q")$ and $(0) subset bb("Q")$).

]


#lemma(number: 22)[
  - _(a)_ Let $frak("a"), frak("b"), frak("p") lt.closed A$ be ideals with $frak("p")$ prime. If $frak("a") subset.not frak("p")$ and $frak("a") dot frak("b") subset frak("p")$, then $frak("b") subset frak("p")$.
  - _(b)_ Let $frak("a")_1, dots.h.c ,frak("a")_n,frak("p") lt.closed A$ be ideals with $frak("p")$ prime. If $inter.big_(i=1)^n frak("a")_i subset frak("p")$ [respectively, $=$], then $frak("a")_j subset frak("p")$ [respectively, $=$] for some $j$.
  - _(c)_ (*Prime Avoidance*) Let $frak("p")_1, dots.h.c ,frak("p")_n,frak("a") lt.closed A$ be ideals with $frak("p")_i$ prime. If $frak("a") subset union.big_(i=1)^n frak("p")_i$, then $frak("a") subset frak("p")_j$ for some $j$.

]


The structure of prime and maximal ideals of a ring is very important. From this point of view, the following class of rings is particularly simple.
#definition(number: "23", title: [Local Ring])[
  A ring $A$ is *local* if it has exactly one maximal ideal $frak("m")$. The local ring is denoted by $(A,frak("m"))$. The associated field $A/frak("m")$ is called the *residue field*.
]


#proposition(number: 24)[
  The following properties on a ring $A$ are equivalent:
  - _(a)_ $(A,frak("m"))$ is a local ring.
  - _(b)_ All the nonunits of $A$ form an ideal $frak("m")$.
  - _(c)_ There exists an ideal $frak("m") eq.not (1)$ such that every $x in A without frak("m")$ is a unit in $A$.
  - _(d)_ There exists a maximal ideal $frak("m") lt.closed A$ such that $1+frak("m")={1+m:m in frak("m")} subset A^( times )$.

]


#example(number: 25)[
  - _(a)_ Every field is a local ring with maximal ideal $frak("m")=(0)$.
  - _(b)_ Let $frak("p") lt.closed k[x_1, dots.h.c ,x_n]$ be a prime ideal. Then
  $
    A=k[x_1, dots.h.c ,x_n]_(frak("p")) := {frac(f, g):f,g in k[x_1, dots.h.c ,x_n],g in.not frak("p")} subset k(x_1, dots.h.c ,x_n)
  $

  is a local ring with ring structure induced by the field $k(x_1, dots.h.c ,x_n)$. The maximal ideal is
  $
    frak("m")=frak("p") dot k[x_1, dots.h.c ,x_n]_(frak("p"))={frac(f, g):f,g in.not frak("p")}.
  $

  This is just the extension with respect to the injection
  $
    k[x_1, dots.h.c ,x_n] arrow.r.hook A, quad f arrow.r.long.bar frac(f, 1).
  $

  - _(c)_ (*Localisation*) Let $A$ be an ID, then there is a field $K := op("Quot")A$ with canonical injection $A arrow.r.hook K$, the so called *quotient field*. As a set, $K={frac(a, b):a,b in A,b eq.not 0}$ with field operations given by the usual rules for fractions. A *multiplicative subset* $S$ of $A$ is a set which is closed under multiplication and which does not contain $0$. By $S^(-1)A$ we shall denote the set of quotients $frac(a, s) in S^(-1)A$ with $s in S$. This is again a ring with canonical injection $A arrow.r.hook S^(-1)A$.

]


#example(number: 26)[
  A typical example is $A_(frak("p")) := S^(-1)A$, where $S := A without frak("p")$ and $frak("p") lt.closed A$ prime ideal. Further, $A_(frak("p"))$ is a local ring with maximal ideal $frak("m")=frak("p")^e=frak("p")A_(frak("p"))$, which contains precisely of the elements $frac(a, s)$ with $a in frak("p")$. Note that $frak("m") inter A=frak("p")$.
]


#proposition(number: 27)[
  We consider the localisation $S^(-1)A$ of an ID. We consider extension and contraction with respect to the natural map $A -> S^(-1)A$. Then
  $
    frak("b")^(c e) ,=frak("b"), quad forall frak("b") lt.closed S^(-1)A,; frak("p")^(e c) ,=frak("p"), quad forall frak("p") lt.closed A text("prime ideal with") frak("p") inter S= nothing .
  $

  In particular, the prime ideals of $S^(-1)A$ are precisely the extensions of the prime ideals of $A$ which have trivial intersection with $S$.
]


#definition(number: "28", title: [Graded Ring])[
  - A *graded ring* $A$ is a ring with a decomposition $A := plus.o.big_(nu in bb("N"))A_nu$ as a direct sum of abelian groups such that $A_nu dot A_mu subset A_(nu+mu), forall nu,mu in bb("N")$.
  - The $A_nu$ are called the *homogeneous components* of degree $nu$ of $A$.
  - Elements of $A_nu$ are said to be *homogeneous*.
  - A *graded* $k$-*algebra* is a $k$-algebra which is a graded ring for which $A_0=k$ and $A_nu$ is a $k$-vector space for all $n in bb("N")$.

]


#example(number: 29)[
  - _(a)_ Every ring $A$ carries a trivial graded ring structure by setting $A_0=A$ and $A_nu=0$ for $nu >= 1$.
  - _(b)_ If $frak("a") lt.closed A$ is an ideal, then
  $
    op("Gr")_frak("a")(A) = plus.o.big_(nu >= 0) op("Gr")_frak("a")(A)_nu := plus.o.big_(nu >= 0) frak("a")^nu/frak("a")^(nu+1)
  $

  is a graded ring (where by convention, $frak("a")^0 := (1)=A$). Multiplication is given as follows: If $overline(a) in frak("a")^nu/frak("a")^(nu+1)$ and $overline(b) in frak("a")^mu/frak("a")^(mu+1)$, then $overline(a) dot overline(b) := a dot b+frak("a")^(nu mu+1) in frak("a")^(nu+mu)/frak("a")^(nu mu+1)$ (this is indeed well-defined). See also *Def. 304*.
  - _(c)_ Let $A=k[x_1, dots.h.c ,x_n]$ and $w=(w_1, dots.h.c ,w_n)$ be an $n$-tuple of positive integers. We let $op("wdeg")(x^alpha) := sum w_i alpha_i$, which is additive in the $alpha_i$. Let $A_nu$ be the $k$-vector space generated by monomials of $op("wdeg")=nu$. Then $A= plus.o.big_(nu >= 0)A_nu$ is a graded $k$-algebra. The elements of $A_nu$ are called *quasihomogeneous* or *weighted homogeneous* of degree $nu$.

]
