#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Discrete Valuations

#definition(number: "148", title: [Discrete Valuation])[
  Let $K$ be a field. A *discrete valuation* on $K$ is a group homomorphism $nu:K^times -> bb("Z")$ such that
  $
    nu(x+y) >= op("min"){nu(x),nu(y)}, quad text("if") x+y eq.not 0.
  $

  Its image is thus of the form $m b b("Z")$. We say that $nu$ is *normalised* if $m=1$.
]


#remark(number: 149)[
  - _(a)_ It is sometimes convenient to extend the definition of $nu$ to all of $K$ by setting $nu(0) := oo$.
  - _(b)_ We can always pass to a normalised valuation by considering $x mapsto m^(-1)nu(x)$.
  - _(c)_ It follows from the definition that $nu(x^(-1))=-nu(x)$.

]


#example(number: 150)[
  - _(a)_ Let $A$ be a UFD, $K := op("Quot")A$ and $p in A$ a prime. Up to units, any element $x in K^times$ can be written as $x := p^r dot frac(a, b)$, where $p divides.not a,b$, so that the integer is uniquely determined. Then $nu_p(x) := r$ defines a discrete valuation. Take, for example, $A=bb("Z"), K=bb("Q")$ and $p in bb("Z")$ any prime number or $A=k[x], K=k(x)$ and $p=f in k[x]$ any irreducible polynomial.
  - _(b)_ Consider the field $cal("M")$ of meromorphic functions on a connected open subset $cal("U")$ of $bb("C")$. For each $P in cal("U")$ and $f in cal("M")^times$, we define $op("ord")_P(f)$ to be $0, m$ or $-m$ according to whether or not $f(P)$ is a unit in $bb("C")$, or has a zero or a pole of order $m$. Then $op("ord")_P:cal("M")^times -> bb("Z")$ is a discrete valuation.
  - _(c)_ Let $A$ be a Dedekind domain and $frak("p") lt.closed A$ be a prime ideal. For any $x in K^times$, where $K=op("Quot")A$, let $frak("p")^(nu_frak("p")(x))$ be the power of $frak("p")$ in the decomposition of $(x)$. By uniqueness, this defines a discrete valuation $nu_frak("p"):K^times -> bb("Z")$. In particular, a DVR (= local Dedekind domain) gives rise to a natural discrete valuation on its quotient field.

]


Further, there is a converse to *Example 150(c)*:
#proposition(number: 151)[
  Let $nu$ be a discrete valuation on $K$, then
  $
    A := {a in K:nu(a) >= 0}
  $

  is a DVR with maximal ideal and group of units given by
  $
    frak("m")={a in K:nu(a)>0} quad text("and") quad A^times ={a in K:nu(a)=0}.
  $

  Moreover, $frak("m")$ is generated by any element $pi$ with $nu(pi)=1$ and the ideals of $A$ are given by
  $
    frak("m")^n=(pi^n)={x in K:nu(x) >= n}, quad (n >= 0).
  $

]

#proof[
  By *Rmk. 149(b)*, we may pass $nu$ to a normalised valuation $nu:K^times arrow.r.twohead bb("Z")$. Thus $exists pi in K^times$ such that $nu(pi)=1$. Moreover, with operations induced by $K$, $A$ is an ID.\
  *Claim 1.* $A^times ={a in K:nu(a)=0}$.\ proof.
  "$subset$"\ If $a in A^times$, then $exists b in A$ such that $a b=1. because nu(1)=nu(1 dot 1)=nu(1)+nu(1).\ therefore nu(1)=0. arrow.r.double nu(a)+nu(b)=nu(a dot b)=nu(1)=0. because$ Both $nu(a)$ and $nu(b) >= 0. therefore nu(a)=nu(b)=0$. "$supset$"\ Let $0 eq.not x in K$ such that $nu(x)=0$. Then $x in A={a in K^times :nu(a) >= 0}.\ because 0=nu(1)=nu(x dot x^(-1))=nu(x)+nu(x^(-1)). therefore nu(x^(-1))=0. arrow.r.double x^(-1) in A$. Hence $x in A^times$.\
  *Remark.* $forall 0 eq.not x in A={a in K^times :nu(a) >= 0}$, say $nu(x) := n >= 0$. Consider $frac(x, pi^n)=x dot frac(1, pi^n).\ arrow.r.double nu(frac(x, pi^n))=nu(x)+nu(frac(1, pi^n))=n+(-n)=0$. By claim 1 we have $frac(x, pi^n) in A$, it follows that $exists u in A^times$ such that $x=u dot pi^n$. Moreover, $because nu(pi)=1. therefore pi in.not A^times . arrow.r.double 0 eq.not (pi) lt.closed.not A$.\
  *Claim 2.* For any $0 eq.not frak("a") lt.closed.not A, exists l in bb("N")$ such that $frak("a")=(pi^l)$.\ proof.
  Consider $nu|_A:A -> bb("Z")_( >= 0)$ with $frak("a") arrow.r.twohead nu(frak("a"))$. We take $l := op("min"){nu(a):a in frak("a")}$ and check that $(pi^l)=frak("a")$. "$subset$"\ By definition there is $a in frak("a")$ such that $nu(a)=l$. Note that from remark, $nu(frac(a, pi^l))=0. arrow.r.double frac(a, pi^l) in A^times . arrow.r.double exists u in A^times$ such that $a=u dot pi^l$. Thus $pi^l=u^(-1)a in frak("a")$. "$supset$"\ For any $0 eq.not a in frak("a")$, from remark we write $a := u dot pi^(nu(a))$, where $nu(a) >= 0$ (since $nu(a) >= l$). Note that $because frak("a") lt.closed.not A$ is proper.\ $therefore$ By claim 1, $nu(a)>0$, further, from the definition of $l$, we have $nu(a) >= l$. Now consider $frac(a, pi^l) in K^times$, then $nu(frac(a, pi^l))=nu(a)-l >= 0. arrow.r.double frac(a, pi^l) in A. arrow.r.double exists b in A$ such that $a=b dot pi^l in (pi^l)$. Thus $frak("a") subset (pi^l)$. To conclude, claim 2 implies that $A$ is a PID.\
  *Claim 3.* $A$ has only one nonzero prime ideal of $A$.\
  proof. Let $0 eq.not frak("a") lt.closed.not A$, from claim 2, we have $frak("a") := (pi^n)$ for some $n in bb("N"). arrow.r.double frak("a")=(pi^n)=(pi).\ because nu(pi)=1. therefore$ claim 1, $(pi) lt.closed.not A$ is a maximal ideal. Now if $n >= 2, (pi^2)$ is not a prime ideal (since $pi in.not (pi^2)$ but $pi dot pi in (pi^2)$). Thus, if $frak("a")=(pi^n)$ is a prime ideal of $A$, we must have $n=1$.
]


#example(number: 152)[
  If $K=bb("Q")$ and $nu_p$ is the valuation defined by the prime $p in bb("Z")$, we find $A=bb("Z")_((p))$ and $frak("m")=(p) bb("Z")_((p))$.
]


#proposition(number: 153)[
  Let $a_1, dots.h.c ,a_m$ be elements of a Dedekind domain $A$ and $frak("p")_1, dots.h.c ,frak("p")_m lt.closed A$ be distinct prime ideals. Then, for any integer $n in bb("N")$, there is an $a in A$ such that $nu_(frak("p")_i)(a-a_i)>n$.
]

#proof[
  $because frak("p")_i$ and $frak("p")_j$ are relatively prime $forall i eq.not j. therefore$ By *Lemma 127*, the ideals $frak("p")_i^(n+1)$ are pairwise relatively prime. By *CRT*, $exists x in A$ such that
  $
    a equiv a_i (op("mod") frak("p")_i^(n+1)), quad (1 <= i <= m).
  $

  So $a-a_i in frak("p")_i^(n+1)$, and hence $(a-a_i) subset frak("p")_i^(n+1)$, so that $frak("p")_i$ appears in the decomposition of $(a-a_i)$ with power $>= n+1$. Therefore $nu_(frak("p")_i)(a-a_i)>n, forall i$.
]


#remark(number: 154)[
  As we are going to see in *§ 2.4*, $nu(a) gt.double n$ means morally a "small" $a$. In this way, we can regard *Prop. 153* as an approximation version of the *CRT*. (cf. *Theorem 257*).
]
