#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge

== Smoothness

#definition(number: "199", title: [Tangent Spaces])[
  Let $k$ be a field.
  - Consider the *formal differential map* defined by
  $
    d:k[x_1, dots.h.c ,x_n] arrow.r.long k[x_1, dots.h.c ,x_n], f arrow.r.long.bar sum_(i=1)^n frac(∂ f, ∂ x_i)(0)x_i,
  $

  where $frac(∂ f, ∂ x_i) in k[x_1, dots.h.c ,x_n]$ is the formal derivative of the polynomial $f$ with respect to $x_i$.
  - We can regard $d f$ as a linear function
  $
    d f:k^n arrow.r.long k, a := (a_1, dots.h.c ,a_n) mapsto d f(a)= sum_(i=1)^n frac(∂ f, ∂ x_i)(0)a_i,
  $

  that is, $d f in k^(n op("vee"))$.
  - Next, let $frak("a") lt.closed k[x_1, dots.h.c ,x_n]$ be an ideal with $frak("a") subset frak("p") := (x_1, dots.h.c ,x_n)$. Geometrically, this means that the closed point corresponding to $frak("p")$ lies in $cal("V")(frak("a"))$. We define the *tangent space* of $frak("a")$ at $frak("p")$ by
  $
    T_frak("p") frak("a") := inter.big_(f in frak("a")) op("ker") d f subset k^n.
  $

  This is clearly a $k$-vector space with *annihilator* $N^op("vee") T_frak("p") frak("a")={d f:f in frak("a")} subset k^(n op("vee"))$.

]


#remark(number: 200)[
  - _(a)_ One immediately verifies the *derivation property* (Leibniz rule):
  $
    d(f g) = f(0) dot d g+g(0) dot d f.
  $

  - _(b)_ As the formal differential is a $k$-linear operator, it is enough to compute $d f$ for a generating system of $frak("a")$.

]


#example(number: 201)[
  Let $f=x_1^2+(x_2-1)^2-1$ and consider $frak("a")=(f) subset bb("R")[x_1,x_2]$. We have $d f=-2x_2$, whence $T frak("a")={(a_1,a_2) in bb("R")^2:a_2=0}$. If we think of $cal("V")(frak("a"))$ in $op("Spec") k[x_1, dots.h.c ,x_n]$ as
  $
    cal("V")(f)=f^(-1)(0)= text("the unit circle through") (0,0) text("and") (0,2),
  $

  (cf. *Rmk. 172*), we can see that $T frak("a")$ corresponds to the geometric tangent space $T_((0,0)) cal("V")(f)$ of $cal("V")(f)$.
]


#proposition(number: 202)[
  The $k$-linear map defined by
  $
    overline(frak("p")) := frak("p")/frak("a") , attach(arrow.r.long, t: phi) T frak("a")^op("vee") := op("Hom")_k(T frak("a"),k),; overline(f) := f+frak("a") , arrow.r.long.bar d f|_(T frak("a")),
  $

  induces an isomorphism
  $
    T frak("a")^op("vee") equiv overline(frak("p"))/(overline(frak("p")))^2.
  $

]

#proof[
  We claim that $phi$ is a well-defined surjective and $op("ker")phi=(overline(frak("p")))^2$.\
  - *(Well-defined).* If $overline(f)=overline(g), (f,g in frak("p"))$, then $f-g in frak("a")$.\ claim. $d(f-g)|_(T frak("a"))=0$. For any $a in T frak("a")= inter.big_(f in frak("a")) op("ker")(d f) subset k^n. because a in op("ker")(d(f-g)).\ therefore d(f-g)(a)=0. arrow.r.double d(f-g)|_(T frak("a"))=0. arrow.r.double d f|_(T frak("a"))=d g|_(T frak("a"))$, i.e. $phi$ is well-defined.
  - *(Surjective).* Let $F in op("Hom")_k(T frak("a"),k)$, i.e. $F:T frak("a") -> k$ is $k$-linear. Note that $T frak("a")$ is a $k$-vector subspace of $k^n$, let ${e_j }_(j=1)^m$ be its $k$-basis where $m <= n$. By suitable linear transformation we may assume the basis is standard. We consider $f := sum_(j=1)^m F(e_j)x_j in frak("p")$, then
  $
    d f= sum frac(∂ f, ∂ x_j)(0)x_j= sum F(e_j)x_j=f.
  $

  Now, we have
  $
    f|_(T frak("a"))(e_j)=f(e_j)= sum_(k=1)^m F(e_k) delta_(j k)=F(e_j), forall 1 <= j <= m.
  $

  Thus, $phi(overline(f))=f|_(T frak("a"))=F$.
  - *(Kernel).* "$subset$"\ If $overline(f) in op("ker")phi, (f in frak("p"))$, then $d f|_(T frak("a"))=0$, i.e. $d f in N^op("vee") T frak("a")$ the annihilator. Thus there is $g in frak("a")$ such that $d f=d g$, it follows that $d(f-g)=0$, which means $f-g$ has no linear terms. Moreover, since $f,g in frak("p")$, they have no constant terms. Hence $f-g$ is of the form
  $
    f-g := sum a_(i j)x_i x_j+ text("higher order terms").
  $

  Since $g in frak("a")$, we conclude that
  $
    overline(f)=overline(f-g)= sum a_(i j) overline(x_i) overline(x_j)+ text("higher order terms") in (overline(frak("p")))^2.
  $

  "$supset$"\ Conversely, note that $(overline(frak("p")))^2$ is generated by ${overline(x_i) overline(x_j)}$ and that $(overline(frak("p")))^2 subset overline(frak("p"))$. Since
  $
    phi(overline(x_i) overline(x_j))=d(x_i x_j)|_(T frak("a"))=(x_i(0)d x_j+x_j(0)d x_i)|_(T frak("a"))=0,
  $

  we have $overline(x_i) overline(x_j) in op("ker")phi$, whence $(overline(frak("p")))^2 subset op("ker")phi$.

  By Isomorphism Theorem we obatain the result.
]


#remark(number: 203)[
  This suggests to define the tangent space at a closed point of an affine scheme as follows:
  - For a maximal ideal $frak("p") in X=op("Spec")A$, define the $k=A/frak("p")$-vector space $T_frak("p")X := (frak("p")/frak("p")^2)^op("vee")$. The tangent space thus defined as a purely local object.
  - Indeed, consider the local ring $(A_frak("p"), frak("p")A_frak("p"))$, (for this we assume again that $A$ is integral though that is not strictly necessary).
  - Since $S=A without frak("p")$ maps to units in $k$, we have
  $
    frak("p")/frak("p")^2 equiv S^(-1)(frak("p")/frak("p")^2) equiv S^(-1) frak("p")/S^(-1) frak("p")^2 equiv frak("p")A_frak("p")/(frak("p")A_frak("p"))^2,
  $

  where the first isomorphism is as $k$-vector spaces, and the second $A$-linear isomorphism follows from exactness of the localisation functor (cf. [AM, 3.3]). In particular, $frak("p")/frak("p")^2 equiv frak("p")A_frak("p")/(frak("p")A_frak("p"))^2$ as $k$-vector spaces, so that $T_frak("p")X equiv (frak("p")A_frak("p")/(frak("p")A_frak("p"))^2)^op("vee")$ can be solely computed from the local ring $A_frak("p")$.

]


#proposition(number: 204)[
  Let $(A,frak("m"))$ be a local Noetherian ring with the residur field $k$. Then
  - _(a)_ The number $op("dim")_k(frak("m")/frak("m")^2)$ is the minimal number of generators for $frak("m")$.
  - _(b)_ $op("dim") A <= op("dim")_k(frak("m")/frak("m")^2)< oo$.

]

#proof[
  Note. Since $A$ is Noetherian, there is a finite minimum number $n$ of generators of $frak("m")$. Further, as $frak("m")$ is finitely generated, so is  $frak("m")/frak("m")^2$ over $A/frak("m")=k$, i.e. $op("dim")_k(frak("m")/frak("m")^2)< oo$.\
  (a) Suppose $frak("m") := (a_1, dots.h.c ,a_m)$, then $overline(a_i) := a_i+frak("m")^2$ generates $frak("m")/frak("m")^2$ as a $k$-vector space, whence $n >= op("dim")_k(frak("m")/frak("m")^2)$. If ${overline(a_i)}_(i=1)^n$ is $k$-dependent, by possibly relabeling ${overline(a_i)}_(i=1)^(n-1)$ still generates $frak("m")/frak("m")^2$. By *Nakayama's Lemma* [AM, 2.8], ${a_i }_(i=1)^(n-1)$ generates $frak("m"). ( -> arrow.l )$.\
  (b) As $A$ is local, from *Example 184* we have
  $
    op("dim") A = op("dim") A_frak("m") = op("height") frak("m").
  $

  But $op("height") frak("m") <= n$ by Exercise.
]


#definition(number: "205", title: [Regular Ring])[
  A local ring $(A,frak("m"))$ is *regular* if $A$ is Noetherian and $op("dim") A=op("dim")_k(frak("m")/frak("m")^2)$.
]


#example(number: 206)[
  - _(a)_ Since a field $(k, 0)$ is zero dimensional, it is always regular.
  - _(b)_ For a DVR $(A,frak("m"))$, we have $frak("m")/frak("m")^2 equiv A/frak("m")=k$, whence it is regular.
  - _(c)_ The localisation $(k[x_1, dots.h.c ,x_n]_frak("p"), frak("p")k[x_1, dots.h.c ,x_n])$ is regular for
  $
    frak("p")k[x_1, dots.h.c ,x_n]/(frak("p")k[x_1, dots.h.c ,x_n])^2 equiv { sum a_i x_i:a_i in k}
  $

  is $n$-dimensional. On the other hand, from *Prop. 187*, we have
  $
    n=op("dim") k[x_1, dots.h.c ,x_n]=op("dim") k[x_1, dots.h.c ,x_n]_frak("p").
  $


]


#proposition(number: 207)[
  A regular ring is an integral domain.
]

#proof[
  Let $(A,frak("m"))$ be a regular local ring with residue field $k=A/frak("m")$. We prove by induction on $n=op("dim")_k(frak("m")/frak("m")^2)=op("dim") A$.\
  For $n=0$, we have $frak("m")=frak("m")^2$. Thus, by *Nakayama*, $frak("m")=0$. Since $A^times =A without frak("m")=A without {0}$, $A$ is a field and thus an integral domain.\ Now, let $n >= 1$ and $frak("p")_i$ be the minimal primes over $(0)$, i.e. for any prime $(0) subset frak("p") subset frak("p")_i$, we have either $frak("p")=(0)$ or $frak("p")=frak("p")_i$. Since $op("dim") A >= 1$, it follows that either $frak("m")$ is minimal (so that $(0)$ is prime, thus $A equiv A/(0)$ is an integral domain) or $frak("m")$ strictly contains these $frak("p")_i$. Assuming this, we will now proceed in three steps:\
  step 1. _$a in frak("m")$ not contained in $frak("m")^2$ nor in any $frak("p")_i$._\
  If not, then $frak("m")$ is contained in $frak("m")^2 union ( union.big frak("p")_i)$. It follows from *(22c)* that either $frak("m") subset frak("m")^2$ (thus $frak("m")=0$ by *Nakayama*) or $frak("m") subset frak("p")_i$ for some $i$ (contradicting the assumption).\
  step 2. _$(A/(a),frak("m")/(a))$ is regular of dimension $n-1$._\
  Indeed, since $a in.not frak("m")^2$, we can extend $overline(a) in frak("m")/frak("m")^2$ to a $k$-basis ${overline(a)=overline(a)_1, dots.h.c ,overline(a)_n }$ of $frak("m")/frak("m")^2$. Hence ${overline(a)_i }_(i=2)^n$ generates the $k$-vector space $V := frac(frak("m")/(a), frak("m")^2/(a))$, so $op("dim")_k V <= n-1$. On the other hand, let
  $
    frak("q")_0 subset.not.eq frak("q")_1 subset.not.eq dots.h.c subset.not.eq frak("q")_n=frak("m")
  $

  be a maximal chain of prime ideals in $A$. It must necessarily start with a minimal prime ideal $frak("q")_0=frak("p")_i$. Since $a in frak("m")$, we can choose the prime ideals in such a way that $a in frak("q")_1$, (cf. [Ch3, \#10]). Therefore,
  $
    frak("q")_0/(a) subset.not.eq frak("q")_1/(a) subset.not.eq dots.h.c subset.not.eq frak("q")_n/(a)=frak("m")/(a)
  $

  is a chain of prime ideals in $A/(a)$, whence $op("dim") A/(a) >= n-1$. Since $op("dim")_k V >= op("dim") A/(a)$ by previous result and $op("dim") A/(a) >= n-1 >= op("dim")_k V$, we thus conclude that $op("dim") A/(a)=op("dim")_k V=n-1$, i.e. $A/(a)$ is regular.\
  step 3. _The induction step._ From induction hypothesis we conclude that $A/(a)$ is an integral domain. In particular, $(a)$ is a prime ideal. Hence we must have $frak("p")_i subset (a)$ for some $i$, so that any $b in frak("p")_i$ is of the form $b=a c, (c in A)$, whence $b in frak("m") dot frak("p")_i$. Now, the finitely generated $A$-module $frak("p")_i$ satisfies $frak("p")_i=frak("m") dot frak("p")_i$. Again, by *Nakayama* we have $frak("p")_i=(0)$, which implies that $(0)$ is a prime ideal, hence $A$ is an integral domain.
]


#remark(number: 208)[
  In fact, regular rings are UFDs, which is the *Auslander-Buchsbaum Theorem*, cf. [Commutative Algebra, Eisenbud, 19.19].
]


#summary-box(title: [Algebraic Summary. 209])[
  We obtain the following notions of rings
  #align(center)[#diagram(
    cell-size: 17mm,
    $
      & & text("Noether") & \
      & #text(fill: red, weight: "bold")[PID of dim A=1] edge("r", arrow.r.double)
      & #text(fill: red, weight: "bold")[Dedekind] edge("u", arrow.r.double) edge("dr", arrow.r.double) & \
      #text(fill: red, weight: "bold")[DVR] edge("ur", arrow.r.double) edge("dr", arrow.r.double) & & & text("normal") \
      & text("regular") edge("r", arrow.r.double) edge("d", arrow.r.double)
      & text("UFD") edge("ur", arrow.r.double) & \
      & text("Noether local") & &
    $,
  )]
  where rings of dimension $1$ are marked in red.
]


#summary-box(title: [Geometric Summary. 210])[
  Both dimension and regularity are local properties in the algebraic and geometric sense:
  - From *Example 184*, Dedekind rings are $1$-dimensional. Moreover, the localisation of a Dedekind ring $A$ is a DVR. They are $1$-dimensional as PIDs in accordance to the local character of the dimension. They are also regular in view of *Example 206*. Hence the affine scheme $X=op("Spec")A$ represents a smooth curve.
  - By *Prop. 187*, the polynomial ring $k[x_1, dots.h.c ,x_n]$ is $n$-dimensional, and its localisation at any prime ideal is regular by *Example 206*. The resulting $n$-dimensional and smooth affine scheme $op("Spec") k[x_1, dots.h.c ,x_n]=bb("A")_k^n$ is called the *affine space* over $k$.

]


#proposition(number: 211)[
  Let $(A,frak("m"))$ be a Noetherian local domain of dimension $1$. Then T.F.A.E.:\ (a) $A$ is a DVR.  (b) $A$ is integrally closed.  (c) $A$ is regular. [Exercise]
]


#example(number: 212)[
  For a nonregular example, take $A$ to be the localisation of the ring
  $
    bb("C")[x,y]/(y^2-x^3)
  $

  at the maximal ideal $(overline(x),overline(y))$. Then $frac(overline(x), overline(y)) in op("Quot")A$ is integral over $A$, (consider $t^2-overline(x) in A[t]$), but not integral over $A$. Hence $A$ is *singular*, i.e. not regular.
]


To highlight the interplay between algebra and geometry, let us again consider the ring of integers of a number field. This has the desirable property of being Dedekind. But already a ring as simple and natural as $bb("Z")[sqrt(5)]$ is not algebraically closed in $bb("Q")(sqrt(5))$. On the other hand, the curve as in *Example 212* is singular and thus not given by a Dedekind ring. We therefore need to enlarge our class of rings.

#definition(number: "213", title: [Order])[
  Let $K$ be an algebraic number field with $n=[K:bb("Q")]$. An *order* of $K$ is a subring $cal("O")$ of $cal("O")_K$ which contains an integral basis of length $n$. The ring $cal("O")_K$ is obviously an order and is called the *maximal order* of $K$.
]


#proposition(number: 214)[
  An order $cal("O")$ of an algebraic number field $K$ is a $1$-dimensional Noetherian integral domain.
]

#proof[
  Since $cal("O")$ is a finitely generated $bb("Z")$-module of rank $n=[K:bb("Q")]$ and $bb("Z")$ is Noetherian, it follows that every ideal $frak("a") lt.closed cal("O")$ is also a finitely generated $bb("Z")$-module. In particular, it is a finitely generated $cal("O")$-module so that $cal("O")$ is Noetherian. Now, if $(0) eq.not frak("p") lt.closed cal("O")$ is prime and $0 eq.not a in frak("p") inter bb("Z")$, then $a cal("O") subset frak("p") subset cal("O")$. Thus, by rescaling the lattice base appropriately, we obtain a $bb("Z")$-basis of $frak("p")$ which is therefore of rank $n$. Hence $cal("O")/frak("p")$ is finite and an integral domain, thus a field (since the map $f_(overline(a)):cal("O")/frak("p") -> cal("O")/frak("p"), overline(b) mapsto overline(a) dot overline(b)$ is bijective). Consequently, $frak("p") lt.closed cal("O")$ is maximal. As $cal("O")$ is an integral domain, it follows that $op("dim") cal("O")=1$.
]


#proposition(number: "215", title: [Akizki-Krull])[
  Let $A$ be a $1$-dimensional Noetherian domain, $K=op("Quot")A$, and $L/K$ be a finite extension. If $B=overline(A)$ is the integral closure of $A$ in $L$, then $B$ is a Dedekind domain. [Exercise]
]

#proof[
  We need to show the following three conditions:\
  claim 1. _$B$ is integrally closed._ Clearly, since it is the integral closure of $A$ in $L$.\
  claim 2. _Every nontrivial prime ideal is maximal._ Since $A subset B$ is an integral extension of integral domain, we have $op("dim") B=op("dim") A=1$. In particular, if $(0) eq.not frak("q") lt.closed B$, then $frak("q")$ must be maximal, otherwise we have the strict chain $(0) subset.not.eq frak("p") subset.not.eq frak("n")$ in $B$ so that $op("dim") B>1. ( -> arrow.l )$.\
  claim 3. _$B$ is Noetherian._ Since $op("Quot")B=L$, we can pick a $K$-basis ${b_i }_(i=1)^n$ of $L$ which is contained in $B$. Then $A[b_1, dots.h.c ,b_n]$ is Noetherian (as $A$ is), and is $1$-dimensional (since $A subset A[b_1, dots.h.c ,b_n]$ is an integral extension). Replacing $A$ by $A[b_1, dots.h.c ,b_n]$ if necessary, we may assume that $L=K$. In particular, it follows that $frak("b") inter A eq.not (0)$ for any ideal $frak("b") lt.closed B$, (if $x=frac(r, s) in frak("b")$ with $r,s in A$, then $s x in frak("b") inter A$). Now, it remains to show that $frak("b")$ is a finitely generated $B$-module. Let $0 eq.not b in frak("b") inter A$. Since $B/(b)B$ is a finitely generated $A$-module, it is Noetherian. But then $frak("b")/(b)B$ is a Noetherian $A$-module as an $A$-submodule, and a fortiori it is Noetherian, and thus a finitely generated $B$-module. Since $(b)B$ is a finitely generated $B$-module, so is $frak("b")$.
]


#corollary(number: "216", title: [Normalisation])[
  The integral closure $cal("O")$ of an order $o$ inside its ring of fractions is a Dedekind ring. Such $cal("O")$ is called the *normalisation* of $o$.
]


#note(number: 217)[
  Let $o$ be a $1$-dimensional Noetherian domain. Singular points of $op("Spec") o$ are by definition primes $frak("p")$, where the localisation $o_frak("p")$ is not regular. Passing to the normalisation yields an integral extension $o arrow.r.hook cal("O")$ and thus a surjective morphism of curves $op("Spec") cal("O") -> op("Spec") o$. \
  Since $cal("O")$ is Dedekind, we may think of this morphism as a _resolution of singularities_. The different points $frak("P")_i in op("Spec") cal("O")$ which are mapped to a singular point $frak("p") in op("Spec") o$ are given by the decomposition
  $
    frak("p") cal("O") := frak("P")_1^(e_1) dots.h.c frak("P")_r^(e_r).
  $

]
