#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Modules

#definition(number: "30", title: [Modules])[
  Let $A$ be a ring.
  - An $A$-module is a set $M$ together with two operations
  $
    +:M times M -> M quad text("and") quad dot :A times M -> M
  $

  such that $(M,+)$ is an abelian group and for all $a,b in A, m,n in M$, we have
  $
    ,bullet (a+b) dot m=a dot m+b dot m ,,bullet a dot (m+n)=a dot m+a dot n ; ,bullet (a b) dot m=a dot (b dot m) ,,bullet 1 dot m=m
  $

  - Let $M, N$ be $A$-modules. A map $phi:M -> N$ is called an $A$-*module homomorphism* or is $A$-*liear* if for all $a in A, m,n in M$,
  $
    phi(a dot m)=a dot phi(m) quad text("and") quad phi(m+n)=phi(m)+phi(n).
  $

  In particular, $phi$ is called an $A$-*module endomorphism* if $M=N$.
  - $op("Hom")_A(M,N)$ [respectively, $op("End")_A(M)$] denotes the set of all $A$-module homomorphisms $M -> N$ [respectively, endomorphisms $M -> M$].
  - $A$-modules together with $A$-linear maps form a category. Isomorphisms in this category are bijective $A$-linear maps $phi:M -> N, phi^(-1)$ being automatically $A$-linear. If such an isomorphism $M -> N$ exists, then $M$ and $N$ are called *isomorphic* and denote $M tilde.equiv N$.

]


#definition(number: "31", title: [Submodules])[
  - Let $M$ be an $A$-module. An abelian subgroup $N$ of $M$ is an $A$-*submodule* of $M$ if it is closed under scalar multiplication, i.e. for all $a in A, n in N$ , we have $a dot n in N$.
  - Let $N subset M$ be an $A$-submodule. Then $m tilde m' attach(arrow.l.r.double.long, t: text("Def.")) m-m' in N$ defines an equivalence relation on $M$ with equivalence class $overline(m) =overline(m+n), (n in N)$. The *quotient module* $M/N$ is an $A$-module structure on the coset space ${overline(m):m in M}$ defined by the following operations:
  $
    overline(m)+overline(m') := overline(m+m') quad text("and") quad overline(m) dot overline(m') := overline(m dot m').
  $

  (cf. *Def. 14* of quotient ring)

]


#example(number: 32)[
  - _(a)_ Every ring is a module over itself with scalar multiplication induced by the ring product. An ideal $cal("I") lt.closed A$ is an $A$-module with scalar multiplication induced by the ring product. In fact, $cal("I")$ is an $A$-submodule.
  - _(b)_ Scalar multiplication $a dot overline(b) := overline(a dot b)$ turns $A/cal("I")$ into an $A$-module.
  - _(c)_ $A^n={(a_1, dots.h.c ,a_n):a_i in A}$ is an $A$-module in the obvious way.
  - _(d)_ $A[x_1, dots.h.c ,x_n]$ is an $A$-module with $a dot sum a_alpha x^alpha := sum (a dot a_alpha)x^alpha$.

]


#definition(number: "33", title: [Graded Modules])[
  A module $M$ over a ring $A := plus.o.big_(nu in bb("N"))A_nu$ is a *graded* $A$-*module* if there is a direct sum decomposition $M := plus.o.big_(mu in bb("Z"))M_nu$ into abelian groups $M_mu$ with $A_nu M_mu subset M_(mu+nu)$.
]


#example(number: 34)[
  Let $A := plus.o.big_(nu in bb("N"))A_nu$ be a graded $k$-algebra and consider the free $A$-module $A^m= plus.o.big_(i=1)^m A e_1$. Let $op("deg") e_i := nu_i in bb("Z")$ and $M_mu$ be the $k$-vector space generated by ${a e_i:a in A_(nu-nu_i)}$. Then $A^m= plus.o.big_(nu in bb("Z"))M_nu$ is a graded $A$-module.
]


#lemma(number: "35", title: [Graded Submodules])[
  Let $M := plus.o.big_(nu in bb("Z"))M_nu$ be a graded $A$-module and $N subset M$ be an $A$-submodule. Then T.F.A.E.:
  - _(a)_ $N$ is graded by the induced grading, i.e. $N := plus.o.big_(nu in bb("Z"))N_nu$ with $N_nu=M_nu inter N$.
  - _(b)_ $N$ is generated by homogeneous elements.
  - _(c)_ Let $m := sum m_nu, (m_nu in M)$. Then $m in N. arrow.l.r.double m_nu in N, forall nu$.

  A submodule satisfying one and thus all of these conditions is called a *graded* or *homogeneous submodule* of $M$. Moreover, if $M=A$, where $A$ is a graded ring, we call $N$ a *graded* or *homogeneous ideal*.
]


#remark(number: 36)[
  Let $M := plus.o.big_(nu in bb("Z"))M_nu$ be a graded $A$-module and $N subset M$ be a graded submodule. Then the quotient $M/N$ is a graded module with $(M/N)_nu=M_nu/N_nu equiv (M_nu+N)/N$. Moreover, if $M=A$ is a graded ring and $N=frak("a")$ is a homogeneous ideal, then $A/frak("a")$ is a graded ring.
]


#definition(number: "37", title: [Homogeneous Degree])[
  Let $A := plus.o.big_(nu >= 0)A_nu$ be a graded ring and $M := plus.o.big_(nu in bb("Z"))M_nu, N := plus.o.big_(nu in bb("Z"))N_nu$ be two graded $A$-modules. An $A$-linear map\ $phi:M -> N$ is *graded* or *homogeneous* of *degree* $d$ if $phi(M_nu) subset N_(nu+d)$. We call $phi$ simply *homogeneous* if it is homogeneous of degree $0$.
]


#example(number: 38)[
  Under the assumptions of the previous definition, multiplication with $f in A_d$ defines a graded morphism $phi:M -> M, m mapsto f dot m$ of degree $d$.
]


#remark(number: 39)[
  If $phi:M -> N$ is a homogeneous morphism, then $op("ker")phi, op("im")phi$ and $op("coker")phi$ are graded $A$-submodules.
]

Let $phi:M -> N$ be an $A$-linear map. We know that its kernel $op("ker")phi= {m in M:phi(m)=0}$ and its image $op("im")phi={n in N:n=phi(m) text("for some") m in M}$ are $A$-submodules of $M$ and $N$, respectively.
#definition(number: "40", title: [Exact Sequences])[
  - A sequence of $A$-modules with $A$-linear maps
  $
    L attach(arrow.r.long, t: alpha) M attach(arrow.r.long, t: beta) N
  $

  is called a *complex* if $op("im")alpha subset op("ker")beta$, i.e. $beta compose alpha=0_L$; and is said to be *exact* at $M$ if $op("im")alpha=op("ker")beta$.
  - A sequence
  $
    dots.h.c arrow.r.long M_(k-1) attach(arrow.r.long, t: alpha_(k-1)) M_(k) attach(arrow.r.long, t: alpha_(k)) M_(k+1) arrow.r.long dots.h.c
  $

  is *exact* [respectively, *complex*] if it is exact [respectively, complex] at every $M_k$.
  - An exact sequence of the form
  $
    0 arrow.r.long L attach(arrow.r.long, t: alpha) M attach(arrow.r.long, t: beta) N arrow.r.long 0
  $

  is called a *short exact sequence* of $A$-modules.

]


#remark(number: 41)[
  - _(a)_ $0 arrow.r.long M attach(arrow.r.long, t: alpha) N$ is exact  $arrow.l.r.double.long op("ker")alpha={0} arrow.l.r.double.long alpha$ is injective.
  - _(b)_ $M arrow.r.long N attach(arrow.r.long, t: beta) 0$ is exact  $arrow.l.r.double.long op("im")beta=N arrow.l.r.double.long beta$ is surjective.
  - _(c)_ $0 arrow.r.long M attach(arrow.r.long, t: phi) N arrow.r.long 0$ is exact at $M$ and $N arrow.l.r.double.long phi$ is an isomorphism.

]


#example(number: 42)[
  If $phi:M -> N$ is an $A$-module homomorphism, then the natural inclusions $iota:op("ker")phi -> M$ and $kappa:op("im")phi -> N$ induce the following short exact sequences:
  $
    0 arrow.r.long op("ker")phi attach(arrow.r.long, t: iota) M attach(arrow.r.long, t: phi) op("im")phi arrow.r.long 0
  $

  and
  $
    0 arrow.r.long op("im")phi attach(arrow.r.long, t: kappa) N arrow.r.long op("coker")phi arrow.r.long 0.
  $

]


#proposition(number: "43", title: [Split Exact])[
  Let $0 -> L attach(arrow.r.long, t: alpha) M attach(arrow.r.long, t: beta) N -> 0$ be a short exact sequence. Then T.F.A.E.:
  - _(a)_ There exists an isomorphism $phi:L plus.o N -> M$ such that
  $
    alpha(l)=phi(i plus.o 0) quad text("and") quad beta compose phi(l plus.o n)=n.
  $

  - _(b)_ There exists a section of $beta$, i.e. a map $kappa:N -> M$ such that $beta compose kappa=1_N$.
  - _(c)_ There exists a retraction of $alpha$, i.e. a map $iota:M -> N$ such that $iota compose alpha=1_M$.

  A short exact sequence which admits a section is called *split exact*.
]


#definition(number: "44", title: [Localisation of Modules])[
  If $M$ is an $A$-module contained in some field $L supset K=op("Quot")A$, then $S^(-1)M$ denotes the set ${frac(m, s):m in M, s in S}$. This becomes an $S^(-1)A$-module in the obvious way and is called the *localisation* of $M$. For example, let $frak("b")$ be an ideal of $S^(-1)A subset K=L$, then $S^(-1)(frak("b") inter A)=frak("b")$ as $S^(-1)A$-modules.
]


#theorem(number: "45", title: [Nakayama's Lemma])[
  Let $(A,frak("m"))$ be a local ring, $frak("a") subset A$ be a proper ideal and $frak("a") dot M := { sum a_i m_i:a_i in frak("a"), m_i in M}$. If $N$ is an $A$-submodule of $M$ such that $N+frak("a")M=M$, then $N=M$. In particular, $frak("a")M =M$ implies $M=0$.
]


#corollary(number: 46)[
  Let $(A,frak("m"))$ be a local ring and $M$ be a finitely generated $A$-module. If $m_1, dots.h.c ,m_n in M$ induce generators of the $k=A/frak("m")$-vector space $M/frak("m")M$, then they also generate $M$.
]


#theorem(number: "47", title: [Modules over PID])[
  Let $A$ be a PID and $M$ a finitely generated $A$-module, then $M$ is a direct sum of cyclic modules, that is, modules of the form $A/(a)$. In particular, $M$ is free if it is torsion-free.
]
