#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Integral Ring Extensions

#definition(number: "91", title: [Integral Extension])[
  Let $A subset B$ be a ring extension. We call $b in B$ *integral* over $A$ if there is a monic polynomial $f in A[x]$ such that $f(b)=0$. If every $b in B$ is integral over $A$, then $B$ is said to be *integral* over $A$. In analogy with algebraic field extensions we also say that $A subset B$ is an *integral extension*.
]


#example(number: 92)[
  - $tau=frac(1+sqrt(5), 2) in bb("Z")[tau]$ (the golden ratio) is integral over $bb("Z")$, where $bb("Z")[tau] subset bb("Q")$ is the ring generated by $bb("Z")$ and $tau$. Indeed, $tau^2-tau-1=0$.
  - $bb("Z") subset bb("Z")[frac(1, 2)]= { sum_(i=0)^n frac(m_i, 2^i):m_i in bb("Z"), n in bb("N")}$ is not an integral extension. \ Indeed, consider $x=frac(p, 2) in bb("Z")[frac(1, 2)]$ with $p>2$ prime. If we had a polynomial relation
  $
    (frac(p, 2))^n+c_(n-1)(frac(p, 2))^(n-1)+ dots.h.c +c_0=0, quad (c_i in bb("Z")),
  $

  then multiplying with $2^n$ shows that $p^n=-2(c_(n-1)(frac(p, 2))^(n-1)+ dots.h.c +c_0 2^(n-1))$, hence $2|p, ( -> arrow.l )$.
  - For an integral domain $A$ we have the natural ring extension $A subset K=op("Quot")(A)$.\ If $A$ is a UFD, then $x in K$ is integral over $A$ iff $x in A$. [Exercise]

]


#proposition(number: 93)[
  Let $A subset B$ be a ring extension, and let $b in B$. Then T.F.A.E.:
  - _(a)_ b is integral over $A$.
  - _(b)_ The subring $A[b] subset B$ is a finite $A$-module. [AM, 5.1]

]

#proof[
  "$(a) arrow.r.double (b)$"\  If $b$ satisfies a monic relation of the form $b^n=- sum_(i=0)^(n-1)a_i b^i, (a_i in A)$, then $A[b]$ is generated by $1, b, dots.h.c , b^(n-1)$. \
  "$(b) arrow.r.double (a)$"\ Consider $b$ as a map $mu_b:A[b] -> A[b], a mapsto b dot a$. Since $A[b]$ is a finite $A$-module,\ $mu_b$ satisfies a monic relation $mu_b^n+a_(n-1) mu_b^(n-1)+ dots.h.c +a_0=0, (a_i in A)$ in $op("End")(M)$, by Cayley-Hamilton [AM, 2.4]. Evaluate at $1$ gives (a).
]


#definition(number: 94)[
  A ring extension $A subset B$ is *finite* if $B$ is a finite $A$-module.
]

#remark(number: "94*", title: [])[
  It follows from *Prop. 93* that a finite ring extension is integral. In fact, any finite ring extension $A subset B$ is of the form $B := A[b_1, dots.h.c ,b_n], (b_i:$ integral over $A$). Hence, an $A$-module $B$ with $A subset B$ is of
  $
    bold(text(" finite type")) + bold(text("integral")) arrow.l.r.double.long bold(text("finite")).
  $

]


#proposition(number: 95)[
  If $A subset B subset C$ are finite [integral] ring extensions, then $A subset C$ is a finite [integral] ring extension. [AM, 5.4]
]

#proof[
  (a) By *Prop. 93* and *Rmk.*, $B$ is generated as an $A$-module by $b_1, dots.h.c ,b_n in B$, and $C$ is generated as a $B$-module by $c_1, dots.h.c ,c_m in C$. Hence $C$ is generated as an $A$-module by $b_i c_j$'s. \ (b) Let $c in C$ satisfy the relation
  $
    c^n+b_(n-1)c^(n-1)+ dots.h.c +b_1 c+b_0=0, quad (b_i in B).
  $

  Then $c$ is also integral over $A[b_0, dots.h.c ,b_(n-1)]$, whence $A[b_0, dots.h.c ,b_(n-1),c]$ is finite over $A[b_0, dots.h.c ,b_(n-1)]$. Since each $b_i$ is integral over $A$, $A[b_0, dots.h.c ,b_(n-1)]$ is finite over $A$, hence $A[b_0, dots.h.c ,b_(n-1),c]$ is finite over $A$. It follows that $c$ is integral over $A$.
]


#lemma(number: 96)[
  Let $A subset B$ be an integral extension.
  - _(a)_ If $frak("b") lt.closed B$, then $frac(A, frak("b") inter A) subset frac(B, frak("b"))$ is an integral extension.
  - _(b)_ If $B$ is an integral domain and $S$ is a multiplicatively closed subset of $A$, then $S^(-1)A subset S^(-1)B$ is an integral ring extension.
  - _(c)_ $A[x] subset B[x]$ is an integral ring extension. [AM, 5.6]

]

#proof[
  (a) Consider the map $phi:A arrow.r.hook B arrow.r.twohead B/frak("b")$, then $op("ker")phi=A inter frak("b") := frak("a"). arrow.r.double overline(phi):A/frak("a") arrow.r.hook B/frak("b")$. Let $overline(x) := x+frak("b") in B/frak("b"), (x in B). because B$ is integral over $A. therefore x$ satisfies
  $
    x^n+a_(n-1)x^(n-1)+ dots.h.c +a_1 x+a_0=0 text("in") B, quad (a_i in A).
  $

  $arrow.r.double overline(x)^n+overline(a_(n-1)) overline(x)^(n-1)+ dots.h.c + overline(a_0)=overline(0)$ in $B/frak("b")$. Now, we have $A/frak("a") attach(arrow.r.hook, t: overline(phi)) B/frak("b"), a_i+frak("a") mapsto a_i+frak("b")=overline(a_i)$,\ may regard $overline(a_i) in A/frak("a"). arrow.r.double overline(x) in B/frak("b")$ is integral over $A/frak("a")$, and hence $B/frak("b")$ is integral over $A/frak("a")$. \
  (b) Let $frac(x, s) in S^(-1)B, (x in B,s in S). because B$ is integral over $A. therefore x$ satisfies
  $
    x^n+a_(n-1)x^(n-1)+ dots.h.c +a_1 x+a_0=0 text("in") B, quad (a_i in A).
  $

  Dividing $s^n$, we have
  $
    (frac(x, s))^n+frac(a_(n-1), s) dot (frac(x, s))^(n-1)+ dots.h.c +frac(a_1, s^(n-1)) dot frac(x, s)+frac(a_0, s^n)=0=frac(0, s^n) text("in") S^(-1)B, quad (frac(a_i, s^(n-i)) in S^(-1)A).
  $

  $arrow.r.double frac(x, s) in S^(-1)B$ is integral over $S^(-1)A$, and hence $S^(-1)B$ is integral over $S^(-1)A$.\
  (c) Let $f := b_n x^n+ dots.h.c +b_1 x+b_0 in B[x], (b_i in B). because b_i$ is integral over $A. therefore b_i$ is also integral over $A[x]$.  Moreover, $because f in A[b_0, dots.h.c ,b_n][x] equiv A[x][b_0, dots.h.c ,b_n]. therefore$ By Prop. 84., $A[x][b_0, dots.h.c ,b_n]$ is a finite $A[x]$-module. $arrow.r.double f$ is integral over $A[x]$.
]


#proposition(number: "97", title: [Integral Closure])[
  The set $overline(A) := { b in B: b text("integral over") A} subset B$ is a subring of $B$. In particular, the sum and the product of two integral elements is again integral, and $overline(overline(A))=overline(A)$. We call $overline(A)$ the *integral closure* of $A$ in $B$.\
  Moreover, if $overline(A)=A$, then $A$ is called *integrally closed* in $B$. [AM, 5.3, 5.5]
]

#proof[
  (i) If $x,y in overline(A)$ , then $A[x,y]$ is finite over $A$, whence $x+y$ and $x dot y$ are integral over $A$ and thus in $overline(A)$. \
  (ii) Since $A subset overline(A)$ and $overline(A) subset overline(overline(A))$ are integral ring extensions, it follows from *Prop. 95* that $overline(A) subset overline(overline(A)) subset overline(A)$, i.e. $overline(overline(A))=overline(A)$.
]


#example(number: 98)[
  If $overline(A)$ is the integral closure of $A$ in $B$, then $S^(-1) overline(A)$ is the integral closure of $S^(-1)A$ in $S^(-1)B$. [Exercise][AM, 5.12]
]
