#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Noether Normalisation

#theorem(number: "194", title: [Noether Normalisation Lemma])[
  Let $k subset B$ be a $k$-algebra of finite type. Then there exists algebraically independent elements $y_1, dots.h.c ,y_l in B$ such that $B$ is a finite $A=k[y_1, dots.h.c ,y_l]$-module, that is, we have
  $
    k subset A=k[y_1, dots.h.c ,y_l] subset B,
  $

  where $A$ is a polynomial algebra over $k$ and $B$ a finite over $A$. Furthermore, if $k$ is infinite the variables $y_1, dots.h.c ,y_l$ are obtained from a linear transformation of the $k$-generators $x_1, dots.h.c ,x_l$ of $B$.
]

#theorem(number: "194*", title: [Generalization])[
  Let $A subset B subset C$ be rings. Suppose that $A$ is Noetherian, $C$ is finitely generated as an $A$-algebra and that $C$ is either \
  *(i)* finitely generated as a $B$-module or *(ii)* integral over $B$.\ Then $B$ is finitely generated as an $A$-algebra. [AM, 7.8]
]

#remark(number: "194**")[
  Since $C$ is of finite type over $A$ and $A subset B$, so is $C$ over $B$. By *Rmk. 94\** the assumptions (i) and (ii) are equivalent.
]

#proofthm(number: "194*")[
  We suppose $C$ satisfies the assumption (i), say $C := B y_1+ dots.h.c +B y_l, (y_j in C). because C$ is a finitely generated $A$-algebra. $therefore C := A[x_1, dots.h.c ,x_m], (x_i in C)$. For each $1 <= i <= m$, we write
  $
    x_i := sum_(j=1)^l b_(i j)y_j, quad (b_(i j) in B).
  $

  Since $C$ is a ring, each $y_i y_j in C$, so we may write
  $
    y_i y_j := sum_(k=1)^l b_(i j k)y_k, quad (b_(i j k) in B).
  $

  Now, let $B_0$ be the $A$-algebra generated by these $b_(i j)$ and $b_(i j k)$'s, then $B_0$ is finitely generated as an $A$-algebra such that $A subset B_0 subset B subset C$. \
  *Claim.* $C$ is a finitely generated $B_0$-module. We first note that for each $x in C=A[x_1, dots.h.c ,x_m], x$ is a polynomial in $x_1, dots.h.c x_m$ with coefficients in $A$. From (1) and (2), $x$ is a linear combination of $y_1, dots.h.c ,y_l$ with coefficients in $B_0$, that is, $x in B_0-op("span"){y_1, dots.h.c ,y_l }$. Thus $C=B_0 y_1+ dots.h.c +B_0 y_l$ is finitely generated as a $B_0$-module.\
  To complete the proof, since $A$ is Noetherian, so is its finitely generated algebra $B_0$, thus $C$ is a Noetherian $B_0$-module. $because B$ is a $B_0$-submodule of $C. therefore B$ is a finitely generated $B_0$-module. Moreover, $B_0$ is a finitely generated $A$-algebra, thus so is $B$.
]


#theorem(number: "195", title: [Hilbert Weak Nullstellensatz])[
  Let $E$ be a finitely generated $k$-algera which is a field. Then $[E:k]< oo$. [AM, 7.9]
]

#proof[
  For the finitely generated $k$-algebra $E$, we write $E := k[alpha_1, dots.h.c ,alpha_n], (alpha_i in E)$.\ *Note:* If each $alpha_i$ is algebraic over $k$, then $E/k$ is algebraic, thus finite, done.\ Now, suppose that $E/k$ is not an algebraic extension. After suitable renumbering indexes, we may assume that (i) ${alpha_i }_(i=1)^r$ is algebraically $k$-independent and (ii) ${alpha_i }_(i=r+1)^n$ is algebraic over $F := k(alpha_1, dots.h.c ,alpha_r). because E/F$ is algebraic, thus finite extension. $therefore E$ is a finitely generated $F$-module. Moreover, $E$ is a finitely generated $k$-algebra, it follows from *Thm. 194* that $F$ is a finitely generated $k$-algebra, say $F := k[beta_1, dots.h.c ,beta_s], (beta_j in F)$. From (ii), for each $1 <= j <= s$, we have
  $
    beta_j := frac(f_j, g_j) in F equiv k(x_1, dots.h.c ,x_r) =op("Quot")(k[x_1, dots.h.c ,x_r]),
  $

  where $f_j,g_j in k[alpha_1, dots.h.c ,alpha_r] equiv k[x_1, dots.h.c ,x_r]$: UFD with $g_j eq.not 0$. Choose an irreducible polynomial $h in k[alpha_1, dots.h.c ,alpha_r] equiv k[x_1, dots.h.c ,x_r]$ such that $op("gcd"){(h,g_j)} tilde 1, forall 1 <= j <= s$, (e.g. $h := g_1 g_2 dots.h.c g_s+1$). $because F$ is a field and $h eq.not 0. therefore h^(-1) in F=k[beta_1, dots.h.c ,beta_s]$. However, $h^(-1)$ cannot be written as a polynomial in variables $beta_1, dots.h.c ,beta_s. ( -> arrow.l )$. Thus $E$ must be algebraic over $k$.
]


#corollary(number: 196)[
  If $k$ is an algebraically closed, then every maximal ideal in $k[x_1, dots.h.c ,x_n]$ is of the form $(x_1-a_1, dots.h.c ,x_n-a_n)$ for $a := (a_1, dots.h.c ,a_n) in bb("A")_k^n$.
]

#proof[
  Since $(x_1-a_1, dots.h.c ,x_n-a_n)$ is the kernel of the map
  $
    op("ev")_a:k[x_1, dots.h.c ,x_n] arrow.r.long k, x_i arrow.r.long.bar a_i,
  $

  it is a maximal ideal. Conversely, let $frak("m") lt.closed k[x_1, dots.h.c ,x_n]$ be a maximal ideal, then $E := k[x_1, dots.h.c ,x_n]/frak("m")$ is a field and a finitely generated $k$-algebra, whence $E/k$ is a finite extension by *Thm. 195*. Since $k$ is algebraically closed, we have an isomorphism $iota:k -> k[x_1, dots.h.c ,x_n]/frak("m")=E$. Choosing inverse images $a_1, dots.h.c ,a_n in k$ for $overline(x_1), dots.h.c ,overline(x_n)$ shows that $(x_1-a_1, dots.h.c ,x_n-a_n)$ is the kernel of the composition $iota compose op("ev")_a:k[x_1, dots.h.c ,x_n] -> k[x_1, dots.h.c ,x_n]/frak("m")$ and is thus equal to $frak("m")$.
]


#proposition(number: 197)[
  Let $k$ be a field and $n in bb("N")$. Then all maximal chains of prime ideals in $k[x_1, dots.h.c ,x_n]$ have length $n$. In particular, $op("dim") k[x_1, dots.h.c ,x_n]=n$.
]

#proof[
  We proof the both statements by induction on $n$. The cases for $n=0$ and $n=1$ are clear. Now let $n >= 2$ and $frak("p")_0 subset.not.eq frak("p")_1 subset.not.eq dots.h.c subset.not.eq frak("p")_r$ be a strict chain of prime ideals in $k[x_1, dots.h.c ,x_n]$. We wish to show that $r <= n$ with equality iff the chain is maximal. Without loss of generality we may assume that (possibly inserting prime ideals)
  - $frak("p")_0=(0)$.
  - $frak("p")_1=(f)$, for $f in k[x_1, dots.h.c ,x_n]$ irreducible. ($k[x_1, dots.h.c ,x_n]$ is factorial!)
  - $frak("p")_r$ is maximal.

  As in the proof of *Thm. 194\**, we may assume (by linearly transforming the coordinates $x_1, dots.h.c ,x_n$ if necessary), that $f in k[x_1, dots.h.c ,x_(n-1)][x_n]$ is monic in $x_n$. In particular,
  $
    k[x_1, dots.h.c ,x_(n-1)] subset k[x_1, dots.h.c ,x_(n-1)][x_n]/(f) =k[x_1, dots.h.c ,x_n]/frak("p")_1
  $

  is an integral ring extension. We push down the strict chain $frak("p")_0 subset.not.eq frak("p")_1 subset.not.eq dots.h.c subset.not.eq frak("p")_r$ of $k[x_1, dots.h.c ,x_n]$ to a chain $(0)= frak("q")_1 subset.not.eq dots.h.c subset.not.eq frak("q")_r$ by first moding out $frak("p")_1$ and second by intersecting with $k[x_1, dots.h.c ,x_(n-1)]$. This chain is strict by "incompatibility". Next, it is maximal if the chain $frak("p")_i$ is maximal. Indeed, $frak("q")_r$ is maximal since it is obtained by restricting a maximal ideal of an integral ring extension. Further, if we could insert some prime ideals $frak("q")$ into the chain $frak("q")_i$, this would be covered by a prime ideal $frak("p") lt.closed k[x_1, dots.h.c ,x_n]$ which would strictly extend the chain $frak("p")_i$ contradicting its maximality. $( -> arrow.l )$. (cf. *Exercise*).\
  By induction hypothesis, $r-1=$ the length of the maximal chain $frak("q")_i$ and $<= n-1$ with equality iff the chain is maximal. Hence, $m <= n$ with equality iff the chain $frak("p")_i$ is maximal.
]


#corollary(number: 198)[
  Any finitely generated $k$-algebra $A$ is of finite dimension. Furtermore, if $A$ is integral, then
  - _(a)_ all maximal chains of prime ideals in $A$ have length $op("dim") A$.
  - _(b)_ $op("dim") A=op("trdeg")_k op("Quot")(A)$.

]

#proof[
  (a) By *Thm. 194* we know that $A$ is a finite, thus an integral extension of $k[x_1, dots.h.c ,x_n]$ for some $n$ so that $op("dim") A=op("dim") k[x_1, dots.h.c ,x_n]=n$ from *Prop. 197*. Furthermore, if $A$ is integral, then $A equiv k[x_1, dots.h.c ,x_r]/frak("p")$ for some $r$ and $frak("p")$ prime ideal. Since all maximal chains of prime ideals in $k[x_1, dots.h.c ,x_r]$ have the same length, so do the maximal chains in the quotient above.\
  (b) Next, the field extension $k(x_1, dots.h.c ,x_n) subset op("Quot")A$ is algebraic for the ring extension $k[x_1, dots.h.c ,x_n] subset A$ is integral. Indeed, if $a,b in A$ are integral over $k[x_1, dots.h.c ,x_n]$, then they are algebraic over $k(x_1, dots.h.c ,x_n)$. It follows that $k(x_1, dots.h.c ,x_n) subset k(x_1, dots.h.c ,x_n)(a,b)$ must be an algebraic (thus, finite) field extension. In particular, $frac(a, b)$ is algebraic over $k(x_1, dots.h.c ,x_n)$ since algebraic elements form a field. Therefore, we have
  $
    op("trdeg")_k op("Quot")(A)=op("trdeg")_k k(x_1, dots.h.c ,x_n)=n=op("dim") A.
  $

]
