#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Tensor Products

#definition(number: "59", title: [Tensor Products])[
  Let $T$ be the free $A$-module generated by the pairs $(m,n)$, where $m in M, n in N$, and $U$ be the $A$-submodule of $T$ generated by the elements:
  $
    ,bullet (a m,n)-a(m,n), ,,bullet (m+m',n)-(m,n)-(m',n),; ,bullet (m,a n)-a(m,n), ,,bullet (m,n+n')-(m,n)-(m,n')
  $

  with $a in A, m,m' in M$ and $n,n' in N$.\
  The *tensor product* of $M$ and $N$ is the $A$-module $M times.o_A N := T/U$. The equivalence class of $(m,n)$ in $T/U$ will be denoted by $m times.o n$; the set ${m times.o n:m in M, n in N}$ is thus a generating system of $M times.o_A N$. Hence, we may define an $A$-linear map $iota:M times N -> M times.o_A N, (m,n) mapsto m times.o n$.
]


#theorem(number: "60", title: [Universal Property])[
  Let $M, N$ and $L$ be $A$-modules. If $alpha:M times N -> L$ is an $A$-bilinear map, then there exists a unique map $overline(alpha):M times.o_A N -> L$ such that $alpha=overline(alpha) compose iota$. In particular, for any other pair $(tilde(T),tilde(iota))$ consisting of an $A$-module $tilde(T)$ and an $A$-linear map $tilde(iota):M times N -> tilde(T)$ there exists a unique isomorphism $psi:M times.o_A N -> tilde(T)$ such that $tilde(iota)=psi compose iota$.
]


#corollary(number: 61)[
  There is a canonical isomorphism of $A$-modules
  $
    cal("B")_A(M,N;P) equiv op("Hom")_A(M times.o_A N,P).
  $

]


#proposition(number: 62)[
  Let $M, M', N, N'$ and $P$ be $A$-modules. We have the canonical isomorphisms:
  - _(a)_ $M times.o_A N equiv N times.o_A M, m times.o n mapsto n times.o m$.
  - _(b)_ $(M times.o_A N) times.o_A P equiv M times.o_A(N times.o_A P), (m times.o n) times.o p mapsto m times.o (n times.o p)$.
  - _(c)_ $A times.o_A M equiv M, a times.o m mapsto a m$.
  - _(d)_ $(M plus.o N) times.o_A P equiv (M times.o_A P) plus.o (N times.o_A P), (m,n) times.o p mapsto (m times.o p, n times.o p)$.

  Further, $A$-linear maps $phi:M -> M'$ and $psi:N -> N'$ define the $A$-linear map
  $
    phi times.o psi:M times.o_A N arrow.r.long M' times.o_A N', m times.o n arrow.r.long.bar phi(m) times.o psi(n).
  $

]


#example(number: 63)[
  - _(a)_ If $M=A^r$ and $N=A^s$ are two free $A$-modules of rank $r$ and $s$ with basis ${e_i }_(i=1)^r$ and ${f_j }_(j=1)^s$, respectively. Then $M times.o_A N equiv A^(r s)$ is again a free $A$-module of rank $r s$ with basis ${e_i times.o f_j:1 <= i <= r, 1 <= j <= s}$.

  - _(b)_ The subscript $A$ at $times.o$ indicates which scalars can be shuffled around. For instance, consider the abelian groups (=$bb("Z")$-modules) $bb("Z")/m bb("Z")$ and $bb("Z")/n bb("Z")$. Then $bb("Z") times.o_(bb("Z"))(bb("Z")/m bb("Z")) equiv bb("Z")/m bb("Z")$, etc. But $(bb("Z")/m bb("Z")) times.o_(bb("Z"))(bb("Z")/n bb("Z"))=0$ if $m$ and $n$ are coprime:\
    Indeed, $a m+b n=1$ for suitable integers $a,b in bb("Z")$ so that
  $
    overline(x) times.o overline(y)=1 dot overline(x) times.o overline(y)=(a m dot overline(x)) times.o overline(y)+overline(x) times.o (b n dot overline(y))=0 times.o overline(y)+overline(x) times.o 0=0.
  $

  - _(c)_ Tensoring of maps does not preserve injectivity. Indeed, let $A=bb("Z")$ and consider the map $alpha:bb("Z") -> bb("Z"), m mapsto 2m$. Then $alpha times.o 1_(bb("Z")/2 bb("Z"))$ is not injective since
  $
    alpha times.o 1_(bb("Z")/2 bb("Z"))(m times.o overline(b))=2a times.o overline(b)=a times.o (2 overline(b))=a times.o 0=0,
  $

  that is, $alpha times.o 1_(bb("Z")/2 bb("Z"))=0$. However, surjectivity is always preserved.

]


#definition(number: "64", title: [Tensor Product of Algebras])[
  - Let $B$ and $C$ be two $A$-algebras via ring homomorphisms $f:A -> B$ and $g:A -> C$. Then $(b times.o c) dot (b' times.o c') := b b' times.o c c'$ defines a ring structure on the $A$-module $D := B times.o_A C$.
  - Moreover, the ring homomorphism $A -> D, a mapsto f(a) times.o g(a)$ turns $D$ into an $A$-algebra with $A$-algebra homomorphisms
  $
    beta:B -> D, b mapsto b times.o 1 quad text("and") quad gamma:C -> D, c mapsto 1 times.o c.
  $

  - The algebra $D$ has the following universal property: For any $A$-algebra $E$ with $A$-algebra homomorphisms
  $
    beta':B -> E quad text("and") quad gamma':C -> E quad text("satisfying") quad beta' compose f=gamma' compose g,
  $

  there exists a unique $A$-algebra homomorphism $lambda:D -> E$ such that $beta'=lambda compose beta$ and $gamma'=lambda compose gamma$.

  #align(center)[
    #diagram(
      cell-size: 15mm,
      $
        E &                                              &                                                \
          & B times.o_A C edge("ul", lambda, -->)        & C edge("ull", gamma', ->) edge("l", gamma, ->) \
          & B edge("uul", beta', ->) edge("u", beta, ->) &            A edge("l", f, ->) edge("u", g, ->)
      $,
    )
  ]
]


#example(number: 65)[
  - _(a)_ (*Extension of Scalars*): If $B$ is an $A$-algebra and $M$ is an $A$-module, then $B times.o_A M$ becomes a $B$-module via $b(b' times.o m) := (b b') times.o m, (b,b' in B, m in M)$. If $M$ is a free $A$-module with basis ${e_i }_(i=1)^n$, then $B times.o_A M$ is a free $B$-module with basis ${1 times.o e_i }_(i=1)^n$.\
    For example, for a field extension $K subset L$, we have a canonical isomorphism:
  $
    L times.o_K K[x_1, dots.h.c ,x_n] arrow.r.long L[x_1, dots.h.c ,x_n], alpha times.o f arrow.r.long.bar alpha f.
  $

  - _(b)_ Let $B := A[x_1, dots.h.c ,x_n]/frak("a")$ and $C := A[y_1, dots.h.c ,y_m]/frak("b")$, then \ $B times.o_A C=A[x_1, dots.h.c ,x_n,y_1, dots.h.c ,y_m]/(frak("a")+frak("b"))$,}\ where we consider $frak("a")$ and $frak("b")$ as ideals of $A[x_1, dots.h.c ,x_n,y_1, dots.h.c ,y_m]$ via extension.
  - _(c)_ These allow the computation of various tensor products. For instance, consider the field extension $bb("Q") subset bb("Q")[alpha] subset bb("C")$ with minimal polynomial $f$ of degree $r$, (cf. *Example 67*). Since $bb("Q")[alpha]$ is separable, $f$ splits completely into simple zeros, whence
  $
    bb("C") times.o_(bb("Q")) bb("Q")[alpha] equiv bb("C") times.o_(bb("Q"))(bb("Q")[x]/(f)) equiv (bb("C")[x]/(f)) dot bb("C")[x] equiv product_(i=1)^n bb("C")[x]/(x-alpha_i)
  $

  as $bb("Q")$-algebras by *CRT*. As a $bb("C")$-vector space, this is isomorphic to $bb("C")^n$.

]
