#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#import "../defs.typ": *
#import "proof-layout.typ": proof
#show: show-theorion

== BU — Blowups and birational constructions <sup-bu>

The initial setting is a Noetherian integral scheme $X$ and a nonzero
coherent ideal $shf.i$. Write
$RR(shf.i)=bigOPlus(shf.i^n, n>=0)$ and
$pi:B=ops.proj_X RR(shf.i)->X$. The graded summand $shf.i^n$ has degree
$n$; on an affine chart the symbol $t$ records this grading inside
$A[t]$. The universal property is II.7.14; the purpose here is to compute
the construction. Purely algebraic assertions explicitly identified
below, including presentations and regular-local-ring facts, are left
to the reader to prove.

=== Rees algebras and the equations of a chart

#metadata(none) <sup-bu-1>
#proposition(number: "BU-1", title: "An invertible ideal, not just a quotient")[
  For a morphism $g:T->X$ such that $shf.i shf.o_T$ is an invertible
  ideal, II.7.14 gives a unique factorization through $B$.
  On $B$, the ideal $shf.i shf.o_B$ is canonically $shf.o_B(1)$, and
  $B->X$ is an isomorphism over $X-V(shf.i)$.
]
#proof[
  On $U=ops.spec A$, put $I=shf.i (U)$ and choose nonzero generators
  $f_0,dots,f_r$. The chart $D_+(f_i t)$ has ring $A[I/f_i]$ by BU-2.
  In this domain, the extended ideal $I$ is generated by $f_i$, a
  nonzerodivisor. The frame $f_i t$ of $shf.o_B(1)$ maps to $f_i$.
  On the overlap with the $j$-th chart, both frames change by $f_j/f_i$,
  so these isomorphisms agree and glue. Where $I$ is the unit ideal,
  its Rees algebra is $A[t]$ and its Proj is $ops.spec A$.

  For the factorization, cover $T$ by opens on which one image of an
  $f_i$ generates the invertible ideal $shf.i shf.o_T$. Such opens
  cover: in a local ring a set generating a free rank-one ideal
  contains a generator. Divide each $g^*f_j$ by this generator inside
  the ideal to define the map from $A[I/f_i]$. Any relation among
  these fractions holds after multiplication by a power of $g^*f_i$;
  that element is a nonzerodivisor, so the relation already holds.
  On intersections the fractions agree, and XL glues the maps.
  Their values on all $f_j/f_i$ also prove uniqueness. Thus one needs
  the image ideal to embed as an invertible subsheaf of $shf.o_T$.
  An arbitrary invertible quotient of $g^*shf.i$ need not have this
  property and describes different data, as in PJ2-1.
]

#metadata(none) <sup-bu-2>
#proposition(number: "BU-2", title: "Charts and saturation")[
  Let $A$ be a domain, $I=(f,f_1,dots,f_r)$, and $f!=0$. Then
  $
    D_+(f t)=ops.spec A[I/f], quad
    A[I/f]=A[f_1/f,dots,f_r/f] subset.eq A_f.
  $
  With $P=A[T_1,dots,T_r]$ and $J=(f T_i-f_i:1<=i<=r)$,
  $
    A[I/f] simeq P/(J:f^infinity), quad
    (J:f^infinity)=union.big_(n>=0)(J:f^n).
  $
]
#proof[
  In the Rees algebra, a degree-zero fraction with denominator
  $(f t)^n$ has numerator $a t^n$ for $a in I^n$, and maps to $a/f^n$
  in $A_f$. These fractions form exactly the subalgebra generated
  by the $f_i/f$. Equality is detected in $A_f$, since the Rees
  algebra is a subring of the domain $A[t]$. This proves the chart
  identification supplied by the Proj construction.

  The map $P->A_f$ sends $T_i$ to $f_i/f$. After localizing at $f$,
  its kernel is generated by $f T_i-f_i$ and its image is $A_f$.
  Contracting that localized ideal gives $(J:f^infinity)$.
  These two polynomial-localization assertions are left to the reader;
  they prove the displayed presentation. On the overlap of the
  $f$ and $f_j$ charts, $f_j/f$ is invertible and
  $f_i/f_j=(f_i/f)/(f_j/f)$. Thus the charts have canonical transition
  maps as subrings of the same fraction field.
]

#metadata(none) <sup-bu-3>
#example(number: "BU-3", title: "A component that must be removed")[
  In $A=k[x,y]$, take $I=(x^2,x y)$ and the $x^2$ chart.
  The naive equation is $x^2 T-x y=x(x T-y)=0$.
  It includes the extra plane $x=0$. Saturating by $x^2$ gives
  $(x T-y)$, so the correct chart is $k[x,T]$ with $y=x T$.
  Indeed its embedding in $A_x$ sends $T$ to $y/x$ and has no
  $x$-torsion. Proving this saturation identity is an algebra exercise.
  Removing a common factor without this kernel calculation would not
  justify the scheme structure of the chart.
]

#metadata(none) <sup-bu-4>
#proposition(number: "BU-4", title: "Exceptional scheme and strict transform")[
  The inverse-image closed subscheme $E=V(shf.i shf.o_B)$ satisfies
  $
    E simeq ops.proj_(V(shf.i))
    bigOPlus(shf.i^n/shf.i^(n+1), n>=0), quad
    shf.o_B(-E)=shf.i shf.o_B simeq shf.o_B(1).
  $
  If $Z subset.eq X$ is closed, its strict transform is the
  scheme-theoretic closure of $pi^(-1)(Z minus V(shf.i))$ in $B$.
  On the $f$ chart it is defined by
  $(J_Z A[I/f]:f^infinity)$, where $J_Z$ is the ideal of $Z$ on $U$.
]
#proof[
  The fiber-product construction of closed subschemes gives
  $E=ops.proj (RR(I) tensor_A A/I)$ on $U$ by PJ2-4.
  Its degree-$n$ component is $I^n/I^(n+1)$, proving the associated
  graded description. By BU-1 the ideal is locally generated by the
  nonzerodivisor $f$, so $E$ is an effective Cartier divisor and its
  ideal bundle is the one displayed.

  In the $f$ chart the inverse image of the complement of the center
  is $D(f)$: every generator of $I$ equals $f$ times an element of
  $A[I/f]$. The ideal of the scheme-theoretic closure from this open
  is the kernel of
  $A[I/f]->(A[I/f]/J_Z A[I/f])_f$.
  The localization kernel is precisely the stated saturation, an
  algebra assertion left to the reader. Further localization commutes
  with this kernel on the Noetherian chart, so the ideals agree on
  overlaps. This definition discards components contained entirely in
  the center and retains scheme structure on its complement.
]

#metadata(none) <sup-bu-5>
#proposition(number: "BU-5", title: "Flat base change")[
  If $g:X'->X$ is flat, then
  $op("Bl")_(shf.i shf.o_(X')) X' simeq B times_X X'$ canonically.
  An arbitrary base change still gives a canonical closed immersion
  $op("Bl")_(shf.i shf.o_(X')) X' -> B times_X X'$,
  which need not be an isomorphism.
]
#proof[
  On $ops.spec A'->ops.spec A$, the natural graded map
  $bigOPlus(I^n tensor_A A', n>=0)->bigOPlus((I A')^n, n>=0)$
  is always surjective: both multiplication and extension of ideals
  send products of $n$ elements of $I$ to products of their images.
  If $A'$ is flat, tensoring $0->I^n->A$ remains injective, identifying
  its image with $I^n A'=(I A')^n$. These are purely algebraic facts
  left to the reader. All identifications are induced by multiplication
  in $A'$, hence commute with restrictions and glue as graded-algebra
  maps. PJ2-4 compares Proj of the pulled-back Rees algebra with the
  fiber product, and PJ2-2 turns the graded surjection into the stated
  closed immersion. Under flatness the graded map is an isomorphism.

  For failure, take $A=k[x,y]$, $I=(x,y)$, and $A'=A/I=k$.
  The blowup of the zero ideal in $k$ is empty, because its Rees
  algebra has no positive-degree part. But the fiber of $B$ is
  $ops.proj k[u,v]=sch.p^1$, by BU-4. Thus arbitrary base change
  commutes with relative Proj while it need not commute with the Rees
  algebra of the image ideal.
]

=== Resolving sections and recording multiplicity

#metadata(none) <sup-bu-6>
#proposition(number: "BU-6", title: "The base ideal and graph closure")[
  Let $shf.l$ be invertible on integral Noetherian $X$, and let
  $s_0,dots,s_r$ be sections with at least one nonzero. Define $shf.i$
  by $op("im")(shf.o_X^(r+1)->shf.l)=shf.i shf.l$.
  On $B=op("Bl")_(shf.i)X$ the transformed sections generate
  $pi^*shf.l times.o shf.o_B(-E)$ and define a morphism
  $h:B->sch.p^r$. The map $(pi,h)$ identifies $B$ with the
  scheme-theoretic graph closure of the original rational map.
]
#proof[
  In a frame $l$ of $shf.l$ on $U=ops.spec A$, write $s_i=f_i l$.
  On the $f_i$ chart of the blowup, the common frame of the transformed
  bundle is $f_i pi^*l$, and the sections have coefficients $f_j/f_i$,
  one of which is $1$. Thus they generate. Replacing $l$ by a unit
  multiple rescales all $f_i$ by the inverse unit; ratios are
  unchanged and the frames $f_i l$ agree. On chart intersections the
  quotient coordinates also agree, so II.7.1 glues the morphism $h$.

  Locally the homogeneous map $A[T_0,dots,T_r]->RR(I)$ sends
  $T_j$ to $f_j t$ and is surjective. It gives a closed immersion
  $B|_U->U times sch.p^r$. The chart where $T_i!=0$ has coordinate
  ring $A[f_j/f_i]$, precisely the subalgebra of $A_(f_i)$ obtained
  by closing the graph on $D(f_i)$. In fact its ideal is the kernel
  of $A[T_j/T_i]->A_(f_i)$, as in BU-2. Since this ring is a domain,
  $D(f_i)$ is schematically dense in the chart; no extra component
  or nilpotent structure can be added to the closure. These closures
  agree under change of frame and restriction, proving the global
  identification. The birational interpretation of this graph is
  #book-link(<sup-rm-6>)[RM's graph construction].
]

#metadata(none) <sup-bu-7>
#proposition(number: "BU-7", title: "Multiplicity in a surface chart")[
  Let $C$ be an effective Cartier curve on a smooth surface over an
  algebraically closed field, and blow up a closed point $p$. If a local
  equation $F$ of $C$ has order $m$ in the regular maximal ideal at $p$,
  then, as Cartier divisors,
  $pi^*C=tildeOf(C)+m E$.
]
#proof[
  Choose regular parameters $x,y$ at $p$. In the $x$ chart put
  $y=x u$. Since $F in (x,y)^m$, its image has the form
  $x^m G$ in the chart ring. On $E$ the residue of $G$ is the
  degree-$m$ initial form of $F$ evaluated at $(1,u)$; it is a
  nonzero polynomial because $F in.not (x,y)^(m+1)$ and
  $op("gr")_(idl.m) shf.o_(X,p) simeq k[x,y]$.
  This associated-graded assertion and the conclusion that $(G)$
  is saturated with respect to $x$ are local algebra exercises:
  if $x H=G Q$, reduction modulo $x$ in the domain $k[u]$ forces
  $Q$ divisible by $x$, after which cancellation applies. Repeat to
  handle every power of $x$.

  BU-4 therefore identifies the strict transform with $G=0$ on this
  chart, while $x=0$ defines $E$. The $y$ chart gives $F=y^m H$ in
  the same way. On the overlap $y=x u$, the factors differ by the
  unit $u^m$, so their Cartier equations agree. Away from $p$ the
  blowup is an isomorphism. These opens prove the global equality,
  without an intersection-theoretic interpretation of multiplicity.
]

=== Regular centers

#metadata(none) <sup-bu-8>
#theorem(number: "BU-8", title: "Exceptional geometry of a regular center")[
  Let $X$ be a Noetherian regular scheme and let $Y$ be a regular closed
  subscheme of $X$, with $Y$
  containing no irreducible component of $X$. The blowup $B$ is regular.
  On a component where $Y$ has codimension $r$,
  $E simeq sch.p_Y(shf.i/shf.i^2)$, and
  $shf.n_(E/B) simeq shf.o_E(-1)$.
  If $X$ and $Y$ are smooth varieties, the exceptional fiber over a
  point is $sch.p^(r-1)$ over its residue field, and $dim B=dim X$.
]
#proof[
  By LP2's regular-immersion criterion, at every point of $Y$ its ideal
  is generated by a regular sequence $f_1,dots,f_r$ that is part of a
  regular system of parameters of the ambient regular local ring.
  Shrink to an affine neighborhood where these generators exist and
  generate the ideal. AL2's associated-graded result gives the
  canonical isomorphism
  $op("Sym")_(shf.o_Y)(shf.i/shf.i^2) simeq op("gr")_(shf.i)shf.o_X$.
  This map sends the class of each $f_i$ to its degree-one initial
  form, so it is independent of chosen generators and agrees on
  overlaps. BU-4 proves the projective-bundle description of $E$.

  To check regularity at a point of the $f_1$ chart above $Y$, write
  its ring, after localization on $X$, as
  $A[T_2,dots,T_r]/(f_1 T_2-f_2,dots,f_1 T_r-f_r)$.
  The needed algebra assertions are as follows, with proofs left to
  the reader. For a regular sequence, this quotient has no $f_1$-torsion,
  so it is the saturated chart of BU-2. At a prime over the center,
  the regular local polynomial ring has the independent classes of
  $f_1,dots,f_r$ in its cotangent space. The $r-1$ classes
  $T_i f_1-f_i$ are linearly independent there (their coefficients
  of $f_i$, for $i>=2$, are $-1$); they are part of a regular system
  of parameters. Quotienting by them gives a regular local ring.
  Every point over the center is in one such chart. Outside the
  center the blowup is an isomorphism, proving regularity everywhere.

  Finally $shf.i_E/shf.i_E^2=shf.o_B(-E)|_E=shf.o_E(1)$ by BU-4;
  dualizing gives the normal bundle and its negative sign. For a
  smooth pair one may choose étale local coordinates with center
  $x_1=dots=x_r=0$; the same charts have coordinates
  $x_1,x_2/x_1,dots,x_r/x_1,x_(r+1),dots,x_d$.
  The fiber formula follows from PJ2-4 and the rank-$r$ conormal
  bundle. Dimension follows either from these charts or from the
  dense open on which $pi$ is an isomorphism. This theorem gives
  properness via relative Proj; Hartshorne projectivity additionally
  follows from PM-3 when $X$ has an ample bundle, in particular for
  a quasi-projective variety.
]

=== Four computations

#metadata(none) <sup-bu-9>
#example(number: "BU-9", title: "The origin of the affine plane")[
  For $I=(x,y) subset k[x,y]$, the blowup has charts
  $U_x=ops.spec k[x,u]$, $y=x u$, and
  $U_y=ops.spec k[v,y]$, $x=v y$.
  On the overlap, $u$ is invertible, $v=u^(-1)$, and $y=x u$.
  The exceptional equations $x=0$ and $y=0$ glue to $sch.p^1$ with
  coordinates $u$ and $v$. The conormal frames satisfy $y=u x$,
  giving $shf.o_(sch.p^1)(1)$ and therefore $shf.n_E=shf.o (-1)$.
  A line $y=a x$ has total equation $x(u-a)=0$ and strict transform
  $u=a$; it meets $E$ at its slope. The line $x=0$ instead meets the
  point $v=0$ of the other chart. Distinct directions are separated.
  These chart equations and transitions follow from BU-2–BU-4; the
  polynomial presentation checks are left to the reader.
]

#metadata(none) <sup-bu-10>
#example(number: "BU-10", title: "The cusp and its normalization")[
  Let $C: y^2=x^3$ over an algebraically closed field of characteristic
  zero. In the $x$ chart of $op("Bl")_0 sch.a^2$, its total transform
  is $x^2(u^2-x)=0$ and its strict transform is $u^2=x$.
  Thus this chart of the strict transform is $ops.spec k[u]$, with
  $x=u^2$, $y=u^3$. In the $y$ chart, substitution $x=v y$ gives
  $y^2(1-v^3 y)=0$; the strict transform satisfies $v^3 y=1$.
  Here $v$ is invertible, so this entire chart lies in the first
  chart, with $v=u^(-1)$. The global strict transform is $sch.a^1$.
]
#proof[
  Saturating the two total-transform ideals by $x$ and $y$ removes
  their squared factors. The resulting ideals and the fact that no
  further factor is removed are polynomial algebra exercises left
  to the reader. BU-4 gives the strict transform, and the displayed
  transition identifies its gluing. Equivalently BU-2 applied inside
  the domain $k[x,y]/(y^2-x^3)$ gives the blowup of the cusp itself.

  The morphism $ops.spec k[u]->C$ is finite, because $u$ is integral
  over $k[u^2,u^3]$ with equation $u^2-x=0$. It is birational because
  $u=y/x$ in the fraction field. Finally $k[u]$ is integrally closed;
  the algebra assertion that a finite birational extension to an
  integrally closed domain is the integral closure is left to the
  reader. Hence this particular blowup is the normalization. Notice
  that the strict transform is smooth but tangent to the exceptional
  curve: its equation is $x=u^2$. Resolving the curve's singularity
  does not yet give a transverse total transform.
]

#metadata(none) <sup-bu-11>
#example(number: "BU-11", title: "The node and its two branches")[
  For the node $y^2=x^2(x+1)$ in characteristic zero, the $x$ chart
  with $y=x t$ has total equation $x^2(t^2-x-1)=0$. Saturation by
  $x$ gives $x=t^2-1$, $y=t(t^2-1)$, a copy of $sch.a^1_t$.
  In the $y$ chart, with $x=v y$, the strict equation is
  $1-v^2(v y+1)=0$. Thus $v$ is invertible, and this chart is already
  contained in the first, with $t=v^(-1)$. The polynomial saturation
  assertions are left to the reader. BU-4 identifies the resulting
  glued curve with the strict transform, and BU-2 identifies it with
  the blowup of the node. The map is finite since $t^2=x+1$, and
  birational since $t=y/x$; the integral-closure argument of BU-10
  identifies it with the normalization. Its inverse image of the
  node consists of the two distinct points $t=1$ and $t=-1$.
  Thus one blowup separates the two branches, whereas the cusp in
  BU-10 has only one point above its singularity.
]

#metadata(none) <sup-bu-12>
#example(number: "BU-12", title: "Blowing up the quadric cone")[
  Let $X: x y=z^2$ in $sch.a^3$ over an algebraically closed field of
  characteristic zero. Blow up $I=(x,y,z)$. Its $x$ chart has
  $y=x v$, $z=x u$ and, after saturation, $v=u^2$; thus its ring is
  $k[x,u]$. The $y$ chart similarly has ring $k[y,w]$ with
  $z=y w$, $x=y w^2$. The $z$ chart has
  $x=z a$, $y=z b$, $a b=1$, so it is $k[z,a,a^(-1)]$.
  It lies in the overlap of the first two charts. Consequently the
  blowup is smooth, including over the vertex.
]
#proof[
  The $x$-chart relation in the cone becomes $x^2(v-u^2)=0$.
  Its saturation is $(v-u^2)$, which has $x$-torsion-free quotient.
  The other two substitutions give the stated rings by the same
  kernel calculation of BU-2. These saturation identities are algebra
  exercises left to the reader. The two affine-plane charts are
  smooth, and the explicit overlap in them is
  $w=u^(-1)$, $y=x u^2$. Hence they glue to a smooth surface.

  The exceptional scheme is the conic $x y=z^2$ in the projective
  space of directions, by the associated graded ring in BU-4.
  The parametrization $[s:t] mapsto [s^2:t^2:s t]$ identifies it with
  $sch.p^1$: on the $x$ chart $u=t/s$, and on the $y$ chart $w=s/t$.
  Its hyperplane bundle is $shf.o_(sch.p^1)(2)$. BU-4 therefore gives
  $shf.n_(E/B)=shf.o_E(-1)=shf.o_(sch.p^1)(-2)$.
  Directly, the conormal frames satisfy $y=u^2 x$, agreeing with
  degree $2$. The ambient cone was singular at the center, so this
  conclusion follows from these charts, not from BU-8.
]

#metadata(none) <sup-bu-13>
#example(number: "BU-13", title: "A pencil of lines")[
  Consider the rational map
  $sch.p^2 arrow.r.dashed sch.p^1$, $[x:y:z] mapsto [x:y]$.
  Its base point is $p=[0:0:1]$. The blowup is the incidence surface
  $ B=V(x v-y u) subset sch.p^2 times sch.p^1. $
  The first projection contracts $E={p} times sch.p^1$; the second
  records the line through $p$ of direction $[u:v]$.
]
#proof[
  Over $z!=0$, put $X=x/z$, $Y=y/z$. The incidence equation on
  $u!=0$ is $Y=X(v/u)$, and on $v!=0$ it is $X=Y(u/v)$.
  These are exactly the two affine charts in BU-9, including their
  transition. Away from $p$, at least one of $x,y$ is nonzero, so
  the equation determines $[u:v]=[x:y]$ uniquely and the first
  projection is an isomorphism. These opens cover the incidence
  surface and identify it with the blowup; the identifications agree
  since they use the same coordinate ratios. BU-6 identifies it with
  the graph closure. The transformed pencil has bundle
  $pi^*shf.o_(sch.p^2)(1) times.o shf.o_B(-E)$.

  To identify the ruling, over $u!=0$ write a point as
  $[x:y:z]=[lambda:lambda t:mu]$, $t=v/u$. Over $v!=0$ write it as
  $[lambda' s:lambda':mu']$, $s=u/v$. The fiber coordinates satisfy
  $[lambda':mu']=[t lambda:mu]$. In the quotient convention this is
  $sch.p_(sch.p^1)(shf.o plus.o shf.o (1))$, with quotient coordinates
  $[mu:lambda]$. The exceptional section is $lambda=0$, hence is
  the quotient onto $shf.o$. PJ2-7 gives its normal bundle $shf.o (-1)$.
]

#exercise(title: "The quadratic Cremona map")[
  For $[x:y:z] mapsto [y z:x z:x y]$, show that the base ideal is
  the ideal of the three coordinate points: on $x!=0$ it is $(y,z)$,
  and cyclically on the other charts. Blow up these three disjoint
  points. Apply BU-6 to obtain a morphism to $sch.p^2$ and check in
  the two charts over each point that the transformed coordinates
  generate. Its hyperplane bundle is
  $pi^*shf.o (2) times.o shf.o (-E_1-E_2-E_3)$, or the divisor class
  $2H-E_1-E_2-E_3$. Determine which strict transforms are contracted.
  This calculation concerns these three explicit centers; it does not
  assert a general factorization theorem for birational maps.
]

The chart computations correspond to Liu 8.1.2–8.1.5; flat base change
and exceptional geometry correspond to 8.1.12 and 8.1.19–8.1.20.
The construction and universal property remain those of
#book-link(<text-ii-7>)[Hartshorne II.7.13–II.7.17].

Related exercises: #book-link(<exercise-ii-7-11>)[II.7.11] uses the Rees and grading tools, and #book-link(<exercise-ii-8-5>)[II.8.5] asks for additional global Picard and canonical formulas beyond BU-8.
