#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#import "../defs.typ": *
#import "proof-layout.typ": proof
#show: show-theorion
#set enum(numbering: "(a)", indent: 1em)

== CS — Closed subschemes and ideal sheaves <sup-cs>

The definitions are in #book-link(<text-ii-3>)[II.3, D7–D8]. The ideal-sheaf
correspondence remains in #book-link(<text-ii-5>)[II.5, Proposition 5.9 and
  Corollary 5.10]. CS-1 gives the affine quotient dictionary; target locality
and base-change stability are deduced in #book-link(<sup-lp-33>)[LP-33].

#metadata(none) <sup-cs-1>
#proposition(number: "CS-1", title: "Affine quotient dictionary")[
  - For $X=ops.spec A$ and $I subset.eq A$, the above results identify the
    ideal sheaf $tildeOf(I)$, the quotient structure sheaf, and the closed
    immersion $ops.spec(A\/I)->X$. On each $D(f)$, the comparison is the
    canonical quotient $A_f\/I A_f simeq (A\/I)_(bar(f))$.

  - In particular, the affine map induced by $A->B$ is a closed immersion
    exactly when this ring map is surjective.

  - Use this as the common entry for II.2.18(c)–(d), II.3.11(b), and
    II.5.5(b), the last of which also uses that a quotient is a finite module.

  - For the ideal of an arbitrary closed subscheme, use the main-text
    correspondence, rather than a new construction of associated sheaves.
]

#proof[
  #set enum(numbering: "1.")

  + *Identify the closed subset.* Write $q:A->A\/I$ for the quotient map. Its prime contraction identifies
    $ops.spec(A\/I)$ with $V(I)$.

  + *Identify the quotient structure sheaf.* On $D(f)$, localization of the exact sequence
    $I->A->A\/I->0$ gives the quotient $A_f\/I A_f$.
    The maps sending $a/f^n$ to $bar(a)/bar(f)^n$ give its canonical
    identification with $(A\/I)_(bar(f))$. These identifications commute with
    further localization and therefore identify the quotient sheaf and the
    structure sheaf on the closed subset. This is precisely the ideal-sheaf
    correspondence of II.5.9–II.5.10.

  + *Characterize affine closed immersions.* A surjection $A->B$ identifies $B$ with its quotient by the kernel, so
    gives a closed immersion. Conversely, the same correspondence assigns to
    a closed immersion into $ops.spec A$ an ideal $I$ and identifies its
    source with $ops.spec(A\/I)$ over $ops.spec A$. Applying the affine
    ring–scheme correspondence shows that the original map $A->B$ is
    surjective.

  + *Record module finiteness.* Finally, $A\/I$ is generated by $1$ as an $A$-module.
]

#metadata(none) <sup-cs-2>
#proposition(number: "CS-2", title: "Restriction and base change")[
  - If $i:Z->X$ has ideal $shf.i$ and $g:X'->X$, the base-changed closed
    subscheme has ideal
    $ops.im(g^*shf.i -> shf.o_(X'))$, denoted $shf.i shf.o_(X')$.

  - For open restriction, this is $shf.i|_(X')$.

  - In general, $g^*shf.i$ itself
    need not embed into $shf.o_(X')$.
]

#proof[
  #set enum(numbering: "1.")

  + *Compute the affine base change.* Cover $X$ by affine opens $U=ops.spec A$, and cover $g^(-1)U$ by affine
    opens $U'=ops.spec B$. If $Z inter U=ops.spec(A\/I)$, the fiber-product
    computation of #book-link(<sup-mg-1>)[MG-1] identifies its pullback to $U'$
    with $ops.spec(tensor(B, A\/I, over: A))$.

  + *Compute the ideal as an image.* Tensor right exactness gives
    $tensor(B, A\/I, over: A) simeq B\/I B$, where $I B$ is the image of
    $tensor(B, I, over: A)->B$, not an asserted copy of its source.
    Thus CS-1 identifies its ideal with this image.

  + *Glue the affine identifications.* All the maps used are
    induced by multiplication and quotient maps; they commute with restriction
    to principal opens. Refining overlaps by such opens proves that the local
    identifications glue to the asserted ideal sheaf on $X'$.

  + *Specialize to open restriction.* For an open immersion, the sheaf pullback is restriction, which is exact,
    so the image is simply $shf.i|_(X')$.
]

#metadata(none) <sup-cs-3>
#example(number: "CS-3", title: "Pullback of an ideal need not be an ideal")[
  For $A=k[t]$, $I=(t)$, and $B=A\/(t)$, the map
  $tensor(I, B, over: A)->B$ is zero although its source is nonzero.
]

#proof[
  Multiplication by $t$ gives an $A$-module isomorphism $A simeq I$, since
  $k[t]$ is a domain. Tensoring it with $B$ identifies
  $tensor(I, B, over: A)$ with $B=k$, which is nonzero. Under this
  identification, the displayed map is multiplication by the image of $t$
  in $B$, hence is zero.
]

#metadata(none) <sup-cs-4>
#proposition(number: "CS-4", title: "Reduced induced structures")[
  - For a closed subset $Z$ of a scheme, there is a unique reduced closed
    subscheme with that underlying subset. On an affine chart, it is cut out by
    the radical ideal corresponding to $Z$; the restriction identifications
    are the ones of CS-1–CS-2.

  - The ideals and closed subschemes are ordered
    in opposite directions: $shf.i subset.eq shf.j$ gives
    $V(shf.j) subset.eq V(shf.i)$ as closed subschemes.

  - For reduction of the whole scheme and its reduced-source universal
    property use #book-link(<sup-xp-9>)[XP-9].
]

#proof[
  #set enum(numbering: "1.")

  + *Choose compatible radical ideals.* For each affine open $U=ops.spec A$, choose the radical ideal $I_U$
    determined by $Z inter U$. The affine closed-set dictionary gives its
    existence and uniqueness. On a principal open $D(f) subset U$,
    the ideal $I_U A_f$ is radical and cuts out $Z inter D(f)$: this uses
    $sqrt(I)A_f=sqrt(I A_f)$, a localization identity left to the reader (Check!).

  + *Glue the reduced closed structure.* Consequently, the ideals from any two charts
    agree after refinement of their intersection by affine principal opens.
    They glue to a quasi-coherent ideal sheaf, and CS-1 constructs its closed
    subscheme. Its affine rings $A\/I_U$ are reduced, so the scheme is
    reduced by #book-link(<sup-xp-9>)[XP-9].

  + *Prove uniqueness.* Conversely, every reduced closed subscheme has radical quotient kernels
    on these charts, forcing the same $I_U$ and hence the same ideal sheaf.

  + *Reverse inclusions.* If $I subset.eq J$, the quotient map $A\/I->A\/J$ is surjective;
    these quotient maps commute with localization and glue to the asserted
    inclusion of closed subschemes. This also proves the reversal of order.
]

#metadata(none) <sup-cs-5>
#example(number: "CS-5", title: "Distinct structures on the same closed subset")[
  The ideals $(t)$ and $(t^2)$ on $sch.a^1_k$ give the same point set
  but distinct closed subschemes; only the first is reduced.
]

#proof[
  A prime contains $t^2$ exactly when it contains $t$, so the two vanishing
  sets agree. The image of $t$ in $k[t]\/(t^2)$ is nonzero, by comparison
  of polynomial degrees, and has square zero. Thus this quotient is not
  reduced, whereas $k[t]\/(t) simeq k$ is reduced. Their distinct ideals
  give distinct closed subschemes by CS-1.
]

#metadata(none) <sup-cs-6>
#corollary(number: "CS-6", title: "Classical vanishing ideals")[
  - For a variety over an algebraically closed field and a closed subvariety,
    use #book-link(<sup-vs>)[VS] to pass to the associated schemes $i:Y->X$.
    The sheaf of regular functions vanishing on $Y$ identifies with its ideal
    sheaf $shf.i_Y$, and the canonical map gives
    $shf.o_X\/shf.i_Y simeq i_*shf.o_Y$ as sheaves of rings on $X$.

  - This is the application of II.5.9–II.5.10 to II.1.21(a)–(b); quotient
    sheaves and stalkwise surjectivity have the meaning of
    #book-link(<sup-sc-4>)[SC-4].

  - Surjectivity on every open is not implied.
    The two-point global-sections example is in #book-link(<sup-sc-examples>)[SC-14].
]

#proof[
  #set enum(numbering: "1.")

  + *Identify the affine vanishing ideal.* Take an affine chart of $X$ corresponding under VS-2 to an affine
    variety with coordinate ring $A$. Its intersection with $Y$ is cut out
    by a radical ideal $I$. The Nullstellensatz identifies $I$ with the
    functions in $A$ vanishing at all classical points of this intersection.
    The algebraic Nullstellensatz is the reader check in this reduction (Check!).

  + *Identify and glue the vanishing sheaf.* The same assertion on each principal open uses the coordinate ring
    $A_f$ and the radical ideal $I A_f$. These principal opens form a basis,
    so the identifications determine the vanishing sheaf as $tildeOf(I)$.
    They commute with restrictions and hence glue on overlapping charts.

  + *Identify the quotient sheaf.* CS-1 now identifies the quotient sheaf with $i_*shf.o_Y$ on every chart,
    and thus globally. This is an isomorphism of sheaves: its quotient map
    is surjective on stalks, as explained in SC-4.
]
