#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *
#import "proof-layout.typ": proof

== LP2 — Further Locality Criteria <sup-lp2>

This supplement collects the local criteria needed for differentials, regular
centers, and relative positivity. Unless explicitly stated otherwise, the
schemes in LP2-1–LP2-9 are locally Noetherian and the morphisms under consideration
are locally of finite type. In this setting they are locally of finite
presentation. For general schemes, retain the finite-presentation hypotheses
where they occur below; finite type alone does not replace them.

*Reading route.* LP2-1–LP2-6 use #book-link(<sup-df-1>)[DF-1–DF-4] and
#book-link(<sup-lp>)[LP's flatness and affine-locality calculus]. LP2-7–LP2-9 use
#book-link(<sup-al2>)[AL2's regular-sequence algebra] and
#book-link(<sup-cs-1>)[CS-1's closed-immersion dictionary]. LP2-11–LP2-12 start
from the definition of relative ampleness in #book-link(<sup-pm-1>)[PM-1];
they can be read independently of LP2-1–LP2-9. No argument below uses cohomology.

=== Relative smoothness and infinitesimal lifting

#metadata(none) <sup-lp2-1>
#definition(number: "LP2-1", title: "The three morphism classes")[
  A morphism $f:X -> Y$ is *unramified* if it is locally of finite type and
  its diagonal $X -> fiber(X, X, base: Y)$ is an open immersion. It is *smooth*
  if it is flat, locally of finite presentation, and has geometrically regular
  fibers. A scheme over a field is geometrically regular when its base change
  to every finite field extension is regular. An *étale* morphism is a smooth
  morphism of relative dimension zero.

  An infinitesimal lifting problem is a commutative square consisting of
  $T_0 -> X$, $T -> Y$, and a closed immersion $T_0 arrow.r.hook T$ defined
  by a square-zero ideal. The three corresponding formal conditions are:
  at most one lift; existence of lifts locally on $T$; and exactly one lift.
  The existence condition deliberately allows an open cover of $T$.
  Smoothness does not assert the existence of a global lift for every $T$.
]

#metadata(none) <sup-lp2-2>
#lemma(number: "LP2-2", title: "The affine algebra used in the criteria")[
  Let $A -> B$ be a finitely presented ring map.
  + The following are equivalent: $B$ is flat over $A$ with geometrically
    regular fibers; every algebra map $B -> C/J$, for an $A$-algebra $C$
    and square-zero ideal $J$, lifts to $C$; and $ops.spec B$ has a principal
    open cover whose rings admit presentations
    $ (A[t_1,dots,t_n]\/ideal(f_1 "," dots "," f_r))_g $
    with an $r$ by $r$ Jacobian minor invertible. In the last expression
    $r<=n$, and the minor differentiates with respect to $r$ selected variables.
  + Uniqueness of such lifts is equivalent to $Omega_(B\/A)=0$. If $B$ is
    merely of finite type, it is also equivalent to the diagonal ideal
    $I=ops.ker(tensor(B, B, over: A) -> B)$ satisfying $I=I^2$; this finitely
    generated ideal is then generated by an idempotent.
  + A finitely presented algebra is étale if and only if it is flat and
    $Omega_(B\/A)=0$. Equivalently it admits the preceding local
    presentations with $r=n$; the lifts then exist uniquely.
  + Over a perfect field, a finitely generated algebra is geometrically
    regular if and only if it is regular.
]
#remark(title: "Reader proof: the algebraic criterion")[
  All assertions in LP2-2 are purely commutative-algebraic theorems, and their
  proofs are left to the reader. The existence argument uses the Jacobian
  matrix to correct chosen lifts modulo $J$: Taylor expansion has no terms
  of degree two in the corrections because $J^2=0$. For the converse,
  lift a polynomial presentation modulo the square of its relation ideal,
  split the resulting conormal map, and choose a nonvanishing minor after
  localization. The equivalence with flat geometrically regular fibers is
  the algebraic smoothness criterion; it is an essential input, not a
  consequence of local freeness of $Omega$ alone. See Liu §6.2 for these
  algebraic forms of the criteria.
]

#metadata(none) <sup-lp2-3>
#proposition(number: "LP2-3", title: "Differentials and lifting on schemes")[
  A locally finite type morphism is unramified if and only if
  $Omega_(X\/Y)=0$. A locally finitely presented morphism is étale if and
  only if it is flat and unramified. Smooth morphisms have locally free
  differentials, whose rank is their relative dimension. The three morphism
  classes have respectively the uniqueness, local existence, and unique
  existence lifting properties of LP2-1, with their stated finiteness hypotheses.
]
#proof[
  Cover $Y$ by $V=ops.spec A$ and each $f^(-1)V$ by $U=ops.spec B$.
  The restriction of $Omega_(X\/Y)$ to $U$ is
  $tildeOf(Omega_(B\/A))$; it is zero exactly when its module of sections
  is zero. On $U times_V U$ the diagonal is induced by multiplication
  $tensor(B, B, over: A) -> B$. LP2-2 identifies vanishing of differentials
  with an idempotent diagonal ideal, so this diagonal is an open and closed
  immersion. These neighborhoods cover the image of the full diagonal.
  Away from its image the question of being an open immersion imposes no
  condition; the local identifications on neighborhoods of each image point
  show that the full diagonal is an open immersion. Conversely, restriction
  of an open diagonal to these affine pairs gives the same idempotent-ideal
  calculation. This proves the unramified criterion.

  Flatness is checked on these affine pairs by
  #book-link(<sup-lp-36>)[LP's flatness criterion]. Apply LP2-2 to obtain the
  étale equivalence. For smoothness, choose the standard charts of LP2-2.
  DF-2 eliminates the differentials corresponding to the invertible minor,
  leaving a free module of rank $n-r$. The same presentation has fibers
  of dimension $n-r$, giving the rank assertion.

  For a lifting square, a nilpotent closed immersion identifies the underlying
  spaces of $T_0$ and $T$. Cover $T$ by affine opens small enough that their
  restrictions to $T_0$ map into an affine $U$ above an affine $V$. The
  lifting problem is precisely $B -> C/J$ over $A$. Apply LP2-2 there.
  In the unramified and étale cases any two lifts agree on affine refinements
  of their intersections, so uniqueness glues them; in the smooth case
  local existence is the conclusion and gluing is not asserted. Conversely,
  the same affine squares test the ring criterion. For formal smoothness,
  local lifts on an affine test scheme imply a global lift: their differences
  are derivations into $J$, and a finite principal cover admits the usual
  denominator-clearing gluing of module sections. This elementary affine
  module gluing assertion is left to the reader.
]

#metadata(none) <sup-lp2-4>
#proposition(number: "LP2-4", title: "Standard smooth charts and étale coordinates")[
  Put $B=(A[t_1,dots,t_n]\/ideal(f_1 "," dots "," f_r))_g$ and suppose
  $Delta=op("det")((partial f_i)/(partial t_j))_(1<=i,j<=r)$ is a unit
  in $B$. Then $ops.spec B -> ops.spec A$ is smooth of relative dimension
  $n-r$. The coordinate map
  $ops.spec B -> sch.a_A^(n-r)$ given by $t_(r+1),dots,t_n$ is étale.
  Every smooth morphism has such charts after restricting both source and
  target. In particular the smooth locus of a locally finitely presented
  morphism is open.
]
#proof[
  Apply LP2-2 with $A$ and with $A'=A[t_(r+1),dots,t_n]$ as base rings.
  Over $A'$ the same minor is square and includes all the remaining
  variables, so the relative dimension is zero. The extra localization at
  $g$ is still a finitely presented algebra, using a new variable and
  relation $g u-1$ if necessary. These statements give the asserted affine
  morphisms through LP2-3.

  At a smooth point, LP2-2 supplies such a presentation on an affine source
  neighborhood over an affine target neighborhood. Inverting its minor
  and the finitely many denominators is an open restriction. Every point
  of the resulting neighborhood is smooth, so these neighborhoods form an
  open set. The algebraic criterion also shows that they contain every
  smooth point, proving openness. The differential map to affine space
  identifies the free basis $d t_(r+1),dots d t_n$, and its compatibility
  on overlaps follows from the universal derivation, as in DF-4.
]

#metadata(none) <sup-lp2-5>
#proposition(number: "LP2-5", title: "Locality, composition, and base change")[
  Smooth, étale, and unramified morphisms are local on both source and target
  for open covers, and are preserved by composition and arbitrary base change.
]
#proof[
  For source restriction replace $B$ by $B_h$ on an affine pair; for target
  restriction replace $A -> B$ by $A_a -> B_a$. In each case the lifting
  criteria of LP2-2 are preserved: elements already invertible modulo a
  square-zero ideal lift to units. Conversely, a principal cover of
  $ops.spec B$ gives local lifts after pulling back that cover to the test
  scheme. Uniqueness glues when required, and local existence requires no
  chosen global gluing. The source and target affine refinements are exactly
  those of #book-link(<sup-lp-6>)[LP-6];
  #book-link(<sup-lp-7>)[LP-7] and #book-link(<sup-lp-9>)[LP's affine
    communication] therefore pass from these covers to arbitrary affine pairs.
  Flatness and finite presentation have the required locality by LP, and
  LP2-2 identifies the resulting class with the geometric definitions.

  Under $A -> A'$, a map from $tensor(B, A', over: A)$ into a test algebra
  is a compatible pair of maps from $B$ and $A'$. Lift the first over the
  already fixed second map. This proves preservation of existence and
  uniqueness. Finite presentation and finite type survive tensor product;
  flatness survives base change by LP. The fiber-product affine charts cover
  the new scheme, so this argument proves arbitrary scheme base change.

  For $X -> Y -> Z$, first lift a test map to $Y$, then to $X$, refining
  the cover of the test scheme at the second step. The composite lift exists
  locally in the smooth case; in the other cases the two applications of
  uniqueness prove the required uniqueness. Finite type and finite
  presentation are preserved by composition, as is flatness. These
  constructions are compatible with restriction of each lifting square,
  completing the scheme argument. The elementary ring facts about units
  modulo nilpotent ideals and tensor-product maps used here are left to
  the reader.
]

#metadata(none) <sup-lp2-6>
#example(number: "LP2-6", title: "What the differential criterion requires")[
  A finite type scheme over a perfect field is smooth if and only if it is
  regular: field-flatness and finite presentation are automatic, and LP2-2
  identifies regularity with geometric regularity. Over an imperfect field
  this fails. The field $K=k[t]\/ideal(t^p-a)$ of
  #book-link(<sup-df-9>)[DF-9] is regular, but
  $tensor(K, K, over: k)=K[u]\/ideal(u^p)$ is not regular.

  The power map of #book-link(<sup-df-8>)[DF-8] is étale exactly where its
  derivative is a unit, with the identity case included. Frobenius is finite
  flat of relative dimension zero with free differentials of rank one;
  LP2-3 therefore rules out smoothness. A useful converse to local freeness
  is the following precise fiber criterion: for a flat locally finitely
  presented morphism, if every geometric fiber is regular, the morphism is
  smooth. This is the definition via fibers, not a conclusion from a rank
  computation alone. The family in #book-link(<sup-vs2>)[VS2] illustrates
  the distinction between a smooth total space and a smooth morphism.
]

=== Local equations and regular immersions

#metadata(none) <sup-lp2-7>
#proposition(number: "LP2-7", title: "Effective Cartier divisors")[
  A closed subscheme $D subset X$ is an effective Cartier divisor if and only
  if, on an open cover of $X$, its ideal is generated by one non-zero-divisor.
  This condition is local on $X$, is preserved under open restriction, and
  is preserved by flat pullback. For an arbitrary pullback the exact
  criterion is that the pulled-back local equation remain a non-zero-divisor.
]
#proof[
  Use #book-link(<sup-cs-1>)[CS-1] to write the closed immersion on
  $U=ops.spec A$ as $ops.spec(A/I) -> ops.spec A$. An identification
  $I simeq A$ whose image in $A$ is multiplication by $a$ is equivalent to
  $I=ideal(a)$ and injectivity of multiplication by $a$. This is precisely
  the invertible-ideal definition of an effective Cartier divisor in
  #book-link(<sup-dv>)[DV]. On an overlap two such generators differ by a
  unit, so the criterion does not depend on trivialization. Restricting to
  $D(s)$ localizes this injective map.

  For a flat affine pullback $A -> B$, tensor
  $0 -> A arrow.r.long^(dot a) A -> A\/ideal(a) -> 0$ with $B$.
  Its first map remains injective and is multiplication by the image of
  $a$. The pulled-back ideal is therefore generated by this non-zero-divisor.
  These local equations have the pulled-back unit transition functions and
  glue. The preservation of injections under flat tensor product is a
  module-algebra fact left to the reader. Without flatness it can fail:
  pulling $V(t) subset ops.spec k[t]$ back to itself makes its equation zero.
]

#metadata(none) <sup-lp2-8>
#proposition(number: "LP2-8", title: "Regular immersions")[
  A closed immersion $i:Z arrow.r.hook X$ is *regular* if its ideal is locally
  generated by a regular sequence. This property is local on the ambient
  scheme near $Z$ and local on $Z$ by neighborhoods in $X$. It is preserved
  by flat base change and by composition of regular closed immersions.
  A regular immersion of codimension $r$ has locally free conormal sheaf
  of rank $r$; the converse is false.
]
#proof[
  On $ops.spec A$ write the ideal as $I=ideal(a_1 "," dots "," a_r)$. Restriction
  localizes the successive injective multiplication maps on
  $A\/ideal(a_1 "," dots "," a_(j-1))$. A flat base change tensors those maps
  with a flat algebra $B$, so they remain injective on the corresponding
  quotient rings; if the resulting closed subscheme is empty there is no
  point at which a positive-codimension assertion is required. For a
  composite, let $J/I$ in $A/I$ be generated by a regular sequence
  $overline(b)_1,dots,overline(b)_s$. Then $J$ is generated by
  $a_1,dots,a_r,b_1,dots,b_s$, a regular sequence in this order.
  Each of these ring assertions, and the freeness of $I\/I^2$ with the
  displayed generators, belongs to #book-link(<sup-al2>)[AL2]; their purely
  algebraic proofs are left to the reader.

  These computations occur on ambient affine neighborhoods of each point
  of $Z$. Finite generation lets one shrink the neighborhoods when lifting
  local generators or removing denominators. A cover of $Z$ by such
  neighborhoods therefore proves the original definition; no equations
  need to be chosen globally and no identification of different generating
  sequences is assumed. To see why the converse fails, take
  $A=k[epsilon]\/ideal(epsilon^2)$ and $I=ideal(epsilon)$. Then $I\/I^2$
  is one-dimensional over $A/I=k$, but its generator is a zero divisor, so
  this closed immersion is not regular.
]

#metadata(none) <sup-lp2-9>
#proposition(number: "LP2-9", title: "Regular closed subschemes and conormal injectivity")[
  A closed immersion of a regular locally Noetherian scheme into a regular
  locally Noetherian scheme is regular. In particular a closed immersion
  $i:X arrow.r.hook Y$ of smooth schemes of finite type over a field is
  regular. In the latter case its conormal sequence is short exact and
  locally split:
  $0 -> shf.i\/shf.i^2 -> i^*Omega_(Y\/k) -> Omega_(X\/k) -> 0$.
]
#proof[
  At $x in X$, write $R=shf.o_(Y,x)$ and $S=R/I=shf.o_(X,x)$.
  Both are regular local rings. The local algebra assertion used here is:
  if a Noetherian regular local ring has a regular quotient, its kernel
  is generated by a regular sequence of length $dim R-dim S$.
  This is #book-link(<sup-al2-12>)[AL2-12], whose purely algebraic proof
  is left to the reader. Choose representatives of the resulting
  generators on an affine neighborhood of $x$. The cokernel of their map
  onto the ideal is finite, and the kernels of the successive multiplication
  maps are finite. They vanish at $x$, hence vanish after inverting an element
  outside its prime ideal. Thus, after shrinking, the same sequence generates
  the ideal and is regular. This proves the geometric regular-immersion
  assertion, with the passage from stalks to neighborhoods made explicit.

  Smooth schemes over $k$ are regular, by LP2-2 after field extension to an
  algebraic closure and the algebraic descent of regularity along a field
  extension. For conormal injectivity use more than regularity of the
  immersion: on an affine pair $B -> C=B/I$, both rings are smooth over
  $k$. The algebraic lifting property of $C$ gives a section
  $C -> B/I^2$ of the quotient. Consequently the square-zero extension is
  the split algebra $C plus.o I/I^2$. Differentiating this split algebra
  and tensoring with $C$ identifies its differentials with
  $Omega_(C\/k) plus.o I/I^2$. The canonical map from $I/I^2$ is the
  second summand inclusion. The quotient $B -> B/I^2$ induces the same
  conormal sequence after tensoring with $C$, because differentials of
  elements of $I^2$ vanish there. These square-zero module calculations are
  left to the reader. They prove injectivity in II.8.4A. Smoothness makes
  $Omega_(C\/k)$ locally free, so the sequence splits locally. The canonical
  differential maps commute with restrictions, and exactness on this affine
  cover yields the global sequence. The splitting need not be canonical.
]

#metadata(none) <sup-lp2-10>
#remark(number: "LP2-10", title: "Where the construction comparisons belong")[
  #book-link(<sup-pj2>)[PJ2] constructs the affine charts and base-change
  isomorphism for relative Proj. Over a Noetherian base, a finitely generated
  graded algebra generated in degree one has standard charts finitely
  generated over the base ring; they are finitely presented because that
  ring is Noetherian. Thus LP's finite-presentation locality applies directly.
  The projective-bundle charts are affine spaces, so LP2-4 proves smoothness
  of their projection and LP2-5 glues it.

  #book-link(<sup-bu>)[BU] proves the flat base-change comparison for Rees
  algebras. It identifies the two blowup constructions themselves;
  LP2-7–LP2-9 then apply to the regular centers and Cartier exceptional divisors
  under their stated hypotheses. The comparison is not asserted for every
  nonflat base change. Projectivity and its stability are handled by
  #book-link(<sup-lp>)[LP], using the constructions of PJ and PJ2.
]

=== A fixed line bundle and relative positivity

#metadata(none) <sup-lp2-11>
#proposition(number: "LP2-11", title: "Locality of relative ampleness")[
  Let $f:X -> Y$ be of finite type between Noetherian schemes, and fix one
  invertible sheaf $shf.l$ on $X$. Relative ampleness of $shf.l$ is local
  on the target. Positive powers and open restrictions
  preserve it, and $shf.l$ is relatively ample if a positive power is.
  Arbitrary base change preserves relative ampleness. On a Noetherian base,
  the definition may be checked on an affine open cover of the target.
]
#proof[
  Use the affine-cover definition of #book-link(<sup-pm-1>)[PM-1].
  Restricting an ample sheaf to an open subscheme preserves ampleness by
  II.5. Refining target covers by affine opens therefore proves target
  locality. We must additionally show that the fixed $shf.l$ is ample over
  every affine open $V=ops.spec A$ of $Y$, not just the chosen cover.
  Choose a finite principal cover $D(a_i)$ of $V$ subordinate to that cover.
  Put $X_i=f^(-1)D(a_i)$. On each $X_i$, nonvanishing loci of sections of
  positive powers of $shf.l$ form an affine basis.

  If $s$ is such a section on $X_i$, the section-extension lemma of II.5
  extends $(f^*a_i)^m s$ to a section $t$ on $X_V$ for some $m$.
  Replace $t$ by $(f^*a_i)t$. Its nonvanishing locus is contained in $X_i$
  and is exactly the nonvanishing locus of $s$ there. Thus sections of powers
  of $shf.l$ on $X_V$ give the same affine basis, proving ampleness on
  $X_V$. Replacing the exponent of any section by a multiple of a fixed
  positive integer leaves its nonvanishing locus unchanged. This proves
  both power assertions; open restriction was used at the start.

  For base change first take $Y=ops.spec A$ and $Y'=ops.spec A'$.
  Choose finitely many nonvanishing loci of sections of powers of $shf.l$
  giving the affine-basis criterion about a point. The inverse image of
  each such affine locus is affine, its coordinate ring being tensor product
  over $A$, and it is the nonvanishing locus of the pulled-back section.
  These loci cover $X'=fiber(X, Y', base: Y)$. To get a basis inside each
  such affine locus, use its principal opens: a section of its coordinate
  ring is a finite sum of tensors. Extend the finitely many coefficients
  from the original affine locus by multiplying each by a sufficiently
  high common power of its defining section, using II.5. Their pulled-back
  linear combination extends the chosen function after that multiplication.
  Multiplying once more by the defining section ensures that its
  nonvanishing locus lies inside the original affine locus. This produces
  exactly the principal refinements from sections of positive powers of
  the pulled-back line bundle. This is the affine section-extension argument of
  II.5, with the elementary localization check left to the reader.
  Apply the affine-basis criterion again and cover a general $Y'$ by affine
  opens. The pullback identifications use the same global sheaf, so they
  agree on intersections.

  The datum here is one $shf.l$ with compatible restrictions. A collection
  of unrelated ample bundles on inverse images of target opens supplies no
  such datum; nor does relative ampleness by itself choose a global
  projective embedding. Those additional issues belong to
  #book-link(<sup-pm>)[PM] and #book-link(<sup-lp>)[LP].
]

#metadata(none) <sup-lp2-12>
#proposition(number: "LP2-12", title: "Spreading from the entire local base")[
  Let $f:X -> Y$ be proper with $Y$ Noetherian, let $y in Y$, and let
  $shf.l$ be an invertible sheaf on $X$. Write
  $X_y^"loc"=fiber(X, ops.spec shf.o_(Y,y), base: Y)$.
  + If the restriction of a coherent sheaf $shf.f$ to $X_y^"loc"$ is
    generated by finitely many global sections, then $shf.f$ is generated
    by finitely many sections over $f^(-1)V$ for some open neighborhood
    $V$ of $y$.
  + If $shf.l|_(X_y^"loc")$ is ample, then $shf.l$ is relatively ample
    over such a $V$.
  These hypotheses concern the entire local base, not merely the closed
  fiber $X_y$.
]
#proof[
  Restrict the target to $ops.spec A$ about $y$ and let $idl.p$ correspond
  to $y$. The proper source is quasi-compact and separated. Choose a finite
  affine cover $U_i=ops.spec B_i$; its pairwise intersections are affine,
  because $X$ is separated over the affine target. Write $M_i$ and $M_(i j)$
  for the modules of sections of $shf.f$ on these opens. Global sections
  are the kernel of the difference map between the finite products of the
  $M_i$ and the $M_(i j)$. Localization is exact and commutes with these
  finite products. Thus
  $
    Gamma(X, shf.f)_idl.p simeq Gamma(X_y^"loc", shf.f|_(X_y^"loc")).
  $
  This purely module-theoretic localization assertion is left to the reader.
  Clear the finitely many denominators in the given sections by an element
  $a in A minus idl.p$. They define an evaluation map on $X_(D(a))$.
  Its coherent cokernel has closed support $Z$ missing $X_y^"loc"$.
  Properness makes $f(Z)$ closed; it misses $y$, so remove it from $D(a)$.
  On the remaining neighborhood evaluation is surjective. This proves
  generation using only sections, finite presentation, and a closed image.

  For ampleness, II.5's ample-sheaf embedding criterion applied over the
  Noetherian affine local base gives an integer $n>0$ and finitely many
  sections of $shf.l^n$ defining an immersion
  $X_y^"loc" arrow.r.hook sch.p_(A_idl.p)^N$. This immersion is proper:
  its graph is closed because projective space is separated, and projection
  from the graph is proper by base change of $X_y^"loc" -> ops.spec A_idl.p$.
  A proper immersion is a closed immersion, by the immersion criterion in
  #book-link(<sup-lp-54>)[LP-54]. Spread these sections as just above; after
  shrinking they generate and give
  $h:X_V -> sch.p_V^N$ with $h^*shf.o (1)=shf.l^n$.

  We spell out why the closed-immersion condition also spreads. Put
  $W_i=h^(-1)D_+(T_i)$. Each $W_i$ is quasi-compact, separated, and of finite
  presentation over the affine base. Its localization at $idl.p$ is affine,
  say $ops.spec C_(i,idl.p)$. This algebra is finitely presented over
  $A_idl.p$; descend its finitely many generators, relations, and coefficients
  to an algebra $C_i$ over some $A_a$, with $a in.not idl.p$.

  The isomorphism $(W_i)_idl.p simeq ops.spec C_(i,idl.p)$ and its inverse
  also descend. Here are the finite data behind this assertion. A map from
  $W_i$ to $ops.spec C_i$ is specified by finitely many global sections
  satisfying finitely many relations. The same finite-affine-cover
  equalizer calculation used above localizes these sections and their
  relations, so the forward map descends after clearing denominators.
  For the inverse, choose a finite affine cover of $W_i$. Cover
  $ops.spec C_(i,idl.p)$ by finitely many principal opens mapping into its
  members. The functions defining those opens and an expression for $1$
  in the ideal they generate descend after further localization. On each
  such open the inverse map is a homomorphism between finitely presented
  algebras; descend the images of generators and the finitely many
  equations they satisfy. On overlaps, refine by finitely many principal
  opens mapping into intersections of members of the affine cover of
  $W_i$. Those intersections are affine by separatedness. Their coordinate
  equalities descend by clearing finitely many more denominators.
  The maps therefore glue. The identities for the two composites are
  checked on these same finite covers and descend by the same argument.
  The purely algebraic finite-generator and localization checks in this
  construction are left to the reader. Taking the product of the finitely
  many elements outside $idl.p$ gives one common target neighborhood on
  which every $W_i$ is affine.

  On that neighborhood, the map from the coordinate ring of $D_+(T_i)$
  to $Gamma(W_i, shf.o_X)$ is surjective after localization at $idl.p$.
  Choose finitely many algebra generators of the latter ring over the
  chart ring. For each one choose a preimage after localization and clear
  both its denominator and the equality asserting it is a preimage.
  Surjectivity then holds before localization on a further common target
  neighborhood. This finite-presentation calculation is also left to the
  reader. By #book-link(<sup-cs-1>)[CS-1], each chart map is a closed
  immersion. They all restrict from the same $h$, hence agree on overlaps,
  and target locality for closed immersions proves that $h$ is a closed
  immersion. Properness was used to remove the support of the evaluation
  cokernel; the later descent uses quasi-compactness, separatedness, and
  finite presentation of the indicated affine diagrams.

  Thus $shf.l^n$ is relatively very ample on that neighborhood.
  LP2-11 implies relative ampleness of $shf.l$. This proof neither starts
  with nor deduces a criterion concerning ampleness on a single fiber.
]

#exercise(title: "LP2 — Checking hypotheses in applications")[
  + Give the square-zero correction for a one-equation standard étale
    algebra $A[t]\/ideal(F)$ on $D(F')$. Explain why the correction is unique.
  + Give a closed immersion with locally free conormal sheaf which is not
    regular, and explain why LP2-9 does not apply.
  + Apply LP2-7 to a flat family and to its inclusion of a special fiber.
    Determine exactly when a fixed effective Cartier divisor remains Cartier.
  + In LP2-12 identify each use of Noetherianity, finite presentation,
    separatedness, and properness. State which denominator-clearing step
    cannot be replaced by an argument only on the closed fiber.
]

*Sources.* Liu §§4.3 and 6.2 for relative morphism classes, §6.3 for regular
immersions, and Proposition 5.1.37 for spreading from a local base. The
projectivity convention remains Hartshorne's, as in
#book-link(<sup-lp>)[LP] and #book-link(<sup-pm>)[PM].

Related exercise: #book-link(<exercise-ii-8-6>)[II.8.6] spells out the affine lifting construction behind LP2-2–LP2-3.
