#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#import "../defs.typ": *
#import "proof-layout.typ": proof
#show: show-theorion

== AL — Algebraic tools for modules <sup-al>

This section contains the
algebra used by #book-link(<sup-sc>)[SC], #book-link(<sup-qc>)[QC],
#book-link(<sup-se>)[SE], and #book-link(<sup-rv>)[RV].

#metadata(none) <sup-al-1>
#definition(number: "AL-1", title: "Finiteness conditions")[
  An $A$-module is:

  + finite if it has finitely many generators;
  + finitely presented if it is the cokernel of a map $A^m->A^n$ with $m,n$ finite;
  + finite free if it is isomorphic to $A^n$ with $n$ finite;
  + finite projective if it is a direct summand of such a finite free module.
]

#metadata(none) <sup-al-2>
#proposition(number: "AL-2", title: "Relations among finiteness conditions")[
  Let $M$ be an $A$-module.

  + If $M$ is finite projective, then $M$ is finitely presented.

  + If $A$ is Noetherian and $M$ is finite, then $M$ is finitely presented.
    The Noetherian hypothesis supplies finite generation of the relations.
]

#proof[

  + *Finite projective modules.* If $A^n=M plus.o K$, projection onto $K$ shows that $K$ is generated by
    the images of the $n$ standard basis vectors. Composing a finite free
    surjection onto $K$ with $K arrow.r.hook A^n$ gives a finite presentation
    of $M$.

  + *Finite modules over a Noetherian ring.* If $A$ is Noetherian and $M$ finite, take a surjection $A^n->M$.
    Its kernel is a submodule of the Noetherian module $A^n$, so is finite
    (Check! the Noetherian module criterion);
    its finite generating set likewise gives the required presentation.
]

#metadata(none) <sup-al-3>
#proposition(number: "AL-3", title: "Localization")[
  Let $S subset.eq A$ be a multiplicative subset.

  + Localization is exact.
  + The maps induced by fractions give a canonical isomorphism
    $
      S^(-1)(tensor(M, N, over: A)) & ->
                                      tensor(S^(-1)M, S^(-1)N, over: S^(-1)A), \
                     tensor(m, n)/s & mapsto tensor(m/s, n/1).
    $
  + The maps induced by fractions give a canonical isomorphism
    $ ops.colim_i S^(-1)M_i -> S^(-1)(ops.colim_i M_i). $
    In particular, localization commutes with arbitrary direct sums.
]

#proof[

  + *Exactness.* A fraction $m/s$ is zero exactly when some $t in S$ kills $m$.
    For an exact pair $M' ->^u M ->^v M''$, a fraction $m/s$ in the kernel
    of the localized $v$ has $t v(m)=0$ for some $t in S$. Write $t m=u(m')$;
    then $m/s=u(m')/(t s)$ is in the image. The reverse inclusion follows
    from $v u=0$. The same zero criterion preserves injections, and lifting a
    numerator preserves surjections. Hence localization is exact.

  + *Tensor products.* The inverse of the tensor comparison sends
    $tensor(m/s, n/t) mapsto tensor(m, n)/(s t)$. Changing either fraction does
    not change this value, by the fraction relation. The map is balanced over
    $S^(-1)A$; check the fraction relations and balancing explicitly (Check!).
    Composing the two maps fixes pure tensors, which generate both modules.

  + *Colimits.* For colimits, an $A$-linear map $M->P$ to an $S^(-1)A$-module
    extends uniquely by $m/s mapsto s^(-1)u(m)$. Thus localization is left
    adjoint to restriction of scalars and preserves colimits by CAT-9. Under
    this adjunction the comparison is the one induced by the original colimit
    injections, so it is exactly the displayed canonical map.
]

#metadata(none) <sup-al-4>
#lemma(number: "AL-4", title: "Localizing Hom")[
  For finitely presented $M$ and arbitrary $N$, the canonical map
  $ S^(-1)ops.hom(M, N, over: A) & ->
                                 ops.hom(S^(-1)M, S^(-1)N, over: S^(-1)A), \
                           u/s & mapsto (m/t mapsto u(m)/t) $ is an isomorphism.
  Finite generation alone does not supply finite relations for this assertion.
]

#proof[

  + *Present Hom as a kernel.* Choose a presentation $A^m ->^d A^n -> M->0$. Applying Hom into $N$
    identifies $ops.hom(M, N)$ with the kernel of $N^n->N^m$ given by
    precomposition with $d$.

  + *Localize the presentation.* Localization preserves this kernel by AL-3 and
    commutes with these finite powers. Localizing the presentation and applying
    Hom into $S^(-1)N$ produces the very same kernel between
    $(S^(-1)N)^n$ and $(S^(-1)N)^m$.

  + *Identify the canonical map.* The identification restricts the
    coordinatewise map $u/s mapsto (m/t mapsto u(m)/(s t))$, hence is the
    asserted comparison. Finite presentation was used for both finite powers,
    not merely for a finite list of generators of $M$.
]

#metadata(none) <sup-al-5>
#proposition(number: "AL-5", title: "Tensor, Hom, and duality")[
  Put $M^or=ops.hom(M, A, over: A)$.

  + The tensor product represents balanced bilinear maps, with natural adjunction
    $
      ops.hom(tensor(M, N, over: A), P, over: A) simeq
      ops.hom(N, ops.hom(M, P, over: A), over: A).
    $
  + If $M$ is finite projective, evaluation $M->(M^or)^or$ is an isomorphism.
  + If $M$ is finite projective, the map
    $
      tensor(M^or, N, over: A) & ->ops.hom(M, N, over: A), \
             tensor(lambda, n) & mapsto (m mapsto lambda(m)n)
    $
    is an isomorphism.

  The sheaf versions of these duality isomorphisms, obtained on trivializing
  covers, are proved in #book-link(<sup-sc-11>)[SC-11]. (Ex. II.5.1(a)~(b))
]

#proof[

  + *The tensor–Hom adjunction.* A map $v:tensor(M, N)->P$ corresponds to
    $n mapsto (m mapsto v(tensor(m, n)))$; the inverse evaluates this formula
    on pure tensors. Balanced bilinearity proves that both assignments are
    well-defined and linear, and equality on pure tensors proves they are inverse.

  + *The dual–tensor comparison.* Choose a splitting $M arrow.r.hook A^r -> M$ of the identity. Images
    $m_i$ of the standard basis and restrictions $lambda_i$ of its coordinate
    functionals satisfy $m=sum_i lambda_i(m)m_i$. The inverse of
    $tensor(M^or, N)->ops.hom(M, N)$ sends $u$ to
    $sum_i tensor(lambda_i, u(m_i))$. One composite fixes $u$ by this identity;
    for the other use $lambda=sum_i lambda(m_i)lambda_i$.

  + *Double-dual evaluation.* The inverse to double-dual evaluation sends $Psi$ to
    $sum_i Psi(lambda_i)m_i$. Evaluating any $lambda$ on this element gives
    $Psi(lambda)$, and the other composite is the same dual-basis identity.
    Thus these inverses belong to the specified canonical maps and do not depend
    on the chosen splitting.
]

#metadata(none) <sup-al-6>
#definition(number: "AL-6", title: "Tensor, symmetric, and exterior algebras")[
  + The tensor algebra of $M$ is the direct sum of all tensor powers, with
    zeroth power $A$ and multiplication by concatenation. It is universal for
    $A$-linear maps from $M$ to associative unital $A$-algebras.

  + Its symmetric algebra is the quotient by $tensor(m, n)-tensor(n, m)$;
    it is universal for maps to commutative $A$-algebras.

  + Its exterior algebra
    is the quotient by $tensor(m, m)$ for every $m$.
    The degree-$r$ exterior power represents alternating $r$-linear maps;
    this definition works also in characteristic two.
]

#proof[

  + *The tensor algebra.* Given a linear map $u:M->B$ into an associative $A$-algebra, its extension
    on a pure tensor of length $n$ is the ordered product
    $u(m_1) dots u(m_n)$, and on degree zero it is the structural map from $A$.
    Multilinearity defines this on each tensor power. Multiplication by
    concatenation makes the extension an algebra homomorphism, and generation
    by degree one proves uniqueness.

  + *The symmetric algebra.* If $B$ is commutative, the commutator
    relations vanish, yielding the symmetric-algebra property.

  + *Exterior powers.* In degree $r$,
    an alternating multilinear map on $M^r$ factors through the tensor power
    and kills every tensor having repeated arguments. The relations
    $m times.o m=0$, together with their polarized consequences
    $m times.o n+n times.o m=0$, generate exactly these relations in degree $r$.
    The resulting quotient therefore represents alternating maps, with no
    division by $2$ or any factorial.
]

#metadata(none) <sup-al-7>
#proposition(number: "AL-7", title: "Scalar extension of tensor, symmetric, and exterior algebras")[
  For any $A$-algebra $B$, the canonical graded maps from scalar extension
  of each of these algebras to the corresponding algebra of
  $tensor(B, M, over: A)$ are isomorphisms. The same holds degree by degree.
  Symmetric and exterior powers are not asserted to be exact functors.
]

#proof[

  + *Tensor powers.* In tensor degree $r$, the comparison sends
    $b times.o (m_1 times.o dots times.o m_r)$ to
    $(b times.o m_1) times.o (1 times.o m_2) times.o dots times.o (1 times.o m_r)$.
    The inverse on pure tensors multiplies all the coefficients in $B$.
    The balancing relations show that these are inverse $B$-linear maps,
    compatible with multiplication and degree zero.

  + *Symmetric relations.* Tensoring a quotient with
    $B$ takes it to the quotient by the image of its relations, by right
    exactness. Under the tensor-algebra comparison, the commutator relations
    generate exactly the symmetric relations after base change.

  + *Exterior relations.* For the exterior
    relations, the square of $sum_i b_i times.o m_i$ expands into diagonal
    squares and polarized pairs; both vanish in the base-changed exterior
    algebra. Conversely, the original squares are among the new squares. Thus
    the relation ideals coincide in both cases.

  + *Homogeneous degrees.* The maps preserve degrees, so
    the resulting graded isomorphisms restrict to each homogeneous degree.
]

#metadata(none) <sup-al-8>
#proposition(number: "AL-8", title: "Ranks and determinant pairing")[
  + For $M$ free of rank $r$, its $n$-th tensor, symmetric, and exterior powers
    have ranks $r^n$, $binom(r+n-1, n)$, and $binom(r, n)$, respectively, for
    $r>=1$. Degree zero is $A$; for $M=0$, every positive-degree power is zero.

  + For finite projective $M$ of constant rank $r$ and $0<=p<=r$, the exterior product pairing
    $Lambda^p M times Lambda^(r-p) M -> Lambda^r M$
    is perfect: it induces
    $Lambda^p M simeq ops.hom(Lambda^(r-p)M, Lambda^r M, over: A)$.
    These assertions apply separately on each constant-rank component.
]

#proof[

  + *Bases and ranks.* For a basis $e_1,dots,e_r$, a basis of the tensor power is indexed by
    ordered $n$-tuples of indices. A symmetric-power basis consists of the
    monomials $e_1^(a_1) dots e_r^(a_r)$ with $sum a_i=n$; the identification
    with the polynomial algebra follows from its universal property. An
    exterior-power basis consists of $e_(i_1) and dots and e_(i_n)$ for
    $i_1<dots<i_n$. The relations reorder every and into this form, with
    repetitions zero. Independence follows by applying the alternating
    coordinate determinants indexed by these subsets. Counting these three
    index sets gives the stated ranks, with the indicated degree-zero cases.

  + *The free determinant pairing.* For $0<=p<=r$, pair an increasing $p$-subset with its complementary
    $(r-p)$-subset. Their and is the top basis vector with sign $+1$ or
    $-1$; every other pairing of those degrees is zero. The pairing matrix is
    therefore a signed permutation matrix and is invertible over any ring.

  + *The finite projective case.* For finite projective $M$, its localization at each prime is finite free:
    choose a basis modulo the maximal ideal, lift a surjection onto the local
    module by Nakayama, split it by projectivity, and apply Nakayama to its
    finite kernel. AL-10 then spreads this basis to a principal neighborhood.
    On these neighborhoods, AL-4 and AL-6 identify the localization of the
    specified pairing with the free pairing just computed. Its kernel and
    cokernel vanish at every prime and hence vanish: a nonzero element has a
    proper annihilator contained in a maximal ideal and stays nonzero there.
    Thus the canonical pairing is perfect globally.
]

#metadata(none) <sup-al-9>
#proposition(number: "AL-9", title: "Filtrations of powers")[
  For $0->M'->M->M''->0$ with finite projective quotient, filter a power
  of $M$ by the number of factors from $M'$. Use the decreasing filtration
  by at least $p$ such factors; no splitting is chosen in the filtration itself.

  + In symmetric degree $n$, the associated graded pieces are
    $ tensor(op("Sym")^p M', op("Sym")^(n-p) M'', over: A), quad 0<=p<=n. $
  + In exterior degree $n$, the associated graded pieces are
    $ tensor(Lambda^p M', Lambda^(n-p) M'', over: A), quad 0<=p<=n. $
  + For sheaves, the same statement holds for locally split short exact sequences.
]

#proof[

  + *Compute the associated graded after splitting.* Let $F^p$ be generated by products with at least $p$ factors from $M'$.
    Choose a splitting $M=M' plus.o M''$, possible because $M''$ is projective.
    The universal properties give
    $op("Sym")(M' plus.o M'') simeq tensor(op("Sym")(M'), op("Sym")(M''))$.
    For exterior algebras, use the graded tensor product, whose interchange
    sign is $(-1)^(a b)$ on factors of degrees $a,b$; the same generator
    and relation argument gives the analogous isomorphism. In degree $n$,
    $F^p$ is the sum of the summands with first degree at least $p$, so its
    successive quotient is the displayed summand of bidegree $(p,n-p)$.

  + *Construct the canonical comparison.* The quotient isomorphism itself is canonical: multiply $p$ elements from
    $M'$ with arbitrary lifts of $n-p$ elements from $M''$, then reduce modulo
    $F^(p+1)$. Changing a lift inserts another factor from $M'$ and changes
    the result by an element of $F^(p+1)$. The symmetric or alternating
    relations descend, so this defines the comparison without a splitting.
    The splitting proves that this comparison is invertible.

  + *Glue the sheaf comparisons.* For locally split
    sheaf sequences make this construction on each splitting open; its independence
    of lifts makes the maps agree on overlaps. SL-3 glues the maps and their
    inverses, giving the same assertion for sheaves.
]

#metadata(none) <sup-al-10>
#lemma(number: "AL-10", title: "Nakayama and spreading finite data")[
  + For a finite module $M$ over a local ring $(A,idl.m)$, generators of
    $M\/idl.m M$ lift to generators of $M$; in particular, $M=idl.m M$
    implies $M=0$.

  + If $M$ is finitely presented and $M_idl.p$ is free, there
    is $f in.not idl.p$ such that $M_f$ is free of that same finite rank.
    Finite presentations allow matrices, inverse maps, and their finitely many
    relations at a prime to be realized after one localization. The Noetherian
    application is #book-link(<sup-se-10>)[SE-10], which solves II.5.7(a).
]

#proof[

  + *Nakayama’s lemma.* First suppose a finite module $Q$ satisfies $Q=idl.m Q$. For generators
    $q_1,dots,q_n$, write $q_i=sum_j a_(i j)q_j$ with all $a_(i j) in idl.m$.
    The adjugate identity shows that $det(I-(a_(i j)))$ kills every generator.
    The adjugate identity and the local-ring unit criterion are algebraic
    checks (Check!). Its residue modulo $idl.m$ is $1$, so it is a unit and
    $Q=0$. For proposed lifts of residue generators, apply this conclusion
    to the finite quotient by their span. This is Nakayama's assertion.

  + *Spread surjectivity.* Now choose a basis of $M_idl.p$ and clear its finitely many denominators
    to obtain $u:A^r->M$ which is an isomorphism at $idl.p$.
    Its cokernel is finite and vanishes there. A product $s in.not idl.p$
    of annihilating denominators for its generators makes $u_s$ surjective.

  + *Control the kernel.* Because $M_s$ is finitely presented, the kernel $K$ of this finite free
    surjection is finite. To see this for any finite free surjection $u:A^r->M$, take a
    presentation $v:A^m->M$ whose kernel is generated by $k_1,dots,k_q$.
    Lift maps $a:A^m->A^r$ and $b:A^r->A^m$ with $u a=v$ and $v b=u$.
    Then $ops.ker(u)$ is generated by the $a(k_j)$ and the vectors
    $(ops.id-a b)e_i$: for $x in ops.ker(u)$, one has $b x in ops.ker(v)$
    and $x=a b x+(ops.id-a b)x$.

  + *Spread the isomorphism and finite identities.* Since $K_idl.p=0$, a further product
    $t in.not idl.p$ kills its finite generating set after localization.
    Consequently, $u_(s t)$ is an isomorphism. The same clearing of finitely many
    matrix entries and relations realizes a finite collection of maps and
    identities on one such principal neighborhood.
]

#metadata(none) <sup-al-11>
#corollary(number: "AL-11", title: "Tensor-invertible finite modules")[
  Over a Noetherian local ring $A$, if finite modules $M,N$ satisfy
  $tensor(M, N, over: A) simeq A$, then both are free of rank one.
  The following residue-field and Nakayama calculation yields
  #book-link(<sup-se-12>)[SE-12], which solves II.5.7(c).
]

#proof[

  + *Reduce to the residue field.* Write $k=A\/idl.m$. Reducing the tensor isomorphism modulo $idl.m$ gives
    $tensor(M\/idl.m M, N\/idl.m N, over: k) simeq k$.
    The dimensions of the two finite-dimensional spaces therefore multiply to
    one, so each is one.

  + *Identify the cyclic modules.* Nakayama gives cyclic presentations $M simeq A\/I$
    and $N simeq A\/J$. Their tensor product is $A\/(I+J)$.
    An $A$-module isomorphism $A\/(I+J) simeq A$ identifies annihilators;
    the annihilator of $A$ is zero, so $I+J=0$. Hence $I=J=0$, proving that
    both modules are free of rank one.
]

#metadata(none) <sup-al-examples>
#metadata(none) <sup-al-12>
#example(number: "AL-12")[
  Tensoring the injection $ZZ ->^2 ZZ$ with $ZZ\/2ZZ$ gives a
  zero map between nonzero modules.
]

#proof[
  The integers have no nonzero element killed by $2$, so the original map
  is injective. The identification $tensor(ZZ, ZZ\/2ZZ, over: ZZ) simeq ZZ\/2ZZ$
  turns its tensor into multiplication by $2$, which is zero. The target
  contains the nonzero class of $1$.
]

#metadata(none) <sup-al-13>
#example(number: "AL-13")[
  The map $(product_(n>=0) ZZ)[1/2] -> product_(n>=0) ZZ[1/2]$
  is not surjective: $(2^(-n))_n$ has no common bounded denominator.
]

#proof[
  Every element on the left has a single representative $(a_n)_n/2^r$.
  If its image were $(2^(-n))_n$, the coordinate $n=r+1$ would give
  $a_(r+1)=1/2$ in $QQ$, impossible for an integer. The target family is
  well-defined because each of its coordinates belongs to $ZZ[1/2]$.
]

#metadata(none) <sup-al-14>
#example(number: "AL-14")[
  Take $M=bigOPlus(ZZ, n>=0)$, $N=ZZ$, and invert $2$.
  Then $ops.hom(M, N)=product_(n>=0) ZZ$, so the Hom localization comparison
  fails by AL-13.
]

#proof[
  A homomorphism from a direct sum is uniquely determined by its value on
  each standard basis vector, with no finiteness constraint on that family.
  The same statement holds after localization, since localization preserves
  direct sums by AL-3. In these coordinates, the Hom comparison is exactly
  the map in AL-13, so its demonstrated failure of surjectivity applies.
]

#metadata(none) <sup-al-15>
#example(number: "AL-15")[
  The $ZZ$-dual of $ZZ\/2ZZ$ is zero; its evaluation into its
  double dual is not an isomorphism.
]

#proof[
  If $u:ZZ\/2ZZ->ZZ$ is linear, then $2u(overline(1))=u(0)=0$.
  Torsion-freeness of $ZZ$ gives $u(overline(1))=0$, hence $u=0$ because
  $overline(1)$ generates the source. The dual and double dual are therefore
  zero, while $ZZ\/2ZZ$ is nonzero.
]
