#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#import "../defs.typ": *
#import "proof-layout.typ": proof
#show: show-theorion

== PJ2 — Relative Proj and projectivization <sup-pj2>

Unless otherwise specified, $Y$ is Noetherian and $shf.s$ is a
quasi-coherent graded $shf.o_Y$-algebra with $shf.s_0=shf.o_Y$, generated
by its coherent degree-one part. Write $P=ops.proj_Y shf.s$ and
$pi:P->Y$. The construction and its twists are those of
#book-link(<text-ii-7>)[II.7.9–II.7.12]; the affine-chart conventions are
those of #book-link(<sup-pj>)[PJ]. Projectivization always parametrizes
invertible quotients. Purely algebraic assertions singled out below are
exercises: their proofs are left to the reader.

=== Quotients, relations, and change of base

#metadata(none) <sup-pj2-1>
#proposition(number: "PJ2-1", title: "The quotient description")[
  For $g:T->Y$, morphisms $h:T->P$ over $Y$ correspond naturally to
  isomorphism classes of pairs $(shf.l,alpha)$, where $shf.l$ is invertible
  and
  $ alpha:g^*shf.s -> bigOPlus(shf.l^(times.o n), n>=0) $
  is a graded algebra map whose degree-one component is surjective.
  An isomorphism of pairs must carry every component of $alpha$ to the
  corresponding component of the other map. The universal pair is
  $(shf.o_P(1),pi^*shf.s -> bigOPlus(shf.o_P(n), n>=0))$.
]
#proof[
  Restrict first to an affine $V=ops.spec A$ in $Y$, with
  $S=Gamma(V, shf.s)$ generated by $s_0,dots,s_r in S_1$. On
  $g^(-1)V$, let $T_i$ be the open where $alpha(s_i)$ generates $shf.l$.
  These opens cover because $alpha_1$ is surjective. Trivializing by
  $alpha(s_i)$ defines a ring map
  $
    (S_(s_i))_0 -> Gamma(T_i, shf.o_T), quad
    a/s_i^d mapsto alpha_d(a)/alpha_1(s_i)^d.
  $
  The elementary localization assertion that this formula respects
  equality of fractions and multiplication is left to the reader.
  It defines $T_i->D_+(s_i)$. On $T_i inter T_j$, both formulas send a
  homogeneous fraction to the same quotient of sections; further
  localization identifies them. XL glues these maps. Refining $V$ to
  a principal affine open gives exactly the same formula with the
  coefficient ring localized, so the construction also glues over $Y$.

  Conversely, pull back the universal quotient: on $D_+(s_i)$ it sends
  $a in S_d$ to $(a/s_i^d)s_i^d$, and $s_i$ generates $shf.o_P(1)$.
  These descriptions show that the two constructions are inverse.
  They also prove naturality under pullback. An isomorphism of quotient
  pairs is unique when it exists, since its effect on the surjective
  degree-one map determines it. Consequently there is no additional
  gluing choice hidden in passage to isomorphism classes.
]

#metadata(none) <sup-pj2-2>
#proposition(number: "PJ2-2", title: "Relations are part of the point")[
  Let $shf.j$ be the homogeneous kernel of
  $op("Sym") shf.s_1 -> shf.s$. There is a canonical closed immersion
  $P->sch.p (shf.s_1)$. An invertible quotient
  $g^*shf.s_1 -> shf.l$ defines a morphism into $P$ precisely when the
  induced symmetric-algebra map annihilates the image of $g^*shf.j$.
]
#proof[
  The surjection of graded algebras gives the closed immersion on every
  affine base chart by PJ-5. Its ideal in $D_+(s_i)$ consists of the
  fractions $a/s_i^d$ with $a in shf.j_d(V)$. By PJ2-1 the given quotient
  defines the chart maps by evaluation of precisely these fractions.
  It factors through the closed subscheme if and only if each evaluates
  to zero. This is exactly the stated annihilation condition, which is
  independent of generators and hence agrees on overlaps. Pullback need
  not preserve the injection of $shf.j$; only its image in the pulled-back
  symmetric algebra is used.
]

#metadata(none) <sup-pj2-3>
#example(number: "PJ2-3", title: "A quotient failing a relation")[
  For $S=k[u,v,w]/(u w-v^2)$, a point is a nonzero triple $(a,b,c)$ up to
  common scaling satisfying $a c=b^2$. The quotient with values $(1,1,0)$
  defines a point of $sch.p^2$ but fails the relation and defines no point
  of $ops.proj S$. The same condition holds for sections over a base:
  the equation is an equality in $shf.l^2$, independently of a frame.
]

#metadata(none) <sup-pj2-4>
#proposition(number: "PJ2-4", title: "Arbitrary base change and fibers")[
  For every $g:Y'->Y$ there is a canonical isomorphism
  $ ops.proj_(Y')(g^*shf.s) simeq P times_Y Y'. $
  Under this isomorphism the new $shf.o (1)$ is the pullback of the old
  $shf.o (1)$; the same holds for all integral twists. In particular
  $P_y simeq ops.proj (shf.s times.o_(shf.o_Y) kappa(y))$.
]
#proof[
  A $Y'$-scheme $T$ mapping to either side specifies, by PJ2-1, the same
  invertible quotient data for $(g compose (T->Y'))^*shf.s$. Applying
  the two descriptions to their universal pairs constructs inverse
  morphisms, not just a bijection of points. Their pullback quotients
  identify the tautological bundles.

  The affine verification makes the absence of flatness explicit.
  For $A->B$, $s in S_1$, the chart map is the canonical isomorphism
  $
    (S_s)_0 times.o_A B simeq ((S times.o_A B)_(s times.o 1))_0, quad
    (a/s^d) times.o b mapsto (a times.o b)/(s times.o 1)^d.
  $
  Prove this algebra assertion by expressing the degree-zero part as
  the direct limit of the modules $S_d$ under multiplication by $s$;
  its proof is left to the reader. Tensor products commute with this
  direct limit without a flatness hypothesis. The maps commute with
  localization at another degree-one element, so their affine inverses
  glue. The frame $s^n$ is carried to $(s times.o 1)^n$, proving the
  comparison for every twist. Take $Y'=ops.spec kappa(y)$ for the fiber.
]

#metadata(none) <sup-pj2-5>
#proposition(number: "PJ2-5", title: "Associated modules and their comparisons")[
  Let $shf.m$ be a quasi-coherent graded $shf.s$-module. On an affine
  base $V$, its associated sheaf has module $(shf.m (V)_s)_0$ on
  $D_+(s)$. Sheafification is exact, and in the degree-one setting
  $tildeOf(shf.m (n)) simeq tildeOf(shf.m) times.o shf.o_P(n)$.
  In PJ2-4, writing $p:P times_Y Y'->P$, one has canonically
  $p^*tildeOf(shf.m) simeq tildeOf(g^*shf.m)$.
]
#proof[
  Restrictions to overlaps are homogeneous localization. Localization
  and taking a graded component are exact; these two algebra assertions
  are left to the reader. Thus kernels and cokernels agree on a covering
  by affine charts and glue to the asserted exact sequence of sheaves.
  Multiplication by the frame $s^n$ identifies the localized degree-zero
  module with the localized degree-$n$ module. Changing from $s$ to $t$
  changes this frame by $(t/s)^n$, the transition function of $shf.o (n)$,
  so the twist isomorphisms glue.

  For base change, the module map is
  $(m/s^d) times.o b mapsto (m times.o b)/(s times.o 1)^d$.
  The direct-limit calculation in PJ2-4 applies with $M_d$ in place of
  $S_d$ and proves bijectivity; compatibility with further localization
  identifies this map with sheaf pullback on each affine fiber product.
  Its canonicity proves overlap agreement. For nonstandard gradings,
  the fraction description remains valid, but the twist argument
  requires a degree giving an invertible local frame; PJ2-10 shows why
  degree one cannot simply be assumed.
]

=== Projective bundles and their sections

#metadata(none) <sup-pj2-6>
#proposition(number: "PJ2-6", title: "Twisting and the normal bundle of a section")[
  For a coherent $shf.e$ and an invertible $shf.m$ on $Y$,
  $sch.p (shf.e times.o shf.m) simeq sch.p (shf.e)$ canonically over $Y$.
  The tautological bundle on the left corresponds to
  $shf.o_(sch.p (shf.e))(1) times.o pi^*shf.m$.
  If $shf.e$ is locally free and
  $0->shf.k->shf.e->shf.l->0$ is an invertible quotient, its section $s$
  has normal bundle $shf.hom (shf.k,shf.l)$.
]
#proof[
  Tensoring a quotient $g^*shf.e->shf.n$ by $g^*shf.m$ and tensoring
  back by its inverse give mutually inverse quotient constructions.
  PJ2-1 identifies them with inverse morphisms and identifies their
  universal quotients, proving the formula for $shf.o (1)$.

  For the normal bundle, cover $Y$ by affines where the quotient splits
  and both $shf.k$ and $shf.l$ are free. Such a cover exists because an
  invertible module is locally projective. Choose a frame $e_0$ mapping
  to the frame $l$ of $shf.l$, and kernel frames $e_1,dots,e_r$.
  In the chart where the image of $e_0$ generates the quotient, the
  coordinates are $z_i=q(e_i)/q(e_0)$ and the section has ideal
  $(z_1,dots,z_r)$. Its conormal module is free on the classes of $z_i$.
  To identify transitions without dependence on the splitting, lift
  $k in shf.k$ through the universal quotient and divide by the image
  of a lift of $l$. Modulo the square of the section ideal, changing
  that lift changes nothing. This gives the canonical conormal map
  $shf.k times.o shf.l^(-1)->shf.i_s/shf.i_s^2$; on the chosen chart
  it sends a basis to the classes of $z_i$, hence is an isomorphism.
  These canonical maps agree on overlaps. Dualizing gives the stated
  normal bundle.
]

#metadata(none) <sup-pj2-7>
#example(number: "PJ2-7", title: "The distinguished section of a ruled surface")[
  Let $F_n=sch.p_(sch.p^1)(shf.o plus.o shf.o (n))$, $n>=0$.
  On $U_0$ with coordinate $t=T_1/T_0$, use the frame $e_0=T_0^n$ of
  $shf.o (n)$; on $U_1$ use $e_1=T_1^n=t^n e_0$.
  If $[a:b_i]=[q(1):q(e_i)]$ denotes quotient coordinates, then
  $[a:b_1]=[a:t^n b_0]$. Near the section $q:shf.o plus.o shf.o (n)->shf.o$
  the fiber coordinates $w_i=b_i/a$ satisfy $w_1=t^n w_0$.
  Hence its conormal bundle is $shf.o (n)$ and its normal bundle is
  $shf.o (-n)$, in agreement with PJ2-6. This computation fixes the sign
  dictated by the quotient convention.
]

#metadata(none) <sup-pj2-8>
#example(number: "PJ2-8", title: "Projectivization with a jumping fiber")[
  On $Y=ops.spec k[t]$ take $shf.e=shf.o_Y plus.o shf.o_Y/(t)$.
  Its symmetric algebra is $k[t,u,v]/(t v)$ with $u,v$ of degree one.
  On $D_+(u)$ the coordinate ring is $k[t,w]/(t w)$, $w=v/u$;
  on $D_+(v)$ it is $k[z]$, $z=u/v$, and $t=0$.
  The overlap has $w$ invertible, $t=0$, and $z=w^(-1)$.
  Thus a copy of $Y$ given by $w=0$ meets an additional vertical
  $sch.p^1$ in one point. The generic fiber is $sch.p^0_(k(t))$ and
  the fiber at $t=0$ is $sch.p^1_k$, by PJ2-4. Projectivization of a
  coherent module need not be a projective-space bundle of fixed rank.
  The symmetric-algebra presentation and chart-ring computations are
  algebra exercises, with proofs left to the reader; the displayed
  transition identifies how their spectra are glued.
]

=== Grading and the tautological sheaf

#metadata(none) <sup-pj2-9>
#proposition(number: "PJ2-9", title: "A sufficiently divisible Veronese")[
  Let $S$ be a finitely generated nonnegative graded algebra over $S_0$.
  For some positive $d$, its Veronese algebra
  $S^((d))=bigOPlus(S_(n d), n>=0)$ is generated in degree one.
  For every positive $d$, the canonical comparison of PJ-9 gives
  $ops.proj S^((d)) simeq ops.proj S$ and identifies
  $shf.o_(ops.proj S^((d)))(m)$ with $shf.o_(ops.proj S)(d m)$.
  In particular, for sufficiently divisible $d$, the latter twists are
  invertible and satisfy the usual tensor-product formulas.
]
#proof[
  The existence of $d$ is the graded-algebra assertion that, for finitely
  many positive integer weights, a sufficiently divisible Veronese of
  the weighted polynomial ring is generated in its first degree; its
  proof, and passage to a graded quotient, are left to the reader.
  It is not necessary to assert that the least common multiple of the
  weights alone always has this property.

  For the geometric comparison use $D_+(f)$ with $deg f$ divisible by
  $d$; these cover since a positive homogeneous element may be replaced
  by its $d$-th power. The chart rings on the two sides coincide as rings
  of homogeneous fractions. Likewise the modules of fractions of degree
  $d m$ coincide after regrading with those of degree $m$. Equality of
  fractions remains the same on the intersections, so the chart and
  module identifications glue. In the degree-one Veronese, the local
  frames already used in PJ2-5 give invertibility and multiplication
  isomorphisms. This conclusion concerns $shf.o (d)$ on the original
  Proj, and gives no such conclusion about $shf.o (1)$.
]

#metadata(none) <sup-pj2-10>
#example(number: "PJ2-10", title: "The weighted plane and its odd module")[
  Let $k$ be algebraically closed of characteristic zero and
  $S=k[x,y,z]$ with degrees $1,1,2$. On $D_+(z)$ put
  $a=x^2/z$, $b=x y/z$, $c=y^2/z$. The ring is
  $R=k[a,b,c]/(a c-b^2)$. The second Veronese is
  $k[A,B,C,Z]/(A C-B^2)$, where $A=x^2$, $B=x y$, $C=y^2$, $Z=z$.
  Hence $ops.proj S$ is the projective quadric cone in $sch.p^3$, and
  $shf.o (2)$ is its hyperplane bundle.
]
#proof[
  Every even-degree monomial in $x,y$ is a product of $x^2,x y,y^2$.
  The resulting presentations, including that their kernels are
  generated by $A C-B^2$, are purely algebraic assertions left to the
  reader. PJ2-9 turns the Veronese presentation into the stated closed
  immersion and identifies its hyperplane bundle.

  To test $shf.o (1)$, use the vertex $idl.m=(a,b,c)$ in the $z$ chart.
  Its module is $M=(S_z)_1$, generated over $R$ by $e=x$ and $f=y$.
  The relations are $b e=a f$ and $c e=b f$. The algebra exercise here
  is to prove this presentation and deduce
  $M/idl.m M simeq k^2$; the two displayed relations have all coefficients
  in $idl.m$. A free module of rank one over $R_(idl.m)$ has a
  one-dimensional residue fiber, so the associated sheaf cannot be
  invertible at the vertex. Away from the vertex, one of $a,c$ is
  invertible and the relations express $M$ with one free generator.

  The module of $shf.o (2)$ is $R z$. Multiplication sends
  $e^2$ to $a z$, $e f$ to $b z$, and $f^2$ to $c z$.
  Its image is $idl.m z$, strictly smaller than $R z$ at the vertex.
  Thus $shf.o (1) times.o shf.o (1)->shf.o (2)$ is not surjective there.
  The failure is in the sheaf multiplication itself, although the
  underlying Proj admits a projective embedding.
]

#exercise(title: "Exercises on relative Proj")[
  + Over $k[t]$, give necessary and sufficient equations on an invertible
    quotient with coordinates $(a,b,c)$ for it to define a section of
    $ops.proj k[t][u,v,w]/(u w-t v^2)$. Compute the special fiber.
  + Starting with PJ2-8, restrict to $D(t)$ and to $V(t)$ and recover
    their fibers directly from both displayed charts.
  + For an invertible $shf.m$, follow a quotient section through
    $sch.p (shf.e times.o shf.m) simeq sch.p (shf.e)$ and compute the
    pullback of the new tautological bundle to the section.
]

The quotient construction refines II.7.12; the nonstandard grading
example explains the hypotheses in II.5.12 and II.7.9. Further source
comparisons are #link("https://stacks.math.columbia.edu/tag/01NS")[Stacks,
  relative Proj as a functor] and
#link("https://stacks.math.columbia.edu/tag/01MM")[invertible twists on Proj].

Related exercise: #book-link(<exercise-ii-7-10>)[II.7.10]. The quotient construction and twist comparison here provide its forward direction; the converse classification is a separate assertion.
