#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Linear Systems
#emph-box()[
  Throughout this subsection, we always assume $X$ is a _nonsingular_ (all local rings are regular) projective variety over an algebraically closed field $k$. Then,
  - Recall that _regular_ $Rightarrow$ UFD, so $X$ is nonsingular implies that $X$ is locally factorial. By _(6.11)_, we have $ops.div (X) simeq ops.cdiv (X)$, and $ops.cl (X) simeq ops.cacl (X)$.
  - As $X$ is integral, $ops.cl (X) simeq ops.pic (X)$ by _(6.15)_.
  - For any invertible $shf.o_X$-module $shf.l$, note that $shf.l in cat.coh (X)$. It follows from _(5.19)_ that $Gamma(X, shf.l)$ is a finite-dimensional $k$-vector space.
]

#definition(title: "Divisor of Zeros")[
  Fix an invertible sheaf $shf.l in cat.mod(shf.o_X)$. Let $0 != s in Gamma(X, shf.l)$ be a nonzero global section. Choose an open cover ${U_i}$ of $X$ on which $phi_i:shf.l|_(U_i) isoto shf.o_X|_(U_i)$. Then, $phi_i (s|_i) in Gamma(U_i, shf.o_X) subset shf.k_X (U_i)$ is nonzero (since $shf.l (U) -> shf.l (V)$ is injective whenever $V subset U$ as $X$ is integral). Thus, ${(U_i,phi_i (s|_i))}$ defines an effective Cartier divisor (depending only on $shf.l$ and $s$), called the _divisor of zeros_ of $s$, and is denoted by $(s)_0$.
]

// Hartshorne II.7, Proposition 7.7
#proposition(number: 7.7)[
  Let $X$ be a nonsingular projective variety over the algebraically closed field $k$. Fix $D_0 in ops.cdiv (X)$ and let $shf.l$ denote the corresponding invertible sheaf $shf.l (D_0) in ops.pic (X)$. Then,
  + *(a).* For each $0 != s in Gamma(X, shf.l)$, the divisor of zeros $(s_0) in ops.cdiv (X)$ is effective, and $(s)_0 tilde.op D_0$.
  + *(b).* Every effective divisor $D in ops.cdiv (X)$ linearly equivalent to $D_0$ is $(s)_0$ for some $s in Gamma(X, shf.l)$.
  + *(c).* Given two nonzero sections $s,s'in Gamma(X, shf.l)$. Then, $(s)_0=(s')_0 arrow.l.r.double.long s'=lambda s$ for some $lambda in k^times$.
]
#proof[
  (a) Given a nonzero global section $s in Gamma(X, shf.l)$.
  - Recall that $shf.l=shf.l (D_0)$ is an $shf.o_X$-submodule of $shf.k_X$, so $s in Gamma(X, shf.k)$ is nonzero, i.e. we have  $s in shf.k^ast (X)=K^times$.
  - Suppose $D_0$ is represented by ${(U_i,f_i)}$ where $f_i in shf.k^ast (U_i)=K^times$. We may choose $U_i != emptyset$ such that $shf.l|_(U_i) simeq shf.o_X|_(U_i)$, and that $shf.l (U_i)=shf.l (D_0)(U_i)$ is generated by $f_i^(-1)$.
  - We have a local isomorphism $phi:shf.l (D_0) -> shf.o_X$ for which $phi_(U_i):shf.l (U_i) isoto shf.o_X (U_i)$ sends $s|_i mapsto f_i dot s|_i$. Therefore, $(s)_0$ is determined by ${(U_i,f_i dot s|_i)}=D_0+ops.dv (s)$, whence $(s)_0 tilde.op D_0$.

  (b) Since $D tilde.op D_0$, we choose an $s in shf.k^ast (X)$ such that $D-D_0=ops.dv (s)$. Then, $ops.dv (s)+D_0=D >= 0$ (i.e. effective), and $ops.dv (s) >= -D_0$. Note that $D_1 >= D_2 arrow.l.r.double.long shf.l (D_1) supset shf.l (D_2)$. Now, $shf.l (-D_0) subset shf.l (ops.dv (s))=shf.o_X spn {s^(-1)}$, whence $s in Gamma(X, shf.l (D_0))$ is nonzero. Therefore, from the proof of _(a)_, we have $D=D_0+ops.dv (s)=(s)_0$.\

  (c) Note that $X in cat.var_k$ is a projective variety, so $shf.o_X (X)=k$ by _(I, 3.4)_. Thus,
  $(s)_0=(s')_0 arrow.l.r.double.long ops.dv (s)=ops.dv (s') arrow.l.r.double.long s/s' in shf.o_X^ast (X)=shf.o_X (X)^times =k^times .$
]

#definition(title: "Linear Systems")[
  Fix a divisor $D_0 in ops.cdiv (X)$, and let $shf.l=shf.l (D_0)$.
  - A _complete linear system_ of $D_0$ on $X$ is the set
  $|D_0| := {D in ops.cdiv (X):text("effective such that") D tilde.op D_0},$
  which is from _(7.7)_ in 1-1 correspondence with the set
  $(Gamma(X, shf.l) without {0})\/k^times simeq sch.p (Gamma(X, shf.l)).$
  - A _linear system_ $idl.d$ of $D_0$ on $X$ is a subset of $|D_0|$, which is a linear subspace for $sch.p (Gamma(X, shf.l))$.
  Note that the map $( dot )_0:Gamma(X, shf.l) -> ops.cdiv (X)$ gives a 1-1 correspondence:

  $
    {V subset Gamma(X, shf.l): k text("-vec to r subspace")} & arrow.l.r.long {idl.d subset |D_0|:text("linear system")}, \
                {s in Gamma(X, shf.l):(s)_0 in idl.d} union {0} & mapsfrom.long quad quad idl.d, \
                                              V quad quad & mapsto.long {(s)_0:0 != s in V}.
  $

  - The _dimension_ of the linear system $idl.d$ is defined to be $dim idl.d := dim sch.p (V)= dim V-1$.
]

// Hartshorne II.7, Definition D4
#definition(title: "Base Point")[
  A point $P in X$ is a _base point_ of a linear system $idl.d$ if $P in ops.supp D$ for every $D in idl.d$. Here, $ops.supp D$ denotes the set $ops.supp D=union.big{Y subset X:text("prime divisor of") D}$.
]

#lemma-box(title: "Fact 7.C")[
  For any nonzero $s in Gamma(X, shf.l)$, the support $ops.supp (s)_0=X without X_s$, where $X_s$ denotes the open subset $X_s={P in X:s_P in.not idl.m_P shf.l_P}$.
]
#proof[
  This question is local, so we may assume $X=ops.spec A$ so that $shf.l=shf.o_X$. Then, we have $0 != s in A, X_s=D(s)$, so $X without X_s=V(s)$. Note that
  $
    s_P in.not idl.m_P shf.l_P=idl.m_P arrow.l.r.double.long s(P)=s_P mod idl.m_P != 0 quad text("in") k(P)=shf.o_(X,P) \/idl.m_P=k.
  $
  Thus, there are no prime divisors on $X_s$, which implies that the prime divisors of $(s)_0$ are the irreducible components of $V(s)$, whence $ops.supp (s)_0=V(s)$.
]

// Hartshorne II.7, Lemma 7.8
#lemma(number: 7.8)[
  Let $idl.d$ be a linear system on $X$ corresponding to the $k$-vector subspace $V subset Gamma(X, shf.l)$. Then,
  + *(i).* A point $P in X$ is a base point of $idl.d arrow.l.r.double.long s_P in idl.m_P shf.l_P$ for every $s in V$.
  + *(ii).* $idl.d$ is base-point-free  $arrow.l.r.double.long shf.l$ is generated by the global sections in $V$.
]
#proof[
  (i) This is clear from _(7.C)_. For (ii), we see that:
  $idl.d subset |D_0| text("is base-point-free") & arrow.l.r.double.long text("For every") P in X, P text("is not a base point"). & arrow.l.r.double.long text("For every") P in X, exists s in V text("such that") s_P in.not idl.m_P shf.l_P. & arrow.l.r.double.long text("For every") P in X, shf.l_P=shf.o_(X,P) spn {s:s in V}. & arrow.l.r.double.long shf.l text("is globally generated by") {s:s in V}.$
]

// Hartshorne II.7, Remark 7.8.1
#remark(title: "7.8.1")[
  A morphism $X->sch.p^n$ is equivalently a base-point-free linear system
  together with spanning sections $s_0,dots.c,s_n$. Choosing a basis changes
  the morphism only by a projective automorphism.
]

// Hartshorne II.7, Remark 7.8.2
#remark(title: "7.8.2")[
  The morphism defined by a base-point-free linear system is a closed
  immersion exactly when the system separates closed points and tangent
  vectors.
]

// Hartshorne II.7, Definition D5
#definition(number: none, title: "Trace of a Linear System")[
  For a closed immersion $i:Y->X$ of nonsingular projective varieties and a
  linear system from $V subset.eq Gamma(X, shf.l)$, its *trace* on $Y$ is the
  system determined by $i^*shf.l$ and the image of
  $V->Gamma(Y, i^*shf.l)$; geometrically its divisors are the intersections
  $D dot Y$ when $Y$ is not contained in $ops.supp D$.
]
