#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Ample Invertible Sheaves
// Hartshorne II.7, Definition D1
#definition(title: "Ample Invertible Sheaves")[
  Fix a Noetherian scheme $X$. An invertible sheaf $shf.l in cat.mod(shf.o_X)$ is _ample_ if for every $shf.f in cat.coh (X)$, there is an integer $n_0>0$ (depending on $shf.f$) such that the sheaf $shf.f times.o shf.l^( times.o n)$ is globally generated for every $n >= n_0$.
]

#lemma-box(title: "Fact 7.B")[
  + *(i).* Let $S$ be a graded ring, which is finitely generated by $S_1$ over a Noetherian ring $S_0=A$. Let $X=ops.proj S$, then $shf.o_X (1)$ is a very ample invertible sheaf relative to $ops.spec A$.
  + *(ii).* Let $X in cat.sch_A$ and $shf.l in cat.mod(shf.o_X)$ be an invertible sheaf. Then, $shf.l$ is very ample relative to $A arrow.l.r.double.long$ There exists $n>0$ and global sections ${s_i}_(i=0)^n$, which generate $shf.l$, such that the corresponding morphism $X -> sch.p_A^n$ is an immersion.
]
#proof[
  (i) Note that $ops.proj S -> ops.spec A$ is projective. By _(5.16.1)_, $shf.o_X (1)$ is very ample over $A$. (ii) follows from _(7.1)_ and the _definition of very ampleness_.
]

// Hartshorne II.7, Remark 7.4.1
#remark(title: "7.4.1")[
  Ample is an absolute notion depending only on $X$, whereas very ample is
  relative to a chosen base scheme.
]

// Hartshorne II.7, Remark 7.4.3
#remark(title: "7.4.3")[
  Serre's theorem says a very ample sheaf on a projective scheme over a
  noetherian ring is ample. The converse holds after taking a positive power,
  by Theorem 7.6.
]

// Hartshorne II.7, Remark 7.4.4
#remark(title: "7.4.4")[
  Chapter III characterizes ampleness through vanishing of higher
  cohomology of coherent sheaves after sufficiently positive twists.
]

// Hartshorne II.7, Proposition 7.5
#proposition(number: 7.5)[
  Let $shf.l in cat.mod(shf.o_X)$ be an invertible sheaf on a Noetherian scheme $X$. T.F.A.E.
  + *(i).* $shf.l$ is ample.  (ii) $shf.l^( times.o m)$ is ample for all $m>0$. (iii) $shf.l^( times.o m)$ is ample for some $m>0$.
]
#proof[
  (i) $Rightarrow$ (ii). Given $shf.f in cat.coh (X)$, then $shf.f times.o shf.l^( times.o n)$ is globally generated for all large $n$, so is $shf.f times.o (shf.l^( times.o m))^( times.o n)$. By definition, $shf.l^m$ is ample.

  (ii) $Rightarrow$ (iii). This is clear.

  (iii) $Rightarrow$ (i). Suppose $shf.l^( times.o m)$ is ample. Given $shf.f in cat.coh (X)$, then $exists n_0>0$ such that $shf.f times.o (shf.l^( times.o m))^( times.o n)$ is globally generated for every $n >= n_0$. Consider $shf.f times.o shf.l in cat.coh (X)$. As $shf.l^( times.o m)$ is ample, $exists n_1>0$ such that $(shf.f times.o shf.l) times.o (shf.l^( times.o m))^( times.o n)$ is globally generated for every $n >= n_1$. Continuing this process, for each $1 <= k <= m-1, exists n_k>0$ such that $(shf.f times.o shf.l^( times.o k)) times.o (shf.l^( times.o m))^( times.o n) simeq shf.f times.o shf.l^( times.o (m n+k))$ is globally generated for every $n >= n_k$. Take $N := m dot max {n_k:0 <= k <= m-1}>0$, then $shf.f times.o shf.l^( times.o n)$ is globally generated for every $n >= N$. Therefore, $shf.l$ is ample.
]

// Hartshorne II.7, Theorem 7.6
#theorem(number: 7.6)[
  Let $X$ be a (Noetherian) scheme of finite type over a Noetherian ring $A$, and $shf.l in cat.mod(shf.o_X)$ be an invertible sheaf. Then
  $shf.l text(" is ample ") arrow.l.r.double.long shf.l^( times.o m) text(" is very ample over ") ops.spec A text(" for some ") m > 0.$
]
#proof[
  ($Leftarrow$) Suppose $shf.l^( times.o m)$ is very ample over $A$. Let $X arrow.r.long^(i) sch.p_A^n$ be the immersion (with $n >= 1$) such that $shf.l^( times.o m) simeq i^ast (shf.o (1))$.
  - Let $overline(X)$ be the closure of $i(X)$ in $sch.p_A^n$. Consider the closed immersion $overline(X) arrow.r.long^(j) sch.p_A^n$ such that $i$ factors through $j$ via the open immersion $X arrow.r.long^(k) overline(X)$, i.e. $i=j k$.
  - Now, $overline(X) -> ops.spec A$ is projective. By _(5.17)_, $shf.o_(overline(X)) (1)=j^ast (shf.o (1))$ is ample on $overline(X)$.
  - For any $shf.f in cat.coh (X)$, it follows from _[5.15]_ that $exists overline(shf.f) in cat.coh (overline(X))$ which extends the coherent sheaf $shf.f$, i.e. $overline(shf.f)|_X simeq shf.f$.
  - Now, if $overline(shf.f) times.o shf.o_(overline(X)) (l)$ is globally generated, then so is
  $(overline(shf.f) times.o shf.o_(overline(X)) (l))|_X & simeq shf.f times.o (shf.o_(overline(X)) (1)|_X)^( times.o l) simeq shf.f times.o (k^ast j^ast shf.o (1))^( times.o l) simeq shf.f times.o (i^ast shf.o (1))^( times.o l) & simeq shf.f times.o (shf.l^( times.o m))^( times.o l)$
  for every large $l>0$. Thus, $shf.l^( times.o m)$ is ample, and hence, $shf.l$ is ample by _(7.5)_.

  ($Rightarrow$) Suppose $shf.l$ is ample.

  (I) Given any $P in X$. Choose an open affine $U in shf.n_P (X)$ on which $shf.l|_U simeq shf.o_X|_U$.
  - Let $Y := X without U$ be the closed subset in $X$, and let $shf.i_Y lt.closed shf.o_X$ be the sheaf of ideal with reduced induced structure. Since $X$ is Noetherian and of finite type over $A$, it follows from _(5.9)_ that $shf.i_Y in cat.coh (X)$. So, $shf.i_Y times.o shf.l^( times.o n)$ is globally generated by ${s_i}$ for some large $n>0$. Now, $(shf.i_Y times.o shf.l^( times.o n))_P=shf.o_(X,P) spn {(s_i)_P}$, so we have $(s_i)_P in.not idl.m_P (shf.i_Y times.o shf.l^( times.o n))_P$ for some $i$. (Otherwise, we have $1=sum_i a_i (s_i)_P in idl.m_P (shf.i_Y times.o shf.l^( times.o n))_P$). Write $s := s_i$.
  - As $shf.l$ is an invertible sheaf, $- times.o shf.l$ is an exact functor, whence $shf.i_Y times.o shf.l^( times.o n) arrow.r.hook {} shf.o_X times.o shf.l^( times.o n) simeq shf.l^( times.o n)$, i.e. we may regard $s in Gamma(X, shf.i_Y times.o shf.l^( times.o n)) subset Gamma(X, shf.l^( times.o n))$. Consider the set $X_s := {Q in X:s_Q in.not idl.m_Q shf.l_Q^( times.o n)}$, which is open in $X$, and that $P in X_s$.
  - Further, we have $X_s subset U$. Indeed, if $Q in.not U$, then
  $ Q in Y=ops.supp (shf.o_X\/shf.i_Y)={x in X:shf.i_(Y,x) != shf.o_(X,x)}, $ i.e. $shf.i_(Y,Q) lt.closed shf.o_(X,Q)$, whence $shf.i_(Y,Q) subset idl.m_Q$. Thus, $s_Q in idl.m_Q shf.l_Q^( times.o n)$, i.e. $Q in.not X_s$.
  - Moreover, as $U simeq ops.spec A$ is open affine and that $shf.l|_U simeq shf.o_X|_U$, the section $s|_U in Gamma(U, shf.l^( times.o n))$ corresponds to a global section $f in Gamma(U, shf.o_X|_U) simeq Gamma(U, shf.o_X^( times.o n))$. This implies that $X_s=U inter X_s=U_f simeq ops.spec A_f$ is affine.
  - _Conclusion._ For any $P in X, exists n>0$ and a global section $s in Gamma(X, shf.l^( times.o n))$ such that $X_s in shf.n_P (X)$ is a open affine neighborhood of $P$.

  (II) Reduction to $shf.l$.
  - Note that $X$ is of finite type over $A$, so $X$ is quasi-compact, i.e. we can cover $X$ by finitely many such open affine ${X_(s_i)}_(i=1)^r$ with each $s_i in Gamma(X, shf.l^( times.o n_i))$.
  - For any $k>0$, note that
  $Q in X_(s_i) arrow.l.r.double.long (s_i)_Q in.not idl.m_Q shf.l_Q^( times.o n_i) arrow.l.r.double.long (s_i^k)_Q in.not idl.m_Q shf.l_Q^( times.o k n_i) arrow.l.r.double.long Q in X_(s_i^k),$
  which shows that $X_(s_i)=X_(s_i^k)$ where $s_i^k in Gamma(X, shf.l^( times.o k n_i))$. Now, pick $n := n_1 ... n_r>0$ and $t_i := s_i^(n/n_i) in Gamma(X, shf.l^( times.o n))$ for each $i$. Then $X_i := X_(t_i)=X_(s_i)$ still gives a finite open affine cover of $X$.
  - From _(7.5)_, $shf.l^( times.o n)$ is ample. Moreover, note that we are only trying to show that $shf.l^( times.o m)$ is very ample over $A$ for some $m>0$. So, we may replace $shf.l^( times.o n)$ by $shf.l$ and assume that $X$ is covered by open affines $X_i=X_(s_i)$ where $s_i in Gamma(X, shf.l)$ ($1 <= i <= r$).

  (III) Define an $A$-morphism $X -> sch.p_A^N$.
  - For each $i$, we let $B_i := Gamma(X_i, shf.o_X|_(X_i))$, i.e. $X_i=ops.spec B_i$. Since $X$ is of finite type over $A$, we have $B_i in fg cat.alg_A$ by _[3.3]_. Let ${b_(i j)}_(j=1)^(k_i)$ denote the set of generators for $B_i$ over $A$. Apply _(5.14b)_ to each $b_(i j) in Gamma(X_i, shf.o_X)$, then $exists m_(i j)>0$ and a global section $c_(i j) in Gamma(X, shf.o_X times.o shf.l^( times.o m_(i j)))=Gamma(X, shf.l^( times.o m_(i j)))$ such that $c_(i j)|_(X_i)=s_i^(m_(i j)) b_(i j)$. As usual, we take $m >= max {m_(i j)}$ such that $s_i^m b_(i j)$ extends to $c_(i j) in Gamma(X, shf.l^( times.o m))$ for every $i,j$.
  - Note that the global sections ${s_i^(m)}_(i=1)^r$ and ${c_(i j)}_(i,j)$ generated the invertible sheaf $shf.l^( times.o m) in cat.mod(shf.o_X)$. By _(7.1)_, they define an $A$-morphism $phi:X -> sch.p_A^N$ such that $shf.l^( times.o m) simeq phi^ast (shf.o (1))$, (where $N=r+sum_(i=1)^r k_i-1$).

  (IV) Show that $phi$ is an immersion.
  - Let ${x_i}_(i=1)^r$ and ${x_(i j)}_(i,j)$ denote the set of homogeneous coordinates of $sch.p_A^N$ via $phi$, i.e. $s_i^m=phi^ast (x_i)$ and $c_(i j)=phi^ast (x_(i j))$ by _(7.1)_.
  - For each $i$, let $U_i := D_+(x_i) subset sch.p_A^N$ (which is open affine), then $phi^(-1) (U_i)=X_(s_i^m)=X_i$. Further, the corresponding ring homomorphism
  $phi^sharp_(U_i): A[y_k, y_(k j)] arrow.r.long B_i, quad y_k=(x_k) / (x_i) mapsto (s_k^m) / (s_i^m), quad y_(k j)=(x_(k j)) / (x_i) mapsto (c_(k j)) / (s_i^m)=b_(k j)$
  is surjective, since $y_(i j) mapsto b_(i j)$ and ${b_(i j)}_(j=1)^(k_i)$ generates $B_i$ over $A$.
  - By _[2.18c]_, the morphism $X_i -> U_i$ between affine schemes via $phi$ is a closed immersion. Thus, $X=union.big_(i=1)^r X_i arrow.r.long^(phi) union.big_(i=1)^r U_i$ is a closed immersion followed by an open immersion $union.big_(i=1)^r U_i arrow.r.hook {} sch.p_A^N$, i.e. $X arrow.r.long^(phi) sch.p_A^N$ is an immersion. Therefore, $shf.l^( times.o m)$ is very ample over $A$.
]

#example(title: "7.6.1")[
  Let $X=sch.p_A^n$ for any Noetherian ring $A$. Then,
  $shf.o (l) text("is ample") arrow.l.r.double.long shf.o (l) text("is very ample") arrow.l.r.double.long l>0.$
]
#proof[
  For any ring $A$, set $S=A[x_0, ... ,x_n]$. Given $d>0$, let ${M_i}_(i=0)^N$ denote the set of monomials in $x_0, ... ,x_n$ of degree $d$ (in a given order where $N=binom(n+d, n)-1$). Then the ring homomorphism
  $theta:A[y_0, ... ,y_N] arrow.r.long S^((d)), quad y_i mapsto M_i$
  gives rise to the closed immersion $ops.proj S^((d)) arrow.r.hook {} sch.p_A^N$ by _[3.12d]_. This corresponds to the $d$-uple embedding
  $rho_d:X=ops.proj S isolongto Y=ops.proj S^((d)) arrow.r.hook {} sch.p_A^N$
  by _[5.13]_. It follows that $shf.o_X (d) simeq shf.o_Y (1)$ is very ample over $A$. In particular, if $A$ is Noetherian, then $shf.o_X (n)$ is ample for every $n>0$ by _(7.5)_ and _(7.6)_. On the other hand, the sheaf $shf.o_X (l)$ has no global sections for $l<0$, one sees easily that $shf.o_X (l)$ cannot be ample for $l <= 0$. Thus, we have the desired result.
]
