#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Morphisms to $sch.p^n$

// Hartshorne II.7, Theorem 7.1
#theorem(number: 7.1)[
  Let $A in R in g$ and $X in cat.sch_A$.
  + *(a).* If $X arrow.r.long^(phi) sch.p_A^n$ is an $A$-morphism, then $phi^ast (shf.o (1))$ is an invertible sheaf on $X$ generated by the global sections $s_i=phi^ast (x_i)$ ($0 <= i <= n$).
  + *(b).* Conversely, if $shf.l$ is an invertible sheaf on $X$, and if ${s_i}_(i=0)^n$ are the global sections generating $shf.l$, then there exists a unique $A$-morphism $X arrow.r.long^(phi) sch.p_A^n$ such that $shf.l simeq phi^ast (shf.o (1))$ and $s_i=phi^ast (x_i)$ under this isomorphism.
]
#proof[
  (a) Write $S=A[x_0, ... ,x_n]$.
  - From _(5.12)_, $shf.o (1)$ on $sch.p_A^n$ is invertible, and from _(5.13)_, $S simeq Gamma_ast (shf.o)$, so $x_i in S_1=Gamma(sch.p_A^n, shf.o (1))$ for each $i$.
  - For any $idl.p in sch.p_A^n=ops.proj S$, we have
  $shf.o (1)_idl.p=S(1)_((idl.p))=(S_p p)_1=(S_p p)_0 spn {(x_i) / (1)}_(i=0)^n=shf.o_p p spn {(x_i) / (1)}_(i=0)^n,$
  i.e. $shf.o (1)$ is generated by global sections $x_0, ... ,x_n$.
  - Recall from the _proof of [5.1d(i)]_ that if $shf.e in cat.mod(shf.o_Y)$ is locally free of rank $r$ covered by ${V_i}$, then $f^ast shf.e in cat.mod(shf.o_X)$ is also locally free of rank $r$ covered by ${U_i}$ where $U_i=f^(-1) (V_i)$ under the morphism $(X,shf.o_X) arrow.r.long^(f) (Y,shf.o_Y)$. Therefore, the $shf.o_X$-module $shf.l=phi^ast (shf.o (1))$ is indeed an invertible sheaf.
  - For any $x in X$, we see that
  $shf.l_x simeq shf.o (1)_(phi(x)) times.o_{shf.o_(phi(x))} shf.o_(X,x)=shf.o_(X,x) spn {(x_i) / (1) times.o 1}_(i=0)^n,$
  whence $shf.l$ is generated by the global sections $s_i=phi^ast (x_i)$.

  (b) We construct such morphism in the following steps:
  - For each $i$, set $X_i := {P in X:(s_i)_P in.not idl.m_P shf.l_P}$, which is an open subset of $X$ (as we have seen before). Then, ${X_i}_(i=0)^n$ is an open cover of $X$. Indeed, for any $P in X$, since ${s_i}_(i=0)^n$ generates $shf.l$, we have $shf.l_P=shf.o_(X,P) spn {(s_i)_P}_(i=0)^n$, say $1=sum_(i=0)^n a_i (s_i)_P$ (where $a_i in shf.o_(X,P)$). There must be at least an $i$ for which $(s_i)_P in.not idl.m_P shf.l_P$, i.e. $P in X_i$, otherwise we have $1=sum_(i=0)^n a_i (s_i)_P in idl.m_P shf.l_P$, a contradiction.
  - Let $U_i := D_+(x_i)$ ($0 <= i <= n$) be the usual open affine cover of $Y=sch.p_A^n=ops.proj S$. We first construct a morphism $X_i arrow.r.long^(phi_i)U_i$.
  - We have a trivialization of the invertible sheaf
  $psi_i:shf.o_X|_(X_i) isolongto shf.l|_(X_i),quad 1 mapsto s_i$
  on the open cover ${X_i}$.
  - Note that $U_i simeq ops.spec A[y_0, ... ,y_n]$ where $y_j=(x_j) / (x_i)$ with $y_i=1$ ommited. We define a ring homomorphism
  $f_i:A[y_0, ... ,y_n] arrow.r.long Gamma(X_i, shf.o_(X_i)), quad y_j mapsto (s_j) / (s_i)$
  and making it $A$-linear. Note that for any $P in X_i$, we have $(s_i)_P in.not idl.m_P shf.l_P simeq idl.m_P shf.o_(X_i,P)$ (as $shf.l$ is invertible), which implies that $((s_j) / (s_i))_P=((s_j)_P) / ((s_i)_P)$ is defined in $shf.o_(X_i,P)$. Thus, $(s_j) / (s_i) in Gamma(X_i, shf.o_(X_i))$, i.e. $f_i$ is well-defined.
  - From _[2.4]_, $f_i$ determines the morphism $phi_i:X_i arrow.r.long^() ops.spec A[y_0, ... ,y_n] simeq U_i$ uniquely.
  - _Check._ We may glue ${phi_i}_(i=0)^n$ along ${X_i}_(i=0)^n$ to obtain a morphism $X arrow.r.long^(phi)Y=sch.p_A^n$, i.e. it suffices to show that $phi_i|_j=phi_j|_i$ for every $i,j$. Write $y_k := (x_k) / (x_i)$ and $y_l' := (x_l) / (x_j)$, then
  $A[y_0, ... ,y_n]_(y_j) simeq A[x_0, ... ,x_n]_((x_i x_j)) simeq A[y_0', ... ,y_n']_(y_i'), U_(i j)=D_+(x_i x_j) simeq ops.spec A[x_0, ... ,x_n]_((x_i x_j)).$
  We have the correspondence of morphisms and ring homomorphisms:
  #remark[Diagram.]
  where the both restrictions $f_i|_j:(y_k) / (y_j)=(x_i x_k) / (x_i x_j) mapsto (s_i s_k) / (s_i s_j)$ and $f_j|_i:(y_l') / (y_i')=(x_l x_j) / (x_i x_j) mapsto (s_l s_j) / (s_i s_j)$ are compatible with $f_(i j):=(x_k x_l) / (x_i x_j) mapsto =(s_k s_l) / (s_i x_j)$. So, $f_(i j)$ determines the middle morphism $U_(i j) arrow X_(i j)$ uniquely, and hence, $phi_i|_j=phi_j|_i$.
  - _Claim._ $shf.l simeq phi^ast (shf.o (1))$ as invertible $shf.o_X$-modules. Note that both $shf.l$ and $phi^ast (shf.o (1))$ are locally free, so it suffices to prove on the open cover ${X_i}_(i=0)^n$ of $X$. We recall some facts:
  - For $f in S_1$, we have $S(n)_((f))=f^n dot S_((f))$ (as $S_((f))$-modules).
  - If $X arrow.r.long^(phi)Y$ is a morphism, and $s in Gamma(Y, shf.l)$ is a global section, there is a canonical morphism $phi^(!) shf.l arrow.r.long^() phi_ast (phi^ast shf.l)$. The pull back of the section $s$ is defined to be
  $phi^ast (s) := phi^(!)_Y (s) in Gamma(Y, f_ast (f^ast shf.l))=Gamma(X, f^ast shf.l).$
  Now, we have the isomorphisms
  $shf.l|_(X_i) arrow.r.long^(psi_i^(-1)) shf.o_X|_(X_i) arrow.r.long^(s_i dot)s_i dot shf.o_X|_(X_i) simeq phi_i^ast (x_i dot shf.o|_(U_i)) simeq phi_i^ast (shf.o (1)|_(U_i)) simeq (phi^ast shf.o (1))|_(X_i)$
  on each $X_i$, which glue to the isomorphism $shf.l simeq phi^ast shf.o (1)$ of $shf.o_X$-modules.

  - Finally, any morphism with these properties must be the one we constructed, so such $A$-morphism $phi$ is unique.
]

// Hartshorne II.7, Proposition 7.2
#proposition(number: 7.2)[
  Let $X arrow.r.long^(phi) sch.p_A^n$ be an $A$-morphism corresponding to an invertible sheaf $shf.l in cat.mod(shf.o_X)$ with generating sections $s_0, ... ,s_n in Gamma(X, shf.l)$ as in _(7.1)_. Then $phi$ is a closed immersion if and only if
  + *(1).* Each open set $X_i=X_(s_i)$ is affine.
  + *(2).* For each $i$, the ring homomorphism
  $f_i:A[y_0, ... ,y_n] arrow.r.long Gamma(X_i, shf.o_(X_i)), quad y_j mapsto (s_j) / (s_i)$
  constructed above is surjective.
]
#proof[
  ($Rightarrow$) Suppose $phi$ is a closed immersion. Then, we have the fibre square:
  #remark[Diagram.]
  Then, $X_i=U_i inter X$ is a closed subscheme of $U_i$. Note that $U_i simeq ops.spec S_((x_i))$ is affine, by _(5.10)_, $X_i$ is also affine, determined uniquely by an ideal $frak("a") lt.closed S_((x_i))$, so that the ring homomorphism $f_i$ is given by $S_((x_i)) arrow.r.twohead S_((x_i))\/frak("a")$, and thus, is surjective.\

  ($Leftarrow$) Suppose (1) and (2) are satisfied. Then the morphism $phi:X_i -> U_i$ is a closed immersion by _[2.18c]_ (since $phi_i$ is induced by $f_i$). Note that $X_i=phi^(-1) (U_i)$ covers $X$ and that _closed immersions are local on the base_, so $phi:X -> sch.p_A^n$ is a closed immersion.
]

#lemma-box(title: "Fact 7.A")[
  Let $X arrow.r.long^(f)Y$ be a closed morphism of schemes of finite type over any field $k$. Then,
  $f text("is injective") arrow.l.r.double.long f text("is injective on closed po in ts").$
]

We will use this fact in the following proposition.

// Hartshorne II.7, Proposition 7.3
#proposition(number: 7.3)[
  Let $X in cat.sch_k$ be a projective scheme over an algebraically closed field $k$, and let $phi:X -> sch.p_k^n$ be a $k$-morphism corresponding to $shf.l$ and $s_0, ... ,s_n in Gamma(X, shf.l)$ as above. Let $V subset Gamma(X, shf.l)$ be the $k$-vector subspace spanned by ${s_i}_(i=0)^n$. Then $phi$ is a closed immersion if and only if
  + *(1).* Elements of $V$ "separate points", i.e. for any two distinct closed points $P,Q in X$, there is an $s in V$ such that $s_P in idl.m_P shf.l_P$ but $s_Q in.not idl.m_Q shf.l_Q$, or vice versa.
  + *(2).* Elements of $V$ "separate tangent vectors", i.e. for each closed point $P in X$, we have
  $idl.m_P shf.l_P\/idl.m_P^2 shf.l_P=k spn {bar{s}_P:s in V, s_P in idl.m_P shf.l_P}.$
]
#proof[
  ($Rightarrow$) If $phi$ is a closed immersion, we may consider $X$ as a closed subscheme of $sch.p_k^n$. From _(5.16)_, $X simeq ops.proj S\/I$ for some homogeneous ideal $I lt.closed S=k[x_0, ... ,x_n]$. So, $phi$ is induced by the natural map $S arrow.r.twohead S\/I$, and thus, $shf.l=shf.o_X (1)$ with $s_i=x_i+I in (S\/I)_1$.
  + *(1).* Given distinct closed points $P,Q in X$, corresponding to the homogeneous maximal ideals $idl.m_P != idl.m_Q$ of $S\/I$. Note that $S\/I=k[s_0, ... ,s_n]$ is finitely generated by $(S\/I)_1$ over $(S\/I)_0=k$, so $exists bar{f} in (S\/I)_1$ for which $bar{f} in idl.m_P$ but $bar{f} in.not idl.m_Q$, i.e. $P in V_+(bar{f})$ but $Q in.not V_+(bar{f})$. Take $s := bar{f} in k spn {s_i}_(i=0)^n=V$, then we have the desired result.
  + *(2).* For any closed point $P in X subset sch.p_k^n$. As $k$ is algebraically closed, we may assume $P=[a_0: ... :a_n]$ with $a_i in k$. Further, we can always apply a suitable automorphism of $sch.p_k^n$, see _(7.1.1)_, and assume $P=[1:0: ... :0]$. It follows that  $P=(0, ... ,0)$ on the open affine $U_0=ops.spec k[y_1, ... ,y_n]$ ($y_i := x_i/x_0$), and that $shf.l|_(U_0) simeq shf.o_X|_(U_0)$. Now, $P in U_0$ corresponds to the maximal ideal
  $idl.m_(U_0,P)= <y_1, ... ,y_n >lt.closed k[y_1, ... ,y_n]=S_((x_0))=shf.o_(U_0,P).$
  Finally, since $phi$ is a closed immersion, the map $phi_P^sharp:shf.o_(U_0,P)=shf.o_(sch.p_k^n,P) -> shf.o_(X,P) simeq shf.l_P$ is surjective. Therefore, the image of ${bar{y}_i}_(i=1)^n$ under $phi_P^sharp$ generates $idl.m_P\/idl.m_P^2$ over $k$.

  ($Leftarrow$) Conversely, suppose $phi$ satisfies (1) and (2).
  - Note that $X$ is projective over $k$, so it is proper over $k$ by _(4.9)_, i.e. the composition $X arrow.r.long^(phi) sch.p_k^n -> ops.spec k$ is proper. Further, $sch.p_k^n -> ops.spec k$ is separated, it follows from _(4.8e)_ that $phi$ is also proper. Thus, by _[4.4]_, $phi$ is a closed map (morphism) and its image $phi(X) subset sch.p_k^n$ is closed.
  - If $P in X$ is a closed point, then $shf.l simeq phi^ast (shf.o (1))$ induces the isomorphism
  $shf.o (1)_(phi(P))\/idl.m_(phi(P)) shf.o (1)_(phi(P)) isolongto shf.l_P\/idl.m_P shf.l_P, quad (x_i)_(phi(P))+idl.m_(phi(P)) shf.o (1)_(phi(P)) mapsto (s_i)_P+idl.m_P shf.l_P$
  of $k$-vector spaces. Hence, if $f in S_1$, we have
  $[phi^ast (f)]_P in idl.m_P shf.l_P arrow.l.r.double.long [f]_(phi(P)) in idl.m_(phi(P)) shf.o (1)_(phi(P)) arrow.l.r.double.long [f]_(phi(P))=0 text("in") kappa(phi(P))=k.$
  - Now, if $P,Q in X$ are distinct closed points, by (1), $exists s in V$ for which $s_P in idl.m_P shf.l_P$ but $s_Q in.not idl.m_Q shf.l_Q$. This means, $exists f in S_1$ for which $phi^ast (f)=s$ and that $[f]_(phi(P))=0$ but $[f]_(phi(Q)) != 0$ in $k$. Thus, $phi(P)=phi(Q)$, i.e. $phi$ is injective on closed points. By _(7.A)_, $phi$ is injective (as a map of sets), and thus, $phi$ is a topological closed embedding.
  - Write $Y=sch.p_k^n$, it remains to show that the sheaf map $phi^sharp:shf.o_Y -> phi_ast shf.o_X$ is surjective. We check on the stalk maps. However, $phi$ maps every closed point $X$ to a closed point of $Y$, so it reduces to show that the map $phi_P^sharp:shf.o_(Y,phi(P)) -> shf.o_(X,P)$ is surjective for every closed point $P in X$. We complete by the following lemma _(7.4)_.
  + *(i).* Clearly, we have $shf.o_(Y,phi(P))\/idl.m_(Y,phi(P)) simeq k simeq shf.o_(X,P)\/idl.m_(X,P)$.
  + *(ii).* By (2) and the fact that $shf.l$ is invertible, we see that
  $idl.m_(Y,phi(P))=k spn {[f]_(phi(P)):f in S_1} arrow.r.twohead k spn {[phi^ast (f)]_P+idl.m_P:f in S_1} =k spn {bar{s}_P:s in V, s_P in idl.m_P}=idl.m_P\/idl.m_P^2.$
  + *(iii).* Note from _[4.9e]_ that $phi$ is also a projective morphism, and that $shf.o_X in cat.qcoh (X)$, it follows from _(5.20)_ that $phi_ast shf.o_X in cat.coh (Y)$. Therefore, $shf.o_(X,P) in fg cat.mod(shf.o_(Y,phi(P)))$.
]

// Hartshorne II.7, Lemma 7.4
#lemma(number: 7.4)[
  Let $f:A arrow.r.long^()B$ be a local homomorphism of local Noetherian rings such that
  + *(i).* $A\/idl.m_A isolongto B\/idl.m_B$ is a ring isomorphism.
  + *(ii).* $idl.m_A arrow.r.twohead idl.m_B\/idl.m_B^2$ is surjective.
  + *(iii).* $B$ is a finitely generated $A$-module.
  Then, $f$ is surjective.
]
#proof[
  Consider the ideal $idl.b := idl.m_A B lt.closed B$, we have $idl.b subset idl.m_B$. From (ii), we have $idl.m_B=idl.b+idl.m_B^2$, it follows from _Nakayama Lemma_ for $(B,idl.m_B)$ that $idl.b=idl.m_B$. Now, apply _Nakayama Lemma_ to $B in cat.mod(A)$. Since $B in fg cat.mod(A)$ by (iii), $1 in B$ gives a generator for $B\/idl.m_A B=B\/idl.m_B = A\/idl.m_A$, i.e. $1 in B$ generates $B$ as an $A$-module. Thus, $f$ is surjective.
]
