#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== The Relative Proj & Projective Space Bundles
#emph-box()[
  *Axiom $dagger$.*
  - $X$ is a Noetherian scheme, and $shf.s in cat.qcoh (X)$ having a structure of graded $shf.o_X$-algebras, i.e. we have $shf.s simeq plus.o.big_(d >= 0) shf.s_d$, where $shf.s_d$ is the _homogeneous part_ of _degree_ $d$.
  - Assume further that $shf.s$ is locally generated by $shf.s_1 in cat.coh (X)$ as an $shf.s_0=shf.o_X$-algebra. Thus, we have $shf.s_d in cat.coh (X)$ for every $d >= 0$.
]

#emph-box()[
  *The Relative $sch.proj$ Construction.*
  Fix a scheme $X$, and a quasi-coherent algebra $shf.s in cat.gr cat.alg_(shf.o_X)$.
  - For any open affine $U=ops.spec A$ of $X$, we have $shf.s (U) in cat.gr cat.alg_(shf.o_X (U))$. Consider $ops.proj shf.s (U)$ with the natural morphism
  $ops.proj shf.s (U) arrow.r.long^(pi_U) ops.spec shf.o_X (U) simeq U.$
  Checking through the _glueing data_, we may glue these ${pi_U}$ along such open affine cover ${U}$ to obtain a scheme, denoted by $sch.proj shf.s$, together with a morphism $sch.proj shf.s arrow.r.long^(pi)X$ and open immersions $ops.proj shf.s (U) arrow.r.long^(psi_U) sch.proj shf.s$, such that ${ops.im psi_U}$ covers $sch.proj shf.s$, and is compatible on the intersections.
  - Such $pi$ is unique with the property that for any open affine $U=ops.spec A$ of $X$, the square
  #remark[Diagram.]
  is a fibre square, which is compatible with all open affine subsets $V subset U$. Further, we have
  $pi^(-1) (U)=ops.im psi_U simeq ops.proj shf.s (U).$
  - From _(5.12c)_, the invertible sheaves $shf.o (1)$ on each $ops.proj shf.s (U)$ are compatible under this construction, so they glue together to give an invertible sheaf $shf.o (1)$ on $sch.proj shf.s$ canonically.
]

#lemma-box(title: "Fact 7.D")[
  Consider the relative construction $sch.proj shf.s arrow.r.long^(pi)X$ as above. Then, we have the following results.
  + *(i).* $pi$ is separated.
  + *(ii).* If $shf.s in cat.alg_(shf.o_X)$ is locally finitely generated, then $pi$ is of finite type.
  + *(iii).* If, in addition to (ii), that $X cat.sch$ is Noetherian, then so is $sch.proj shf.s$.
  + *(iv).* If, in addition to (iii), that $shf.s$ satisfies ($dagger$), then $pi$ is proper.
]
#proof[
  These are in fact the more detailed results of _(7.10a)_. To see (i), we use the fact of _(4.1)_ and the fact that "separated is local on the base _(4.6f)_", whence each $pi_U$ is separated, and so is $pi$.
]

#example(title: "7.8.7")[
  If $shf.s=shf.o_X[T_0, ... ,T_n]$ is the polynomial algebra, then $sch.proj shf.s=sch.p_X^n$ with its twisting sheaf $shf.o (1)$ defined earlier.
]

// Hartshorne II.7, Lemma 7.9
#lemma(number: 7.9)[
  Let $X$ and $shf.s$ satisfy ($dagger$), and let $shf.l in cat.mod(shf.o_X)$ be an invertible sheaf. We define a new sheaf
  $shf.s ast shf.l := plus.o.big_(d >= 0) (shf.s_d times.o_(shf.o_X) shf.l^( times.o d)) in cat.gr cat.alg_(shf.o_X).$
  Then $shf.s ast shf.l$ also satisfies ($dagger$), and there is a canonical isomorphism
  $phi:Y'=sch.proj (shf.s ast shf.l) arrow.r.long^(tilde.op)Y=sch.proj shf.s,$
  commuting with the projections $Y arrow.r.long^(pi)X$ and $Y' arrow.r.long^(pi')X$, and having the property that
  $shf.o_(Y') (1) simeq phi^ast shf.o_Y (1) times.o_{shf.o_(Y')}(pi')^ast shf.l.$
]
#proof[
  We divide into the following steps.\

  (I) For any open affine $U subset X$ satisfying $shf.l|_U simeq shf.o_X|_U, exists$ canonical $U$-isomorphism
  $phi_U:ops.proj (shf.s ast shf.l)(U) arrow.r.long^(tilde.op) ops.proj shf.s (U),$
  compatible with all open affine subsets $V subset U$.

  *proof.* Clearly, we have $shf.s ast shf.l in cat.qcoh (X)$. Given an $shf.o_X (U)$-basis ${eta}$ of $shf.l (U)$. Define a map
  $alpha_U:shf.s (U) arrow.r.long (shf.s ast shf.l)(U), quad s=sum_(d >= 0)s_d mapsto sum_(d >= 0)s_d times.o eta^( times.o d).$
  This is a graded $shf.o_X (U)$-algebra isomorphism since for each $d >= 0$, the map $shf.s_d (U) -> (shf.s ast shf.l)_d, s mapsto s times.o eta^( times.o d)$ comes from the isomorphism $(shf.s_d times.o shf.l^( times.o d))|_U simeq shf.s_d|_U times.o shf.l|_U^( times.o d) simeq shf.s_d|_U times.o shf.o_X|_U^( times.o d) simeq shf.s_d|_U$. Thus, $alpha_U$ induces an isomorphism $phi_U:ops.proj (shf.s ast shf.l)(U) arrow.r.long^(tilde.op) ops.proj shf.s (U)$.

  _Check._ The isomorphism $phi_U$ is independent of the choice of the basis $eta$.
  - Suppose ${eta'}$ is another $shf.o_X (U)$-basis of $shf.l (U)$, then $exists f in shf.o_X (U)^times$ for which $eta'=f dot eta$. We also have a graded $shf.o_X (U)$-algebra isomorphism
  $alpha'_U:shf.s (U) arrow.r.long^(tilde.op) (shf.s ast shf.l)(U), quad s=sum_(d >= 0)s_d mapsto sum_(d >= 0)s_d times.o eta'^( times.o d).$
  It follows that $alpha'_U (s)=sum_(d >= 0)f^d (s_d times.o eta^( times d))=sum_(d >= 0) alpha_U (s_d)$.
  - _Fact._ For any homomorphism $S arrow.r.long^(alpha)T$, set $G(psi) := {idl.p in ops.proj T:idl.p in.not supset alpha(S_+)}$ (as in _[2.14]_). Suppose $f in T_0$ is a unit, we consider the graded homomorphism
  $alpha':S arrow.r.long T, quad s=sum_(d >= 0)s_d mapsto sum_(d >= 0)f^d alpha(s_d).$
  Then, $G(alpha)=G(alpha')$, and the induced morphisms $G(alpha) arrow.r.long^() ops.proj S$ are the same.
  - Now, the question reduces to prove the fact above. Consider the graded homomorphism
  $theta:T arrow.r.long T, quad t=sum_(d >= 0)t_d mapsto sum_(d >= 0)f^d t_d.$
  As $f in T_0$ is a unit, $theta$ has an inverse homomorphism given by $sum_(d >= 0)t_d mapsto sum_(d >= 0)f^(-d) t_d$. Thus, $theta$ is an automorphism. Now, $alpha'=theta alpha$, so the result clearly follows.
  Finally, for the _compatibility_, note that if $V subset U$ is affine, ${eta|_V}$ is an $shf.o_X (V)$-basis for $shf.l (V)$.\

  (II) The isomorphisms $phi_U$ glue to give an isomorphism $phi:sch.proj (shf.s ast shf.l) arrow.r.long^(tilde.op) sch.proj shf.s$ commuting with the projections, i.e. the following diagram commutes
  #remark[Diagram.]
  *proof.* Cover $X$ with open affines $U$ satisfying $shf.l|_U simeq shf.o_X|_U$. For each such $U$, we have the composition
  $ops.proj (shf.s ast shf.l)(U) arrow.r.long^(phi_U) ops.proj shf.s (U) arrow.r.long^(pi_U)U.$
  Since $phi_U$ is compatible with every open affine subset $V subset U$ by (I), they agree on the intersections, which implies that these $phi_U$ can be glued. Thus, $exists$ isomorphism $sch.proj (shf.s ast shf.l) arrow.r.long^(phi) sch.proj shf.s$ such that
  #remark[Diagram.]
  which is in fact a fibre square, where $psi_U,psi_U'$ are defined in the construction. Now, $pi phi$ is another morphism $ops.proj (shf.s ast shf.l) arrow.r.long^()X$ satisfying $(pi phi) psi'_U=pi psi_U phi_U=iota_U (pi_U phi_U)$. From the _uniqueness_ of the relative construction $sch.proj$, we have $pi'=pi phi$.\

  (III) _Check._ $shf.s ast shf.l in cat.gr cat.alg_(shf.o_X)$ is locally generated by $(shf.s ast shf.l)_1=shf.s_1 times.o shf.l$ over $shf.o_X$, and thus, $shf.s ast shf.l$ satisfies ($dagger$).\

  (IV) Show the isomorphism of sheaves.

  *proof.* Cover $X$ with open affines $U$ satisfying $shf.l|_U simeq shf.o_X|_U$. For each such $U$, consider the following commutative diagram
  #remark[Diagram.]
  Write $Y=sch.proj shf.s, Y'=sch.proj (shf.s ast shf.l)$ and $Y_U=ops.proj shf.s (U), Y'_U=ops.proj (shf.s ast shf.l)(U)$. Then we have the following two isomorphisms:
  $(phi^ast shf.o_Y (1))|_(Y'_U) & simeq phi^ast (shf.o_Y (1)|_(Y_U)) simeq phi^ast (phi_U)_ast shf.o_(Y_U) (1) simeq (phi_U')_ast phi_U^ast shf.o_(Y_U) (1) & simeq (phi'_U)_ast shf.o_(Y_U') (1) simeq shf.o_(Y') (1)|_(Y_U')quad text("(i)") (pi'^ast shf.l)|_(Y'_U) & simeq (pi_U')^ast (shf.l|_U) isolongto (pi'_U)^ast (shf.o_X|_U) simeq shf.o_(Y')|_(Y_U')quad text("(ii)")$
  Thus, the following isomorphism:
  $alpha_U:(phi^ast shf.o_Y (1) times.o pi'^ast shf.l)|_(Y'_U) simeq (phi^ast shf.o_Y (1))|_(Y'_U) times.o (pi'^ast shf.l)|_(Y'_U) isolongto shf.o_(Y') (1)|_(Y_U') times.o shf.o_(Y')|_(Y_U') simeq shf.o_(Y') (1)$
  for each such $U$. Further, this is independent of the chosen $shf.o_X (U)$-basis for $shf.l (U)$ (similar to the proof of (I)), and is compatible with all open affine subsets $V subset U$. Thus, these ${alpha_U}$ can be glued along such cover ${U}$ of $X$ and obtain an isomorphism $alpha:phi^ast shf.o_Y (1) times.o pi'^ast shf.l arrow.r.long^(tilde.op) shf.o_(Y') (1)$.
]

#lemma-box(title: "Fact 7.E")[
  Let $X$ be a Noetherian scheme and suppose $shf.f in cat.coh (X)$ is globally generated by the sections ${s_i}_(i in I)$. Then $shf.f$ can be generated by a finite subset of ${s_i}_(i in I)$.
]
#proof[
  From assumption, $exists$ surjective morphism $shf.o_X^( plus.o I) arrow.r.long^(phi) shf.f$. As $X$ is Noetherian, it can be covered by finitely many open affines $U_j=ops.spec A_j$ ($1 <= j <= n$) where each $A_j$ is Noetherian. Now, for each $1 <= j <= n$, $phi$ restricts to the surjective morphism
  $tildeOf(A)_j^( plus.o I)=shf.o_X^( plus.o I)|_(U_j) arrow.r.twohead shf.f|_(U_j) = tildeOf(M)_j$
  where $M_j in fg cat.mod(A_j)$. From _(5.2)_, the homomorphism $A_j^( plus.o I) arrow.r.long^()M_j$ is also surjective. Since $M_j$ is finitely generated over the Noetherian ring $A_j$, it follows that $M_j$ is a Noetherain $A_j$-module, and thus, any $A_j$-submodule of $M_j$ is finitely generated. Thus, $exists$ finite subset $J_j subset I$ such that ${s_i|_j}_(i in J_j)$ generates $M_j$, so $shf.f_P=shf.o_(X,P) spn {[s_i|_j]_P:i in J_j}$ for all $P in U_j$. Finally, take $J := union.big_(j=1)^n J_j$, then $shf.f$ is globally generated by finitely many sections ${s_i}_(i in J)$.
]

// Hartshorne II.7, Proposition 7.10
#proposition(number: 7.10)[
  Let $X, shf.s$ satisfy ($dagger$), with $Y=sch.proj shf.s arrow.r.long^(pi)X$ and $shf.o_Y (1)$ constructed as above. Then:
  + *(a).* $pi$ is proper, and thus, separated of finite type.
  + *(b).* If $X$ admits an ample invertible sheaf $shf.l$, then $pi$ is projective, and $shf.o_Y (1) times.o pi^ast (shf.l^( times.o n)) in cat.mod(shf.o_Y)$ is very ample over $X$ for suitable $n>0$.
]
#proof[
  (a) For any open affine subset $U subset X$, note that $ops.proj shf.s (U) arrow.r.long^(pi_U)U$ is projective _(4.8.1)_, and thus, proper _(4.9)_. But, _proper is local on the base (4.8f)_, so $pi$ is proper.\

  (b) Suppose $shf.l in cat.mod(shf.o_X)$ is an ample invertible sheaf. Since $shf.s_1 in cat.coh (X), exists n>0$ such that $shf.s_1 times.o shf.l^( times.o n)$ is globally generated. Further, as $X$ is Noetherian, $shf.s_1 times.o shf.l^( times.o n)$ can be generated by finitely many global sections, i.e. $exists$ surjective morphism $shf.o_X^( plus.o (N+1)) arrow.r.long^() shf.s_1 times.o shf.l^( times.o n)$ for some $N>0$. This allows us to define a surjective morphism
  $shf.o_X[T_0, ... ,T_N] arrow.r.long^() plus.o.big_(d >= 0) shf.s_d times.o shf.l^( times.o n d)=shf.s ast shf.l^( times.o n),$
  which gives rise to a closed immersion (as closed immersion is local on the base) defined by
  $i:Y=sch.proj shf.s arrow.r.long^(phi^(-1) tilde.op) sch.proj (shf.s ast shf.l^( times.o n)) arrow.r.hook sch.proj shf.o_X[T_0, ... ,T_N] = sch.p_X^N.$
  Therefore, $pi:Y arrow.r.hook {i} sch.p_X^N -> X$ is projective.

  Now, using the notations in _(7.9)_ with $Y'=sch.proj (shf.s ast shf.l^( times.o n))$, then $i$ is an immersion satisfying
  $i^ast shf.o_(sch.p_X^N) (1) & simeq (phi^(-1))^ast shf.o_(Y') (1) simeq (phi^(-1))^ast (phi^ast shf.o_Y (1) times.o pi'^ast shf.l^( times.o n)) & simeq (phi^(-1))^ast phi^ast (shf.o_Y (1) times.o pi^ast shf.l^( times.o n)) simeq shf.o_Y (1) times.o pi^ast shf.l^( times.o n).$
  Thus, $shf.o_Y (1) times.o pi^ast shf.l^( times.o n)$ is very ample over $X$.
]

// Hartshorne II.7, Definition D6
#definition(title: "Projective Space Bundles")[
  Given a Noetherian scheme $X$ and  a locally free sheaf $shf.e in cat.coh (X)$. Let $shf.s := S(shf.e)= plus.o.big_(d >= 0)S^d (shf.e)$, then $shf.s in cat.gr cat.alg_(shf.o_X)$ satisfies ($dagger$). We define the _projective space bundle_ associated to $shf.e$ to be the space $sch.p (shf.e)=sch.proj shf.s$, which comes with a projection $sch.p (shf.e) arrow.r.long^(pi)X$ and an invertible sheaf $shf.o (1)$.
]

#remark[
  If $shf.e in cat.mod(shf.o_X)$ is a free sheaf of rank $n+1$ over some open set $U subset X$, then we have
  $pi^(-1) (U) simeq ops.proj S(shf.e)(U) simeq ops.proj shf.o_X (U)[x_0, ... ,x_n] simeq sch.p_U^n.$
]

// Hartshorne II.7, Proposition 7.11
#proposition(number: 7.11)[
  Let $tildeOf(X)=sch.p (shf.e) arrow.r.long^(pi)X$ be a projective space bundle. Then
  + *(a).* If $ops.rank(shf.e, over: (shf.o_X)) >= 2$, there is a canonical isomorphism $shf.s arrow.r.long^(tilde.op) plus.o.big_(l in ZZ) pi_ast (shf.o_(tildeOf(X)) (l))$.
  + *(b).* There is a natural surjective morphism $pi^ast shf.e arrow.r.long^(phi) shf.o_Y (1)$.
]
#proof[
  (a) Say $ops.rank(shf.e, over: (shf.o_X))=r+1$. Cover $X$ with open affines $U=ops.spec A$ on which $shf.e|_U simeq shf.o_X|_U^( plus.o r)$. For each such $U$, write $S=A[x_0, ... ,x_r]$, then $pi^(-1) (U) simeq ops.proj S$, so that the isomorphism
  $S arrow.r.long^(tilde.op) Gamma_ast (shf.o_{pi^(-1) (U)})= plus.o.big_(l in ZZ) Gamma(pi^(-1) (U), shf.o_(tildeOf(X)) (l))= plus.o.big_(l in ZZ) Gamma(U, pi_ast shf.o_(tildeOf(X)) (l))$
  of graded $S$-algebras induces the isomorphism
  $shf.s|_U simeq S(shf.e|_U) simeq A[x_0, ... ,x_r]tilde.op arrow.r.long^(tilde.op) ( plus.o.big_(l in ZZ) Gamma(U, pi_ast shf.o_(tildeOf(X)) (l)))tilde.op simeq ( plus.o.big_(l in ZZ) pi_ast shf.o_(tildeOf(X)) (l)))|_U.$
  Thus, these glue to give an isomorphism $shf.s arrow.r.long^(tilde.op) plus.o.big_(l in ZZ) pi_ast (shf.o_(tildeOf(X)) (l))$.\

  (b) This is just the relative version of _(5.16.2)_, i.e. the twisting sheaf $shf.o (1)$ on $sch.p^n$ is globally generated by ${x_i}_(i=0)^n$.
]

// Hartshorne II.7, Proposition 7.12
#proposition(number: 7.12)[
  Let $tildeOf(X)=sch.p (shf.e) arrow.r.long^(pi)X$ be a projective space bundle. Then to give a morphism $Y arrow.r.long^(f) sch.p (shf.e)$, it is equivalent to give an invertible sheaf $shf.l in cat.mod(shf.o_Y)$ and a surjective morphism $g^ast shf.e arrow.r.long^(psi) shf.l$. _Note._ This is a local version of (7.1).
]
#proof[
  ($Rightarrow$) Given a morphism $Y arrow.r.long^(f) sch.p (shf.e)$. By _(7.11b)_, $exists$ surjective morphism $pi^ast shf.e arrow.r.long^(phi) shf.o_(tildeOf(X)) (1)$. Applying the exact functor $f^ast (-)$ to the morphism gives a surjective map
  $g^ast (shf.e)=f^ast pi^ast shf.e arrow.r.long^(f^ast phi)f^ast shf.o_(tildeOf(X)) (1).$
  Thus, we take $psi=f^ast phi$ and $shf.l=f^ast shf.o_(tildeOf(X)) (1) in cat.mod(shf.o_Y)$.\

  ($Leftarrow$) Given an invertible sheaf $shf.l in cat.mod(shf.o_Y)$ with a surjective morphism $g^ast shf.e arrow.r.long^(psi) shf.l$. I claim that there is a unique morphism $Y arrow.r.long^(f) sch.p (shf.e)=tildeOf(X)$ such that $shf.l simeq f^ast shf.o_(tildeOf(X)) (1)$, and that $psi$ is obtained by applying $f^ast$ to $psi$.
  - _Note._ This is in fact a local question on $X$, so taking an open affine cover ${U:shf.e|_U text("is free")}$ of $X$ reduces the statement to _(7.1)_.
  - If $X=ops.spec A$ and $shf.e simeq shf.o_X^( plus.o (n+1))$, then $tildeOf(X)=sch.p_A^n$. Now that $g^ast shf.e in cat.mod(shf.o_Y)$ is free and $psi$ is surjective, so $psi$ is uniquely determined by $n+1$ global sections generating $shf.l$, say $s_i in Gamma(Y, shf.l)$ ($0 <= i <= n$). From _(7.1)_, these sections ${s_i}_(i=0)^n$ uniquely determine a morphism $Y arrow.r.long^(f) sch.p_A^n=tildeOf(X)$ satisfying $shf.l simeq f^ast shf.o_(tildeOf(X)) (1)$ and $s_i=f^ast (x_i)$.
  - Further, there is a natural surjective morphism $pi^ast shf.e arrow.r.long^(phi) shf.o_Y (1)$ by _(7.11b)_. It follows that $f^ast phi$ is another surjective morphism $g^ast shf.e arrow.r.long^()f^ast shf.o_(tildeOf(X)) (1) simeq shf.l$ determined by the global sections ${s_i}_(i=0)^n$ generating $shf.l$. Thus, we have $psi=f^ast phi$ by _uniqueness_.
  - Finally, the uniqueness of such morphism $f$ follows from _(7.1)_.
]

// Hartshorne II.7, Definition D7
#definition(number: none, title: "Blowing Up")[
  Let $X$ be noetherian and $shf.i$ a coherent ideal sheaf. With the Rees
  algebra $RR(shf.i)=bigOPlus(shf.i^d, d>=0)$, the *blowing-up of $X$ along $shf.i$*
  is $tilde(X)=ops.proj RR(shf.i)$ with its projection $pi:tilde(X)->X$. Equivalently
  it is the blowing-up along the closed subscheme defined by $shf.i$.
]

// Hartshorne II.7, Definition D8
#definition(number: none, title: "Inverse Image Ideal Sheaf")[
  For $f:X->Y$ and an ideal sheaf $shf.i subset.eq shf.o_Y$, the inverse image
  ideal is the image of $f^*shf.i->shf.o_X$, equivalently the ideal generated by
  the image of $f^(-1)shf.i$; it is denoted $f^(-1)shf.i dot shf.o_X$.
]

// Hartshorne II.7, Proposition 7.13
#proposition(number: "7.13")[
  Let $pi:tilde(X)->X$ be the blowing-up of a coherent ideal $shf.i$ on a
  noetherian scheme, and let $Y$ be its closed subscheme.

  + $pi^(-1)shf.i dot shf.o_(tilde(X))$ is invertible.
  + Over $U=X-Y$, the map $pi^(-1) (U)->U$ is an isomorphism.
]


// Hartshorne II.7, Proposition 7.14
#proposition(number: "7.14", title: "Universal Property of Blowing Up")[
  If $f:Z->X$ makes $f^(-1)shf.i dot shf.o_Z$ invertible, there is a unique
  $g:Z->tilde(X)$ with $f=pi compose g$.
]


// Hartshorne II.7, Corollary 7.15
#corollary(number: "7.15")[
  If $f:Y->X$ is a morphism of noetherian schemes, blowing up an ideal $shf.i$
  on $X$ and its inverse image on $Y$ produces a unique compatible map of
  blowups $tilde(Y)->tilde(X)$. If $f$ is a closed immersion, so is this map.
]


// Hartshorne II.7, Definition D9
#definition(number: none, title: "Strict Transform")[
  In Corollary 7.15, when $Y subset.eq X$ is closed, the resulting closed
  subscheme $tilde(Y) subset.eq tilde(X)$ is the *strict transform* of $Y$.
]

// Hartshorne II.7, Proposition 7.16
#proposition(number: "7.16")[
  If $X$ is a variety and $0!=shf.i subset.eq shf.o_X$ is coherent, its blowup
  $tilde(X)$ is a variety; $pi$ is birational, proper, and surjective. If
  $X$ is quasi-projective, respectively projective, then so is $tilde(X)$,
  and $pi$ is projective.
]


// Hartshorne II.7, Theorem 7.17
#theorem(number: "7.17")[
  Let $X$ be quasi-projective over $k$. Every birational projective morphism
  $f:Z->X$ of varieties is isomorphic over $X$ to the blowing-up of a
  coherent ideal sheaf on $X$.
]


// Hartshorne II.7, Remark 7.17.1
#remark(title: "7.17.1")[
  The ideal sheaf producing a given projective birational morphism is not
  unique; replacing it by suitable powers or twists can give the same Proj.
]

// Hartshorne II.7, Remark 7.17.2
#remark(title: "7.17.2")[
  Arbitrary coherent ideals make blowing up extremely general. Geometric
  applications often restrict to smooth or normally flat centers; for smooth
  projective surfaces, birational maps factor into blowups and blowdowns of
  points.
]
