import Mathlib.RingTheory.Ideal.AssociatedPrime.Finiteness
import Mathlib.RingTheory.Ideal.AssociatedPrime.Localization
import Mathlib.RingTheory.Regular.RegularSequence
import Mathlib.RingTheory.PicardGroup
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.Tactic

/-!
AL2 verification companion.

The prose expressly assigns the pure algebra proofs to the reader. This file
checks the available associated-prime, localization, semilocal-triviality, and
regular-sequence interfaces, together with the two-element Koszul calculation
actually used in AL2-9–AL2-10. Mathlib's `IsAssociatedPrime` initially uses a radical
annihilator, unlike Hartshorne's annihilator definition. `associated_iff` below
supplies the Noetherian comparison and checks the nonzero witness.

Remaining coverage, not claimed as kernel-checked here: the normal-form ring
presentations in AL2-4, the polynomial associated-graded isomorphism in AL2-8,
general Koszul exactness, the depth/CM/Serre theorems quoted from II.8, and the
coordinate-ring dimension, regularity, and normality calculations in AL2-13.
AL2-12's regular-quotient theorem is also a reader algebra exercise: for a
Noetherian regular local A with A/I regular local, I is generated by a subset
of a regular system of parameters. Neither that generator theorem nor its
codimension formula is asserted as checked here.
The cone/cusp scheme conclusions depend on precisely those reader algebra
exercises and on the affine correspondence; a scheme-level normality theorem
for these two presentations is not encoded in this file.
-/

noncomputable section
namespace Supplements.AL2

open Submodule

/-- Hartshorne's associated-prime definition, including its nonzero witness. -/
def Associated {A M : Type*} [CommRing A] [AddCommGroup M] [Module A M]
    (p : Ideal A) : Prop :=
  p.IsPrime ∧ ∃ m : M, m ≠ 0 ∧ p = (⊥ : Submodule A M).colon {m}

theorem associated_iff {A M : Type*} [CommRing A] [AddCommGroup M]
    [Module A M] [IsNoetherianRing A] (p : Ideal A) :
    Associated (M := M) p ↔ IsAssociatedPrime p M := by
  rw [Associated, isAssociatedPrime_iff]
  constructor
  · rintro ⟨hp, m, _, hm⟩
    exact ⟨hp, m, hm⟩
  · rintro ⟨hp, m, hm⟩
    refine ⟨hp, m, ?_, hm⟩
    intro h
    subst m
    apply hp.ne_top
    rw [hm]
    ext a
    simp [Submodule.mem_colon_singleton]

/-- AL2-1: finite associated-prime set under the actual finiteness hypotheses. -/
theorem associated_finite (A M : Type*) [CommRing A] [IsNoetherianRing A]
    [AddCommGroup M] [Module A M] [Module.Finite A M] :
    (associatedPrimes A M).Finite := associatedPrimes.finite A M

/-- AL2-1: zero divisors on a module, without confusing them with ring zero divisors. -/
theorem associated_zero_divisors (A M : Type*) [CommRing A] [IsNoetherianRing A]
    [AddCommGroup M] [Module A M] :
    (⋃ p ∈ associatedPrimes A M, (p : Set A)) =
      {a : A | ∃ m : M, m ≠ 0 ∧ a • m = 0} :=
  biUnion_associatedPrimes_eq_zero_divisors A M

abbrev associatedNonempty := @associatedPrimes.nonempty

abbrev associatedLocalization :=
  @Module.associatedPrimes.preimage_comap_associatedPrimes_eq_associatedPrimes_of_isLocalizedModule

abbrev associatedMinimal :=
  @Module.associatedPrimes.minimalPrimes_annihilator_subset_associatedPrimes

/-- AL2-5: total fractions invert regular elements, also for non-domains. -/
theorem total_quotient_injective (A Q : Type*) [CommRing A] [CommRing Q]
    [Algebra A Q] [IsFractionRing A Q] :
    Function.Injective (algebraMap A Q) := IsFractionRing.injective A Q

/-- AL2-5: an invertible module over a semilocal ring is free of rank one. -/
theorem semilocal_frame (A P : Type*) [CommRing A]
    [Finite (MaximalSpectrum A)] [AddCommGroup P] [Module A P]
    [Module.Invertible A P] : Nonempty (P ≃ₗ[A] A) :=
  Module.Invertible.free_iff_linearEquiv.mp inferInstance

abbrev regularCons := @RingTheory.Sequence.isRegular_cons_iff

abbrev regularPermutation := @IsLocalRing.isRegular_of_perm

abbrev regularFlatTensor := @RingTheory.Sequence.IsWeaklyRegular.isWeaklyRegular_lTensor

section TwoEquations
variable {A : Type*} [CommRing A]

/-- The first two Koszul differentials with the sign convention of AL2-10. -/
def koszulOne (a b : A) : A × A →ₗ[A] A where
  toFun p := a * p.1 + b * p.2
  map_add' := by intros; simp only [Prod.fst_add, Prod.snd_add]; ring
  map_smul' := by intros; simp only [Prod.smul_fst, Prod.smul_snd, smul_eq_mul, RingHom.id_apply]; ring

def koszulTwo (a b : A) : A →ₗ[A] A × A where
  toFun c := (-b * c, a * c)
  map_add' := by intros; ext <;> simp [mul_add]
  map_smul' := by intros; ext <;> simp [smul_eq_mul, mul_comm, mul_left_comm]

theorem koszul_composite (a b : A) :
    (koszulOne a b).comp (koszulTwo a b) = 0 := by
  apply LinearMap.ext
  intro c
  change a * (-b * c) + b * (a * c) = 0
  ring

/-- Injectivity of the left Koszul differential uses the first regular element. -/
theorem koszul_two_injective {a b : A} (ha : Function.Injective (a * ·)) :
    Function.Injective (koszulTwo a b) := by
  intro c d h
  exact ha (congrArg Prod.snd h)

/--
AL2-9–AL2-10: all relations of a regular pair are the displayed Koszul relations.
`hb` is exactly regularity of b on A/(a), expressed by membership in (a).
The next theorem gives the bridge from the ordinary quotient-module predicate.
-/
theorem koszul_pair_exact {a b : A} (ha : Function.Injective (a * ·))
    (hb : ∀ y : A, a ∣ b * y → a ∣ y) :
    Function.Exact (koszulTwo a b) (koszulOne a b) := by
  intro p
  constructor
  · intro hp
    change a * p.1 + b * p.2 = 0 at hp
    have hy : a ∣ b * p.2 := ⟨-p.1, by linear_combination hp⟩
    obtain ⟨c, hc⟩ := hb p.2 hy
    refine ⟨c, ?_⟩
    apply Prod.ext
    · apply ha
      change a * (-b * c) = a * p.1
      linear_combination -hp + b * hc
    · exact hc.symm
  · rintro ⟨c, rfl⟩
    change a * (-b * c) + b * (a * c) = 0
    ring

/-- Quotient regularity gives the divisibility hypothesis used above. -/
theorem quotient_regular_divisibility {a b : A}
    (hb : IsSMulRegular (A ⧸ Ideal.span {a}) b) :
    ∀ y : A, a ∣ b * y → a ∣ y := by
  intro y hy
  have hby : (Ideal.Quotient.mk (Ideal.span {a})) (b * y) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton.mpr hy)
  have heq : b • ((Ideal.Quotient.mk (Ideal.span {a})) y) = b • (0 : A ⧸ Ideal.span {a}) := by
    simpa [Algebra.smul_def] using hby
  have hyzero := hb heq
  exact Ideal.mem_span_singleton.mp (Ideal.Quotient.eq_zero_iff_mem.mp hyzero)

/-- The actual relation behind the nonregular pair (x²,xy) in AL2-10. -/
theorem nonregular_pair_relation (x y : A) : y * x ^ 2 - x * (x * y) = 0 := by
  ring

end TwoEquations
end Supplements.AL2
