import Mathlib.RingTheory.Support
import Mathlib.RingTheory.Finiteness.Ideal
import Mathlib.RingTheory.Localization.Finiteness
import Mathlib.Algebra.Module.LocalizedModule.Int
import Mathlib.RingTheory.Spectrum.Prime.FreeLocus
import Mathlib.RingTheory.Nilpotent.Lemmas
import Mathlib.RingTheory.PicardGroup
import Mathlib.Topology.Sheaves.AddCommGrpCat
import Mathlib.Topology.Sheaves.SheafCondition.UniqueGluing
import Mathlib.LinearAlgebra.TensorProduct.RightExactness
import Mathlib.Tactic

/-!
SE. `Module.support` is defined by nonzero prime localizations, precisely the
stalk support of the associated sheaf. Hartshorne coherence is used only over
Noetherian rings/schemes; no coherence convention is changed here.
SE-1/3/4 use the topological zero-neighborhood criterion, kernel computation,
and stalk exactness below. No global extension-by-zero functor is constructed.
SE-7 checks radical containment versus an ideal power and clearing finitely
many denominators; the identification with the sheaf kernel is by the affine
basis in the prose. SE-8's finite numerators, finite sum and local span
interfaces check the affine enlargement; gluing that enlargement with the
original coherent subsheaf and the finite induction over X are not packaged
as a theorem of coherent sheaves. SE-11 uses residue fiber rank, not fraction
field rank: `fiberRankFormula` records the comparison. Its critical reduced
kernel argument is proved below. The assembly of these local surjections into openness of the fiber-rank
loci and the full sheaf equivalence remain interface assembly gaps.
SE-12's existing proof is covered by ii-5-exe.lean and module-algebra.lean.
-/
open TopologicalSpace AlgebraicGeometry
noncomputable section
namespace Supplements.SE

abbrev supportLocalization := @Module.mem_support_iff
abbrev supportZeroCriterion := @Module.notMem_support_iff'
abbrev finiteSupportAnnihilator := @Module.support_eq_zeroLocus
abbrev cyclicSupport := @Module.support_quotient
abbrev supportPower := @Ideal.exists_pow_le_of_le_radical_of_fg
abbrev localizationZero := @IsLocalizedModule.eq_zero_iff
abbrev clearFiniteDenominators := @IsLocalizedModule.exist_integer_multiples_of_finite
abbrev unitRescalingSpan := @Submodule.span_smul_eq_of_isUnit
abbrev numeratorFormula := @IsLocalizedModule.map_integerMultiple
abbrev numeratorSpan := @IsLocalizedModule.smul_mem_finsetIntegerMultiple_span
abbrev localizedSpan := @Submodule.localized'_span
abbrev finiteSum := @Submodule.fg_iSup
abbrev finiteLocalizedSubmodule := @Submodule.localized'_fg
abbrev affineFiniteCover := @Module.Finite.of_localizationSpan_finite
abbrev freeNeighborhoodSameRank := @Module.FinitePresentation.exists_free_localizedModule_powers
abbrev fiberRankFormula := @Module.rankAtStalk_eq_finrank_tensorProduct
abbrev freeRankLocallyConstant := @Module.isLocallyConstant_rankAtStalk_freeLocus
abbrev spreadSurjection := @Module.exists_localizedMap_away_surjective_of_localizedMap_atPrime_surjective
abbrev fiberDimensionBound := @LinearMap.finrank_le_finrank_of_surjective
abbrev tensorSurjection := @TensorProduct.map_surjective
abbrev nakayama := @Submodule.eq_bot_of_le_smul_of_le_jacobson_bot
abbrev tensorFiberRank := @Module.rankAtStalk_tensorProduct
abbrev stalkExactness := @TopCat.Sheaf.exact_iff_stalkFunctor_map_exact
abbrev gluing := @TopCat.Sheaf.existsUnique_gluing'

/-- SE-1: the zero-germ neighborhood property implies closed section support. -/
theorem closed_support_of_local_zero {X : Type*} [TopologicalSpace X]
    (Z : Set X) (h : ∀ x ∈ Z, ∃ U : Set X, IsOpen U ∧ x ∈ U ∧ U ⊆ Z) :
    IsClosed Zᶜ := by
  apply IsOpen.isClosed_compl
  rw [isOpen_iff_mem_nhds]
  intro x hx
  obtain ⟨U, hU, hxU, hUZ⟩ := h x hx
  exact Filter.mem_of_superset (hU.mem_nhds hxU) hUZ

/-- SE-3: the support submodule is exactly the kernel of restriction. -/
theorem restriction_kernel {R M N : Type*} [Ring R] [AddCommGroup M]
    [AddCommGroup N] [Module R M] [Module R N]
    (res : M →ₗ[R] N) (m : M) : m ∈ res.ker ↔ res m = 0 := Iff.rfl

/-- SE-8: finitely many finite lists of numerator generators lie in one finite submodule. -/
theorem finite_enlargement {R M : Type*} [Ring R] [AddCommGroup M] [Module R M]
    {ι : Type*} [Finite ι] (K : ι → Submodule R M) (hK : ∀ i, (K i).FG) :
    ∃ N : Submodule R M, N.FG ∧ ∀ i, K i ≤ N := by
  exact ⟨⨆ i, K i, Submodule.fg_iSup K hK, fun i => le_iSup K i⟩

/-- SE-8's affine enlargement: a finite localized module is generated by
one finite submodule of the original module. No finiteness of M is assumed. -/
theorem finite_submodule_spans_localization {R A M L : Type*}
    [CommRing R] [CommRing A] [Algebra R A]
    [AddCommGroup M] [Module R M] [AddCommGroup L]
    [Module R L] [Module A L] [IsScalarTower R A L]
    (S : Submonoid R) [IsLocalization S A] (f : M →ₗ[R] L)
    [IsLocalizedModule S f] [Module.Finite A L] :
    ∃ N : Submodule R M, N.FG ∧ N.localized' A S f = ⊤ := by
  classical
  obtain ⟨t, ht⟩ := (inferInstance : Module.Finite A L).1
  let T := IsLocalizedModule.finsetIntegerMultiple S f t
  refine ⟨Submodule.span R (T : Set M), Submodule.fg_span T.finite_toSet, ?_⟩
  rw [Submodule.localized'_span]
  apply top_unique
  rw [← ht]
  apply Submodule.span_le.mpr
  intro x hx
  let m := IsLocalizedModule.integerMultiple S f t id ⟨x, hx⟩
  have hm : m ∈ T := by
    exact Finset.mem_image.mpr ⟨⟨x, hx⟩, Finset.mem_attach _ _, rfl⟩
  have hfm : f m ∈ Submodule.span A (f '' (T : Set M)) :=
    Submodule.subset_span ⟨m, hm, rfl⟩
  rw [IsLocalizedModule.map_integerMultiple] at hfm
  apply (Submodule.smul_mem_iff_of_isUnit
    (Submodule.span A (f '' (T : Set M)))
    (IsLocalization.map_units A (IsLocalizedModule.commonDenom S f t id))).mp
  simpa only [algebraMap_smul, Submonoid.smul_def, id_eq] using hfm

/-- SE-9's affine terminal assertion: every element is in a finite submodule. -/
theorem finite_submodule_contains {R M : Type*} [Ring R] [AddCommGroup M]
    [Module R M] (m : M) : ∃ N : Submodule R M, N.FG ∧ m ∈ N := by
  exact ⟨Submodule.span R {m}, Submodule.fg_span_singleton m,
    Submodule.subset_span (Set.mem_singleton m)⟩

/-- SE-11: a relation vector zero in every residue field is zero over a reduced ring. -/
theorem reduced_relation_zero {R : Type*} [CommRing R] [_root_.IsReduced R]
    {ι : Type*} (v : ι → R) (h : ∀ (p : Ideal R), p.IsPrime → ∀ i, v i ∈ p) : v = 0 := by
  funext i
  exact (nilpotent_iff_mem_prime.mpr (fun p hp => h p hp i)).eq_zero

/-- SE-11: applying that coordinate calculation to every kernel vector proves injectivity. -/
theorem reduced_presentation_injective {R M : Type*} [CommRing R] [_root_.IsReduced R]
    [AddCommGroup M] [Module R M] {ι : Type*} (f : (ι → R) →ₗ[R] M)
    (h : ∀ v ∈ f.ker, ∀ (p : Ideal R), p.IsPrime → ∀ i, v i ∈ p) :
    Function.Injective f := by
  apply LinearMap.ker_eq_bot.mp
  apply le_antisymm _ bot_le
  intro v hv
  exact reduced_relation_zero v (h v hv)
end Supplements.SE

/- SE-10 now includes the free-stalk equivalence of II.5.7(a,b); SE-12
contains II.5.7(c). The repeated basis-spreading and tensor-inverse algebra
are cited from AL-10/9 rather than reproved in an application. ii-5-exe.lean
checks the free locus and tensor inverse; the existing local/global interface
boundary is unchanged by this consolidation. -/

/- Reader-check annotations now identify the terminal algebraic/topological
inputs in the prose. The mathematical reductions and the verification coverage
of the declarations in this companion are unchanged. -/
