#import "@preview/theorion:0.4.0": *
#show: show-theorion
#import "../defs.typ": *

=== Exercises

// Hartshorne II.8, Exercise 8.1
#metadata(none) <exercise-ii-8-1>
#exercise(title: "Exercise 8.1")[
  Strengthen the differential criteria to arbitrary points.

  + If $(B,idl.m)$ contains $k$ and $k(B)\/k$ is separably generated, prove that
    $0 -> idl.m\/idl.m^2 -> Omega_(B\/k) times.o k(B) -> Omega_(k(B)\/k) -> 0$ is exact.
  + If moreover $k$ is perfect and $B$ is a localization of a finite-type
    $k$-algebra, show that $B$ is regular iff $Omega_(B\/k)$ is free of rank
    $dim B+ops.trdeg_k k(B)$.
  + For irreducible finite-type $X\/k$, with $k$ perfect and $dim X=n$, show
    that $shf.o_(X,x)$ is regular iff $Omega_(X\/k),x$ is free of rank $n$.
  + Deduce that the regular locus of a variety over an algebraically closed
    field is open dense.
]

See #book-link(<sup-df-3>)[DF-3] (residue-field sequence and separable closed-point case); for relative smoothness, see #book-link(<sup-lp2-3>)[LP2-3].

// Hartshorne II.8, Exercise 8.2
#exercise(title: "Exercise 8.2")[
  Let $X$ be an $n$-dimensional variety and $shf.e$ locally free of rank greater
  than $n$, generated by a subspace $V subset.eq Gamma(X, shf.e)$. Show that some
  $s in V$ is nowhere in $idl.m_x shf.e_x$. Deduce an exact sequence
  $0 -> shf.o_X -> shf.e -> shf.e' -> 0$ with $shf.e'$ locally free.
]

// Hartshorne II.8, Exercise 8.3
#exercise(title: "Exercise 8.3 (Product Schemes)")[
  + For $X,Y$ over $S$, prove
    $Omega_((X times_S Y)\/S) simeq p_1^*Omega_(X\/S) plus.o p_2^*Omega_(Y\/S)$.
  + If $X,Y$ are nonsingular over $k$, deduce
    $omega_(X times Y) simeq p_1^*omega_X times.o p_2^*omega_Y$.
  + For a nonsingular plane cubic $Y$ and $X=Y times Y$, show that
    $p_g (X)=1$ but $p_a (X)=-1$.
]

// Hartshorne II.8, Exercise 8.4
#metadata(none) <exercise-ii-8-4>
#exercise(title: "Exercise 8.4 (Complete Intersections in Projective Space)")[
  Let $Y subset.eq sch.p^n$ have codimension $r$.

  + Show that $Y$ is a complete intersection iff it is the scheme-theoretic
    intersection of $r$ hypersurfaces.
  + If $dim Y>=1$, $Y$ is normal, and $Y$ is a complete intersection, prove
    that it is projectively normal; deduce surjectivity of
    $Gamma(sch.p^n, shf.o (l))->Gamma(Y, shf.o_Y (l))$ for $l>=0$ and connectedness of $Y$.
  + Given $d_1,dots.c,d_r>=1$, $r<n$, use Bertini to construct a nonsingular
    irreducible complete intersection of those degrees.
  + For such $Y$, show $omega_Y simeq shf.o_Y (sum_i d_i-n-1)$.
  + Derive the geometric-genus formulas for a degree-$d$ hypersurface and for
    a curve in $sch.p^3$ cut out by surfaces of degrees $d,e$.
]

For (d), see #book-link(<sup-df-13>)[DF-13]; for the plane-curve case, see #book-link(<sup-df-14>)[DF-14].

// Hartshorne II.8, Exercise 8.5
#metadata(none) <exercise-ii-8-5>
#exercise(title: "Exercise 8.5 (Blowing Up a Nonsingular Subvariety)")[
  In Theorem 8.24 assume $ops.codim(Y, X)=r>=2$.

  + Prove $ops.pic tilde(X) simeq ops.pic X plus.o ZZ$, where the factors map by
    $pi^*$ and $n mapsto shf.o_(tilde(X)) (n Y')$.
  + Prove $omega_(tilde(X)) simeq pi^*omega_X times.o shf.o_((r-1) Y')$.
]

For the exceptional divisor and its normal bundle, see #book-link(<sup-bu-8>)[BU-8].

// Hartshorne II.8, Exercise 8.6
#metadata(none) <exercise-ii-8-6>
#exercise(title: "Exercise 8.6 (Infinitesimal Lifting)")[
  Let $A$ be a finite-type $k$-algebra with $ops.spec A$ nonsingular, let
  $0->shf.i->B'->B->0$ have $shf.i^2=0$, and let $f:A->B$.

  + Show that two lifts differ by an element of
    $ops.hom(Omega_(A\/k), shf.i, over: A)$ and conversely.
  + Present $A=P\/J$ with $P$ polynomial, lift $P->B$ to $P->B'$, and obtain
    an $A$-linear map $J\/J^2->shf.i$.
  + Use the conormal exact sequence and its dual to alter the lift so that it
    kills $J$, proving that $f$ lifts to $A->B'$.
]

See #book-link(<sup-lp2-2>)[LP2-2] and #book-link(<sup-lp2-3>)[LP2-3] (lifting criteria; algebraic proofs left to the reader).

// Hartshorne II.8, Exercise 8.7
#exercise(title: "Exercise 8.7")[
  An infinitesimal extension of $X$ by a coherent $shf.f$ is a square-zero
  thickening with ideal $shf.f$. The trivial one has
  $shf.o_(X')=shf.o_X plus.o shf.f$ and
  $(a,f)(a',f')=(a a',a f'+a' f)$. Show that if $X$ is affine and nonsingular,
  every infinitesimal extension by $shf.f$ is isomorphic to the trivial one.
]

// Hartshorne II.8, Exercise 8.8
#exercise(title: "Exercise 8.8")[
  For a nonsingular projective variety define
  $P_n=dim_k Gamma(X, omega_X^n)$ and
  $h^(q,0)=dim_k Gamma(X, ops.wedge^q Omega_(X\/k))$. Generalize the proof of 8.19
  to show that all plurigenera $P_n$ and Hodge numbers $h^(q,0)$ are
  birational invariants.
]
