#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Some Local Algebra

// Hartshorne II.8, Theorem 8.21A
#theorem(number: "8.21A")[
  Let $(A,idl.m)$ be a noetherian local ring.

  + Every regular local ring is Cohen–Macaulay.
  + A localization of a Cohen–Macaulay ring is Cohen–Macaulay.
  + If $A$ is Cohen–Macaulay, then $x_1,dots.c,x_r in idl.m$ is an $A$-regular
    sequence iff $dim A\/(x_1,dots.c,x_r)=dim A-r$.
  + The quotient of a Cohen–Macaulay ring by a regular sequence is
    Cohen–Macaulay.
  + If $shf.i=(x_1,dots.c,x_r)$ is generated by such a sequence, then
    $(A\/shf.i)[t_1,dots.c,t_r] -> ops.gr_shf.i A$ is an isomorphism. Equivalently,
    $shf.i\/shf.i^2$ is free of rank $r$ and $S^n (shf.i\/shf.i^2) simeq shf.i^n\/shf.i^(n+1)$.
]


// Hartshorne II.8, Theorem 8.22A
#theorem(number: "8.22A", title: "Serre's Criterion for Normality")[
  A noetherian ring $A$ is normal iff:

  + $A_idl.p$ is regular for every prime $idl.p$ of height at most one; and
  + $ops.depth A_idl.p >= 2$ for every prime $idl.p$ of height at least two.
]


// Hartshorne II.8, Definition D7
#definition(number: none, title: "Local Complete Intersections")[
  A closed subscheme $Y$ of a nonsingular variety $X$ is a *local complete
  intersection* in $X$ if its ideal sheaf can locally be generated by
  $ops.codim(Y, X)$ elements at every point.
]

// Hartshorne II.8, Remark 8.22.2
#remark(title: "8.22.2")[
  Being a local complete intersection is intrinsic to $Y$, independent of
  the nonsingular ambient variety. A proof uses the cotangent complex; this
  fact is not needed below.
]

// Hartshorne II.8, Proposition 8.23
#proposition(number: "8.23")[
  Let $Y$ be a local complete intersection subscheme of a nonsingular variety
  over $k$. Then $Y$ is Cohen–Macaulay, and $Y$ is normal iff it is regular in
  codimension one.
]


// Hartshorne II.8, Theorem 8.24
#theorem(number: "8.24")[
  Let $X$ be nonsingular, $Y subset.eq X$ a nonsingular closed subvariety with
  ideal $shf.i$, and $pi:tilde(X)->X$ its blowup. Let $Y'$ be defined by
  $shf.i'=pi^(-1)shf.i dot shf.o_(tilde(X))$. Then:

  + $tilde(X)$ is nonsingular;
  + $Y'->Y$ is naturally $sch.p (shf.i\/shf.i^2)$; and
  + under this isomorphism, $shf.n_(Y'\/tilde(X)) simeq shf.o_(sch.p (shf.i\/shf.i^2)) (-1)$.
]


// Hartshorne II.8, Theorem 8.25A
#theorem(number: "8.25A", title: "Cohen Structure Theorem")[
  Let $A$ be a complete local ring containing a field $k$. If its residue
  field $k(A)$ is separably generated over $k$, then $A$ contains a subfield
  $K supset.eq k$ mapping isomorphically onto $A\/idl.m$; $K$ is a field of
  representatives.
]
