#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#import "../defs.typ": *

#show: show-theorion

=== Exercises

// Hartshorne II.9, Exercise 9.1
#exercise(title: "Exercise 9.1 (Formal-Regular Functions)")[
  Let $Y subset.eq sch.p_k^n$ be connected, nonsingular, and positive-dimensional,
  and let $hat(X)$ be the completion of $sch.p^n$ along $Y$, with ideal $shf.j$.

  + Use 8.13 and 8.17 to embed $shf.j\/shf.j^2$ in $shf.o_Y (-1)^(plus.o(n+1))$.
  + Show $Gamma(Y, shf.j^r\/shf.j^(r+1))=0$ for $r>=1$.
  + From the successive exact sequences prove
    $Gamma(Y, shf.o_X\/shf.j^r)=k$ for every $r$.
  + Conclude $Gamma(hat(X), hat(shf.o)_X)=k$.
]

// Hartshorne II.9, Exercise 9.2
#exercise(title: "Exercise 9.2")[
  Under the hypotheses of Exercise 9.1, let $f:sch.p^n->Z$ be a morphism of
  $k$-varieties. If $f(Y)$ is one closed point $P$, use formal-regular
  functions to prove that $f(sch.p^n)=P$.
]

// Hartshorne II.9, Exercise 9.3
#exercise(title: "Exercise 9.3")[
  Prove the affine-formal analogue of 5.6: if
  $0->shf.f'->shf.f->shf.f''->0$ is exact on an affine formal scheme and $shf.f'$ is
  coherent, then its sequence of global sections is exact. Reduce modulo
  powers of an ideal of definition, apply the affine-scheme result, and pass
  to the inverse limit using 9.1, 9.2, and 9.6.
]

// Hartshorne II.9, Exercise 9.4
#exercise(title: "Exercise 9.4")[
  Use Exercise 9.3 to show that an extension of coherent sheaves on a
  noetherian formal scheme is coherent.
]

// Hartshorne II.9, Exercise 9.5
#exercise(title: "Exercise 9.5")[
  If a coherent sheaf on a noetherian formal scheme is generated by global
  sections, prove that finitely many of those sections suffice.
]

// Hartshorne II.9, Exercise 9.6
#exercise(title: "Exercise 9.6")[
  Let $shf.j$ be an ideal of definition and
  $Y_n=(hat(X),shf.o_(hat(X))\/shf.j^n)$. Assuming
  $(Gamma(Y_n, shf.o_(Y_n)))$ satisfies Mittag–Leffler, prove
  $ops.pic hat(X) simeq ops.lim ops.pic Y_n$.

  + Prove the units also satisfy Mittag–Leffler.
  + Compatible trivializations modulo $shf.j^n$ prove injectivity.
  + Construct compatible transition maps for a system of invertible sheaves,
    take its coherent inverse limit, and prove it is locally free of rank one.
  + Verify the hypothesis when $hat(X)$ is affine or every $Y_n$ is projective
    over a field.
]
