// ==============================
// Custom Math Definitions
// ==============================

#import "@preview/theorion:0.4.0": note-box
#import "ops.typ"
#import "cat.typ"
#import "sym.typ"

// block
#let notation(body) = note-box(title: "Notation", body)

// ideal generated by `x`
#let ideal(x) = $lr(chevron.l #x chevron.r)$
// wide tilde of `x`
#let tildeOf(x) = $accent(#x, tilde.op)$
// tensor product of `x` and `y` over `base`
#let tensor(x, y, base) = $#x times.o_#base #y$
// fiber product of `x` and `y` over `base`
#let fiber(x, y, base: "") = $#x times_#base #y$
// a morphism named `top` under category `bottom`
#let morph(top, bottom) = $stretch(->, size: #150%)_#bottom^#top$
#let inclusion(top, bottom) = $stretch(arrow.r.hook, size: #150%)_#bottom^#top$
// direct sum of `val` under index set from `bottom` to `top`
#let bigOPlus(val, bottom, top: none) = $attach(plus.o.big, tr: #top, br: #bottom) #val$
// coproduct of `val` under index set from `bottom` to `top`
#let coprod(val, bottom, top: none) = $attach(product.co, tr: #top, br: #bottom) #val$

// --- symbols ---
#let simeq = $tilde.equiv$
#let eqBy(x) = $attach(=, b: #x)$
#let isoBy(x) = $attach(tilde.equiv, b: #x)$
#let to = $arrow.r.long$
#let Leftarrow = $arrow.l.double$
#let Rightarrow = $arrow.r.double$

// --- math operators ---
#let ops = ops

// --- math symbols ---
#let cat = cat
#let idl = sym.idl
#let sch = sym.sch
#let shf = sym.shf

#let Af = $frak("A")$
#let Bf = $frak("B")$

#let red = $op("red")$
#let reg = $op("reg")$

#let isoto = $arrow.r.tilde$
#let isolongto = $arrow.r.tilde$
#let spn = $"-span"$

#let fg(x) = $frak("f.g.")#x$
#let vect = $"vect-"$
