// ==============================
// Custom Math Definitions
// ==============================

// ideal generated by `x`
#let ideal(x) = $lr(chevron.l #x chevron.r)$
// wide tilde of `x`
#let tildeOf(x) = $accent(#x, tilde.op)$
// tensor product of `x` and `y` over `base`
#let tensor(x, y, base) = $#x times.o_#base #y$
// a morphism named `top` under category `bottom`
#let morph(top, bottom) = $stretch(->, size: #150%)_#bottom^#top$
#let inclusion(top, bottom) = $stretch(arrow.r.hook, size: #150%)_#bottom^#top$
// direct sum of `val` under index set from `bottom` to `top`
#let bigOPlus(val, bottom, top: none) = $attach(plus.o.big, tr: #top, br: #bottom) #val$
// coproduct of `val` under index set from `bottom` to `top`
#let coprod(val, bottom, top: none) = $attach(product.co, tr: #top, br: #bottom) #val$

// --- symbols ---
#let simeq = $tilde.equiv$
#let eqBy(x) = $attach(=, b: #x)$
#let isoBy(x) = $attach(tilde.equiv, b: #x)$
#let to = $arrow.r.long$
#let Leftarrow = $arrow.l.double$
#let Rightarrow = $arrow.r.double$

// --- math operators ---
#let E = $op("E")$
#let Ann = $op("Ann")$
#let Ass = $op("Ass")$
#let Supp = $op("Supp")$
#let WeakAss = $op("~Ass")$
#let Im = $op("Im")$
#let Spec = $op("Spec")$
#let SPEC = $op("Spec")$
#let Sp = $op("sp")$
#let maxSpec = $op("mSpec")$
#let Hom(from, to, over) = $op("Hom")_#over paren.l #from, #to paren.r$
#let Soc = $op("Soc")$
#let Ht = $op("ht")$
#let AA = $bb("A")$
#let V = $op("V")$
#let Aut = $op("Aut")$
#let Char = $op("char")$
#let Frac = $op("Frac")$
#let Proj = $op("Proj")$
#let PROJ = $op("Proj")$
#let stimes = $op("ⓢ")$
#let End = $op("End")$
#let Ker = $op("Ker")$
#let Coker = $op("coker")$
#let LCM = $op("LCM")$
#let CDiv = $op("CDiv")$
#let Div = $op("Div")$
#let Pic = $op("Pic")$
#let id = $op("id")$
#let Cl = $op("Cl")$
#let CaCl = $op("CaCl")$
#let dv = $op("div")$
#let Der = $op("Der")$
#let Gal = $op("Gal")$
#let nil = $op("nil")$
#let pr = $op("pr")$
#let trdeg = $op("trdeg")$
#let rank = $op("rank")$
#let cd = $op("cd")$
#let codim = $op("codim")$
#let sgn = $op("sgn")$
#let Ob = $op("Ob")$
#let GL = $op("GL")$

// --- calligraphic / script letters ---
#let scr(it) = text(features: ("ss01",), box($cal(it)$))

#let EE = $scr("E")$
#let FF = $scr("F")$
#let GG = $scr("G")$
#let HH = $scr("H")$
#let II = $scr("I")$
#let JJ = $scr("J")$
#let KK = $scr("K")$
#let LL = $scr("L")$
#let MM = $scr("M")$
#let NN = $cal("N")$
#let OO = $cal("O")$
#let Ss = $scr("S")$
#let TT = $cal("T")$
#let Af = $frak("A")$
#let Bf = $frak("B")$
#let Aa = $scr("A")$
#let PP = $bb("P")$

#let aa = $frak("a")$
#let bb = $frak("b")$
#let dd = $frak("d")$
#let pp = $frak("p")$
#let qq = $frak("q")$
#let nn = $frak("n")$
#let mm = $frak("m")$

#let red = $op("red")$
#let reg = $op("reg")$
#let Shf = $frak("Shf")$
#let Psh = $frak("Psh")$
#let LRS = $frak("LRS")$
#let Sch = $frak("Sch")$
#let Var = $frak("Var")$
#let Ab = $frak("Ab")$
#let Ring = $frak("Ring")$
#let Top = $frak("Top")$

#let In = $op("in")$
#let Ext = $op("Ext")$
#let Spe = $op("Spé")$
#let HHom = $scr("Hom")$
#let isoto = $arrow.r.tilde$
#let isolongto = $arrow.r.tilde$
#let spn = $"-span"$

#let GR = $frak("Gr")$
#let fg(x) = $frak("f.g.")#x$
#let MOD(x) = {
  if x == "" [
    $frak("Mod")$
  ] else [
    $frak("Mod")_#x$
  ]
}
#let qcoh = $frak("Qch")$
#let ALG = $frak("Alg")$
#let coh = $frak("Coh")$
#let vect = $"vect-"$
