// ==============================
// Custom Math Definitions
// ==============================

#import "@preview/theorion:0.4.0": note-box
#import "ops.typ"
#import "cat.typ"
#import "sym.typ"

// Keep cross-references clickable when their targets are included.
// Standalone previews display the text when the target is absent.
#let book-link(target, body) = context {
  if query(target).len() > 0 {
    link(target, body)
  } else {
    body
  }
}

// block
#let notation(body) = note-box(title: "Notation", body)
#let exercise(title: "Exercise", body) = block(
  width: 100%,
  inset: 1em,
  radius: .4em,
  fill: rgb("#f7eed8"),
)[
  #strong(title) #body
]
#let example(number: none, title: "", body) = block(
  width: 100%,
  inset: 1em,
  radius: .4em,
  fill: rgb("#b5e7f4"),
)[
  #let t = {
    let heading = "Example" + if number == none { "" } else { " " + str(number) }
    if title != "" {
      heading + " (" + title + ")."
    } else { heading + "." }
  }
  #strong(t) #body
]

// Preserve the remark styling while allowing an explicit reference number.
#let remark(number: none, title: "", body) = {
  let heading = if number == none {
    if title == "" { "Remark" } else { title }
  } else {
    "Remark " + str(number) + if title == "" { "" } else { " (" + title + ")" }
  }
  note-box(fill: rgb("#118D8D"), title: heading, icon-name: "comment", body)
}

// ideal generated by `x`
#let ideal(x) = $lr(chevron.l #x chevron.r)$
// wide tilde of `x`
#let tildeOf(x) = $accent(#x, tilde.op)$
// Pure tensor `tensor(x, y)`, or tensor product over a base via
// `tensor(x, y, over: base)`.
#let tensor(x, y, over: "") = $#x times.o_#over #y$
// fiber product of `x` and `y` over `base`
#let fiber(x, y, base: "") = $#x times_#base #y$
// a morphism named `top` under category `bottom`
#let morph(top, bottom) = $stretch(->, size: #150%)_#bottom^#top$
#let inclusion(top, bottom) = $stretch(arrow.r.hook, size: #150%)_#bottom^#top$
// direct sum of `val` under index set from `bottom` to `top`
#let bigOPlus(val, bottom, top: none) = $attach(plus.o.big, tr: #top, br: #bottom) #val$
// coproduct of `val` under index set from `bottom` to `top`
#let coprod(val, bottom, top: none) = $attach(product.co, tr: #top, br: #bottom) #val$

// --- symbols ---
#let simeq = $tilde.equiv$
#let eqBy(x) = $attach(=, b: #x)$
#let isoBy(x) = $attach(tilde.equiv, b: #x)$
#let to = $arrow.r.long$
#let Leftarrow = $arrow.l.double$
#let Rightarrow = $arrow.r.double$

// --- math operators ---
#let ops = ops

// --- math symbols ---
#let cat = cat
#let idl = sym.idl
#let sch = sym.sch
#let shf = sym.shf

#let Af = $frak("A")$
#let Bf = $frak("B")$

#let red = $op("red")$
#let reg = $op("reg")$

#let isoto = $arrow.r.tilde$
#let isolongto = $arrow.r.tilde$
#let spn = $"-span"$

#let fg(x) = $frak("f.g.")#x$
#let vect = $"vect-"$
