#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

=== The Relative Proj & Projective Space Bundles
#emph-box()[
  *Axiom $dagger$.*
  - $X$ is a Noetherian scheme, and $Ss in qcoh(X)$ having a structure of graded $OO_X$-algebras, i.e. we have $Ss simeq plus.o.big_(d >= 0) Ss_d$, where $Ss_d$ is the _homogeneous part_ of _degree_ $d$.
  - Assume further that $Ss$ is locally generated by $Ss_1 in coh(X)$ as an $Ss_0=OO_X$-algebra. Thus, we have $Ss_d in coh(X)$ for every $d >= 0$.
]

#emph-box()[
  *The Relative $PROJ$ Construction.*
  Fix a scheme $X$, and a quasi-coherent algebra $Ss in GR ALG_(OO_X)$.
  - For any open affine $U=Spec A$ of $X$, we have $Ss(U) in GR ALG_(OO_X(U))$. Consider $Proj Ss(U)$ with the natural morphism
  $Proj Ss(U) arrow.r.long^(pi_U) Spec OO_X(U) simeq U.$
  Checking through the _glueing data_, we may glue these ${pi_U}$ along such open affine cover ${U}$ to obtain a scheme, denoted by $PROJ Ss$, together with a morphism $PROJ Ss arrow.r.long^(pi)X$ and open immersions $Proj Ss(U) arrow.r.long^(psi_U) PROJ Ss$, such that ${Im psi_U}$ covers $PROJ Ss$, and is compatible on the intersections.
  - Such $pi$ is unique with the property that for any open affine $U=Spec A$ of $X$, the square
  #remark[Diagram.]
  is a fibre square, which is compatible with all open affine subsets $V subset U$. Further, we have
  $pi^(-1)(U)=Im psi_U simeq Proj Ss(U).$
  - From _(5.12c)_, the invertible sheaves $OO(1)$ on each $Proj Ss(U)$ are compatible under this construction, so they glue together to give an invertible sheaf $OO(1)$ on $PROJ Ss$ canonically.
]

#lemma-box(title: "Fact 7.D")[
  Consider the relative construction $PROJ Ss arrow.r.long^(pi)X$ as above. Then, we have the following results.
  + *(i).* $pi$ is separated.
  + *(ii).* If $Ss in ALG_(OO_X)$ is locally finitely generated, then $pi$ is of finite type.
  + *(iii).* If, in addition to (ii), that $X Sch$ is Noetherian, then so is $PROJ Ss$.
  + *(iv).* If, in addition to (iii), that $Ss$ satisfies ($dagger$), then $pi$ is proper.
]
#proof[
  These are in fact the more detailed results of _(7.10a)_. To see (i), we use the fact of _(4.1)_ and the fact that "separated is local on the base _(4.6f)_", whence each $pi_U$ is separated, and so is $pi$.
]

#example(title: "7.8.7")[
  If $Ss=OO_X[T_0, ... ,T_n]$ is the polynomial algebra, then $PROJ Ss=PP_X^n$ with its twisting sheaf $OO(1)$ defined earlier.
]

#lemma(number: 7.9)[
  Let $X$ and $Ss$ satisfy ($dagger$), and let $LL in MOD(OO_X)$ be an invertible sheaf. We define a new sheaf
  $Ss ast LL := plus.o.big_(d >= 0)(Ss_d times.o_(OO_X) LL^( times.o d)) in GR ALG_(OO_X).$
  Then $Ss ast LL$ also satisfies ($dagger$), and there is a canonical isomorphism
  $phi:Y'=PROJ(Ss ast LL) arrow.r.long^(tilde.op)Y=PROJ Ss,$
  commuting with the projections $Y arrow.r.long^(pi)X$ and $Y' arrow.r.long^(pi')X$, and having the property that
  $OO_(Y')(1) simeq phi^ast OO_Y(1) times.o_{OO_(Y')}(pi')^ast LL.$
]
#proof[
  We divide into the following steps.\

  (I) For any open affine $U subset X$ satisfying $LL|_U simeq OO_X|_U, exists$ canonical $U$-isomorphism
  $phi_U:Proj(Ss ast LL)(U) arrow.r.long^(tilde.op) Proj Ss(U),$
  compatible with all open affine subsets $V subset U$.

  *proof.* Clearly, we have $Ss ast LL in qcoh(X)$. Given an $OO_X(U)$-basis ${eta}$ of $LL(U)$. Define a map
  $alpha_U:Ss(U) arrow.r.long (Ss ast LL)(U), quad s=sum_(d >= 0)s_d mapsto sum_(d >= 0)s_d times.o eta^( times.o d).$
  This is a graded $OO_X(U)$-algebra isomorphism since for each $d >= 0$, the map $Ss_d(U) -> (Ss ast LL)_d, s mapsto s times.o eta^( times.o d)$ comes from the isomorphism $(Ss_d times.o LL^( times.o d))|_U simeq Ss_d|_U times.o LL|_U^( times.o d) simeq Ss_d|_U times.o OO_X|_U^( times.o d) simeq Ss_d|_U$. Thus, $alpha_U$ induces an isomorphism $phi_U:Proj(Ss ast LL)(U) arrow.r.long^(tilde.op) Proj Ss(U)$.

  _Check._ The isomorphism $phi_U$ is independent of the choice of the basis $eta$.
  - Suppose ${eta'}$ is another $OO_X(U)$-basis of $LL(U)$, then $exists f in OO_X(U)^times$ for which $eta'=f dot eta$. We also have a graded $OO_X(U)$-algebra isomorphism
  $alpha'_U:Ss(U) arrow.r.long^(tilde.op)(Ss ast LL)(U), quad s=sum_(d >= 0)s_d mapsto sum_(d >= 0)s_d times.o eta'^( times.o d).$
  It follows that $alpha'_U(s)=sum_(d >= 0)f^d(s_d times.o eta^( times d))=sum_(d >= 0) alpha_U(s_d)$.
  - _Fact._ For any homomorphism $S arrow.r.long^(alpha)T$, set $G(psi) := {pp in Proj T:pp in.not supset alpha(S_+)}$ (as in _[2.14]_). Suppose $f in T_0$ is a unit, we consider the graded homomorphism
  $alpha':S arrow.r.long T, quad s=sum_(d >= 0)s_d mapsto sum_(d >= 0)f^d alpha(s_d).$
  Then, $G(alpha)=G(alpha')$, and the induced morphisms $G(alpha) arrow.r.long^() Proj S$ are the same.
  - Now, the question reduces to prove the fact above. Consider the graded homomorphism
  $theta:T arrow.r.long T, quad t=sum_(d >= 0)t_d mapsto sum_(d >= 0)f^d t_d.$
  As $f in T_0$ is a unit, $theta$ has an inverse homomorphism given by $sum_(d >= 0)t_d mapsto sum_(d >= 0)f^(-d) t_d$. Thus, $theta$ is an automorphism. Now, $alpha'=theta alpha$, so the result clearly follows.
  Finally, for the _compatibility_, note that if $V subset U$ is affine, ${eta|_V}$ is an $OO_X(V)$-basis for $LL(V)$.\

  (II) The isomorphisms $phi_U$ glue to give an isomorphism $phi:PROJ(Ss ast LL) arrow.r.long^(tilde.op) PROJ Ss$ commuting with the projections, i.e. the following diagram commutes
  #remark[Diagram.]
  *proof.* Cover $X$ with open affines $U$ satisfying $LL|_U simeq OO_X|_U$. For each such $U$, we have the composition
  $Proj(Ss ast LL)(U) arrow.r.long^(phi_U) Proj Ss(U) arrow.r.long^(pi_U)U.$
  Since $phi_U$ is compatible with every open affine subset $V subset U$ by (I), they agree on the intersections, which implies that these $phi_U$ can be glued. Thus, $exists$ isomorphism $PROJ(Ss ast LL) arrow.r.long^(phi) PROJ Ss$ such that
  #remark[Diagram.]
  which is in fact a fibre square, where $psi_U,psi_U'$ are defined in the construction. Now, $pi phi$ is another morphism $Proj(Ss ast LL) arrow.r.long^()X$ satisfying $(pi phi) psi'_U=pi psi_U phi_U=iota_U(pi_U phi_U)$. From the _uniqueness_ of the relative construction $PROJ$, we have $pi'=pi phi$.\

  (III) _Check._ $Ss ast LL in GR ALG_(OO_X)$ is locally generated by $(Ss ast LL)_1=Ss_1 times.o LL$ over $OO_X$, and thus, $Ss ast LL$ satisfies ($dagger$).\

  (IV) Show the isomorphism of sheaves.

  *proof.* Cover $X$ with open affines $U$ satisfying $LL|_U simeq OO_X|_U$. For each such $U$, consider the following commutative diagram
  #remark[Diagram.]
  Write $Y=PROJ Ss, Y'=PROJ(Ss ast LL)$ and $Y_U=Proj Ss(U), Y'_U=Proj(Ss ast LL)(U)$. Then we have the following two isomorphisms:
  $(phi^ast OO_Y(1))|_(Y'_U) & simeq phi^ast (OO_Y(1)|_(Y_U)) simeq phi^ast (phi_U)_ast OO_(Y_U)(1) simeq (phi_U')_ast phi_U^ast OO_(Y_U)(1) & simeq (phi'_U)_ast OO_(Y_U')(1) simeq OO_(Y')(1)|_(Y_U')quad text("(i)") (pi'^ast LL)|_(Y'_U) & simeq (pi_U')^ast (LL|_U) isolongto (pi'_U)^ast (OO_X|_U) simeq OO_(Y')|_(Y_U')quad text("(ii)")$
  Thus, the following isomorphism:
  $alpha_U:(phi^ast OO_Y(1) times.o pi'^ast LL)|_(Y'_U) simeq (phi^ast OO_Y(1))|_(Y'_U) times.o (pi'^ast LL)|_(Y'_U) isolongto OO_(Y')(1)|_(Y_U') times.o OO_(Y')|_(Y_U') simeq OO_(Y')(1)$
  for each such $U$. Further, this is independent of the chosen $OO_X(U)$-basis for $LL(U)$ (similar to the proof of (I)), and is compatible with all open affine subsets $V subset U$. Thus, these ${alpha_U}$ can be glued along such cover ${U}$ of $X$ and obtain an isomorphism $alpha:phi^ast OO_Y(1) times.o pi'^ast LL arrow.r.long^(tilde.op) OO_(Y')(1)$.
]

#lemma-box(title: "Fact 7.E")[
  Let $X$ be a Noetherian scheme and suppose $FF in coh(X)$ is globally generated by the sections ${s_i}_(i in I)$. Then $FF$ can be generated by a finite subset of ${s_i}_(i in I)$.
]
#proof[
  From assumption, $exists$ surjective morphism $OO_X^( plus.o I) arrow.r.long^(phi) FF$. As $X$ is Noetherian, it can be covered by finitely many open affines $U_j=Spec A_j$ ($1 <= j <= n$) where each $A_j$ is Noetherian. Now, for each $1 <= j <= n$, $phi$ restricts to the surjective morphism
  $tildeOf(A)_j^( plus.o I)=OO_X^( plus.o I)|_(U_j) arrow.r.twohead FF|_(U_j) = tildeOf(M)_j$
  where $M_j in fg MOD(A_j)$. From _(5.2)_, the homomorphism $A_j^( plus.o I) arrow.r.long^()M_j$ is also surjective. Since $M_j$ is finitely generated over the Noetherian ring $A_j$, it follows that $M_j$ is a Noetherain $A_j$-module, and thus, any $A_j$-submodule of $M_j$ is finitely generated. Thus, $exists$ finite subset $J_j subset I$ such that ${s_i|_j}_(i in J_j)$ generates $M_j$, so $FF_P=OO_(X,P) spn {[s_i|_j]_P:i in J_j}$ for all $P in U_j$. Finally, take $J := union.big_(j=1)^n J_j$, then $FF$ is globally generated by finitely many sections ${s_i}_(i in J)$.
]

#proposition(number: 7.10)[
  Let $X, Ss$ satisfy ($dagger$), with $Y=PROJ Ss arrow.r.long^(pi)X$ and $OO_Y(1)$ constructed as above. Then:
  + *(a).* $pi$ is proper, and thus, separated of finite type.
  + *(b).* If $X$ admits an ample invertible sheaf $LL$, then $pi$ is projective, and $OO_Y(1) times.o pi^ast (LL^( times.o n)) in MOD(OO_Y)$ is very ample over $X$ for suitable $n>0$.
]
#proof[
  (a) For any open affine subset $U subset X$, note that $Proj Ss(U) arrow.r.long^(pi_U)U$ is projective _(4.8.1)_, and thus, proper _(4.9)_. But, _proper is local on the base (4.8f)_, so $pi$ is proper.\

  (b) Suppose $LL in MOD(OO_X)$ is an ample invertible sheaf. Since $Ss_1 in coh(X), exists n>0$ such that $Ss_1 times.o LL^( times.o n)$ is globally generated. Further, as $X$ is Noetherian, $Ss_1 times.o LL^( times.o n)$ can be generated by finitely many global sections, i.e. $exists$ surjective morphism $OO_X^( plus.o (N+1)) arrow.r.long^() Ss_1 times.o LL^( times.o n)$ for some $N>0$. This allows us to define a surjective morphism
  $OO_X[T_0, ... ,T_N] arrow.r.long^() plus.o.big_(d >= 0) Ss_d times.o LL^( times.o n d)=Ss ast LL^( times.o n),$
  which gives rise to a closed immersion (as closed immersion is local on the base) defined by
  $i:Y=PROJ Ss arrow.r.long^(phi^(-1) tilde.op) PROJ(Ss ast LL^( times.o n)) arrow.r.hook PROJ OO_X[T_0, ... ,T_N] = PP_X^N.$
  Therefore, $pi:Y arrow.r.hook {i} PP_X^N -> X$ is projective.

  Now, using the notations in _(7.9)_ with $Y'=PROJ(Ss ast LL^( times.o n))$, then $i$ is an immersion satisfying
  $i^ast OO_(PP_X^N)(1) & simeq (phi^(-1))^ast OO_(Y')(1) simeq (phi^(-1))^ast (phi^ast OO_Y(1) times.o pi'^ast LL^( times.o n)) & simeq (phi^(-1))^ast phi^ast (OO_Y(1) times.o pi^ast LL^( times.o n)) simeq OO_Y(1) times.o pi^ast LL^( times.o n).$
  Thus, $OO_Y(1) times.o pi^ast LL^( times.o n)$ is very ample over $X$.
]

#definition(title: "Projective Space Bundles")[
  Given a Noetherian scheme $X$ and  a locally free sheaf $EE in coh(X)$. Let $Ss := S(EE)= plus.o.big_(d >= 0)S^d(EE)$, then $Ss in GR ALG_(OO_X)$ satisfies ($dagger$). We define the _projective space bundle_ associated to $EE$ to be the space $PP(EE)=PROJ Ss$, which comes with a projection $PP(EE) arrow.r.long^(pi)X$ and an invertible sheaf $OO(1)$.
]

#remark[
  If $EE in MOD(OO_X)$ is a free sheaf of rank $n+1$ over some open set $U subset X$, then we have
  $pi^(-1)(U) simeq Proj S(EE)(U) simeq Proj OO_X(U)[x_0, ... ,x_n] simeq PP_U^n.$
]

#proposition(number: 7.11)[
  Let $tildeOf(X)=PP(EE) arrow.r.long^(pi)X$ be a projective space bundle. Then
  + *(a).* If $rank_(OO_X) EE >= 2$, there is a canonical isomorphism $Ss arrow.r.long^(tilde.op) plus.o.big_(l in ZZ) pi_ast (OO_(tildeOf(X))(l))$.
  + *(b).* There is a natural surjective morphism $pi^ast EE arrow.r.long^(phi) OO_Y(1)$.
]
#proof[
  (a) Say $rank_(OO_X) EE=r+1$. Cover $X$ with open affines $U=Spec A$ on which $EE|_U simeq OO_X|_U^( plus.o r)$. For each such $U$, write $S=A[x_0, ... ,x_r]$, then $pi^(-1)(U) simeq Proj S$, so that the isomorphism
  $S arrow.r.long^(tilde.op) Gamma_ast (OO_{pi^(-1)(U)})= plus.o.big_(l in ZZ) Gamma(pi^(-1)(U), OO_(tildeOf(X))(l))= plus.o.big_(l in ZZ) Gamma(U, pi_ast OO_(tildeOf(X))(l))$
  of graded $S$-algebras induces the isomorphism
  $Ss|_U simeq S(EE|_U) simeq A[x_0, ... ,x_r]tilde.op arrow.r.long^(tilde.op)( plus.o.big_(l in ZZ) Gamma(U, pi_ast OO_(tildeOf(X))(l)))tilde.op simeq ( plus.o.big_(l in ZZ) pi_ast OO_(tildeOf(X))(l)))|_U.$
  Thus, these glue to give an isomorphism $Ss arrow.r.long^(tilde.op) plus.o.big_(l in ZZ) pi_ast (OO_(tildeOf(X))(l))$.\

  (b) This is just the relative version of _(5.16.2)_, i.e. the twisting sheaf $OO(1)$ on $PP^n$ is globally generated by ${x_i}_(i=0)^n$.
]

#proposition(number: 7.12)[
  Let $tildeOf(X)=PP(EE) arrow.r.long^(pi)X$ be a projective space bundle. Then to give a morphism $Y arrow.r.long^(f) PP(EE)$, it is equivalent to give an invertible sheaf $LL in MOD(OO_Y)$ and a surjective morphism $g^ast EE arrow.r.long^(psi) LL$. _Note._ This is a local version of (7.1).
]
#proof[
  ($Rightarrow$) Given a morphism $Y arrow.r.long^(f) PP(EE)$. By _(7.11b)_, $exists$ surjective morphism $pi^ast EE arrow.r.long^(phi) OO_(tildeOf(X))(1)$. Applying the exact functor $f^ast (-)$ to the morphism gives a surjective map
  $g^ast (EE)=f^ast pi^ast EE arrow.r.long^(f^ast phi)f^ast OO_(tildeOf(X))(1).$
  Thus, we take $psi=f^ast phi$ and $LL=f^ast OO_(tildeOf(X))(1) in MOD(OO_Y)$.\

  ($Leftarrow$) Given an invertible sheaf $LL in MOD(OO_Y)$ with a surjective morphism $g^ast EE arrow.r.long^(psi) LL$. I claim that there is a unique morphism $Y arrow.r.long^(f) PP(EE)=tildeOf(X)$ such that $LL simeq f^ast OO_(tildeOf(X))(1)$, and that $psi$ is obtained by applying $f^ast$ to $psi$.
  - _Note._ This is in fact a local question on $X$, so taking an open affine cover ${U:EE|_U text("is free")}$ of $X$ reduces the statement to _(7.1)_.
  - If $X=Spec A$ and $EE simeq OO_X^( plus.o (n+1))$, then $tildeOf(X)=PP_A^n$. Now that $g^ast EE in MOD(OO_Y)$ is free and $psi$ is surjective, so $psi$ is uniquely determined by $n+1$ global sections generating $LL$, say $s_i in Gamma(Y, LL)$ ($0 <= i <= n$). From _(7.1)_, these sections ${s_i}_(i=0)^n$ uniquely determine a morphism $Y arrow.r.long^(f) PP_A^n=tildeOf(X)$ satisfying $LL simeq f^ast OO_(tildeOf(X))(1)$ and $s_i=f^ast (x_i)$.
  - Further, there is a natural surjective morphism $pi^ast EE arrow.r.long^(phi) OO_Y(1)$ by _(7.11b)_. It follows that $f^ast phi$ is another surjective morphism $g^ast EE arrow.r.long^()f^ast OO_(tildeOf(X))(1) simeq LL$ determined by the global sections ${s_i}_(i=0)^n$ generating $LL$. Thus, we have $psi=f^ast phi$ by _uniqueness_.
  - Finally, the uniqueness of such morphism $f$ follows from _(7.1)_.
]
