#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

=== Nonsingular Varieties

#definition(title: "Nonsingular Varieties")[
  - *(Abstract Varieties).* From now on, our _(abstract) variety_ means an integral separated scheme of finite type over an algebraically closed field $k$.
  - *(Nonsingularity).* An (abstract) variety $X$ over $k$ is _nonsigular_ if all its local rings $OO_X,P$ are regular.
]
#theorem(number: "8.14")[
  Any localization of a regular local ring at a prime ideal is again a regular local ring.
]
#theorem(number: "8.15")[
  Let $X$ be an irreducible separated scheme of finite type over $k$. Then,
  $
    op("Omega")_(X/k) in MOD(OO_X)\ text("is locally free of rank")\ n=op("dim") X\ arrow.l.r.double.long \ X\ text("is a nons in gular variety over")\ k.
  $
]
#proof[
  Note that the question is local by covering $X$ with open affine subsets, so we may assume $X$ is affine, say $X=Spec A$.
  - If $P in X$ is a closed point, we have $op("dim") OO_X,op("Pattach")(=, b: "_[3.20a]_")op("dim") X=n,\ OO_X,P/ mm_P simeq k$. Write $B= OO_X,P=A_mm$, where $mm = mm_P$ corresponds to the point $P$. Thus,
  $
    (op("Omega")_(X/k))_op("Pattach")(simeq, b: "text(\"(8.9.2)\")")(op("Omega")_(A/k))op("widetilde")_op("Pattach")(simeq, b: "text(\"(5.1)\")")(op("Omega")_(A/k))_mm attach(simeq, b: "text(\"(8.2)\")")op("Omega")_(B/k).
  $
  - Since $X$ is of finite type over $k$, we have $A in fg ALG_k$. Further, $k$ is perfect as it is algebraically closed, so we see from _(8.8)_ that
  $
    op("Omega")_(B/k) in MOD(B)\ text("is free of rank")\ n\ arrow.l.r.double.long \ B\ text("is regular").
  $
  - Thus, we have
  $
                                     op("Omega")_(X/k) \
                       text("is locally free of rank") \
                                                     n & attach(arrow.l.r.double.long, b: "text(\"[5.7b]\")") \
             (op("Omega")_(X/k))_P in op("MOD")_OO_X,P \
                   text("is free of rank $n$ for all") \
                                                P in X \
                                                       & arrow.l.r.double.long \
                  (op("Omega")_(A_mm /k)) in MOD(A_mm) \
    text("is free of rank $n$ for all closed po in t") \
                               mm op("triangleleft") X \
                                                       & attach(arrow.l.r.double.long, b: "text(\"(8.8)\")") \
                                                  A_mm \
             text("is regular for all closed po in t") \
                               mm op("triangleleft") A \
                                                       & attach(arrow.l.r.double.long, b: "text(\"(8.14)\")") \
                                                  A_pp \
                    text("is regular for all po in t") \
                               pp op("triangleleft") A \
                                                       & arrow.l.r.double.long \
                                             X= Spec A \
              text("is (integral and) nons in gular").
  $
  Here, for the second arrow, we note that is $M_mm$ is a free $A_mm$-module (where $mm op("triangleleft") A$ maximal), then $M_pp =(M_mm )_pp =M_mm times.o_AA_pp$ is a free $A_pp$-module for any prime $pp op("triangleleft") A$ with $pp subset mm$.
]
#corollary(number: "8.16")[
  If $X in Var_k$, then there is an open dense subset $U subset X$ which is nonsingular. Note, this gives a new proof of _(I, 5.3)_.
]
#proof[
  Suppose $op("dim") X=n$ and write $K=K(X)$. Then $trdeg_op("kK")=n$ by _[3.20b_, where $K/k$ is a finitely generated field extension, whence $K/k$ is separably generated by _(I, 4.8)_. Now, we have $rank_op("Kop")("Omega")_(K/k)attach(=, b: "_(8.6)_") trdeg_op("kK")=n$. On the other hand, we note that $(op("Omega")_(X/k))_op("eta")=op("Omega")_(K/k)$ where $op("eta") in X$ is the generic point. Clearly, the field $K$ is a regular local ring, so _(8.8)_ shows that $(op("Omega")_(X/k))_op("eta")=op("Omega")_(K/k)$ is a free $OO_X,op("eta")=K$-module of rank $n$. By _[5.7a]_, $exists \ U in NN_op("eta")(X)$ on which $op("Omega")_(X/k)|_U in MOD(OO_X|_U)$ is free of rank $n$. Thus, $U$ is a nonsingular variety over $k$ by _(8.15)_. Clearly, such $U$ is a dense subset as it is a nonempty open set in the irreducible topological space $X$. Done!
]
#theorem(number: "8.17")[
  Let $X$ be a nonsingular variety over $k$, and let $Y subset X$ be an irreducible closed subscheme with its ideal sheaf $II$. Then, $Y$ is nonsingular if and only if
  + *(1).* $op("Omega")_(Y/k) in MOD(OO_Y)$ is locally free.
  + *(2).* The sequence of _(8.12)_ is exact on the left, i.e.
  $
    0 arrow.r.long II / II^2 arrow.r.long op("Omega")_(X/k) times.o OO_Y arrow.r.long op("Omega")_(Y/k) arrow.r.long 0.
  $
  Furthermore, in this case, $II$ is locally generated by $r= codim (Y,X)$ elements, and $II / II^2 in MOD(OO_Y)$ is a locally free sheaf of rank $r$.
]
#proof[
  ($op("Leftarrow")$) Suppose both (1) and (2) are satisfied.
  - From (1), $op("Omega")_(Y/k)$ is locally free. By _(8.15)_, it suffices to show that $rank_OO_op("Yop")("Omega")_(Y/k)=op("dim") Y$. Say $q= rank_OO_op("Yop")("Omega")_(Y/k)$.
  - As $X$ is nonsingular, we see also from _(8.15)_ that $op("Omega")_(X/k) in MOD(OO_X)$ is locally free of rank $n=op("dim") X$. By (2), it follows that $rank_OO_Y( II / II^2)=n-q$. By _Nakayama Lemma_, $II$ can be locally generated by $n-q$ elements. Thus, $op("dim") Y >= n-(n-q)=q$ by _[I, 1.9]_.
  - For any closed point $P in Y$, write $B := OO_Y,P$, then
  $
    op("dim") op("Yattach")(<=, b: "text(\"(I,5.2)\")")op("dim")_k( mm_P/ mm_P^2)attach(=, b: "text(\"(8.7)\")") rank_k(op("Omega")_(B/k) times.o_op("Bk"))= rank_op("Bop")("Omega")_(Y/k)= rank_OO_op("Yop")("Omega")_(Y/k)=q.
  $
  Therefore, $Y$ is nonsingular, and that $rank_OO_Y( II / II^2)=n-q=op("dim") X-op("dim") Y= codim (Y,X)$.
  ($op("Rightarrow")$) Conversely, suppose $Y$ is a nonsingular variety.
  - Again, (1) follows from _(8.15)_, and that $rank_OO_op("Yop")("Omega")_(Y/k)=op("dim") Y$, say $q$. Further, we have the exact sequence $II / II^2 arrow.r.long op("Omega")_(X/k) times.o OO_Y arrow.r.long op("Omega")_(Y/k) arrow.r.long 0$ of $OO_Y$-modules from _(8.12)_. So, it suffices to show that $op("delta")$ is injective.
  - Let $y in Y$ be any closed point. We have the short exact sequence
  $
    0 arrow.r.long Im op("delta")= Ker op("phi") arrow.r.long op("Omega")_(X/k) times.o OO_Y arrow.r.long op("Omega")_(Y/k) arrow.r.long 0
  $
  of $OO_Y$-modules (as $op("phi")$ is surjective). Note that $op("Omega")_(Y/k) in coh (Y)$ by _(8.9.1)_, so $Ker op("phi") in coh (Y)$ by _(5.7)_ Thus, $( Im op("delta"))_y=( Ker op("phi"))_y$ is a free $OO_Y,y$-module of rank $r=n-q$. From _[5.7a]_, $exists \ U in NN_y(Y)$ on which $( Ker op("phi"))|_U in MOD(OO_Y|_U)$ is free of rank $r$. Now, we may choose some sections $x_i in op("Gamma")(U, II )$ ($1 <= i <= r$) such that $op("dx")_i_i=1^r$ forms an $OO_Y|_U$-basis of $( Ker op("phi"))|_U$.
  - Now, consider the ideal sheaf $II '$ generated by the sections $x_i_i=1^r$ over $OO_X$, and let $Y' subset X$ be the corresponding closed subscheme. Then, we have $II ' subset II$, and thus,
  $
    Y'= Supp ( OO_X/ II ')=y in X: II_y' subset.neq OO_X,y supset y in X: II_y subset.neq OO_X,y= Supp ( OO_X/ II )=Y.
  $
  - From this construction, $op("dx")_i_i=1^r$ generates a free $OO_Y'$-submodule of $op("Omega")_(X/k) times.o OO_Y'$ of rank $r$ in the neighborhood $U in NN_y(Y')$. Apply the exact sequence of _(8.12)_ again to $Y'$, then the map $op("delta"): II '/ II '^2 to op("Omega")_(X/k) times.o OO_Y'$ is injective since $( Im op("delta"))_y= Im (op("delta")_y)$ is free of rank $r$ on each closed point $y in Y$. Further, this shows that $op("Omega")_(Y'/k) in op("MOD")_OO_Y'$ is locally free of rank $n-r=q$.
  - Finally, applying these results to the proof of ($op("Leftarrow")$) yields that $Y'$ is nonsingular (thus, irreducible and integral) of dimension $op("dim") Y'=q$. So, $Y subset Y'$ are integral schemes having the same dimension, so we must have $Y=Y'$ and $II = II '$. Therefore, $op("delta")$ is injective.
]
#lemma(number: "8.D")[
  Let $(A, mm )$ be a regular local ring, and given a nonzero element $a in mm$. Then, $A/chevron.l a chevron.r$ is a regular local ring $arrow.l.r.double.long \ a in.not mm^2$.
]
#proof[
  Suppose $A$ is regular of dimension $n >= 1$. Denote $V$ for the $k$-vector space
  $
    (mm /chevron.l a chevron.r)/(( mm /chevron.l a chevron.r)^2) simeq (A/chevron.l a chevron.r)/(mm /chevron.l a chevron.r) times.o_A/chevron.l a chevron.r mm /chevron.l a chevron.r simeq k times.o_A/chevron.l a chevron.r mm /chevron.l a chevron.r.
  $
  ($op("Rightarrow")$) Suppose $A/chevron.l a chevron.r$ is regular. Suppose on the contrary that $a in mm^2$, then we have $( mm /chevron.l a chevron.r)^2= mm^2/chevron.l a chevron.r$, whence $V simeq mm / mm^2$. Thus, $op("dim") A/chevron.l a chevron.r=op("dim")_op("kV")=op("dim") A=n$. However, if we choose a maximal chain
  $
    pp_0/chevron.l a chevron.r subset.neq pp_1/chevron.l a chevron.r subset.neq dots.c subset.neq pp_n/chevron.l a chevron.r= mm /chevron.l a chevron.r
  $
  of prime ideals of $A/chevron.l a chevron.r$, as $a != 0$ and $A$ is integral (since it is regular), we obtain a chain $0 subset.neq pp_0 subset.neq pp_1 subset.neq dots.c subset.neq pp_n= mm$ of prime ideals of $A$, whence $op("dim") A >= n+1$, a contradiction.\
  ($op("Leftarrow")$) _Claim._ $A/chevron.l a chevron.r$ is regular of dimension $n-1$. Clearly, $A/chevron.l a chevron.r$ is also a local ring with maximal ideal $mm /chevron.l a chevron.r$. If $a in.not mm^2$, we may extend $op("bar")a in mm / mm^2$ to a $k$-basis $op("bar")a_i_i=1^n$ of $mm / mm^2$ (where $a_i in mm$ and $op("bar")a=op("bar")a_1$). Then, $1 times.o (a_i+chevron.l a chevron.r)_i=2^n$ generates the $k$-vector space $V$, whence $op("dim")_op("kV") <= n-1$. On the other hand, consider a maximal chain $0= pp_0 subset.neq pp_1 subset.neq dots.c subset.neq pp_n= mm$ of prime ideals of $A$. (Note. $A$ is regular, thus integral). Moreover, $A$ is Noetherian with $0 != a in mm$, so we may modify the chain $pp_i_i=0^n$ and assume that $a in pp_1$. Thus,
  $
    pp_1/chevron.l a chevron.r subset.neq pp_2/chevron.l a chevron.r subset.neq dots.c subset.neq pp_n/chevron.l a chevron.r= mm /chevron.l a chevron.r
  $
  is a chain of prime ideal of $A/chevron.l a chevron.r$, whence $op("dim") A/chevron.l a chevron.r >= n-1$. However, we already have $op("dim") A/chevron.l a chevron.r <= op("dim")_op("kV")$. Combining these all, we obtain $op("dim") A/chevron.l a chevron.r=op("dim")_op("kV")=n-1$.
]
#theorem(number: "8.18. (Bertini Theorem")[
  Let $X$ be a nonsingular closed subvariety of $PP_k^n$. Then
  + *(i).* There exists a hyperplane $H subset PP_k^n$, not containing $X$, such that the scheme $op("Hop")("cap") X$ is regular at every point.
  + *(ii).* The set of such hyperplanes forms an open dense subset of the complete linear system $|H|$, considered as a projective space.
]
#proof[
  (I) For each closed point $x in X$, we consider the set
  $
    B_x := text("hyperplanes")\ H\ |\ H supset X,\ text("or")\ op("Hop")("not") supset X\ text("with")\ x in op("Hop")("cap") X\ text("non-regular").
  $
  Note that a hyperplane $H subset PP_k^n$ is determined by a nonzero global section $f in S_1=op("Gamma")( PP_k^n, OO (1))=:V$. Fix an $f_0 in V$ for which $x_0 in.not H_0 := V_+(f_0)$. Now, we define a map of $k$-linear spaces as follows:
  #remark[Diagram.]
  where $i$ is the closed immersion $X arrow.r.hook PP_k^n=Y$. Now, the scheme $op("Hop")("cap") X$ is given by $V_+(f)op("cap") X=V_+(i^op("hash") (f/f_0))$. Thus, we see that
  - First, note that
  $
    x in op("Hop")("setm in us") H_0\ arrow.l.r.double.long \ op("Big")[(f)/(f_0)op("Big")]_x in mm_Y,x\ arrow.l.r.double.long \ op("phi")_x(f) in mm_x.
  $
  - Suppose $X$ is defined by the homogeneous prime ideal $op("Iop")("triangleleft") S=k[x_0, dots.c ,x_n]$, i.e. $OO_X simeq (S/I)op("widetilde")$. Then
  $
    H supset X\ text("(as a closed subscheme)")\ & arrow.l.r.double.long \ f in I\ arrow.l.r.double.long \ op("Big")[i^op("hash") op("Big")((f)/(f_0)op("Big"))op("Big")]_x=op("Big")[(f)/(f_0)op("Big")]_x+chevron.l op("phi")_x(f) chevron.r\
    & arrow.l.r.double.long \ op("phi")_x(f)=0\ text("in")\ mm_x= mm_Y,x/chevron.l op("phi")_x(f) chevron.r.
  $
  - If $op("Hop")("not") supset X$, then $x in op("Hop")("cap") X\ arrow.l.r.double.long \ op("phi")_x(f)=[i^op("hash") (f/f_0)]_x in mm_x$ is nonzero. In this case,
  $
    x in op("Hop")("cap") X\ text("is nonregular")\ & arrow.l.r.double.long \ OO_op("Hop")("cap") X,x= OO_X,x/chevron.l op("phi")_x(f) chevron.r\ text("is not a regular r in g")\ &attach(arrow.l.r.double.long, b: "text(\"(8.D)\")")\ op("phi")_x(f) in.not mm_x^2.
  $
  Therefore, we conclude that $H in B_x\ arrow.l.r.double.long \ f in Ker (op("phi")_x)$. \
  (II) Since $x in X$ is a closed point and $k$ is algebraically closed, the maximal ideal $mm_x$ is generated by $a_op("jx")_i-a_op("jx")_i:1 <= i,j <= n$ where $a_i in k$ not all zero. Now, it is an algebraic problem: writing $A= OO_X,x,\ mm = mm_x,\ M=A/ mm^2$, then
  $(a_op("jx")_i-a_op("ix")_j)/f_0+ mm^2_i,j$ generates $mm / mm^2 subset M$ over $k$. In particular, $A^op("times")=op("Aop")("setm in us") mm$ implies that the image of $op("phi")_x(f_0)=f_0/f_0+ mm^2$ generates the $k$-vector space $M/ mm M simeq k$. By _Nakayama (AM, 2.8)_, $M$ is finitely generated by $op("phi")_x(a_op("jx")_i-a_op("jx")_i)_i,op("jop")("cup")op("phi")_x(f_0)$ over $k$, and therefore, $op("phi")_x$ is surjective. Now, the _Isomorphism Theorem_ gives $V/ Ker op("phi")_x simeq A/ mm^2$. If $op("dim") X=r$, recall that $V=k spn x_i_i=0^n$, we obtain
  $
    op("dim")_k( Ker op("phi")_x) &=op("dim")_op("kV")-op("dim")_k(V/ Ker op("phi")_x)=(n+1)-op("dim")_k(A/ mm^2)\ &=(n+1)-op("Big")[op("dim")_k( mm / mm^2)+op("dim")_k(A/ mm^2)/(mm / mm^2)\ op("Big")]=(n+1)-op("Big")[attach(op("dim") X, b: "text(\"nons in gular\")")+op("dim")_op("kk")\ op("Big")]\ &=(n+1)-(r+1)=n-r.
  $
  Now, we may identify $B_x= PP ( Ker op("phi")_x)$, i.e. a linear system of hyperplanes in $|H_0|$, which has dimension $op("dim") B_x=n-r-1$. (cf. S II.7).
]
