#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

=== Ample Invertible Sheaves
#definition(title: "Ample Invertible Sheaves")[
  Fix a Noetherian scheme $X$. An invertible sheaf $LL in MOD(OO_X)$ is _ample_ if for every $FF in coh(X)$, there is an integer $n_0>0$ (depending on $FF$) such that the sheaf $FF times.o LL^( times.o n)$ is globally generated for every $n >= n_0$.
]

#lemma-box(title: "Fact 7.B")[
  + *(i).* Let $S$ be a graded ring, which is finitely generated by $S_1$ over a Noetherian ring $S_0=A$. Let $X=Proj S$, then $OO_X(1)$ is a very ample invertible sheaf relative to $Spec A$.
  + *(ii).* Let $X in Sch_A$ and $LL in MOD(OO_X)$ be an invertible sheaf. Then, $LL$ is very ample relative to $A arrow.l.r.double.long$ There exists $n>0$ and global sections ${s_i}_(i=0)^n$, which generate $LL$, such that the corresponding morphism $X -> PP_A^n$ is an immersion.
]
#proof[
  (i) Note that $Proj S -> Spec A$ is projective. By _(5.16.1)_, $OO_X(1)$ is very ample over $A$. (ii) follows from _(7.1)_ and the _definition of very ampleness_.
]

#proposition(number: 7.5)[
  Let $LL in MOD(OO_X)$ be an invertible sheaf on a Noetherian scheme $X$. T.F.A.E.
  + *(i).* $LL$ is ample.  (ii) $LL^( times.o m)$ is ample for all $m>0$. (iii) $LL^( times.o m)$ is ample for some $m>0$.
]
#proof[
  (i) $Rightarrow$ (ii). Given $FF in coh(X)$, then $FF times.o LL^( times.o n)$ is globally generated for all large $n$, so is $FF times.o (LL^( times.o m))^( times.o n)$. By definition, $LL^m$ is ample.

  (ii) $Rightarrow$ (iii). This is clear.

  (iii) $Rightarrow$ (i). Suppose $LL^( times.o m)$ is ample. Given $FF in coh(X)$, then $exists n_0>0$ such that $FF times.o (LL^( times.o m))^( times.o n)$ is globally generated for every $n >= n_0$. Consider $FF times.o LL in coh(X)$. As $LL^( times.o m)$ is ample, $exists n_1>0$ such that $(FF times.o LL) times.o (LL^( times.o m))^( times.o n)$ is globally generated for every $n >= n_1$. Continuing this process, for each $1 <= k <= m-1, exists n_k>0$ such that $(FF times.o LL^( times.o k)) times.o (LL^( times.o m))^( times.o n) simeq FF times.o LL^( times.o (m n+k))$ is globally generated for every $n >= n_k$. Take $N := m dot max {n_k:0 <= k <= m-1}>0$, then $FF times.o LL^( times.o n)$ is globally generated for every $n >= N$. Therefore, $LL$ is ample.
]

#theorem(number: 7.6)[
  Let $X$ be a (Noetherian) scheme of finite type over a Noetherian ring $A$, and $LL in MOD(OO_X)$ be an invertible sheaf. Then
  $LL text(" is ample ") arrow.l.r.double.long LL^( times.o m) text(" is very ample over ") Spec A text(" for some ") m > 0.$
]
#proof[
  ($Leftarrow$) Suppose $LL^( times.o m)$ is very ample over $A$. Let $X arrow.r.long^(i) PP_A^n$ be the immersion (with $n >= 1$) such that $LL^( times.o m) simeq i^ast (OO(1))$.
  - Let $overline(X)$ be the closure of $i(X)$ in $PP_A^n$. Consider the closed immersion $overline(X) arrow.r.long^(j) PP_A^n$ such that $i$ factors through $j$ via the open immersion $X arrow.r.long^(k) overline(X)$, i.e. $i=j k$.
  - Now, $overline(X) -> Spec A$ is projective. By _(5.17)_, $OO_(overline(X))(1)=j^ast (OO(1))$ is ample on $overline(X)$.
  - For any $FF in coh(X)$, it follows from _[5.15]_ that $exists overline(FF) in coh(overline(X))$ which extends the coherent sheaf $FF$, i.e. $overline(FF)|_X simeq FF$.
  - Now, if $overline(FF) times.o OO_(overline(X))(l)$ is globally generated, then so is
  $(overline(FF) times.o OO_(overline(X))(l))|_X & simeq FF times.o (OO_(overline(X))(1)|_X)^( times.o l) simeq FF times.o (k^ast j^ast OO(1))^( times.o l) simeq FF times.o (i^ast OO(1))^( times.o l) & simeq FF times.o (LL^( times.o m))^( times.o l)$
  for every large $l>0$. Thus, $LL^( times.o m)$ is ample, and hence, $LL$ is ample by _(7.5)_.

  ($Rightarrow$) Suppose $LL$ is ample.

  (I) Given any $P in X$. Choose an open affine $U in NN_P(X)$ on which $LL|_U simeq OO_X|_U$.
  - Let $Y := X without U$ be the closed subset in $X$, and let $II_Y lt.closed OO_X$ be the sheaf of ideal with reduced induced structure. Since $X$ is Noetherian and of finite type over $A$, it follows from _(5.9)_ that $II_Y in coh(X)$. So, $II_Y times.o LL^( times.o n)$ is globally generated by ${s_i}$ for some large $n>0$. Now, $(II_Y times.o LL^( times.o n))_P=OO_(X,P) spn {(s_i)_P}$, so we have $(s_i)_P in.not mm_P(II_Y times.o LL^( times.o n))_P$ for some $i$. (Otherwise, we have $1=sum_i a_i(s_i)_P in mm_P(II_Y times.o LL^( times.o n))_P$). Write $s := s_i$.
  - As $LL$ is an invertible sheaf, $- times.o LL$ is an exact functor, whence $II_Y times.o LL^( times.o n) arrow.r.hook {} OO_X times.o LL^( times.o n) simeq LL^( times.o n)$, i.e. we may regard $s in Gamma(X, II_Y times.o LL^( times.o n)) subset Gamma(X, LL^( times.o n))$. Consider the set $X_s := {Q in X:s_Q in.not mm_Q LL_Q^( times.o n)}$, which is open in $X$, and that $P in X_s$.
  - Further, we have $X_s subset U$. Indeed, if $Q in.not U$, then
  $Q in Y=Supp(OO_X/II_Y)={x in X:II_(Y,x) != OO_(X,x)},$
  i.e. $II_(Y,Q) lt.closed OO_(X,Q)$, whence $II_(Y,Q) subset mm_Q$. Thus, $s_Q in mm_Q LL_Q^( times.o n)$, i.e. $Q in.not X_s$.
  - Moreover, as $U simeq Spec A$ is open affine and that $LL|_U simeq OO_X|_U$, the section $s|_U in Gamma(U, LL^( times.o n))$ corresponds to a global section $f in Gamma(U, OO_X|_U) simeq Gamma(U, OO_X^( times.o n))$. This implies that $X_s=U inter X_s=U_f simeq Spec A_f$ is affine.
  - _Conclusion._ For any $P in X, exists n>0$ and a global section $s in Gamma(X, LL^( times.o n))$ such that $X_s in NN_P(X)$ is a open affine neighborhood of $P$.

  (II) Reduction to $LL$.
  - Note that $X$ is of finite type over $A$, so $X$ is quasi-compact, i.e. we can cover $X$ by finitely many such open affine ${X_(s_i)}_(i=1)^r$ with each $s_i in Gamma(X, LL^( times.o n_i))$.
  - For any $k>0$, note that
  $Q in X_(s_i) arrow.l.r.double.long (s_i)_Q in.not mm_Q LL_Q^( times.o n_i) arrow.l.r.double.long (s_i^k)_Q in.not mm_Q LL_Q^( times.o k n_i) arrow.l.r.double.long Q in X_(s_i^k),$
  which shows that $X_(s_i)=X_(s_i^k)$ where $s_i^k in Gamma(X, LL^( times.o k n_i))$. Now, pick $n := n_1 ... n_r>0$ and $t_i := s_i^(n/n_i) in Gamma(X, LL^( times.o n))$ for each $i$. Then $X_i := X_(t_i)=X_(s_i)$ still gives a finite open affine cover of $X$.
  - From _(7.5)_, $LL^( times.o n)$ is ample. Moreover, note that we are only trying to show that $LL^( times.o m)$ is very ample over $A$ for some $m>0$. So, we may replace $LL^( times.o n)$ by $LL$ and assume that $X$ is covered by open affines $X_i=X_(s_i)$ where $s_i in Gamma(X, LL)$ ($1 <= i <= r$).

  (III) Define an $A$-morphism $X -> PP_A^N$.
  - For each $i$, we let $B_i := Gamma(X_i, OO_X|_(X_i))$, i.e. $X_i=Spec B_i$. Since $X$ is of finite type over $A$, we have $B_i in fg ALG_A$ by _[3.3]_. Let ${b_(i j)}_(j=1)^(k_i)$ denote the set of generators for $B_i$ over $A$. Apply _(5.14b)_ to each $b_(i j) in Gamma(X_i, OO_X)$, then $exists m_(i j)>0$ and a global section $c_(i j) in Gamma(X, OO_X times.o LL^( times.o m_(i j)))=Gamma(X, LL^( times.o m_(i j)))$ such that $c_(i j)|_(X_i)=s_i^(m_(i j)) b_(i j)$. As usual, we take $m >= max {m_(i j)}$ such that $s_i^m b_(i j)$ extends to $c_(i j) in Gamma(X, LL^( times.o m))$ for every $i,j$.
  - Note that the global sections ${s_i^(m)}_(i=1)^r$ and ${c_(i j)}_(i,j)$ generated the invertible sheaf $LL^( times.o m) in MOD(OO_X)$. By _(7.1)_, they define an $A$-morphism $phi:X -> PP_A^N$ such that $LL^( times.o m) simeq phi^ast (OO(1))$, (where $N=r+sum_(i=1)^r k_i-1$).

  (IV) Show that $phi$ is an immersion.
  - Let ${x_i}_(i=1)^r$ and ${x_(i j)}_(i,j)$ denote the set of homogeneous coordinates of $PP_A^N$ via $phi$, i.e. $s_i^m=phi^ast (x_i)$ and $c_(i j)=phi^ast (x_(i j))$ by _(7.1)_.
  - For each $i$, let $U_i := D_+(x_i) subset PP_A^N$ (which is open affine), then $phi^(-1)(U_i)=X_(s_i^m)=X_i$. Further, the corresponding ring homomorphism
  $phi^sharp_(U_i): A[y_k, y_(k j)] arrow.r.long B_i, quad y_k=(x_k) / (x_i) mapsto (s_k^m) / (s_i^m), quad y_(k j)=(x_(k j)) / (x_i) mapsto (c_(k j)) / (s_i^m)=b_(k j)$
  is surjective, since $y_(i j) mapsto b_(i j)$ and ${b_(i j)}_(j=1)^(k_i)$ generates $B_i$ over $A$.
  - By _[2.18c]_, the morphism $X_i -> U_i$ between affine schemes via $phi$ is a closed immersion. Thus, $X=union.big_(i=1)^r X_i arrow.r.long^(phi) union.big_(i=1)^r U_i$ is a closed immersion followed by an open immersion $union.big_(i=1)^r U_i arrow.r.hook {} PP_A^N$, i.e. $X arrow.r.long^(phi) PP_A^N$ is an immersion. Therefore, $LL^( times.o m)$ is very ample over $A$.
]

#example(title: "7.6.1")[
  Let $X=PP_A^n$ for any Noetherian ring $A$. Then,
  $OO(l) text("is ample") arrow.l.r.double.long OO(l) text("is very ample") arrow.l.r.double.long l>0.$
]
#proof[
  For any ring $A$, set $S=A[x_0, ... ,x_n]$. Given $d>0$, let ${M_i}_(i=0)^N$ denote the set of monomials in $x_0, ... ,x_n$ of degree $d$ (in a given order where $N=binom(n+d, n)-1$). Then the ring homomorphism
  $theta:A[y_0, ... ,y_N] arrow.r.long S^((d)), quad y_i mapsto M_i$
  gives rise to the closed immersion $Proj S^((d)) arrow.r.hook {} PP_A^N$ by _[3.12d]_. This corresponds to the $d$-uple embedding
  $rho_d:X=Proj S isolongto Y=Proj S^((d)) arrow.r.hook {} PP_A^N$
  by _[5.13]_. It follows that $OO_X(d) simeq OO_Y(1)$ is very ample over $A$. In particular, if $A$ is Noetherian, then $OO_X(n)$ is ample for every $n>0$ by _(7.5)_ and _(7.6)_. On the other hand, the sheaf $OO_X(l)$ has no global sections for $l<0$, one sees easily that $OO_X(l)$ cannot be ample for $l <= 0$. Thus, we have the desired result.
]
