#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

=== Linear Systems
#emph-box()[
  Throughout this subsection, we always assume $X$ is a _nonsingular_ (all local rings are regular) projective variety over an algebraically closed field $k$. Then,
  - Recall that _regular_ $Rightarrow$ UFD, so $X$ is nonsingular implies that $X$ is locally factorial. By _(6.11)_, we have $Div(X) simeq CDiv(X)$, and $Cl(X) simeq CaCl(X)$.
  - As $X$ is integral, $Cl(X) simeq Pic(X)$ by _(6.15)_.
  - For any invertible $OO_X$-module $LL$, note that $LL in coh(X)$. It follows from _(5.19)_ that $Gamma(X, LL)$ is a finite-dimensional $k$-vector space.
]

#definition(title: "Divisor of Zeros")[
  Fix an invertible sheaf $LL in MOD(OO_X)$. Let $0 != s in Gamma(X, LL)$ be a nonzero global section. Choose an open cover ${U_i}$ of $X$ on which $phi_i:LL|_(U_i) isoto OO_X|_(U_i)$. Then, $phi_i(s|_i) in Gamma(U_i, OO_X) subset KK_X(U_i)$ is nonzero (since $LL(U) -> LL(V)$ is injective whenever $V subset U$ as $X$ is integral). Thus, ${(U_i,phi_i(s|_i))}$ defines an effective Cartier divisor (depending only on $LL$ and $s$), called the _divisor of zeros_ of $s$, and is denoted by $(s)_0$.
]

#proposition(number: 7.7)[
  Let $X$ be a nonsingular projective variety over the algebraically closed field $k$. Fix $D_0 in CDiv(X)$ and let $LL$ denote the corresponding invertible sheaf $LL(D_0) in Pic(X)$. Then,
  + *(a).* For each $0 != s in Gamma(X, LL)$, the divisor of zeros $(s_0) in CDiv(X)$ is effective, and $(s)_0 tilde.op D_0$.
  + *(b).* Every effective divisor $D in CDiv(X)$ linearly equivalent to $D_0$ is $(s)_0$ for some $s in Gamma(X, LL)$.
  + *(c).* Given two nonzero sections $s,s'in Gamma(X, LL)$. Then, $(s)_0=(s')_0 arrow.l.r.double.long s'=lambda s$ for some $lambda in k^times$.
]
#proof[
  (a) Given a nonzero global section $s in Gamma(X, LL)$.
  - Recall that $LL=LL(D_0)$ is an $OO_X$-submodule of $KK_X$, so $s in Gamma(X, KK)$ is nonzero, i.e. we have  $s in KK^ast (X)=K^times$.
  - Suppose $D_0$ is represented by ${(U_i,f_i)}$ where $f_i in KK^ast (U_i)=K^times$. We may choose $U_i != emptyset$ such that $LL|_(U_i) simeq OO_X|_(U_i)$, and that $LL(U_i)=LL(D_0)(U_i)$ is generated by $f_i^(-1)$.
  - We have a local isomorphism $phi:LL(D_0) -> OO_X$ for which $phi_(U_i):LL(U_i) isoto OO_X(U_i)$ sends $s|_i mapsto f_i dot s|_i$. Therefore, $(s)_0$ is determined by ${(U_i,f_i dot s|_i)}=D_0+dv(s)$, whence $(s)_0 tilde.op D_0$.

  (b) Since $D tilde.op D_0$, we choose an $s in KK^ast (X)$ such that $D-D_0=dv(s)$. Then, $dv(s)+D_0=D >= 0$ (i.e. effective), and $dv(s) >= -D_0$. Note that $D_1 >= D_2 arrow.l.r.double.long LL(D_1) supset LL(D_2)$. Now, $LL(-D_0) subset LL(dv(s))=OO_X spn {s^(-1)}$, whence $s in Gamma(X, LL(D_0))$ is nonzero. Therefore, from the proof of _(a)_, we have $D=D_0+dv(s)=(s)_0$.\

  (c) Note that $X in Var_k$ is a projective variety, so $OO_X(X)=k$ by _(I, 3.4)_. Thus,
  $(s)_0=(s')_0 arrow.l.r.double.long dv(s)=dv(s') arrow.l.r.double.long s/s' in OO_X^ast (X)=OO_X(X)^times =k^times .$
]

#definition(title: "Linear Systems")[
  Fix a divisor $D_0 in CDiv(X)$, and let $LL=LL(D_0)$.
  - A _complete linear system_ of $D_0$ on $X$ is the set
  $|D_0| := {D in CDiv(X):text("effective such that") D tilde.op D_0},$
  which is from _(7.7)_ in 1-1 correspondence with the set
  $(Gamma(X, LL) without {0})/k^times simeq PP(Gamma(X, LL)).$
  - A _linear system_ $dd$ of $D_0$ on $X$ is a subset of $|D_0|$, which is a linear subspace for $PP(Gamma(X, LL))$.
  Note that the map $( dot )_0:Gamma(X, LL) -> CDiv(X)$ gives a 1-1 correspondence:
  ${V subset Gamma(X, LL): k text("-vec to r subspace")} &arrow.l.r.long {dd subset |D_0|:text("linear system")}, {s in Gamma(X, LL):(s)_0 in dd} union {0} &mapsfrom.long quad quad dd, V quad quad & mapsto {(s)_0:0 != s in V}.$
  - The _dimension_ of the linear system $dd$ is defined to be $dim dd := dim PP(V)= dim V-1$.
]

#definition(title: "Base Point")[
  A point $P in X$ is a _base point_ of a linear system $dd$ if $P in Supp D$ for every $D in dd$. Here, $Supp D$ denotes the set $Supp D=union.big{Y subset X:text("prime divisor of") D}$.
]

#lemma-box(title: "Fact 7.C")[
  For any nonzero $s in Gamma(X, LL)$, the support $Supp(s)_0=X without X_s$, where $X_s$ denotes the open subset $X_s={P in X:s_P in.not mm_P LL_P}$.
]
#proof[
  This question is local, so we may assume $X=Spec A$ so that $LL=OO_X$. Then, we have $0 != s in A, X_s=D(s)$, so $X without X_s=V(s)$. Note that
  $s_P in.not mm_P LL_P=mm_P arrow.l.r.double.long s(P)=s_P mod mm_P != 0 quad text("in") k(P)=OO_(X,P)/mm_P=k.$
  Thus, there are no prime divisors on $X_s$, which implies that the prime divisors of $(s)_0$ are the irreducible components of $V(s)$, whence $Supp(s)_0=V(s)$.
]

#lemma(number: 7.8)[
  Let $dd$ be a linear system on $X$ corresponding to the $k$-vector subspace $V subset Gamma(X, LL)$. Then,
  + *(i).* A point $P in X$ is a base point of $dd arrow.l.r.double.long s_P in mm_P LL_P$ for every $s in V$.
  + *(ii).* $dd$ is base-point-free  $arrow.l.r.double.long LL$ is generated by the global sections in $V$.
]
#proof[
  (i) This is clear from _(7.C)_. For (ii), we see that:
  $dd subset |D_0| text("is base-point-free") & arrow.l.r.double.long text("For every") P in X, P text("is not a base point"). & arrow.l.r.double.long text("For every") P in X, exists s in V text("such that") s_P in.not mm_P LL_P. & arrow.l.r.double.long text("For every") P in X, LL_P=OO_(X,P) spn {s:s in V}. & arrow.l.r.double.long LL text("is globally generated by") {s:s in V}.$
]
