#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Differentials
=== Kaehler Differential

#definition(title: "Deriviations")[
  Given $A in Ring ,\ B in ALG_A$ and $M in MOD(B)$. An $A$-_deriviation_ of $B$ into $M$ is a map $d:B to M$ satisfying:
  + *(D1).* $d$ is additive.
  + *(D2).* $d(bb')=op("bdb")'+b' op("db")$ for every $b,b' in B$.
  + *(D3).* $op("da")=0$ for every $a in A$.
  The set of all $A$-deriviations of $B$ into $M$ is denoted by $Der_A(B,M)$.
]
#definition(title: "Modules of Relative Differential Forms")[
  Given $A$ and $B$ as above. The _module of relative differential forms_ of $B$ over $A$ is a pair $chevron.l op("Omega")_(B/A),d chevron.r$, where $op("Omega")_(B/A) in MOD(B)$ and $d in Der_A(B,op("Omega")_(B/A))$, satisfying the _Universal Property_: for any $M in MOD(B)$, and any $d' in Der_A(B,M)$, there exists a unique homomorphism $f:op("Omega")_(B/A) arrow.r.long M$ such that $d'=op("fd")$.
]
#remark[
  Let $F in MOD(B)$ be a free module with a $B$-basis of symbols $op("db"):b in B$. Consider the set
  $
    F' := B spn d(b+b')-op("db")-op("db")',\ d(bb')-op("bdb")'-b' op("db"),\ op("da")\ |\ b,b' in B,\ a in A,
  $
  which is a $B$-submodule of $F$. We define $op("Omega")_(B/A) := F/F' in MOD(B)$ with $A$-deriviation given by
  $
    d:B arrow.r.long F/F',op("quad") b mapsto op("db")+F'.
  $
  Further, we have a natural isomorphism $Der_A(B,M)attach(isolongto, b: "Ab")op("Hom")_(B)(op("Omega")_(B/A),M)$ in $M in MOD(B)$.
]
#proof[
  We show that such construction satisfies the _Universal Property_. Given any pair $chevron.l M,d' chevron.r$, we define
  $
    f:F/F' arrow.r.long M,op("quad") op("db")+F' mapsto d'b,
  $
  which is clearly $B$-linear and we have $op("fd")=d'$. Suppose there is another homomorphism $f':F/F' arrow.r.long M$ such that $f'd=d'$. Then we have $f'd=d'=op("fd")$. But $d$ is surjective, which implies that the homomorphism $f'=f$ is unique.
]
#proposition(number: "8.1")[
  Let $B in ALG_A$, and let $f:B times.o_op("AB") arrow.r.long B$ be the natural "diagonal homomorphism" defined by $b times.o b mapsto b$, and set $I := Ker f$. Regarding $B times.o_op("AB") in MOD(A)$, then $I/I^2$ has a $B$-module structure given by
  $
    op("Bop")("times") I/I^2 arrow.r.long I/I^2,op("quad") b dot (b' times.o b''+I^2) mapsto bb' times.o b''+I^2.
  $
  Now, define a map
  $
    d:B arrow.r.long I/I^2,op("quad") b mapsto (1 times.o b-b times.o 1)+I^2.
  $
  Then, the pair $chevron.l I/I^2,d chevron.r$ gives a relative differential form $op("Omega")_(B/A)$.
]
#proof[
  (I) _Check._ $d in Der_A(B,I/I^2)$ is an $A$-deriviation.
  + *(D1).* This is easy.
  + *(D2).* Note that $(1 times.o b-b times.o 1)(1 times.o b'-b' times.o 1) in I^2$, which implies $1 times.o bb'+bb' times.o 1=b times.o b'+b' times.o b$ in $I/I^2$. Thus, for any $b,b' in B$, we have
  $
    op("bdb")'+b' op("db") & =b(1 times.o b'-b' times.o 1)+b'(1 times.o b-b times.o 1)+I^2 \
                           & =b times.o b'-bb' times.o 1+b' times.o b-bb' times.o 1+I^2 \
                           & =1 times.o bb'-bb' times.o 1+I^2=d(bb').
  $
  + *(D3).* Clearly, $op("da")=1 times.o a-a times.o 1+I^2=0+I^2$ for all $a in A$.
  (II) _Claim._ The pair $chevron.l I/I^2,d chevron.r$ satisfies the _Universal Property_ of $op("Omega")_(B/A)$.
  - _Claim_. The kernel $I$ is generated by $1 times.o b-b times.o 1:\ b in B$.
  Clearly, $1 times.o b-b times.o 1 in I$ for every $b in B$. On the other hand, we note that for any $b times.o b' in B times.o_op("AB")$, we have
  $
    b times.o b'=bb' times.o 1+b(1 times.o b'-b' times.o 1).
  $
  Now, suppose $op("sum")_op("ia")_i(b_i times.o b_i') in I$, then $op("sum")_op("ia")_op("ib")_op("ib")_i'=f(op("sum")_op("ia")_i(b_i times.o b_i'))=0$, whence
  $
    op("sum") a_i(b_i times.o b_i')=op("underbrace")op("sum") a_i(b_op("ib")_i' times.o 1)_=0+op("sum") a_op("ib")_i(1 times.o b_i'-b_i' times.o 1) in B spn 1 times.o b-b times.o 1:\ b in B.
  $
  - For any pair $chevron.l M,d' chevron.r$ with $M in MOD(B)$ and $d' in Der_A(B,M)$, we define
  $
    h:I/I^2 arrow.r.long M,op("quad")1 times.o b-b times.o 1+I^2 mapsto d'b,
  $
  which is clearly $B$-linear and satisfies $d'=op("hd")$. Further, $d$ is surjective, which shows that such $h$ must be unique.
]
#proposition(number: "8.2")[
  If $A',B in ALG_A$, and $B' := B times.o_AA'$. Then, $op("Omega")_(B'/A') simeq op("Omega")_(B/A) times.o_op("BB")'$ (as $B'$-modules). Further, if $S subset B$ is multiplicatively closed, then $op("Omega")_S^(-1)B/A simeq S^(-1)op("Omega")_(B/A)$.
]
#proof[
  Let $chevron.l op("Omega")_(B/A),d chevron.r$ be the differential form of $B/A$. First, note that
  $
    op("Omega")_(B/A) times.o_op("BB")'=op("Omega")_(B/A) times.o_B(B times.o_AA') simeq op("Omega")_(B/A) times.o_AA'.
  $
  - We consider the map $d' := d times.o op("mathds")1:B'=B times.o_AA' to op("Omega")_(B/A) times.o_AA'$, which clearly satisfies (D1) and (D3). For (D2), we see that
  $
    (d times.o op("mathds")1)((b_1 times.o a_1')(b_1 times.o a_2')) &=(d times.o op("mathds")1)(b_1b_2 times.o a_1'a_2')=d(b_1b_2) times.o a_1'a_2'\ &=(b_1op("db")_2+b_2op("db")_1) times.o a_1'a_2'\ &=b_1op("db")_2 times.o a_1'a_2'+b_2op("db")_1 times.o a_1'a_2'\ &=(b_1 times.o a_1')(op("db")_2 times.o a_2')+(b_2 times.o a_2')(op("db")_1 times.o a_1'),
  $
  for any $b_1 times.o a_1',b_2 times.o a_2' in B times.o_AA'=B$. Therefore, $d' in Der_A'(B',op("Omega")_(B/A) times.o_AA')$.
  - _Claim._ The pair $chevron.l op("Omega")_(B/A) times.o_AA',d' chevron.r$ satisfies the _Universal Property_ of $op("Omega")_(B'/A')$.
  Given any $M in MOD(B')$ and any $D' in Der_A'(B',M)$. Clearly, the composition $D'i$ is an $A$-deriviation of $B$ into $M$, i.e. $D'i in Der_A(B,M)$, where $i:B arrow.r.hook B',\ b mapsto b times.o 1$ is the canonical injection of $B$-algebras. By the _Universal Property_ of $op("Omega")_(B/A)$, $exists \ D in Der_A(op("Omega")_(B/A),M)$ for which $D'i=op("Dd")$. Now, consider the $B'$-module homomorphism
  $
    E:op("Omega")_(B/A) times.o_AA' arrow.r.long M,op("quad") c times.o a mapsto a' op("Dc").
  $
  Then, for any $b times.o a' in B'$, we have
  $
    op("Ed")'(b times.o a')=E(op("db") times.o a')=a'D(op("db"))=a'D'i(b)=a'D'(b times.o 1)=D'(b times.o a').
  $
  Therefore, $op("Ed")'=D'$ as required. The uniqueness is clear, so we get $chevron.l op("Omega")_(B/A) times.o_op("BB")',d' chevron.r simeq op("Omega")_(B'/A')$.
]
#example(title: "8.2.1")[
  Consider $B=A[x_1, dots.c ,x_n]$. Then $op("Omega")_(B/A) in MOD(B)$ is a free module of rank $n$ generated by $op("dx")_1, dots.c ,op("dx")_n$. In general, for $B=A[x_i_i in I]$, the $B$-module $op("Omega")_(B/A)$ is free with a $B$-basis $op("dx")_i_i in I$.
]
#proof[
  Clearly, $op("dx")_i_i in I$ generates $op("Omega")_(B/A)$, so it suffices to show that $op("dx")_i_i in I$ is $B$-linearly independent. Suppose $op("sum") f_op("idx")_i=0$ ($f_i in B$). For any $j in I$, consider the $j$th partial derivative $op("partial")/op("partial") x_j in Der_A(B,B)$. Then $chevron.l B,op("partial")/op("partial") x_j chevron.r$ gives a pair. By _Universal Property_ of $op("Omega")_(B/A),\ exists$ unique $op("Omega")_(B/A) arrow.r.long B$ such that $op("theta")_op("jd")=op("partial")/op("partial") x_j$. It follows that $op("theta")_j(op("dx")_i)=op("partial") x_i/op("partial") x_j=op("delta")_(op("ij"))$ for every $i in I$. Thus, we have
  $
    0=op("theta")_j(op("sum") f_op("idx")_i)=op("sum") f_op("iop")("theta")_j(op("dx")_i)=op("sum") f_op("iop")("delta")_(op("ij"))=f_j
  $
  for every $j in I$. Therefore, $op("dx")_i_i in I$ is $B$-linearly independent.
]
#lemma(number: "8.A (Categorical Fact")[
  Suppose we have morphisms $A arrow.r.long B arrow.r.long C$ in an Abelian category $Af$ such that $op("uv")=0$ and $u$ is epi. If the sequence
  $
    op("Hom")_Af (A,T) arrow.l.long op("Hom")_Af (B,T) arrow.l.long op("Hom")_Af (C,T)
  $
  is exact (in $Ab$) for every $T in Ob Af$. Then, $(B arrow.r.long C)= Coker (A arrow.r.long B)$, and thus, (this is equivalent to that) the sequence $A to B to C to 0$ is exact in $Af$.
]
#proof[
  Consider $T := Coker (A arrow.r.long B) in Af$ with $B arrow.r.long T$. Then, we have $op("pv")=0$. By _exactness_, $exists \ op("alpha") in op("Hom")_Af (C,T)$ such that $op("alpha") u=p$. Note that the morphism $B arrow.r.long C$ satisfies $op("uv")=0$, it follows from the _Universal Property of Cokernel (or Coequalizer)_, $exists$ unique $T arrow.r.long C$' with $op("theta") p=u$. Now, $u=op("theta") p=op("theta")op("alpha") u$, but $u$ is epi, so $op("theta")op("alpha")=op("mathds")1_C$; on the other hand, $op("alpha")op("theta") p=op("alpha") u=p$, but $chevron.l T,p chevron.r= Coker v$, i.e. $p$ is epi, so $op("alpha")op("theta")=op("mathds")1_T$. Therefore, $C=T$, and thus, $(B arrow.r.long C)= Coker (A arrow.r.long B)$.
]
#remark(title: "8.A*")[
  As a special case of _(8.A)_. Suppose the morphism $A arrow.r.long B$ is mono [resp. epi]. If one can show that the map $op("Hom")_Af (A, Coker v) arrow.l.long op("Hom")_Af (B, Coker v)$ is epi [resp. $op("Hom")_Af (A,A) arrow.l.long op("Hom")_Af (B,A)$ is mono], then $A arrow.r.long B$ is an isomorphism.
]
#proposition(number: "8.3. (1st Fundamental Exact Sequence")[
  Consider the ring homomorphisms $A arrow.r.long to B arrow.r.long C$. Then there is a natural exact sequence of $C$-modules:
  $
    op("Omega")_(B/A) times.o_op("BC") arrow.r.long op("Omega")_(C/A) arrow.r.long op("Omega")_(C/B) arrow.r.long 0.
  $
]
#proof[
  We apply the categorical fact _(8.A)_. First, we define the maps
  $
    v:op("Omega")_(B/A) times.o_op("BC") & arrow.r.long \
                      op("Omega")_(C/A), & u:op("Omega")_(C/A)               & arrow.r.long \
                      op("Omega")_(C/B), \
                      d_(B/A)b times.o c & mapsto c dot d_(C/A)op("psi")(b). &     d_(C/A)c & mapsto \
                               d_(C/B)c,
  $
  which are clearly $C$-linear.
  - Note that $u$ is clearly surjective. Further, for any $b in B$ and $c in C$, we have
  $
    op("uv")(d_(B/A)b times.o c)=u(c dot d_(C/A)op("psi")(b))=c dot u(d_(C/A)op("psi")(b))=c dot op("underbrace")d_(C/B)op("psi")(b)_=0=0.
  $
  - Now, it suffices to show that the exactness of the sequence $op("Hom")_(C)(-,T)$ for any $T in MOD(C)$, which can be rewrite as
  #remark[Diagram.]
  where $op("alpha")$ is just the map $D mapsto D$. Since we already have $op("uv")=0$, it only remains to show that $Ker (- compose op("psi")) subset Im op("alpha")$. Suppose $D in Der_A(C,T)$ with $op("Dop")("psi")=0$, i.e. the differential is $0$ on $B$, so we may extend $D$ to a $B$-deriviation of $C$, i.e. $D in Der_B(C,T)$.
]
#proposition(number: "8.4. (2nd Fundamental Exact Sequence")[
  Let $B in ALG_A,\ op("Iop")("triangleleft") B$, and $C=B/I$. Then there is a natural exact sequence of $C$-modules:
  $
    I/I^2 arrow.r.long op("Omega")_(B/A) times.o_op("BC") arrow.r.long op("Omega")_(C/A) arrow.r.long 0,
  $
  where $op("delta")$ is a $C$-module homomorphism defined by
  $
    op("delta"):I/I^2 arrow.r.long op("Omega")_(B/A) times.o_op("BC"),op("quad") b+I^2 mapsto d_(B/A)b times.o 1.
  $
]
#proof[
  We again apply the fact _(8.A)_ and use the notations in _(8.3)_.
  - Note that $op("Omega")_(C/A)$ is generated by $d_(C/A)op("bar")b$ (where $op("bar")b=b+I in C,\ b in B$). Further, we have $v(d_(B/A)b times.o 1)=d_(C/A)op("psi")(b)=d_(C/A)op("bar")b$. Thus, $v$ is surjective.
  - For any $b in I$, we have $op("bar")b=0$ in $C$, so $op("vop")("delta")(b+I^2)=v(d_(B/A)b times.o 1)=d_(C/A)op("bar")b=0.$
  - For any $T in MOD(C)$, we again rewrite the sequence $op("Hom")_(C)(-,T)$:
  #remark[Diagram.]
  Again, we have only to show that  $Ker ( dot )|_I subset Im (- compose op("psi"))$. Indeed, if $D in Der_A(B,T)$ with $D|_I=0$, this clearly lifts to an $A$-deriviation $B/I to T$.
]
#corollary(number: "8.5")[
  Let $B in fg ALG_A$ or $B=S^(-1)R$ for some $R in fg ALG_A$, then $op("Omega")_(B/A) in fg MOD(B)$.
]
#proof[
  In the first case, write $B=A[x_1, dots.c ,x_n]/I$. From _(8.4)_, the map $op("Omega")_(A[x_1, dots.c ,x_n]/A) times.o_A[x_1, dots.c ,x_n]B arrow.r.long op("Omega")_(B/A)$ is surjective. Further, $op("dx")_i times.o 1_i=1^n$ is a $B$-basis of $op("Omega")_(A[x_1, dots.c ,x_n]/A) times.o_A[x_1, dots.c ,x_n]B$, which implies that $op("Omega")_(B/A)$ is finitely generated by $d_(B/A)op("bar")x_i_i=1^n$ over $B$. Now, for the second case, we see that
  $
    op("Omega")_(B/A)=op("Omega")_S^(-1)R/op("Aattach")(simeq, b: "text(\"(8.2)\")")S^(-1)op("Omega")_(R/A)=S^(-1)R spn d_(R/A)op("bar")x_i/1_i=1^n in fg MOD(B).
  $
]
#lemma(number: "8.B")[
  Let $k subset K subset L$ be finitely generated field extensions. We have the following four cases:
  + *(i).* If $L/K$ is purely transcendental, then $rank_op("Lop")("Omega")_(L/k)= rank_op("Kop")("Omega")_(K/k)+ trdeg_op("KL")$.
  + *(ii).* If $L/K$ is algebraic and separable, then $rank_op("Lop")("Omega")_(L/k)= rank_op("Kop")("Omega")_(K/k)$.
  + *(iii).* If $L=K(t)$ is algebraic but purely inseparable over $K$, then $rank_op("Lop")("Omega")_(L/k) >= rank_op("Kop")("Omega")_(K/k)$.
  + *(iv).* If, in general, $L/K$ is algebraic and purely inseparable, then $rank_op("Lop")("Omega")_(L/k) >= rank_op("Kop")("Omega")_(K/k)$.
]
#proof[
  Note that $L/k$ is finitely generated, so $rank_op("Lop")("Omega")_(L/k)< in op("fty")$ by _(8.5)_. Put $r := trdeg_op("KL")$, which is finite since $L/K$ is finitely generated. Further, we may assume $K subset.neq L$, otherwise the result is clear.\
  (i) $L/K$ is purely transcendental, say $L=K(t_1, dots.c ,t_r)$. Put $B := K[x_1, dots.c ,x_r]$, then $L simeq Frac B$ (over $K$). In this case, the exact sequence in _(8.3)_ becomes
  $
    0 arrow.r.long op("Omega")_(K/k) times.o_op("KB") arrow.r.long op("Omega")_(B/k) arrow.r.long op("Omega")_(B/K) arrow.r.long 0,
  $
  and it splits since $v$ has a left inverse given by:
  $
    w:op("Omega")_(B/k) arrow.r.long op("Omega")_(K/k) times.o_op("KB"),op("quad") d_(B/k)f mapsto op("sum")_(op("alpha")=(op("alpha")_1, dots.c ,op("alpha")_r))d_(K/k)f_op("alpha") times.o x_1^(op("alpha")_1) dots.c x_r^(op("alpha")_r).
  $
  Now, we get
  $
    op("Omega")_(B/k) simeq (op("Omega")_(K/k) times.o_op("KB")) plus.o op("Omega")_(B/K)attach(=, b: "text(\"(8.2.1)\")")(op("Omega")_(K/k) times.o_op("KB")) plus.o op("Bdx")_1 plus.o dots.c plus.o op("Bdx")_r,\
    op("Omega")_(L/k)attach(simeq, b: "text(\"(8.2)\")") Frac op("Omega")_(B/k) simeq (op("Omega")_(K/k) times.o_op("KL")) plus.o op("Ldt")_1 plus.o dots.c plus.o op("Ldt")_r,
  $
  whence $rank_op("Lop")("Omega")_(L/k)= rank_op("Kop")("Omega")_(K/k)+r$.\
  (ii) If $L/K$ is algebraic and separable, since $L/K$ is finitely generated, it is also finite separable. By _Primitive Element Theorem_, $exists \ t in L$ such that $L=K(t)$. Let $f in K[x]$ be the minimal polynomial of $t$ of degree $n >= 2$, then $t^k_k=0^n-1$ is a $K$-basis for $L$. Now, to see the ranks are equal, it suffices to show that $op("Omega")_(K/k) times.o_op("KL") arrow.r.long op("Omega")_(L/K)$ defined in _(8.3)_ is an isomorphism.
  - _Claim._ $op("Omega")_(L/K)=0$. Given any $d in Der_K(L,op("Omega")_(L/K))$. For any $op("alpha") in L$, since $L/K$ is finite separable, we have $g(op("alpha"))=0$ but $g'(op("alpha")) != 0$ for some polynomial $g in K[x]$. It follows that $0=op("df")(op("alpha"))=f'(op("alpha"))op("dop")("alpha")$, whence $op("dop")("alpha")=0$. But $op("Omega")_(L/K)$ is generated by the set $op("dop")("alpha"):\ op("alpha") in L$, thus, $op("Omega")_(L/K)=0$.
  - Now, apply $op("Omega")_(L/K)=0$ to the exact sequence in _(8.3)_, then $v$ is surjective. Finally, to show that $v$ is injective, it is enough to show that the map
  #remark[Diagram.]
  is surjective for any $T in MOD(L)$. Now, for any $D in Der_k(L,T)$, we define
  $
    E:L arrow.r.long T,op("quad")\ op("sum")_(k=0)^(n-1)a_op("kt")^k mapsto \ op("sum")_(k=0)^(n-1)t^op("kDa")_k.
  $
  It is easy to show that $E in Der_k(L,T)$ and that $E mapsto D$.
  (iii) Suppose $L=K(t)$ is algebraic but purely inseparable over $K$. In this case, we may assume that $t in.not K,\ Char k=p>0$, and $e >= 1$ is the minimal for which $a=t^(p^e) in K$. I claim that
  $
    rank_op("Lop")("Omega")_(L/k)=op("left")op("begin")op("arraylc")
    rank_op("Kop")("Omega")_(K/k)+1, & text("if") \
                         d_(K/k)a=0; \
      rank_op("Kop")("Omega")_(K/k), & text("if") \
                      d_(K/k)a != 0. \
    op("end")op("arrayop")("right").
  $
  Note that $f := x^(p^e)-a in K[x]$ is the minimal polynomial of $t$, and that $L simeq K[x]/chevron.l f chevron.r$. Now,
  $
    op("Omega")_(L/K) &attach(simeq, b: "text(\"(8.4)\")")(op("Omega")_(K[x]/k) times.o_K[x]L)/ Im op("delta") attach(simeq, b: "text(\"(i)\")")[(op("Omega")_(K/k) times.o_KK[x] plus.o K[x]op("dx")) times.o_K[x]L]/ Im op("delta")\ & simeq [(op("Omega")_(K/k) times.o_op("KL")) plus.o op("Ldx")]/ Im op("delta")
  $
  as $L$-modules, where $op("delta")op("bar")f=d_(K/k)f times.o 1=-d_(K/k)a times.o 1$. If $d_(K/k)a=0$, then clearly, $rank_op("Lop")("Omega")_(L/k)= rank_op("Kop")("Omega")_(K/k)+1$; otherwise, $op("delta")op("bar")f$ generates an $L$-subspace of $op("Omega")_(L/k)$ of rank $1$, so $rank_op("Lop")("Omega")_(L/k)= rank_op("Kop")("Omega")_(K/k)+1-1= rank_op("Kop")("Omega")_(K/k)$.\
  (iv) In general, if $L/K$ is algebraic and purely inseparable, say $L=K(t_1, dots.c ,t_m)$ with $t_i in.not K$. We have a chain of purely inseparable field extensions:
  $
    K subset K(t_1) subset K(t_1,t_2) subset dots.c subset K(t_1, dots.c ,t_m)=L.
  $
  Therefore, we have the inequality $rank_op("Lop")("Omega")_(L/k) >= rank_op("Kop")("Omega")_(K/k)$ by (iii).
]
#proposition(number: "8.C")[
  Let $k subset K subset L$ be finitely generated field extensions. Then
  $
    rank_op("Lop")("Omega")_(L/k) >= rank_op("Kop")("Omega")_(K/k)+ trdeg_op("KL"),
  $
  and the equality holds if $L$ is separably generated over $K$.
]
#proof[
  First, we write $L=K(t_1, dots.c ,t_n)$ such that $t_i_i=1^r$ is a transcendence basis for $L/K$. Write $E=K(t_1, dots.c ,t_r)$ so that $E/K$ is purely transcendental and $L/E$ is algebraic. From _(6.Bi)_, we have $rank_op("Eop")("Omega")_(E/k)= rank_op("Kop")("Omega")_(K/k)+r$, so we may now reduce to the case where $L/K$ is algebraic.
  Let $K_s$ denote the set of all separable elements of $L$ over $K$. Since $L/K$ is algebraic, now $K_s/K$ is finite separable, and $L/K_s$ is finitely generated and purely inseparable. It follows from _(8.Bii)_ that $rank_K_op("sop")("Omega")_(K_s/k)= rank_op("Kop")("Omega")_(K/k)$, so we reduce to the case (iv) of _(6.B)_. Therefore, we obtain the inequality.
  Now, suppose $L/K$ is separably generated, there exists a transcendence basis $t_i_i=1^r$ of $K/k$ for which $E=K(t_1, dots.c ,t_r)/K$ is purely transcendental and $L/E$ is separable algebraic. Therefore,
  $
    rank_op("Lop")("Omega")_(L/k)attach(=, b: "text(\"(6.Bii)\")") rank_op("Eop")("Omega")_(E/k)attach(=, b: "text(\"(6.Bi)\")") rank_op("Kop")("Omega")_(K/k)+r
  $
  as required.
]
#theorem(number: "8.6")[
  Let $K/k$ be a finitely generated field extension. Then,
  + *(i).* $rank_op("Kop")("Omega")_(K/k) >= trdeg_op("kK")$.
  + *(ii).* The equality holds $arrow.l.r.double.long \ K/k$ is separably generated.
  + *(iii).* Moreover, if $K/k$ is algebraic, then $op("Omega")_(K/k)=0\ arrow.l.r.double.long \ K/k$ is separable.
]
#proof[
  Now, (i) and the direction ($op("Leftarrow")$) of (ii) are just the special case of _(8.C)_. Further, we have shown the direction ($op("Leftarrow")$) of (iii) in _(8.Bii)_. It remains to show the direction ($op("Rightarrow")$) of both (ii) and (iii).
  (iii) Suppose $op("Omega")_(K/k)=0$, i.e. $rank_op("kop")("Omega")_(K/k)=0$, so $trdeg_op("kK")=0$. Now, for any intermediate field $k subset E subset K$, we have $rank_op("kop")("Omega")_(E/k)=0$. One can show that the cases (i), (iii) and (iv) in _(6.B)_ cannot happen, i.e. $K/k$ is separable and algebraic. (For example, the case (iii), since $op("Omega")_(E/k)=0$, we can only have $d_(E/k)a=0$, whence $rank_op("Kop")("Omega")_(K/k)=1>0$, a contradiction).
  (ii) Now, assume that $rank_op("Kop")("Omega")_(K/k)= trdeg_op("kK")=r >= 1$. Let $op("dx")_i_i=1^r$ be a $K$-basis for $op("Omega")_(K/k)$, then $op("dx")_i times.o 1_i=1^r$ forms a $K$-basis for $op("Omega")_(k(x_1, dots.c ,x_r)/k) times.o_k(x_1, dots.c ,x_r)K$. By _(8.3)_, this gives $op("Omega")_(K/k(x_1, dots.c ,x_r))=0$, whence $K/k(x_1, dots.c ,x_r)$ is separable and algebraic by (iii). Further, as $trdeg_op("kK")=r$, the set $x_i_i=1^r$ must form a transcendence basis for $K/k$, and hence, a separating transcendence basis. Therefore, $K/k$ is separably generated.
]
#proposition(number: "8.7")[
  Let $B$ be a local ring containing its residue field $k=B/ mm$. Then, the map\ $op("delta"): mm / mm^2 arrow.r.long op("Omega")_(B/k) times.o_op("Bk")$ defined in _(8.4)_ is an isomorphism.
]
#proof[
  Note that $op("Omega")_(k/k)=0$, so _(8.4)_ implies that $op("delta")$ is surjective. We have only to show that $op("delta")$ is injective.
  - Recall that the dual functor $( dot )^ast =op("Hom")_(D)(-,D)$ over a division ring $D$ is a contravariant exact functor, and thus, it suffices to show that the map
  $
    op("delta")':op("Hom")_(k)(op("Omega")_(B/k) times.o_op("Bk"),k) arrow.r.long op("Hom")_(k)( mm / mm^2,k)
  $
  is surjective.
  - We note that
  $
    op("Hom")_(k)(op("Omega")_(B/k) times.o_op("Bk"),k) simeq op("Hom")_(B)(op("Omega")_(B/k),k)= Der_k(B,k).
  $
  It follows that if $d in Der_k(B,k)$, then $op("delta")'(d)$ is obtained by restricting to $mm$, and that $d( mm^2)=0$.
  - We have a short exact sequence $0 to mm to B to k to 0$ of $B$-modules, but the fact that our $k subset B$ implies that such exact sequence splits, and hence, $B simeq mm plus.o k$.
  - Now, given any $h in op("Hom")_(k)( mm / mm^2,k)$, we define the $k$-deriviation
  $
    d:B arrow.r.long k,op("quad") b := c+op("lambda") mapsto h(c+ mm^2)=h(op("bar")c).
  $
  It is clear that $op("delta")'(d)=h$. Further, we see that
  $
    d(bb') &=d((c+op("lambda"))(c'+op("lambda")'))=d(op("cc")'+op("cop")("lambda")'+c' op("op")("lambda")+op("underbrace")op("lambda")op("lambda")'_in k)=h(op("underbrace")op("overl in e")op("cc")'_in mm^2+op("lambda")'op("bar")c+op("lambda")op("bar")c')\ &=h(op("bar")op("cop")("bar")c'+op("bar")c' op("op")("bar")c+op("lambda")'op("bar")c+op("lambda")op("bar")c') attach(=, b: "op(\"ktext\")(\"-l in ear\")")(c'+op("lambda")')h(op("bar")c)+(c+op("lambda"))h(op("bar")c')=b' op("db")+op("bdb")',
  $
  for any $b=c+op("lambda"),b'=c'+op("lambda")' in B$. Thus, $d in Der_k(B,k)$, and therefore, $op("delta")'$ is surjective.
]
#theorem(number: "8.8")[
  Let $B$ be a local ring containing its residue field $k=B/ mm$. Assume further that $k$ is perfect, and that $B=S^(-1)R$ for some $R in fg ALG_k$. Then,
  $
    op("Omega")_(B/k) in MOD(B)\ text("is a free module with")\ rank_op("Bop")("Omega")_(B/k)=op("dim") B\ arrow.l.r.double.long \ B\ text("is a regular local r in g").
  $
]
#proof[
  ($op("Rightarrow")$) Note that such $B$ is a Noetherian ring from our assumption. Suppose that $op("Omega")_(B/k)$ is a free $B$-module of rank $op("dim") B$. Then
  $
    op("dim")_k mm / mm^2attach(=, b: "text(\"(8.7)\")")op("dim")_k(op("Omega")_(B/k) times.o_op("Bk"))= rank_op("kop")("Omega")_(B/k)=op("dim") B.
  $
  Therefore, $B$ is a regular local ring. In particular, this implies that $B$ is an integral domain.
  ($op("Leftarrow")$) Suppose that $B$ is a regular local ring with $op("dim") B=r$. Then,
  $
    op("dim")_k(op("Omega")_(B/k) times.o_op("Bk"))attach(=, b: "text(\"(8.7)\")")op("dim")_k mm / mm^2attach(=, b: "B:\\ text(\"regular\")")op("dim") B=r.
  $
  On the other hand, let $K= Frac B$, then $op("Omega")_(B/k) times.o_op("BK")= Frac op("Omega")_(B/k)attach(=, b: "_(8.2)_")op("Omega")_(K/k)$. Now that $k$ is perfect, it follows from _(I, 4.8)_ that $K/k$ is separably generated, and thus,
  $
    r=op("dim") op("Battach")(=, b: "text(\"(I, 1.8)\")")op("dim")_op("Kop")("Omega")_(K/k)attach(=, b: "text(\"(8.6)\")") trdeg_op("kK").
  $
  Finally, our assumption of $B$ gives that $op("Omega")_(B/k) in fg MOD(B)$. We conclude that $op("Omega")_(B/k)$ is a free module of rank $r$ by using the following lemma _(8.9)_.
]
#lemma(number: "8.9")[
  Let $A$ be a Noetherian local domain, with residue field $k$ and $K= Frac A$. Suppose that $M in fg MOD(A)$ satisfies $op("dim")_k(M times.o_op("Ak"))=op("dim")_K(M times.o_op("AK"))=r$, then $M$ is free of rank $r$.
]
#proof[
  Since $op("dim")_k(M times.o_op("Ak"))=r$, the _Nakayama Lemma_ states that $M$ can be generated by $r$ elements, i.e. $exists$ surjective map $A^(plus.o r) arrow.r.long M$. Put $I := Ker op("phi")$. Note that $K$ is a flat $A$-module (as it is a field), i.e. $- times.o_op("AK")$ is an exact functor, we have an exact sequence
  $
    0 arrow.r.long I times.o_op("AK") arrow.r.long K^(plus.o r) arrow.r.long op("phi") times.o op("mathds")1M times.o_op("AK") arrow.r.long 0
  $
  of $A$-modules. Further, we have $op("dim")_K(M times.o_op("AK"))=r$, i.e. $M times.o_op("AK") simeq K^(plus.o r)$, so $S^(-1)I=I times.o_op("AK")=0$ where $S=op("Aop")("setm in us")0$. Thus, $exists \ s in S$ for which $op("sI")=0$. But $I$ is torsion-free (as it is a submodule of a free module), so $I=0$, and thus, $M simeq A^(plus.o r)$ is free of rank $r$.
]
