#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

=== Invertible Sheaves

#proposition(number: 6.12)[
  If $LL$ and $MM$ are invertible sheaves on a ringed space $X$, so is
  $tensor(LL, MM, OO_X)$. If $LL$ is any invertible sheaf on $X$, then there
  exists an invertible sheaf $LL^(-1)$ on $X$ such that
  $tensor(LL, LL^(-1), OO_X) simeq OO_X$.
]

#proof[
  For the first statement, note that $tensor(OO_X, OO_X, OO_X) simeq OO_X$.
  For the latter, take $LL^(-1) := LL^ast$. Then
  $tensor(LL^ast, LL, OO_X) simeq HHom_(OO_X)(LL, LL) = OO_X$ by _[5.1]_.
]

#definition(title: "Picard Group")[
  For any ringed space $X$, define the *Picard group* on $X$, denoted
  $Pic(X)$, to be the group of isomorphism classes of invertible sheaves on
  $X$, under the operation $tensor(#none, #none, OO_X)$. Note that _(6.12)_
  shows that $(Pic(X), tensor)$ is a group with identity $OO_X$.
]

#definition(title: "Associated Sheaf to Cartier Divisors")[
  Fix a scheme $X$ and let $D in CDiv(X)$ be represented by ${ (U_i, f_i) }$.
  Define $LL(D)$ to be the $OO_X$-submodule of $KK_X$ generated locally by
  $f_i^(-1)$ on $U_i$. This is well-defined, since
  $f_i / f_j in OO_X^times (U_i inter U_j)$, so both $f_i^(-1)$ and
  $f_j^(-1)$ generate the same $OO_X$-submodule. In particular,
  $LL(0) = OO_X$.
]

#lemma(
  number: "6.D", // number: 6.D
)[
  Given $X in Sch$ and any $U in TT_X$, then
  $
    f in KK_X(U) text(" is a unit")
    arrow.l.r.double.long
    f_x in KK_(X, x) text(" is ") OO_(X, x) text("-torsion-free for every ")
    x in U.
  $
]

#proof[
  The case $U = emptyset$ is clear, so assume $U != emptyset$.

  - Suppose $f in KK(U)$ such that $f(x) in KK_x^times$ for every $x in U$
    (note $KK_x$ equals the stalk of the presheaf total quotient ring). Take
    $g(x) := f(x)^(-1)$ for each $x in U$; this defines $g$ in the presheaf
    total quotient ring on $U$. We check that $g in KK(U)$. Indeed, if
    $x in U$, then there exists $V in NN_x(X)$ with $V subset U$ and
    $s$ in the presheaf total quotient ring on $V$ such that
    $f(y) = s_y$ in the presheaf stalk for every $y in V$. Now, if $t$ is a
    presheaf section on $W$ with $t_y = (s_y)^(-1)$ in the presheaf stalk for
    every $y in V inter W$, then $g(y) = t_y$ for every $y in V inter W$,
    which shows that $g in KK(U)$. Further, it is easy to see that
    $g in KK(U)^times$. Therefore,
    $
      f in KK(U)^times
      arrow.l.r.double.long
      f(x) in KK_x^times text(" for every ") x in U.
    $
    It remains to prove the following claim.

  - *Claim.* $f(x) in KK_x^times$ for every $x in U$ iff $f(x)$ is
    $OO_x$-torsion-free, i.e. $Ann_(OO_x)(f(x)) = 0$, for every $x in U$.

    $(Rightarrow)$ Given $x in U$, if $s in Ann_(OO_x)(f(x))$, then
    $s dot f(x) = 0$ in $KK_x$, hence $s = 0$ since $f(x)$ is a unit.

    $(Leftarrow)$ Given $x in U$, there exists $V in NN_x(X)$ with
    $V subset U$ such that $f(y) = (a \/ s)_y$ for every $y in V$, where
    $a in OO_X(V)$ and $s in OO_(X, reg)(V)$. Since $f(y)$ is
    $OO_y$-torsion-free for each $y in V$, so is each $a_y in OO_y$. Thus
    $a_y in OO_y$ is regular for every $y in V$, i.e.
    $a in OO_(X, reg)(V)$. Therefore $f(x) = (a \/ s)_x in KK_x$ is a unit.
]

#corollary(
  number: "6.E", // number: 6.E
)[
  Let $X$ be a scheme and $LL$ be an invertible $OO_X$-submodule of $KK_X$.
  Then, for each $x in X$, the stalk $LL_x$ is an $OO_(X, x)$-submodule of
  $KK_(X, x)$ generated by a unit.
]

#lemma(
  number: "6.F", // number: 6.F
)[
  #set enum(numbering: "i)", spacing: 1em)

  + *(Algebraic Fact).* Given $A in Ring$ and $B in ALG_A$. Suppose $M, N$ are
    $A$-submodules of $B$ such that one of them is generated by a regular
    element of $B$ over $A$. Then the natural homomorphism
    $
      tensor(M, N, A) arrow.r.twohead_(ALG_A) M dot N, quad
      m times.o n mapsto m n,
    $
    is an isomorphism.

  + For $X in Sch$ and $OO_X$-submodules $FF, GG$ of $KK_X$, define
    $FF dot GG in ALG_(OO_X)$ to be the sheafification of
    $U mapsto FF(U) dot GG(U)$. If both $FF$ and $GG$ are invertible sheaves,
    then the canonical morphism
    $tensor(FF, GG, OO_X) arrow.r.twohead_(ALG_(OO_X)) FF dot GG$ is an
    isomorphism.
]

#proof[
  Part (ii) follows from _(6.E)_ and (i).
]

#proposition(number: 6.13)[
  Let $X$ be a scheme. Then:

  #set enum(numbering: "a)", spacing: 1em)

  + For any $D in CDiv(X)$, the subsheaf $LL(D)$ is an invertible sheaf on
    $X$. The map $D mapsto LL(D)$ gives a one-to-one correspondence
    $
      CDiv(X) arrow.l.r.double.long
      { text("invertible subsheaves of ") KK_X }.
    $

  + $LL(D_1 - D_2) simeq tensor(LL(D_1), LL(D_2)^(-1), OO_X)$.

  + $D_1 tilde.op D_2 arrow.l.r.double.long LL(D_1) simeq LL(D_2)$ as
    invertible $OO_X$-modules.
]

#proof[
  *(a).* We proceed in three steps.

  - *(I).* Given any $D = { (U_i, f_i) } in CDiv(X)$, show that $LL(D)$ is
    invertible.

    For each $i$, consider the morphism
    $phi_i: OO_X|_(U_i) -> LL(D)|_(U_i)$ given by
    $
      (phi_i)_V: OO_X(V) -> LL(D)(V), quad
      1 mapsto f_i^(-1)|_V
      text(" for every ") V subset U_i.
    $
    This induces
    $(phi_i)_x: OO_x -> LL(D)_x, 1_x mapsto (f_i^(-1))_x$ for each
    $x in U_i$. From the definition of $LL(D)$, we have
    $LL(D)_x = OO_x spn { (f_i^(-1))_x }$, and
    $(f_i^(-1))_x, (f_j^(-1))_x$ generate the same $OO_x$-submodule, since
    $(f_i^(-1))_x \/ (f_j^(-1))_x$ is invertible in $LL(D)_x$. It follows that
    $(phi_i)_x$ is an isomorphism for each $x in U_i$, whence
    $phi_i: OO_X|_(U_i) isoto LL(D)|_(U_i)$ for every $i$. Therefore,
    $LL(D)$ is an invertible $OO_X$-module.

  - *(II).* For any invertible $OO_X$-submodule $LL$ of $KK$, construct a
    Cartier divisor.

    - Cover $X$ with an open cover ${U_i}$ such that
      $LL|_(U_i) simeq OO_X|_(U_i)$ for all $i$. For each $i$, pick
      $f_i in LL(U_i) subset KK(U_i)$ corresponding to $1 in OO(U_i)$ under
      this isomorphism.

    - *Check.* $f_i in KK^times (U_i)$ for each $i$. By _(6.D)_, it suffices
      to show that $(f_i)_x in LL_x subset KK_x$ is $OO_x$-torsion-free for
      every $x in U_i$. This is clear since $LL_x simeq OO_x$.

    - *Claim.* ${ (U_i, f_i) } in CDiv(X)$. Indeed, for any $i, j$, since
      $LL|_(U_i) simeq OO_X|_(U_i)$ and $LL|_(U_j) simeq OO_X|_(U_j)$, both
      $f_i|_j$ and $f_j|_i$ generate $LL(U_(i j))$ over $OO_X(U_(i j))$,
      where $U_(i j) := U_i inter U_j$. Hence there exists
      $u in OO_X(U_(i j))$ such that $f_i|_j = u dot f_j|_i$, i.e.
      $(f_i^(-1)|_j) \/ (f_j^(-1)|_i) in
      OO_X (U_(i j))^times = OO_X^times (U_(i j))$.

    - *Check.* ${ (U_i, f_i^(-1)) }$ is independent of the choice of the open
      cover ${U_i}$. Thus ${ (U_i, f_i^(-1)) } in CDiv(X)$ is a well-defined
      Cartier divisor.

  - *(III).* Check the constructions are inverse to each other.

    - For any Cartier divisor $D in CDiv(X)$,
      $
        D = { (U_i, f_i) } & mapsto LL(D): text(" generated by ") {f_i^(-1)}
                             text(" with ") 1 in OO_X|_(U_i) isoto f_i^(-1)
                             in LL|_(U_i) \
                           & mapsto { (U_i, (f_i^(-1))^(-1)) } = D.
      $

    - For any invertible $OO_X$-submodule $LL subset KK$ with
      $f_i in LL|_(U_i) isoto 1 in OO_X|_(U_i)$, we have
      $
        LL mapsto { (U_i, f_i^(-1)) } = D
        mapsto LL(D): text(" generated by ") { (f_i^(-1))^(-1) } = {f_i},
      $
      whence $LL(D) = LL$.

  *(b).* By choosing a common refinement of open covers, assume
  $D_1 = { (U_i, f_i) }$ and $D_2 = { (U_i, g_i) }$, where
  $f_i, g_i in KK^times (U_i)$. Then $D_1 + D_2 = { (U_i, f_i g_i) }$.
  For each $x in X$,
  $
    LL(D_1 + D_2)_x & = OO_x spn { (f_i g_i)^(-1)_x }
                      = OO_x spn { (f_i)^(-1)_x (g_i)^(-1)_x } \
                    & = (LL(D_1) LL(D_2))_x,
  $
  whence
  $
    LL(D_1 + D_2) = LL(D_1) dot LL(D_2)
    isoBy("(6.F)") tensor(LL(D_1), LL(D_2), OO_X).
  $

  *(c).* By (b), it suffices to show that
  $D := D_1 - D_2$ is principal iff $LL(D) simeq OO_X$.

  - $(Rightarrow)$ If $D tilde.op 0$, then $LL(D) simeq OO_X$. Indeed, if
    $D = { (X, f) }$, then $LL(D)$ is globally generated by $f^(-1)$.

  - $(Leftarrow)$ If $LL(D) simeq OO_X$, say
    $f in LL(D)(X) isoto 1 in OO_X (X)$. Thus
    ${ (X, f^(-1)) }$ is principal.
]

#corollary(number: 6.14)[
  For any scheme $X in Sch$, we have an injective group homomorphism
  $
    CaCl(X) -> Pic(X), quad D mapsto LL(D),
  $
  where $CaCl(X)$ denotes the group of Cartier divisors modulo linear
  equivalence.
]

#proposition(number: 6.15)[
  If $X$ is an integral scheme, then the homomorphism in _(6.14)_ is an
  isomorphism.
]

#proof[
  - From _(6.14)_, it suffices to show that the homomorphism
    $CaCl(X) -> Pic(X)$ is surjective. By _(6.13a)_, we only have to show
    that every invertible sheaf is isomorphic to a subsheaf of $KK_X$.

  - Since $X$ is integral, it follows from _(6.Ciii)_ that $KK_X$ is the
    constant sheaf of $K = K(X)$.

  - For any $LL in Pic(X)$, consider
    $MM := tensor(LL, KK_X, OO_X) in MOD(OO_X)$. Since $LL$ is invertible,
    there exists an open cover ${U_i}$ of $X$ such that
    $LL|_(U_i) simeq OO_X|_(U_i)$. Then
    $
      MM|_(U_i) simeq tensor(LL|_(U_i), KK_X|_(U_i), OO_X|_(U_i))
      simeq KK|_(U_i)
    $
    is the constant sheaf of $K$ for every $i$. Further, $X$ is irreducible,
    so $MM simeq KK_X$ is the constant sheaf of $K$ by _(6.Cii)_.

  - Therefore, we have the natural injective morphism
    $LL arrow.r.hook tensor(LL, KK_X, OO_X) simeq KK_X$, i.e. we may regard
    $LL$ as a subsheaf of $KK_X$.
]

#corollary(number: 6.16)[
  If $X$ is an integral, separated, Noetherian, locally factorial scheme, then
  there is a natural isomorphism $Cl(X) isoto Pic(X)$.
]

#proof[
  Indeed,
  $Cl(X) isoBy("(6.11)") CaCl(X) isoBy("(6.15)") Pic(X)$.
]

#corollary(number: 6.17)[
  If $X = PP_k^n$ for any field $k$, then every invertible sheaf on $X$ is
  isomorphic to $OO_X(l)$ for some $l in ZZ$.
]

#proof[
  Since $X = PP_k^n$ satisfies the condition of _(6.11)_, we have the
  following one-to-one correspondence:

  #align(center)[
    #diagram(
      $
        ZZ edge("r", text("(6.4)"), arrow.l.r)
        & Cl(X) edge("r", text("(6.11)"), arrow.l.r)
        & CaCl(X) edge("r", text("(6.15)"), arrow.l.r)
        & Pic(X) \
        1 edge("r", mapsto)
        & H = V_+(x_0) edge("r", mapsto)
        & D = { (U_i, x_i / x_0) }_(i=0)^n edge("r", mapsto)
        & LL(D)
      $,
    )
  ]

  Indeed:

  - *(6.4).* Write $S := k[x_0, dots.c, x_n]$. Then the function field is
    $K = S_((0)) = (Frac S)_0$. Further, $x_0$ corresponds to the prime ideal
    $pp = (x_0)$ of height $1$, so we have the DVR given by
    $S_(pp) = k[{x_j / x_i : i != 0}]$ with its maximal ideal generated by
    $x_0 / x_i$. Thus $nu_H (x_0 / x_i) = 1$.

  - *(6.11).* Set $U_i := D_+(x_i)$, the usual open cover of $Proj S$. Then
    $
      x_i / x_0 in (Frac S)_0^times = K^times = KK_X^times (U_i)
    $
    and
    $
      x_i / x_j in k[{x_k x_l \/ (x_i x_j) : 0 <= k, l <= n}]^times
      = S_((x_i x_j))^times simeq OO_X^times (U_i inter U_j).
    $
    Further, $Gamma_ast(OO_X) simeq S$ by _(5.13)_, i.e.
    $OO_X(d)(X) = S_d$ for every $d >= 0$.

  - *(6.15).* The subsheaf $LL(D) subset KK_X$ is generated by
    ${ x_0 / x_i }_(i=1)^n$.

  We show that $LL(D) simeq OO_X(1)$ so that the generator
  $1 in ZZ$ corresponds to the generator $OO_X(1) in Pic(X)$. Consider
  the morphism $psi: LL(D) -> OO_X(1)$ given by
  $
    psi_(U_i): LL(D)(U_i) -> OO_X(1)(U_i) simeq (S_(x_i))_1, quad
    x_0 / x_i mapsto x_0 / 1
  $
  for each $i$, which is clearly an isomorphism by the definition of $LL(D)$.
  Thus $psi: LL(D) isoto OO_X(1)$, and therefore we have the group
  isomorphism
  $ (ZZ, +) isoto (Pic(X), tensor), quad l mapsto OO_X(l). $
]

#definition(title: "Effective Cartier Divisors")[
  - A Cartier divisor ${ (U_i, f_i) } in CDiv(X)$ is *effective* if
    $f_i in Gamma(U_i, OO_X|_(U_i))$ for every $i$.

  - In this case, define the *associated subscheme* $Y$ to be the closed
    subscheme of codimension $1$ defined by the sheaf of ideals $II$ which is
    locally generated by $f_i$.
]

#remark(title: "6.17.1")[
  If $X in Sch$ satisfies the condition of _(6.11)_, then the definition above
  gives a one-to-one correspondence under the isomorphism in _(6.11)_:
  $
    {D in Div(X) : text("effective")}
    arrow.l.r.double.long
    {D in CDiv(X) : text("effective")}.
  $
]

#proposition(number: 6.18)[
  Let $D in CDiv(X)$ be an effective Cartier divisor and let $Y$ be the
  associated *locally principal* closed subscheme, i.e. whose sheaf of ideals is
  locally generated by a single element. Then $II_Y simeq LL(-D)$.
]

#proof[
  The sheaf $LL(-D)$ is a subsheaf of $KK_X$ locally generated by $f_i$ on
  $U_i$. Since $D$ is effective, $f_i in OO_X (U_i)$ for each $i$, which
  implies that $LL(-D)$ is in fact a subsheaf of $OO_X$. Therefore,
  $LL(-D) simeq II_Y$, the ideal sheaf of $Y$.
]
