#import "@preview/theorion:0.4.0": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import cosmos.clouds: *
#show: show-theorion
#import "defs.typ": *

== Divisors

=== Weil Divisors

#emph-box()[
  *Axiom $(star)$.* Throughout this section, $X$ is a Noetherian, integral,
  separated scheme, which is regular in codimension $1$, i.e. every local ring
  $OO_x$ of dimension $1$ is regular.
]

#definition(title: "Weil Divisors")[
  Fix a scheme $X in Sch$ satisfying $(star)$.

  - *(Prime Divisor).* A *prime divisor* on $X$ is a closed integral
    subscheme $Y$ such that $codim(Y, X) = 1$.

  - *(Weil Divisor).* Let
    $
      Div(X) := text("the free abelian group generated by the prime divisors").
    $
    Its elements are called *Weil divisors*.

  - *(Effective Divisors).* An *effective divisor* is a (Weil) divisor
    $D = sum_i n_i Y_i in Div(X)$ with $n_i >= 0$ for every $i$.
]

#remark[
  Let $X in Sch$ satisfy $(star)$, and let $Y$ be a prime divisor.

  - As $Y$ is integral, it has a unique generic point $eta in Y$. Consider the
    local ring $OO_(X, eta)$. Let $U = Spec A$ be an open affine neighborhood
    of $eta in X$, say $eta = pp in Spec A$. By the axiom, $A$ is a
    Noetherian integral domain, so is its localization
    $A_pp = OO_(U, eta) = OO_(X, eta)$. Further,
    $
      dim OO_(X, eta) = codim(overline({eta}), X) = codim(Y, X) = 1.
    $
    Again from the axiom, $OO_(X, eta)$ is regular. Therefore, the local ring
    $OO_(X, eta)$ is a DVR.

  - Since $X$ is also an integral scheme, it has a unique generic point
    $mu in X$ (caution: $mu$ may not be the same as $eta$). By _(4.A)_, we
    have $Frac OO_(X, eta) = k(mu) =: K$, the function field of $X$.

  - As $OO_(X, eta)$ is a DVR in $K$, there exists a discrete valuation
    $nu_Y: K^times -> ZZ$ such that
    $
      OO_(X, eta) = { f in K : nu_Y (f) >= 0 } union {0}, \
      mm_(X, eta) = { f in K : nu_Y (f) > 0 }, \
      OO_(X, eta)^times = { f in K : nu_Y (f) = 0 },
    $
    where $mm_(X, eta) := ideal(pi)$ is principal with $nu_Y (pi) = 1$.

  - Since $X$ is separated, by _[4.5]_, such $Y$ is uniquely determined by
    $nu_Y$. *Why?*

  - Fix $f in K^times$. We say that $f$ has a *zero* [resp. *pole*] along $Y$
    of order $abs(nu_Y (f)) in ZZ_(>0)$ if $nu_Y (f) > 0$
    [resp. $nu_Y (f) < 0$].
]

#remark[
  If $X = Spec A$ is affine, there is a one-to-one correspondence
  $
    {Y subset X : text("prime divisor")} & arrow.l.r.double.long {pp in Spec A : Ht pp = 1}, \
                            Spec(A / pp) & arrow.long.l pp.
  $
]

#proof[
  Indeed, we see that

  - $Y subset X$ is a closed subscheme iff $Y simeq Spec(A / aa)$ for some
    $aa lt.closed A$.
  - $Y$ is an integral scheme iff $A / aa$ is an integral domain iff
    $aa = pp lt.closed A$ is a prime ideal.
  - Further, $codim(Y, X) = dim A - dim(A / pp) = Ht pp$.
]

#definition(title: "Regular Functions")[
  Given an integral scheme $X$, we say:

  - $f in K(X)$ is *regular* at $x in X$ if
    $f in OO_(X, x) arrow.r.hook_(text("(4.A)")) K(X)$.

  - $f in K(X)$ is *regular* on an open affine subset $U = Spec A$ of $X$ if
    $f in OO_X(U) = A arrow.r.hook_(text("[3.6]")) K(X)$.
]

#lemma(number: 6.1)[
  Let $X in Sch$ satisfy $(star)$, and let $f in K^times$ be a nonzero function
  on $X$. Then the valuation $nu_Y (f) = 0$ for all but finitely many prime
  divisors $Y$ on $X$.
]

#proof[
  - Let $U = Spec A$ be an open affine subset of $X$ on which $f$ is regular,
    i.e. $f in OO_X(U)$. Then $Z := X - U$ is a proper closed subset of
    $X$.

  - If $codim(Z, X) > 1$, then $Z$ cannot contain a subscheme $Y$ with
    $codim(Y, X) = 1$, i.e. $Z$ cannot contain a prime divisor of $X$. If
    $codim(Z, X) = 1$ and if $Y$ is a prime divisor of $X$ contained in $Z$,
    then $Y$ is an irreducible component of $Z$. Since $X$ is a Noetherian
    scheme, it is a Noetherian topological space, so is its subspace $Z$ with
    induced topology. By _(I, 1.5)_, $Z$ has finitely many irreducible
    components, so there are only finitely many such prime divisors
    $Y subset Z$ of $X$; all the others must meet $U$.

  - To see the prime divisors which meet $U$, it suffices to consider the prime
    divisors $Y$ of $U$, since $U subset X$ is open. It remains to show that
    there are only finitely many prime divisors $Y$ of $U = Spec A$ for which
    $nu_Y (f) != 0$.

  - Recall from the proof of _[2.9]_ that every open subset $V subset Y$ must
    contain its generic point $eta$. Then for the open subset $U subset X$, the
    inclusion $OO_X(U) arrow.r.hook K$ can be factored as
    $OO_X(U) -> OO_(X, eta) arrow.r.hook K$, which gives
    $OO_X(U) arrow.r.hook OO_(X, eta)$. Now we may view
    $f in OO_(X, eta)$, so $nu_Y (f) >= 0$.

  - If $Y$ is a prime divisor of $U = Spec A$, it corresponds to some prime
    ideal $pp lt.closed A$, i.e. $Y = V(pp) simeq Spec(A / pp)$ from the
    remark. Then
    $
      nu_Y (f) > 0 & arrow.l.r.double.long f in mm_(X, eta) = pp A_pp \
                   & arrow.l.r.double.long f in pp \
                   & arrow.l.r.double.long sqrt(ideal(f)) subset sqrt(pp) = pp \
                   & arrow.l.r.double.long Y = V(pp) subset V(ideal(f)).
    $

  - Since $X$ is integral, $A = OO_X(U)$ is a reduced integral domain, i.e.
    $ideal(0) = nil(A) in Spec A$. Since $f in K^times$ is nonzero,
    $f in.not nil(A)$, so $W := V(ideal(f)) subset U$ is a proper closed
    subset by _[AM, 1.17ii]_. Moreover, $X$ is Noetherian, so is its open
    affine subset $U$, hence $U$ is a Noetherian topological space. Again by
    _(I, 1.5)_, $W$ can contain only finitely many irreducible closed subsets
    $Y subset U$ with $codim(Y, X) = 1$, i.e. there can only be finitely many
    prime divisors $Y$ for which $nu_Y (f) > 0$.
]

#proposition(number: 6.2)[
  Let $A$ be a Noetherian domain. Then
  $
    A text(" is a UFD")
    arrow.l.r.double.long
    X = Spec A text(" is normal and ") Cl(X) = 0.
  $
]

#proof[
  - If $A$ is a UFD, then it is integrally closed, whence $X = Spec A$ is
    normal.

  - From _(I.1.12)_, it suffices to show that if $A$ is an integrally closed
    Noetherian domain, then every prime ideal of height $1$ is principal iff
    $Cl(Spec A) = 0$.

  - $(Rightarrow)$ Suppose every prime ideal of height $1$ is principal.

    - Consider a prime divisor $Y$ of $X$, and let $pp in Spec A$ be its
      corresponding prime ideal of height $1$. By assumption, say
      $pp = ideal(f)$ for some $f in A$. Further, $pp = eta in Y$ is its unique
      generic point, so $OO_(X, eta) = A_pp$ is a DVR with unique maximal ideal
      $mm_eta = pp A_pp = ideal(f / 1)$. It follows that
      $nu_Y (f) = nu_Y (f) - nu_Y (1) = nu_Y (f / 1) = 1$ since
      $
        OO_(X, eta)
        = {x in K^times : nu_Y (x) > 0}
        union {x in K^times : nu_Y (x) = 0}
        = mm_eta union OO_(X, eta)^times.
      $

    - If $Z subset X$ is another prime divisor with corresponding prime ideal
      $qq = mu$, then since $f in A$ and $A$ is integral, we have
      $f / 1 in A_qq = OO_(Z, mu)$, so $nu_Z (f) = nu_Z (f / 1) >= 0$. If
      $nu_Z (f / 1) > 0$, then $f / 1 in mm_mu = qq A_qq$, i.e. $f in qq$.
      This implies that $pp = ideal(f) subset qq$. But $Ht pp = Ht qq = 1$,
      so $pp = qq$, whence $Z = overline({mu}) = overline({eta}) = Y$, a
      contradiction. Thus $nu_Z (f) = 0$ whenever $Z != Y$, i.e.
      $dv(f) = 1 dot Y$.

    - Finally, for any divisor $D in Div(X)$, we have
      $
        D := sum_(text("finite")) n_i Y_i
        = sum_(text("finite")) n_i dv(f_i)
        = dv(product_(text("finite")) f_i^(n_i)),
      $
      which is a principal divisor. Therefore, $Cl(Spec A) = 0$.

  - $(Leftarrow)$ Conversely, suppose $Cl(Spec A) = 0$ and let
    $pp in Spec A$ with $Ht pp = 1$.

    - Let $Y = Spec(A / pp)$ be the corresponding prime divisor of $X$ to
      $pp$. Since $A$ is an integrally closed Noetherian domain, so is
      $A_pp$. Further, $dim A_pp = Ht pp = 1$, so $A_pp$ is a DVR.

    - For the divisor $Y in Div(X)$, since $Cl(X) = 0$, there exists
      $f in K^times$ such that $Y = dv(f)$. So $nu_Y (f) = 1 > 0$, and hence
      $f in pp A_pp$, the maximal ideal of $A_pp$. But $A_pp$ is a DVR, so its
      maximal ideal is principal, say $pp A_pp = ideal(pi)$. Then
      $nu_Y (pi) = 1$, so $nu_Y (f / pi) = 0$, i.e. $f / pi in A_pp^times$.
      Thus $pp A_pp = ideal(pi) = ideal(f)$.

    - If $qq in Spec A$ is another prime ideal of height $1$, we have another
      corresponding prime divisor $Z = Spec(A / qq)$. As $dv(f) = Y$, we see
      that $nu_Z (f) = 0$, i.e. $f in A_qq$. It follows that
      $f in inter_(Ht qq = 1) A_qq eqBy("(6.3)") A$. Now,
      $f in A inter pp A_pp = pp$, which implies $ideal(f) subset pp$.

    - For $g in pp$, we have $g / 1 in pp A_pp$, so
      $nu_Y (g) = nu_Y (g / 1) > 0$. By the similar argument as above, if
      $W subset X$ is any other prime divisor, then $nu_W(g) = 0$. Thus
      $nu_W(g / f) >= 0$, i.e. $g / f in A_qq$, for every prime divisor
      $W subset X$ with corresponding prime ideal $qq$. Again,
      $g / f in inter_(Ht qq = 1) A_qq eqBy("(6.3)") A$, so
      $g in ideal(f)$. Thus $pp subset ideal(f)$, and therefore
      $pp = ideal(f)$ is principal.
]

#proposition(
  number: 6.3,
)[
  Let $A$ be an integrally closed Noetherian domain. Then
  $
    A = inter { A_pp : pp lt.closed A text(" prime with ") Ht pp = 1 }.
  $
]

#lemma-box(title: "Fact 6.A")[
  Let $X$ be a scheme satisfying $(star)$, and let $x in X$. Then
  $
    x text(" is not in any prime divisor ") Y text(" of ") X
    arrow.l.r.double.long
    x = eta, text(" the unique generic point of ") X.
  $
]

#proof[
  $(Leftarrow)$ Suppose $eta in Y$ for some $Y$. Let $U = Spec A$ be an open
  affine neighborhood of $eta in X$. Then $U inter Y$ is a prime divisor of
  $U$, i.e. $U inter Y simeq Spec(A / pp)$ for some $pp in Spec A$ with
  $Ht pp = 1$. But $xi = overline(0) in U inter Y$, which corresponds to
  $pp in U$, is the generic point of $Y$, so $eta = xi$, i.e. $pp = (0)$,
  which contradicts $Ht pp = 1$.

  $(Rightarrow)$ Let $U = Spec A$ be an open affine neighborhood of $x in X$,
  say $x = pp$ in $U$. From the assumption, we have
  $pp / qq in.not Spec(A / qq)$ for any $qq in Spec A$ with $Ht qq = 1$. Now,
  if $pp != (0)$, say $0 != a in pp$, then there exists a minimal prime ideal
  $qq lt.closed A$ such that $ideal(a) subset qq subset pp$. By _(I.1.11)_,
  we have $Ht qq = 1$, whence $pp / qq in Spec(A / qq)$, a contradiction.
  Therefore $pp = (0)$ in $U$, i.e. $x = eta$.
]

#lemma(
  number: "6.B", // number: 6.B
)[
  Suppose $X = PP_k^n = Proj S$ for any field $k$, i.e. $S_0 = k$ and
  $S_+ = lr(chevron.l x_0, dots.c, x_n chevron.r)$ is a maximal ideal of $S$. Then $X$
  satisfies $(star)$, so we may talk about divisors on $X = PP_k^n$.

  #set enum(numbering: "i)", spacing: 1em)

  + For any subset $Y subset X$, define
    $I_+(Y) := inter { pp : pp in Y }$; in particular,
    $I_+(emptyset) = S$. Then $I_+(Y_2) subset I_+(Y_1)$ for any subsets
    $Y_1 subset Y_2 subset X$.

  + If $aa lt.closed S$ is any homogeneous ideal, then
    $V_+(aa) = emptyset arrow.l.r.double.long sqrt(aa) = S$ or $S_+$.

  + If $aa lt.closed S$ is any homogeneous ideal with $V_+(aa) != emptyset$,
    then $I_+(V_+(aa)) = sqrt(aa)$.

  + For any $Y subset X$, we have $V_+(I_+(Y)) = overline(Y)$.

  + The operations $I_+(-)$ and $V_+(-)$ set up an inclusion-reversing
    one-to-one correspondence:
    $
      {aa lt.closed S : aa text(" homogeneous radical ideal with ") aa
        text(" not containing ") S_+} \
      arrow.l.r.double.long
      {Y subset X : text("closed subset")}, \
      aa mapsto V_+(aa), quad I_+(Y) arrow.long.l Y.
    $
    Note that $S arrow.l.r.double.long emptyset$ and $S_+ mapsto emptyset$.
    In particular, this restricts to the one-to-one correspondence between
    the following two subsets:
    $
      Proj S =
      {pp lt.closed S : pp text(" homogeneous prime ideal with ") pp
        text(" not containing ") S_+}\
      arrow.l.r.double.long
      {Y subset X : text("irreducible closed subset")}.
    $

  + Further, the correspondence above yields:
    $
      {pp in Proj S : Ht pp = 1} & arrow.l.r.double.long
                                   {Y subset PP_k^n : text("prime divisor, i.e. irreducible hypersurface")} \
                                 & arrow.l.r.double.long
                                   {f in S : text("homogeneous and irreducible, up to associates")}, \
                        ideal(f) & arrow.long.l V_+(f) arrow.long.l f,
    $
    if we give each closed subset the reduced induced subscheme structure.
]

#proof[
  *(vi).* Clearly, a homogeneous prime ideal with $Ht pp = 1$ corresponds to an
  irreducible closed subset with $codim(Y, X) = 1$, and note that
  $Ht S_+ = Ht(lr(chevron.l x_0, dots.c, x_n chevron.r)) = n + 1 > 1$. This gives the first
  correspondence. For the second:

  - Given such $pp$ with $Ht pp = 1$. As $S = k[x_0, dots.c, x_n]$ is a UFD,
    it follows from _(I.1.12)_ that $pp = ideal(f)$ is principal for some
    homogeneous $f in S$. Further, $S$ is an integral domain, so $f$ is
    irreducible.

  - Given an irreducible homogeneous polynomial $f in S$. Since $S$ is a UFD,
    $ideal(f) lt.closed S$ is a homogeneous prime ideal and obviously does not
    contain $S_+$, whence $ideal(f) in Proj S$. Moreover, as $S$
    is Noetherian, _(I.1.11)_ implies that $Ht ideal(f) = 1$.
]

#proposition(number: 6.4)[
  Let $X = PP_k^n$ for any field $k$. For any divisor $D = sum n_i Y_i$,
  define the degree of $D$ by
  $op("deg") D := sum n_i op("deg") Y_i$, where $op("deg") Y_i$ is the degree
  of the hypersurface $Y_i$, i.e. if $Y_i = V_+(f_i)$, then
  $op("deg") Y_i = op("deg") f_i$. Let $H = V_+(x_0)$ be the hyperplane.
  Then:

  #set enum(numbering: "a)", spacing: 1em)

  + If $D$ is any divisor of degree $d$, then $D tilde.op d H$.
  + For any $f in K^times$, $op("deg") dv(f) = 0$.
  + The degree function gives an isomorphism
    $op("deg"): Cl(X) -> ZZ$.
]

#proof[
  *(b).* Suppose $S = k[x_0, dots.c, x_n]$ is the homogeneous coordinate ring
  of $X = PP_k^n$.

  - The function field $K$ of $X$ is $S_((0)) = (Frac S)_0$.

  - If $g in S_d$ with $d >= 0$ is a homogeneous polynomial, then as $S$ is a
    UFD, we may factor $g$ into irreducible polynomials
    $g = a g_1^(n_1) dots.c g_r^(n_r)$, where $a in k$ and
    $g_i in S^h$ is irreducible. By _(6.B)_, each $Y_i := V_+(g_i)$ is a
    hypersurface of degree $d_i = op("deg") g_i$. Now we may extend the
    function $dv: K^times -> Div(X)$ to $S^h -> Div(X)$ by letting
    $dv(g) := sum n_i Y_i in Div(X)$. This makes sense since
    $nu_(Y_i)(g) = nu_(g_i)(g) = n_i$. It follows that
    $
      op("deg") dv(g) = sum_(i=1)^r n_i op("deg") Y_i
      = sum_(i=1)^r n_i d_i = op("deg") g = d.
    $

  - For any $f in K^times = (Frac S)_0$, write $f := g / h$ with
    $g, h in S_d$ and $d >= 0$. Then
    $dv(f) = dv(g) - dv(h)$, since $nu_(g_i)(h) = 0$ for every $i$ and
    similarly for $h$, whence
    $
      op("deg") dv(f) = op("deg") dv(g) - op("deg") dv(h) = d - d = 0.
    $

  *(a).* Suppose $D in Div(X)$ is any divisor of degree $d$.

  - We may write $D := D_1 - D_2$ such that both $D_1$ and $D_2$ are effective
    divisors of degrees $d_1, d_2 >= 0$, respectively.

  - For any prime divisor $Y_i$, it corresponds to an irreducible homogeneous
    polynomial $h_i in S$ from _(6.B)_, i.e. $Y_i = V_+(h_i)$. Now, for
    $j = 1, 2$, set $g_j := product_(text("finite")) h_i^(n_(i j)) in S^h$.
    Then
    $
      D_j = sum_(text("finite")) n_(i j) Y_i
      = sum_(text("finite")) n_(i j) dv(h_i)
      = dv(g_j),
    $
    where
    $op("deg") g_j = sum_(text("finite")) n_(i j) op("deg") h_i
    = op("deg") D_j = d_j$.

  - Finally, take $f := g_1 / (x_0^d g_2)$. Then
    $
      op("deg") f = op("deg") g_1 - (d op("deg") x_0 + op("deg") g_2)
      = d_1 - d - d_2 = 0,
    $
    whence $f in (Frac S)_0 = K^times$. Thus
    $
      D - d H = dv(g_1) - dv(g_2) - d dv(x_0) = dv(f)
    $
    is a principal divisor, and therefore $D tilde.op d H$.

  *(c).* From above, we obtain a group homomorphism
  $op("deg"): Div(X) -> ZZ$.

  - By (b), the group of principal divisors is contained in
    $Ker(op("deg"))$.

  - By (a), if $op("deg") D = 0$, then $D tilde.op 0$, i.e. $Ker(op("deg"))$ is
    contained in the group of principal divisors. Further, for any
    $d in ZZ$, we have $d H mapsto d$. Therefore, this lifts to a group
    isomorphism $op("deg"): Cl(X) isoto ZZ$ by the isomorphism theorem.
]

#proposition(number: 6.5)[
  Let $X in Sch$ satisfy $(star)$. Suppose $Z subset X$ is a proper closed
  subset and $U := X - Z$. Then:

  #set enum(numbering: "a)", spacing: 1em)

  + There is a surjective homomorphism
    $
      Cl(X) -> Cl(U), quad
      D = sum n_i Y_i mapsto sum_(Y_i inter U != emptyset) n_i (Y_i inter U).
    $

  + If $codim(Z, X) >= 2$, then $Cl(X) -> Cl(U)$ is an isomorphism.

  + If $Z subset X$ is an irreducible subset of codimension $1$, then there is
    an exact sequence
    $
      ZZ -> Cl(X) -> Cl(U) -> 0,
    $
    where the first map is defined by $1 mapsto 1 dot Z$.
]

#proof[
  *(a).* We proceed by the following steps:

  - Let $Y subset X$ be any prime divisor such that $Y inter U != emptyset$. I
    claim that $Y inter U$ is a prime divisor of $U$. Note that $U$ also
    satisfies $(star)$. Since $Y inter U arrow.r.hook U$ is the base change of
    the closed immersion $Y arrow.r.hook X$ via $U arrow.r.hook X$, it is also
    a closed immersion. Also, $Y inter U$ is an integral scheme as it is an open
    subscheme of the integral scheme $Y$. Further, the codimension remains the
    same on its nonempty open subset, so $Y inter U$ is indeed a prime divisor
    of $U$.

  - Now define $phi: Div(X) -> Div(U)$ on prime divisors by
    $phi(Y) = Y inter U$ if $Y inter U != emptyset$, and $phi(Y) = 0$
    otherwise. Since $Z subset X$ is a proper closed subset and
    $X in Top$ is Noetherian, there are only finitely many possibilities of
    $Y$ satisfying $Y subset Z$, i.e. $Y inter U = emptyset$.

  - I claim that $phi$ sends principal divisors of $X$ to those of $U$. Let
    $xi, eta$ be generic points of $X, Y$, respectively, where
    $Y inter U != emptyset$ and $K = OO_(X, xi)$. For any $f in K^times$, note
    that $Frac OO_(U, eta) = Frac OO_(X, eta) eqBy("(4.A)") K$, so
    $nu_(Y inter U)$ and $nu_Y$ define the same valuation, i.e.
    $nu_(Y inter U)(f) = nu_Y (f)$. Thus
    $
      phi(dv(f))
      = sum_(Y_i inter U != emptyset) nu_(Y_i)(f) (Y_i inter U)
      = sum_(Y_i inter U != emptyset) nu_(Y_i inter U)(f) (Y_i inter U)
      = dv_U(f).
    $
    Therefore, $phi$ induces a group homomorphism $Cl(X) -> Cl(U)$.

  - Clearly, $Cl(X) -> Cl(U)$ is surjective since every prime divisor of $U$
    is the restriction of its closure in $X$.

  *(b).* Since $X$ is a Noetherian topological space, decompose $Z$ into
  finitely many irreducible components $Z := union_(i=1)^r Z_i$. If
  $Y subset X$ is a prime divisor with $Y inter U = emptyset$, i.e.
  $Y subset Z$, then $Y subset Z_i$ for some $i$. It follows that
  $
    1 = codim(Y, X) >= codim(Z_i, X) >= codim(Z, X) >= 2,
  $
  a contradiction. Hence
  $
    phi: {Y subset X : text("prime divisor")}
    -> {Y inter U subset U : text("prime divisor")}
  $
  is bijective, and therefore $Cl(X) isoto Cl(U)$.

  *(c).* If there are no prime divisors $Y subset X$ meeting $U$, then $Z$ is
  the only prime divisor of $X$. This implies
  $Ker(Cl(X) -> Cl(U)) subset Im(ZZ -> Cl(X))$. The containment
  $(supset)$ is clear, so the sequence is exact at $Cl(X)$.
]

