#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Exercises

// Hartshorne I.1, Exercise 1.1
#exercise(title: "Exercise 1.1")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + Let $Y$ be the plane curve $y = x^2$. Show that $A(Y)$ is isomorphic to a
    polynomial ring in one variable over $k$.
  + Let $Z$ be the plane curve $x y = 1$. Show that $A(Z)$ is not isomorphic
    to a polynomial ring in one variable over $k$.
  + Let $f$ be any irreducible quadratic polynomial in $k[x,y]$, and let $W$
    be the conic defined by $f$. Show that $A(W)$ is isomorphic to $A(Y)$ or
    $A(Z)$. Which one is it when?
]

// Hartshorne I.1, Exercise 1.2
#exercise(title: "Exercise 1.2 (The Twisted Cubic Curve)")[
  Let $Y subset.eq sch.a^3$ be
  $Y = { (t, t^2, t^3) | t in k }$. Show that $Y$ is an affine variety of
  dimension $1$. Find generators for $I(Y)$, and show that $A(Y)$ is
  isomorphic to a polynomial ring in one variable over $k$. We say that $Y$
  is given parametrically by $x = t$, $y = t^2$, $z = t^3$.
]

// Hartshorne I.1, Exercise 1.3
#exercise(title: "Exercise 1.3")[
  Let $Y$ be the algebraic set in $sch.a^3$ defined by $x^2 - y z$ and
  $x z - x$. Show that $Y$ is a union of three irreducible components.
  Describe them and find their prime ideals.
]

// Hartshorne I.1, Exercise 1.4
#exercise(title: "Exercise 1.4")[
  Identifying $sch.a^2$ with $sch.a^1 times sch.a^1$ in the natural way, show that the
  Zariski topology on $sch.a^2$ is not the product topology of the Zariski
  topologies on the two copies of $sch.a^1$.
]

// Hartshorne I.1, Exercise 1.5
#exercise(title: "Exercise 1.5")[
  Show that a $k$-algebra $B$ is isomorphic to the affine coordinate ring of
  an algebraic set in some $sch.a^n$ if and only if $B$ is a finitely generated
  $k$-algebra with no nilpotent elements.
]

// Hartshorne I.1, Exercise 1.6
#exercise(title: "Exercise 1.6")[
  Any nonempty open subset of an irreducible topological space is dense and
  irreducible. If $Y$ is a subset of a topological space $X$ that is
  irreducible in its induced topology, then its closure $overline(Y)$ is also
  irreducible.
]

// Hartshorne I.1, Exercise 1.7
#exercise(title: "Exercise 1.7")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + Show that the following conditions are equivalent for a topological space
    $X$: (i) $X$ is noetherian; (ii) every nonempty family of closed subsets
    has a minimal element; (iii) $X$ satisfies the ascending chain condition
    for open subsets; (iv) every nonempty family of open subsets has a
    maximal element.
  + A noetherian topological space is quasi-compact: every open cover has a
    finite subcover.
  + Any subset of a noetherian topological space is noetherian in its induced
    topology.
  + A noetherian space that is also Hausdorff is a finite set with the discrete
    topology.
]

// Hartshorne I.1, Exercise 1.8
#exercise(title: "Exercise 1.8")[
  Let $Y$ be an affine variety of dimension $r$ in $sch.a^n$. Let $H$ be a
  hypersurface in $sch.a^n$, and assume $Y subset.not H$. Show that every
  irreducible component of $Y inter H$ has dimension $r - 1$.
]

// Hartshorne I.1, Exercise 1.9
#exercise(title: "Exercise 1.9")[
  Let $idl.a subset.eq A = k[x_1, ..., x_n]$ be an ideal generated by $r$
  elements. Show that every irreducible component of $Z(idl.a)$ has dimension at
  least $n - r$.
]

// Hartshorne I.1, Exercise 1.10
#exercise(title: "Exercise 1.10")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + If $Y$ is any subset of a topological space $X$, show that
    $dim Y <= dim X$.
  + If $X$ is covered by open subsets $U_i$, show that
    $dim X = sup_i dim U_i$.
  + Give an example of a topological space $X$ and a dense open subset $U$
    with $dim U < dim X$.
  + If $Y$ is a closed subset of an irreducible finite-dimensional topological
    space $X$ and $dim Y = dim X$, show that $Y = X$.
  + Give an example of a noetherian topological space of infinite dimension.
]

// Hartshorne I.1, Exercise 1.11
#exercise(title: "Exercise 1.11*")[
  Let $Y subset.eq sch.a^3$ be the curve parametrized by
  $x = t^3$, $y = t^4$, $z = t^5$. Show that $I(Y)$ is a prime ideal of
  height $2$ in $k[x,y,z]$ that cannot be generated by two elements. We say
  that $Y$ is not a local complete intersection.
]

// Hartshorne I.1, Exercise 1.12
#exercise(title: "Exercise 1.12")[
  Give an irreducible polynomial $f in RR[x,y]$ whose zero set
  $Z(f) subset.eq sch.a_RR^2$ is not irreducible.
]
