#import "@preview/theorion:0.4.0": *
#import cosmos.clouds: *
#show: show-theorion
#import "../defs.typ": *

=== Exercises

// Hartshorne I.2, Exercise 2.1
#exercise(
  title: "Exercise 2.1 (Homogeneous Nullstellensatz)",
)[
  If $idl.a lt.closed S$ is a homogeneous ideal, and $f in S$ is any homogeneous polynomial of positive degree such that $f(P) = 0$ for every $P in Z_+(idl.a)$ (in $sch.p^n$), i.e. $f in I_+(Z_+(idl.a))$, then $f^m in idl.a$ for some $m > 0$.
]

#proof[
  Change the problem into $sch.a^(n+1)$ and use the usual *Nullstellensatz*.
]

// Hartshorne I.2, Exercise 2.2
#exercise(title: "Exercise 2.2")[
  For a homogeneous ideal $idl.a lt.closed S$, the following are equivalent:

  + $Z_+(idl.a) = emptyset$
  + $sqrt(idl.a) = S$ or $S_+$, the *irrelevant* maximal ideal.
  + $idl.a supset S_d$ for some $d > 0$ (and thus $idl.a supset S_d$ for all large $d > 0$).
]

// Hartshorne I.2, Exercise 2.3
#exercise(title: "Exercise 2.3")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + If $T_1 subset.eq T_2$ are subsets of the homogeneous elements of $S$,
    show that $Z(T_1) supset.eq Z(T_2)$.
  + If $Y_1 subset.eq Y_2$ are subsets of $sch.p^n$, show that
    $I(Y_1) supset.eq I(Y_2)$.
  + Show that $I(Y_1 union Y_2) = I(Y_1) inter I(Y_2)$.
  + If $idl.a subset.eq S$ is homogeneous and $Z(idl.a) != emptyset$, show that
    $I(Z(idl.a)) = sqrt(idl.a)$.
  + For any $Y subset.eq sch.p^n$, show that $Z(I(Y)) = overline(Y)$.
]

// Hartshorne I.2, Exercise 2.4
#exercise(title: "Exercise 2.4")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + Show that algebraic sets in $sch.p^n$ correspond inclusion-reversingly to
    homogeneous radical ideals of $S$ unequal to the irrelevant maximal ideal
    $S_+$, via $Y mapsto I(Y)$ and $idl.a mapsto Z(idl.a)$.
  + Show that an algebraic set $Y subset.eq sch.p^n$ is irreducible if and only if
    $I(Y)$ is prime.
  + Show that $sch.p^n$ is irreducible.
]

// Hartshorne I.2, Exercise 2.5
#exercise(title: "Exercise 2.5")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + Show that $sch.p^n$ is a noetherian topological space.
  + Show that every algebraic set in $sch.p^n$ is uniquely a finite union of
    irreducible algebraic sets, none containing another. These are its
    irreducible components.
]

// Hartshorne I.2, Exercise 2.6
#exercise(title: "Exercise 2.6")[
  If $Y$ is a projective variety with homogeneous coordinate ring $S(Y)$,
  show that $dim S(Y) = dim Y + 1$.

  _Hint:_ Let $phi_i: U_i -> sch.a^n$ be the homeomorphism of Proposition 2.2,
  let $Y_i = phi_i (Y inter U_i)$, and identify $A(Y_i)$ with the degree-zero
  part of $S(Y)_(x_i)$. Show that
  $S(Y)_(x_i) simeq A(Y_i)[x_i,x_i^(-1)]$, compare transcendence degrees, and
  conclude also that $dim Y = dim Y_i$ whenever $Y_i$ is nonempty.
]

// Hartshorne I.2, Exercise 2.7
#exercise(title: "Exercise 2.7")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + Show that $dim sch.p^n = n$.
  + If $Y subset.eq sch.p^n$ is a quasi-projective variety, show that
    $dim Y = dim overline(Y)$.

  _Hint:_ Use Exercise 2.6 to reduce to Proposition 1.10.
]

// Hartshorne I.2, Exercise 2.8
#exercise(title: "Exercise 2.8")[
  Show that a projective variety $Y subset.eq sch.p^n$ has dimension $n - 1$ if
  and only if it is the zero set of a single irreducible homogeneous polynomial
  of positive degree. Such a $Y$ is called a *hypersurface* in $sch.p^n$.
]

// Hartshorne I.2, Exercise 2.9
#exercise(title: "Exercise 2.9 (Projective Closure of an Affine Variety)")[
  Identify $sch.a^n$ with $U_0 subset.eq sch.p^n$ using $phi_0$. For an affine
  variety $Y subset.eq sch.a^n$, its closure in $sch.p^n$ is its *projective closure*
  $overline(Y)$.

  #set enum(numbering: "a)", spacing: 0.8em)

  + Show that $I(overline(Y))$ is generated by the homogenizations
    $beta(I(Y))$, with $beta$ as in the proof of Proposition 2.2.
  + Let $Y subset.eq sch.a^3$ be the twisted cubic of Exercise 1.2. Find
    generators for $I(Y)$ and $I(overline(Y))$, and use this example to show
    that homogenizing a set of generators of $I(Y)$ need not generate
    $I(overline(Y))$.
]

// Hartshorne I.2, Exercise 2.10
#exercise(title: "Exercise 2.10 (The Cone over a Projective Variety)")[
  Let $Y subset.eq sch.p^n$ be a nonempty algebraic set and let
  $theta: sch.a^(n+1) without {0} -> sch.p^n$ send affine coordinates
  $(a_0,...,a_n)$ to homogeneous coordinates $(a_0:...:a_n)$. Define the
  *affine cone* over $Y$ by $C(Y) = theta^(-1) (Y) union {0}$.

  #set enum(numbering: "a)", spacing: 0.8em)

  + Show that $C(Y)$ is an algebraic set in $sch.a^(n+1)$ whose ideal is $I(Y)$,
    regarded as an ordinary ideal of $k[x_0,...,x_n]$.
  + Show that $C(Y)$ is irreducible if and only if $Y$ is.
  + Show that $dim C(Y) = dim Y + 1$.

  The projective closure of $C(Y)$ in $sch.p^(n+1)$ is called the *projective
  cone* over $Y$.
]

// Hartshorne I.2, Exercise 2.11
#exercise(title: "Exercise 2.11 (Linear Varieties in Projective Space)")[
  A hypersurface defined by a linear polynomial is called a hyperplane.

  #set enum(numbering: "a)", spacing: 0.8em)

  + For a variety $Y subset.eq sch.p^n$, show that the following are equivalent:
    (i) $I(Y)$ can be generated by linear polynomials; (ii) $Y$ is an
    intersection of hyperplanes. Such a $Y$ is called a *linear variety*.
  + If $Y$ is a linear variety of dimension $r$ in $sch.p^n$, show that $I(Y)$
    is minimally generated by $n-r$ linear polynomials.
  + Let $Y,Z$ be linear varieties in $sch.p^n$, with $dim Y = r$ and $dim Z = s$.
    If $r+s-n >= 0$, show that $Y inter Z != emptyset$. Whenever the
    intersection is nonempty, show that it is a linear variety of dimension at
    least $r+s-n$.
]

// Hartshorne I.2, Exercise 2.12
#exercise(title: "Exercise 2.12 (The $d$-uple Embedding)")[
  For $n,d > 0$, let $M_0,...,M_N$ be all monomials of degree $d$ in
  $x_0,...,x_n$, where $N = binom(n+d,d)-1$. Define
  $rho_d: sch.p^n -> sch.p^N$ by
  $rho_d (a_0:...:a_n) = (M_0 (a):...:M_N (a))$.

  #set enum(numbering: "a)", spacing: 0.8em)

  + Let $theta: k[y_0,...,y_N] -> k[x_0,...,x_n]$ send $y_i$ to $M_i$, and
    let $idl.a = ops.ker (theta)$. Show that $idl.a$ is a homogeneous prime ideal, so
    $Z(idl.a)$ is a projective variety in $sch.p^N$.
  + Show that the image of $rho_d$ is exactly $Z(idl.a)$.
  + Show that $rho_d$ is a homeomorphism from $sch.p^n$ onto $Z(idl.a)$.
  + Show that the twisted cubic in $sch.p^3$ is the $3$-uple embedding of $sch.p^1$
    for a suitable choice of coordinates.
]

// Hartshorne I.2, Exercise 2.13
#exercise(title: "Exercise 2.13")[
  Let $Y$ be the image of the $2$-uple embedding of $sch.p^2$ in $sch.p^5$, the
  Veronese surface. If $Z subset.eq Y$ is a closed curve, show that there is a
  hypersurface $V subset.eq sch.p^5$ such that $V inter Y = Z$.
]

// Hartshorne I.2, Exercise 2.14
#exercise(title: "Exercise 2.14 (The Segre Embedding)")[
  Let $psi: sch.p^r times sch.p^s -> sch.p^N$, where $N = r s + r + s$, send
  $(a_0:...:a_r),(b_0:...:b_s)$ to $(...,a_i b_j,...)$ in lexicographic order.
  Show that the image of this injective map is a subvariety of $sch.p^N$.

  _Hint:_ Give $sch.p^N$ coordinates $z_(i j)$ and let $idl.a$ be the kernel of
  $k[{z_(i j)}] -> k[x_0,...,x_r,y_0,...,y_s]$, $z_(i j) mapsto x_i y_j$.
  Show that $ops.im (psi) = Z(idl.a)$.
]

// Hartshorne I.2, Exercise 2.15
#exercise(title: "Exercise 2.15 (The Quadric Surface in $PP^3$)")[
  Let $Q subset.eq sch.p^3$ be the surface $x y - z w = 0$.

  #set enum(numbering: "a)", spacing: 0.8em)

  + Show that $Q$ is the Segre embedding of $sch.p^1 times sch.p^1$ for a suitable
    choice of coordinates.
  + Show that $Q$ contains two families of lines ${L_t}$ and ${M_t}$,
    parametrized by $t in sch.p^1$, such that distinct lines in the same family
    do not meet, while $L_t inter M_u$ is one point for every $t,u$.
  + Show that $Q$ contains curves other than these lines, and deduce that the
    Zariski topology on $Q$ is not carried by the Segre map to the product
    topology on $sch.p^1 times sch.p^1$.
]

// Hartshorne I.2, Exercise 2.16
#exercise(title: "Exercise 2.16")[
  #set enum(numbering: "a)", spacing: 0.8em)

  + Let $Q_1,Q_2 subset.eq sch.p^3$ be the quadric surfaces
    $x^2-y w=0$ and $x y-z w=0$. Show that $Q_1 inter Q_2$ is the union of a
    twisted cubic curve and a line, so an intersection of varieties need not
    be a variety.
  + Let $C subset.eq sch.p^2$ be the conic $x^2-y z=0$ and let $L$ be the line
    $y=0$. Show that $C inter L$ is one point $P$, but
    $I(C)+I(L) != I(P)$.
]

// Hartshorne I.2, Exercise 2.17
#exercise(title: "Exercise 2.17 (Complete Intersections)")[
  A variety $Y$ of dimension $r$ in $sch.p^n$ is a *(strict) complete
  intersection* if $I(Y)$ can be generated by $n-r$ elements. It is a
  *set-theoretic complete intersection* if it is the intersection of $n-r$
  hypersurfaces.

  #set enum(numbering: "a)", spacing: 0.8em)

  + If $Y = Z(idl.a)$ and $idl.a$ can be generated by $q$ elements, show that
    $dim Y >= n-q$.
  + Show that a strict complete intersection is a set-theoretic complete
    intersection.
  + Show that the converse is false: for the twisted cubic
    $Y subset.eq sch.p^3$, prove that $I(Y)$ cannot be generated by two elements,
    but find hypersurfaces $H_1,H_2$ of degrees $2$ and $3$ with
    $Y = H_1 inter H_2$.
  + It is an unsolved problem whether every closed irreducible curve in
    $sch.p^3$ is a set-theoretic intersection of two surfaces. See Hartshorne [1]
    and Hartshorne [5, III, Section 5].
]
